### PR TITLE
Add Podcasts

### PR DESCRIPTION
**Pull request by skat00sh**
https://github.com/rShetty/awesome-podcasts

A curated of list of podcasts for software developers. It contains plenty of resources for developers who like to listen on the go. 

**[Insert URL to the list here]**

**[Explain what this list is about and why it should be included here]**

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

## Requirements for your pull request

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title.<br>For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
	- Be added at the bottom of the appropriate category.
- The list I'm submitting complies with these requirements:

## Requirements for your Awesome list

- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
- It's the result of hard work and the best I could possibly produce.
- Non-generated Markdown file in a GitHub repo.
- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
- Not a duplicate.
- Only has awesome items. Awesome lists are curations of the best, not everything.
- Includes a project logo/illustration whenever possible.
	- Either fullwidth or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
	- The image should link to the project website or any relevant website.
	- The image should be high-DPI. Set it to maximum half the width of the original image.
- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
	- Should be placed on the right side of the readme heading.
	- Should link back to this list.
- Has a Table of Contents section.
	- Should be named `Contents`, not `Table of Contents`.
	- Should be the first section in the list.
	- Should only have one level of sub-lists, preferably none.
- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
	- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
	- [WTFPL](http://www.wtfpl.net) and [Unlicense](http://unlicense.org) are not acceptable licenses.
	- If you use a license badge, it should be SVG, not PNG.
- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
	- The file should be named `contributing.md`. Casing is up to you.
- Has consistent formatting and proper spelling/grammar.
	- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
	- The description starts with an uppercase character and ends with a period.
	- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.

Go to the top and read it again.

### CODE REVIEW

**Comment by skat00sh** [comment]
@sindresorhus I've tried to follow all the contribution instructions, still if there's any modification is needed before accepting this PR, please do update here.
Thanks

**Comment by legodude17** [comment]
> Monthly once

I don't think this is correct grammer

**Comment by skat00sh** [comment]
@legodude17  Where is this written, could you please point out?

**Comment by skat00sh** [comment]
@legodude17 It conveys the required information, still you are welcome to raise an issue on the repo.

**Comment by sindresorhus** [comment]
Hey, sorry for the lack of response, please see #1363.

**Comment by lorabv** [comment]
There is already an entry for [Podcasts](https://github.com/guipdutra/awesome-geek-podcasts/blob/master/README.md) under [Entertainment](https://github.com/sindresorhus/awesome#entertainment). Why don't you get in contact with its creator and try to figure out if you can merge your lists?

**Comment by DovAmir** [comment]
This is a PR review

great content, some minor issues

no capital letter

> Frequency : every Monday

no period at end of sentance



> Description: Interviews and discussions about where code and people meet and why #PeopleMatter
> 
> Description: High level concepts in data science, and longer interview with researchers and practitioners
> 
> Description: Data science, machine learning, artificial intelligence
> 
> Description: Podcast that teaches high level fundamentals of Machine Learning with exercises


please review  https://github.com/sindresorhus/awesome/pull/1331

**Comment by sindresorhus** [comment]
Ping @skat00sh @rShetty

**Comment by rShetty** [comment]
@sindresorhus Will look into this and fix the issues, Is it fine to have 2 lists on podcasts ?

**Comment by sindresorhus** [comment]
> Is it fine to have 2 lists on podcasts ?

No, but I think this one can replace the existing one, as this one is more comprehensive and better organized.

**Comment by skat00sh** [comment]
@sindresorhus Just to be sure, as @DovAmir pointed in PR review, these are exhaustively all the inputs/suggestions/correction from your end. It would be really helpful if you could tell if there is anything else so that once done, the PR could be successfully merged.

**Comment by rShetty** [comment]
@skat00sh Can you help fix the conflicts plz ?

**Comment by skat00sh** [comment]
@rShetty I don't have the access to see the conflicts:
screenshot from 2019-03-01 10-29-44

Also, I asked @sindresorhus to just have a look again and confirm if the changes suggested by @DovAmir are exhaustive, it would be really helpful if I can get a revert on that as well.

**Comment by skat00sh** [comment]
@sindresorhus Should I assume that this conversation will be resumed after a few months? 
I respect that you are trying to maintain strict quality standards here but in lack of a timely feedback it's really hard to keep up with the contributions.

**Comment by sindresorhus** [comment]
It was waiting for you to fix the merge conflict. I'm gonna close this. Do a new PR that replaces the existing `Podcasts` entry. Make sure you follow https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md, you will want to read it again.

---

The logo needs to say `podcasts`, not `podcast`.

---

Run https://github.com/sindresorhus/awesome-lint and fix as much as makes sense.

---

Go through https://github.com/ayr-ton/awesome-geek-podcasts and see if there's anything that can be added from it to your list.

**Pull request closed without merging**
