### PR TITLE
Add PostgreSQL

### PR DESCRIPTION
**Pull request by titopao**

### CODE REVIEW

**Comment by davisonio** [comment]
There's some great content here but an [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) would be a great addition to this list. @dhamaniasad

**Comment by davisonio** [comment]
Also perhaps changing the link title in this PR to `PostgreSQL` would be better? I know we can often refer to it as Postgre but PostgreSQL is more often used and provides a better description

**Comment by sindresorhus** [comment]
Thanks for the suggestion. Would you mind reading the [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md) :)

**Comment by sindresorhus** [comment]
Closing for lack of response.

**Pull request closed without merging**
