### PR TITLE
Add CSS Resources

### PR DESCRIPTION
**Pull request by MarketingPip**
**https://github.com/MarketingPipeline/Awesome-CSS-Resources**

**A fresh / new, bigger updated list of CSS frameworks & resource**

Please note - I have NOT added a short description. As all the other resources / links under CSS section do not have any description (assuming this is done purposely).

### CODE REVIEW

**Comment by sindresorhus** [comment]
I also don't see how this is different from the main CSS list. "resources & frameworks" is literally what most lists contain.

**Review by CAPTINHOPE — APPROVED** [review]

**Review by Lissy93 — CHANGES_REQUESTED** [review]
Your addition also doesn't follow the pattern, check the URL, it should end with `#readme`

The list itself also doesn't pass the lint check, [here's a list of the issues](https://github.com/sindresorhus/awesome/runs/7433675507?check_suite_focus=true)

But also, as already mentioned - this list doesn't seem to add any additional value, which isn't already included within other lists above.

**Comment by MarketingPip** [comment]
> Your addition also doesn't follow the pattern, check the URL, it should end with `#readme`

Can you further explain on this? 

> But also, as already mentioned - this list doesn't seem to add any additional value, which isn't already included within other lists above.

I think you take a better comparison look at the difference between this list & other's. I have literally spent countless hours reviewing these resources I have added to it. All thing's that would act as beneficial, creative or time saving resources to anybody in the front end (or even not front end) community. 


Like some of the CSS style sheets I have added to the list might be low of star count (I have found lot's of lost open source goodies), but they are either one of the three, or ALL of the three points above. 


Other list's too I have compared, have just literal junk in them. Or are bare in their resources and just limited to some CSS reset's & frameworks. 

Not anything cool like style sheets for Dungeon's & Dragon themed site etc, style sheet that looks like a piece of paper, stylesheet's for the LGBT community & lot's more than just cool stylesheet's. 

@sindresorhus mentioned as well I missed a few points in the pull request. Which I still need to address, one being linting that you / @Lissy93 mentioned!

**Comment by Lissy93** [comment]
> > Your addition also doesn't follow the pattern, check the URL, it should end with `#readme`
> 
> Can you further explain on this? 


The link to your project should skip to content. Add `#readme` after it. Take a look at all the other additions if you need an example. 

---

Have you reviewed any of the open PRs?

You should read through the [guidelines](https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md) as there's a few points you've missed. If you're unsure about anything, best thing to do is look at all the [merged PRs](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Amerged) as examples.

**Review by nerd00f — APPROVED** [review]
very cool list, would like it to be added

**Comment by Firoj6483** [comment]
Add colour

**Comment by MarketingPip** [comment]
> Add colour

@Firoj6483 - what is the insight here....

**Comment by MarketingPip** [comment]
Still working on this! Give me a little longer & I will have this up to ALL standards. :+1:  Apologizes for any delays.

**Comment by alan-christian** [comment]
cheering for you

**Comment by EmagdnimR139** [comment]
Thank you it truly means alot o me I'm i haveing ben useing xomputers since a little kid but I just recently tryed takeing it very secruous I'm specal ed been classfied sinc 96 so its a little bit mote changling for me that you for the support

**Comment by Jogai** [comment]
Grouping by alphabet is a bit arbitrary I think. For example, the 7, 98, 95 and xp css projects make more sens to be under one heading. I imagine its not easy to classify them all, but still... 
Also I think using list items would make it a bit clearer to read.

**Comment by Nassarjj1** [comment]
> Grouping by alphabet is a bit arbitrary I think. For example, the 7, 98, 95 and xp css projects make more sens to be under one heading. I imagine its not easy to classify them all, but still... 
> 
> Also I think using list items would make it a bit clearer to read.

**Comment by sindresorhus** [comment]
I'm going to pass on this. It does not follow the guidelines and I don't see what it provides over the existing CSS list.

**Comment by MarketingPip** [comment]
> I'm going to pass on this. It does not follow the guidelines and I don't see what it provides over the existing CSS list.

I have still not done the fixes/ changes required.

This list literally consists of more frameworks / stylesheets that I have taken MANUAL time to add to the list.

**Pull request closed without merging**
