### PR TITLE
added Codeface text editor font list to Resources links

### PR DESCRIPTION
**Pull request by chrissimpkins**
Added [Codeface](https://github.com/chrissimpkins/codeface), a comprehensive list of fonts for text editors/source code and repository of the font binary files to the Resources list

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks. Looks good. Would be awesome if you could link back here in your list so users can easily discover more awesome lists ;)

**Comment by chrissimpkins** [comment]
Thanks Sindre.  I really appreciate it and will add the link back to this list.

**Comment by chrissimpkins** [comment]
Link added to the main gallery page!

> § A proud member of the [Awesome Syndicate](https://github.com/sindresorhus/awesome)

**Comment by arthurvr** [comment]
Thanks! Awesome list, by the way!

**Comment by chrissimpkins** [comment]
Thank you!

**Pull request merged**
