### PR TITLE
Add Stock Resources

### PR DESCRIPTION
**Pull request by lipis**
https://github.com/neutraltone/awesome-stock-resources

It's different than [Images](https://github.com/heyalexej/awesome-images) which contains only free photo resources.

### CODE REVIEW

**Comment by aleksandar-todorovic** [comment]
Please read the `awesome.md` file in this repository. In it, you'll see this:

> Apart from suggesting a particular item on your list, you should also inform your readers why it's on the list and how they will benefit from it.

Also, in `create-list.md` it says:

> Wait at least a couple of weeks after creating a list before submitting to this list to give it a chance to mature.

**Comment by lipis** [comment]
Should be OK now, ~4K stars, 18 contributors and couple of weeks later.. :)

**Comment by sindresorhus** [comment]
Added

**Comment by lipis** [comment]
Thanks!

**Pull request closed without merging**
