### PR TITLE
awesome-atom to the list of editors

### PR DESCRIPTION
**Pull request by aleksandar-todorovic**
Not sure if it has enough content for now.

I will contribute to this list regularly if the owner of the list allows it.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Sounds good. Can always just fork and link to your fork if the owner is unresponsive.

**Comment by sindresorhus** [comment]
Would be nice if that list linked back here. Maybe you can do a PR for that repo.

**Comment by aleksandar-todorovic** [comment]
I submitted one Pull Request to the owner of the repo as a test a few hours ago. 
I am planning on linking back to this repository in my future Pull Requests after I see how this Pull Request goes.

**Comment by aleksandar-todorovic** [comment]
I just wanted to inform you that the repository in question now links back to this repository. :+1:

**Pull request merged**
