### PR TITLE
Add IRC

### PR DESCRIPTION
**Pull request by davisonio**
Open source messaging protocol.

https://github.com/davisonio/awesome-irc

IRC is an open source messaging protocol. This is a list that curates the clients, servers and other resources you can use with IRC.

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

- Reviewed #1591 and #1590.

Adheres to all requirements.

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

## Requirements for your pull request

- **Don't waste my time.** Do a good job, adhere to all the guidelines, and be responsive.
- **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).**
	Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration.
- You have read and understood the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a title in the format `Add Name of List`.
	- ✅ `Add Swift`
	- ✅ `Add Software Architecture`
	- ❌ `Update readme.md`
	- ❌ `Add Awesome Swift`
	- ❌ `Add swift`
	- ❌ `Adding Swift`
	- ❌ `Added Swift`
- Your entry here should include a short description about the project/theme of the list. **It should not describe the list itself.** The first character should be uppercase and the description should end in a dot. It should be an objective description and not a tagline or marketing blurb.
	- ✅ `- [iOS](…) - Mobile operating system for Apple phones and tablets.`
	- ✅ `- [Framer](…) - Prototyping interactive UI designs.`
	- ❌ `- [iOS](…) - Resources and tools for iOS development.`
	- ❌ `- [Framer](…)`
	- ❌ `- [Framer](…) - prototyping interactive UI designs`
- Your entry should be added at the bottom of the appropriate category.
- The suggested Awesome list complies with the below requirements.

## Requirements for your Awesome list

- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
- Don't open a Draft / WIP pull request while you work on the guidelines. A pull request should be 100% ready and should adhere to all the guidelines when you open it.
- Run [`awesome-lint`](https://github.com/sindresorhus/awesome-lint) on your list and fix the reported issues. If there are false-positives or things that cannot/shouldn't be fixed, please [report it](https://github.com/sindresorhus/awesome-lint/issues/new).
- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- ✅ `Mobile operating system for Apple phones and tablets.`
	- ✅ `Prototyping interactive UI designs.`
	- ❌ `Resources and tools for iOS development.`
	- ❌ `Awesome Framer packages and tools.`
- It's the result of hard work and the best I could possibly produce.
	**If you have not put in considerable effort into your list, your pull request will be immediately closed.**
- The repo name of your list should be in lowercase slug format: `awesome-name-of-list`.
	- ✅ `awesome-swift`
	- ✅ `awesome-web-typography`
	- ❌ `awesome-Swift`
	- ❌ `AwesomeWebTypography`
- The heading title of your list should be in [title case](https://capitalizemytitle.com/) format: `# Awesome Name of List`.
	- ✅ `# Awesome Swift`
	- ✅ `# Awesome Web Typography`
	- ❌ `# awesome-swift`
	- ❌ `# AwesomeSwift`
- Non-generated Markdown file in a GitHub repo.
- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
- Not a duplicate. Please search for existing submissions.
- Only has awesome items. Awesome lists are curations of the best, not everything.
- Includes a project logo/illustration whenever possible.
	- Either centered, fullwidth, or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
	- The image should link to the project website or any relevant website.
	- **The image should be high-DPI.** Set it to maximum half the width of the original image.
- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
	- Should be placed on the right side of the readme heading.
		- Can be placed centered if the list has a centered graphics header.
	- Should link back to this list.
- Has a Table of Contents section.
	- Should be named `Contents`, not `Table of Contents`.
	- Should be the first section in the list.
	- Should only have one level of [nested lists](https://commonmark.org/help/tutorial/10-nestedLists.html), preferably none.
- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
	- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
	- [WTFPL](http://www.wtfpl.net) and [Unlicense](http://unlicense.org) are not acceptable licenses.
	- **If you use a license badge, it should be SVG, not PNG.**
	- To verify that you've read all the guidelines, please add comment with just the word `unicorn`.
- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
	- The file should be named `contributing.md`. Casing is up to you.
- Has consistent formatting and proper spelling/grammar.
	- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
	- The description starts with an uppercase character and ends with a period.
	- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.
- Doesn't include an `Inspired by awesome-foo` or `Inspired by the Awesome project` kinda link at the top of the readme. The Awesome badge is enough.

**Go to the top and read it again.**

### CODE REVIEW

**Comment by davisonio** [comment]
Unicorn!

**Comment by irazasyed** [comment]
Awesome list but there are several issues as per [awesome-lint](https://github.com/sindresorhus/awesome-lint). You might wanna fix them.


```
❯ awesome-lint https://github.com/davisonio/awesome-irc
✖ Linting

  readme.md:217:137
  ✖    1:1    License was not detected by GitHub                            remark-lint:awesome/github
  ✖    7:1    Multiple Table of Contents lists found                        remark-lint:awesome/toc
  ✖   32:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   33:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   34:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   35:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   36:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   37:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   38:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   39:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   40:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   41:149  List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖   42:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   43:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   44:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   45:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   46:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   47:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   48:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   49:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   50:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   51:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   61:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   62:60   List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖   63:68   List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖   64:85   List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖   65:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   69:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   70:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   71:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   72:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   73:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   83:96   List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖   99:139  List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  100:116  List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  101:85   List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  102:96   List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  103:124  List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  104:83   List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  105:45   List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  106:192  List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  107:78   List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  108:54   List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  109:84   List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  110:83   List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  111:104  List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  112:101  List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  118:51   List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖  119:88   List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  120:93   List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  121:89   List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  122:69   List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  123:88   List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  124:119  List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  125:169  List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  132:77   List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  133:69   List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  134:73   List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  135:159  List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  136:68   List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  137:64   List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  138:86   List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  139:75   List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  140:137  List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  154:46   List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖  155:65   List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖  159:51   List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖  210:3    Invalid list item link                                        remark-lint:awesome/list-item
  ✖  211:3    Invalid list item link                                        remark-lint:awesome/list-item
  ✖  217:137  Link to https://twitter.com/davisonio is dead                 remark-lint:no-dead-urls

  70 errors
```

**Comment by davisonio** [comment]
`awesome-lint` unfortunately brings up many false positives. Since we use icons in front of list items and we include a source code link after the description. (Invalid list item link) (List item description must end with proper punctuation).

License is included and there's a table of contents

**Comment by sindresorhus** [comment]
The link icons needs to be high-DPI (set to half their real size).

---

> A curated list of awesome IRC resources.

I don't think `awesome` should be linkified here.

---

> Includes a succinct description of the project/theme at the top of the readme. (Example)

**Comment by davisonio** [comment]
> The link icons needs to be high-DPI (set to half their real size).

For now have removed until we can do this



> I don't think `awesome` should be linkified here.

Removed

> Includes a succinct description of the project/theme at the top of the readme. (Example)

Added!

Anything else?

**Comment by sindresorhus** [comment]
> `Komanda](komanda.io) - Designed for people who write code (beta). (source) Linux`

The link syntax here is broken.

**Comment by sindresorhus** [comment]
Tweet: https://twitter.com/awesome__re/status/1163172150213316608

**Pull request merged**
