### PR TITLE
Add Tesla

### PR DESCRIPTION
**Pull request by Kikobeats**
Hello,

I just added https://github.com/teslahunt/awesome-tesla, a list I'm maintaining that collects the best third-party utilities, libraries, and tools to know more about Tesla motors vehicles.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

**Comment by Kikobeats** [comment]
for the records

- [x] rename `master` into `main` branch.
- [x] fixed [some](https://github.com/teslahunt/awesome-tesla/commit/4b8f3444f4ccac85a353b930220be430e2d92b4d) style issues

Right now `awesome-lint` is reporting 0 issues 🙂

**Comment by vadim0x60** [comment]
0 `awesome-lint` issues is great, but you should also comment on 2 other pull requests and write their numbers here

**Comment by Kikobeats** [comment]
I'll do it; I can see the irony you are adding that comment (that is not saying anything new) just for satisfying that rule for [your PR](https://github.com/sindresorhus/awesome/pull/1963)

feeling it's at the end a vicious circle .cc @sindresorhus

**Comment by Jogai** [comment]
And dont forget the magic word ;)

You cant blame the maintainers. The repo gets a lot of pr's, so you want them to be high quality, even if its a bit obnoxious.

**Comment by Kikobeats** [comment]
@Jogai sorry but you have to read better my words: I'm not blaming the maintainer, I'm blaming the way the current rules are not working at all.

**Comment by Jogai** [comment]
If thats the case then you can try discussing that, but in the end the rules are set by the maintainers to favour them.

**Comment by sindresorhus** [comment]
> feeling it's at the end a vicious circle .cc @sindresorhus

Uhm, @vadim0x60 did things correctly. You are the one that didn't properly read the guidelines.

**Comment by sindresorhus** [comment]
I'm going to pass on this list for now. Awesome lists are hard work and it's expected that you put a lot of effort into it. Your list is very minimal and does not follow many of the guidelines. You can try submitting again in some months if the list has considerably improved.

**Pull request closed without merging**
