### PR TITLE
Add "Awesome Standard"

### PR DESCRIPTION
**Pull request by feross**
https://github.com/feross/awesome-standard

### CODE REVIEW

**Comment by aleksandar-todorovic** [comment]
Please read the [awesome manifesto](https://github.com/sindresorhus/awesome/blob/master/awesome.md), update the list to comply with it and then ping us back.

**Comment by feross** [comment]
What in particular are you objecting to? Your answer is unhelpful.

**Comment by feross** [comment]
cc @sindresorhus

**Comment by aleksandar-todorovic** [comment]
No contributing guidelines at the moment.

**Comment by feross** [comment]
No problem - that's fixed now!

**Pull request merged**
