### PR TITLE
Add Audio Visualization

### PR DESCRIPTION
**Pull request by willianjusten**
Audio Visualization

This PR will add a [curated list](https://github.com/willianjusten/awesome-audio-visualization) of awesome Audio Visualization related resources =)

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please read the [instructions](https://github.com/sindresorhus/awesome/blob/master/create-list.md) for creating a new list, [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

Especially this part:

> Wait at least a couple of weeks after creating a list before submitting to give it a chance to mature.

Ping me here in a few weeks and I'll reopen ;)

-

You should also keep all the content in the main readme and not create a lot of sub-documents until it's actually needed.

**Comment by sindresorhus** [comment]
I ❤️ the logo btw :)

**Comment by willianjusten** [comment]
Ops, sorry for that. I forgot about the time to wait.

About the content, don't you think it's better to keep in separated files? I thought it was more organized and easier to find and read.

And thanks, I love the logo <3

**Comment by egeerardyn** [comment]
@willianjusten : I love the idea of the separated lists, but I think it only pays when a list grows too large. Right now, I think it makes navigating your list harder, rather than easier. Also, I find it quite hard to quickly see the focus of your list right now. And I love the logo as well :-)

**Comment by willianjusten** [comment]
You're right @egeerardyn, I've added all links to the readme for a while, if the list grows to much, I'll separate in files again.

I've added a link to [wikipedia](https://en.wikipedia.org/wiki/Music_visualization) explaining more about Audio Visualization. The basic is, you take the frequency and amplitude of sounds to create graphic images, like the old visualizers on Winamp, for example =)

**Comment by willianjusten** [comment]
Hey @sindresorhus, I think we can reopen this issue right? We have 2 weeks passed, more than 150 stars and some great guys contributing on the list =)

Btw, look the logo working, hope you like it  <3 (http://www.shiz.co/aav/)

**Comment by sindresorhus** [comment]
I think this still needs some work. Items in the `Experiments` section should have a short description. Right now it's just an incoherent list of random things. The `Libraries` section should have their project description added so users can easily see what they're about. Items in the `People to Follow` section should have commentary on what they're relevant and should be followed. I would remove the `Other Awesome Lists` section. You already link to `awesome` in the badge and the two other lists are unmaintained and incomplete (you're not doing your users any favors linking to them). `What is Audio Visualization?` is good, but I would like to see a succinct one sentence explanation of audio visualization directly in the readme.

**Comment by willianjusten** [comment]
Thanks for the quick answer, I'll fix that =)

**Comment by willianjusten** [comment]
Hi @sindresorhus, I thinks it's ok for now =)

**Comment by sindresorhus** [comment]
Looks better now. Added. :)

Some more things I'd like to see improved:

- Go through a fix all grammar and typos. E.g. "create musics with this sequencer by Joe Harry." `musics` => `music`.
- Capitalize the first character in descriptions. `an immersion to the space` => `An immersion to the space`
- Don't put newlines between items. Right now it looks very messy.

**Comment by willianjusten** [comment]
Thanks for your tips and patience =)

**Pull request closed without merging**
