### PR TITLE
Add Icons

### PR DESCRIPTION
**Pull request by notlmn**
https://github.com/notlmn/awesome-icons

I've been into web development for 5 years, but the number of icon projects that people know are very limited (like FontAwesome, Material Design, and maybe Octicons).

This list provides a list of awesome enough icon projects that are awesome enough, hosted mostly on GitHub.

---------------

By submitting this pull request I confirm I've read and complied with the requirements mentioned in PR template, except for
- having a more detailed explanation in the readme, I think the list is enough descriptive
- ~having a `contribution.md` file~ (fixed)

### CODE REVIEW

**Comment by notlmn** [comment]
Updated the repo with contribution guidelines and CoC, also setup to automatically lint using `awesome-lint`.

**Comment by sindresorhus** [comment]
> This pull request has a descriptive title in the format Add Name of List (Example: Add Swift), not Update readme.md or Add awesome list.

**Comment by sindresorhus** [comment]
> Be added at the bottom of the appropriate category.

**Comment by sindresorhus** [comment]
> Includes a project logo/illustration whenever possible.

Your list is about icons. Makes sense to have an actual icon graphic in it.

**Comment by sindresorhus** [comment]
`downloadable SVG/PNG/Font icon projects` => `downloadable SVG/PNG/font icon projects`

**Comment by notlmn** [comment]
I've added a graphic that is somewhat closely related to icons.

Please review again.

**Comment by sindresorhus** [comment]
> downloadable SVG/PNG/Font icon projects => downloadable SVG/PNG/font icon projects

This was not done in your readme.

**Comment by sindresorhus** [comment]
> One tag One icon, no font or svg, pure CSS.

I know you didn't write the descriptions, but it's expected that you ensure the descriptions are of high quality too. Please go through each description and improve them.

**Comment by sindresorhus** [comment]
The section descriptions should also end in a `.`.

**Comment by notlmn** [comment]
> > downloadable SVG/PNG/Font icon projects => downloadable SVG/PNG/font icon projects
> 
> This was not done in your readme.

Oh, I only changed that in the readme and not in the repo description. Done now.

--------------------

> The section descriptions should also end in a `.`.

Done.

--------------------

> > One tag One icon, no font or svg, pure CSS.
> 
> I know you didn't write the descriptions, but it's expected that you ensure the descriptions are of high quality too. Please go through each description and improve them.

I didn't mean to change them from what the original author intended them to be, so left them as is. Changed this one though.

**Comment by sindresorhus** [comment]
> I didn't mean to change them from what the original author intended them to be, so left them as is. 

You should. From experience, most authors have no idea how to write good descriptions. For example, in Awesome Node.js I have pretty much rewritten the description for every entry.

**Comment by sindresorhus** [comment]
Tweet: https://twitter.com/awesome__re/status/1129292915191140352

**Pull request merged**
