### PR TITLE
Add Ethereum

### PR DESCRIPTION
**Pull request by Tom2718**
**https://github.com/Tom2718/Awesome-Ethereum**

Ethereum is a decentralized platform for creating smart contracts. There are lots of resources available that are outdated and deprecated. This awesome list aims to keep only up-to-date and relevant links. Furthermore, other lists focus too much on bringing publicity to other projects. I don't want this to happen and so won't include any projects being built on top of Ethereum. 

**Reviewed PRs**
[1431 Comment](https://github.com/sindresorhus/awesome/pull/1431#issuecomment-434213289)
[1437 Comment](https://github.com/sindresorhus/awesome/pull/1437#issuecomment-434211965)

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

## Requirements for your pull request

- **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).** Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration.
- I have read and understood the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title in the format `Add Name of List` (Example: `Add Swift`), not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
	- Be added at the bottom of the appropriate category.
- The list I'm submitting complies with the below requirements.

## Requirements for your Awesome list

- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
- It's the result of hard work and the best I could possibly produce.
- Non-generated Markdown file in a GitHub repo.
- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
- Not a duplicate.
- Only has awesome items. Awesome lists are curations of the best, not everything.
- Includes a project logo/illustration whenever possible.
	- Either centered, fullwidth, or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
	- The image should link to the project website or any relevant website.
	- The image should be high-DPI. Set it to maximum half the width of the original image.
- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
	- Should be placed on the right side of the readme heading.
		- Can be placed centered if the list has a centered graphics header.
	- Should link back to this list.
- Has a Table of Contents section.
	- Should be named `Contents`, not `Table of Contents`.
	- Should be the first section in the list.
	- Should only have one level of [nested lists](https://commonmark.org/help/tutorial/10-nestedLists.html), preferably none.
- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
	- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
	- [WTFPL](http://www.wtfpl.net) and [Unlicense](http://unlicense.org) are not acceptable licenses.
	- If you use a license badge, it should be SVG, not PNG.
- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
	- The file should be named `contributing.md`. Casing is up to you.
- Has consistent formatting and proper spelling/grammar.
	- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
	- The description starts with an uppercase character and ends with a period.
	- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.

Go to the top and read it again.

### CODE REVIEW

**Comment by benedekrozemberczki** [comment]
[x] Has 2 reviews.
[x] Pull request is done with proper heading.
[x] It is old enough.
[x] Has a logo and it is properly placed.
[x] Includes the Awesome badge.
[x] The repo has a TOC.
[x] The repo has a proper license.
[x] Has a contributing.md it is properly named.

**Comment by dreamingechoes** [comment]
Looks good, but it seems that there's another pull request about Ethereum opened: https://github.com/sindresorhus/awesome/pull/1429. I don't know what's the way to solve this kind of situations, maybe @sindresorhus can help with this 😄

**Comment by damccorm** [comment]
This list looks good stylistically to me (I don't have anything to add here), but there are now 2 other Ethereum PR's: #1486 and #1429. Maybe you can coordinate with them and try to combine lists and make sure nothing is missing?

**Comment by sindresorhus** [comment]
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

**Comment by sindresorhus** [comment]
```
❯ awesome-lint https://github.com/Tom2718/Awesome-Ethereum
✖ Linting

  readme.md:47:3
  ✖   40:4    Text "Github" should be written as "GitHub"             awesome/spell-check
  ✖   47:3    Incorrect indentation before bullet: remove 1 space     list-item-bullet-indent
  ✖   47:45   List item description must start with valid casing      awesome/list-item
  ✖   48:3    Incorrect indentation before bullet: remove 1 space     list-item-bullet-indent
  ✖   48:58   List item description must start with valid casing      awesome/list-item
  ✖   49:3    Incorrect indentation before bullet: remove 1 space     list-item-bullet-indent
  ✖   49:51   List item description must start with valid casing      awesome/list-item
  ✖   50:3    Incorrect indentation before bullet: remove 1 space     list-item-bullet-indent
  ✖   51:3    Incorrect indentation before bullet: remove 1 space     list-item-bullet-indent
  ✖  105:4    Text "Youtube" should be written as "YouTube"           awesome/spell-check
  ✖  106:4    Text "Youtube" should be written as "YouTube"           awesome/spell-check
  ✖  117:49   List item description must start with valid casing      awesome/list-item
  ✖  127:65   List item description must start with valid casing      awesome/list-item
  ✖  139:49   Text "javascript" should be written as "JavaScript"     awesome/spell-check
  ✖  149:69   List item description must end with proper punctuation  awesome/list-item
  ✖  150:324  List item description must end with proper punctuation  awesome/list-item
  ✖  151:154  List item description must end with proper punctuation  awesome/list-item
  ✖  158:49   List item description must start with valid casing      awesome/list-item
  ✖  168:4    Text "Github" should be written as "GitHub"             awesome/spell-check

  19 errors
```

https://github.com/sindresorhus/awesome-lint

**Comment by Tom2718** [comment]
Fixed (and added Travis linting)

**Comment by sindresorhus** [comment]
> Includes a succinct description of the project/theme at the top of the readme. (Example)

---

> Includes a project logo/illustration whenever possible.
> **The image should be high-DPI. Set it to maximum half the width of the original image.**

---

Linkify `Ethereum` in `An awesome list about everything related to the Ethereum platform.` to the wikipedia page for it.

---

I don't think the `Inspired by Awesome Python and Awesome Machine Learning` line is very useful. If you really want it I would place it at the end of the readme.

---

The items in the `Documentation` section doesn't need the `Ethereum` prefix. It's implied.

**Comment by Tom2718** [comment]
Done. I'm very impressed by how in-depth you are!

**Comment by sindresorhus** [comment]
The `An awesome list about everything related to the Ethereum platform. Ethereum is an open-source, blockchain and smart contract computing platform.` looks unaligned. Can you add a force linebreak (`<br>`) between the sentences?

**Comment by sindresorhus** [comment]
> Done. I'm very impressed by how in-depth you are!

The project is called Awesome after all :)

**Comment by sindresorhus** [comment]
Thank you for the quick response.

**Comment by sindresorhus** [comment]
Tweet: https://twitter.com/awesome__re/status/1089110258943909890

**Pull request merged**
