### PR TITLE
Add Fuse

### PR DESCRIPTION
**Pull request by vinkla**
Do you agree this should be under platforms?

### CODE REVIEW

**Comment by sindresorhus** [comment]
I think `Miscellaneous` would be a better fit.

**Comment by vinkla** [comment]
Fuse is very similar to Cordova, React and Xamarin.

**Comment by bentstamnes** [comment]
@sindresorhus I second @vinkla on this - Fuse is definitely a fully fledged platform for native app development.

**Comment by sindresorhus** [comment]
Oh, I thought this was an awesome list for [FUSE](https://en.wikipedia.org/wiki/Filesystem_in_Userspace).

**Comment by vinkla** [comment]
:+1:

**Comment by bentstamnes** [comment]
@sindresorhus I can see the conFUSEion. ;)

**Comment by sindresorhus** [comment]
Would be awesome if you could add the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) to your readme :D

**Comment by vinkla** [comment]
I'll fix that asap ;)

**Pull request closed without merging**
