### PR TITLE
Add Peer-to-peer

### PR DESCRIPTION
**Pull request by RichardLitt**
Looks awesome.

### CODE REVIEW

**Comment by sindresorhus** [comment]
@kgryte Can you read the [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md), and ensure you follow it? Quick things I noticed: add description to all items, use a better license (see awesome manifest), contributing guidelines.

**Comment by sindresorhus** [comment]
Closing as @kgryte said he created the list for himself and don't intend to maintain it.

**Comment by kgryte** [comment]
Actually, I never said that I don't intend to maintain it. I stated that I "am not looking to maintain it for anyone other than myself".

**Comment by RichardLitt** [comment]
Regardless of contrib guidelines, manifestos, or intent to maintain: it is still a pretty incredible list, and should be on this list of awesome lists. 

@kgryte, well done.

**Comment by sindresorhus** [comment]
> am not looking to maintain it for anyone other than myself

@RichardLitt :arrow_up: Awesome lists are collaborative. Do a fork that welcomes contributions and I'll be happy to include it.

**Comment by retrohacker** [comment]
Started a curated list here: https://github.com/retrohacker/awesome-decentralization.

The purpose of this list is to act as a jumping off point for people wanting to build decentralized applications w/ untrusted peers. It has a collection of libraries broken apart by programming language, a collection of platforms and services (databases, etc.), and a collection of research papers.

**Pull request closed without merging**
