### PR TITLE
Add Progressive Web Apps

### PR DESCRIPTION
**Pull request by TalAter**
**https://github.com/TalAter/awesome-progressive-web-apps**

A curated list of only the best learning resources, reference material, videos, tutorials and case studies for progressive web apps.

**I know this repo is less than 20 days old, but I have actually been working on this list as research for my book for the past 4 months. I have read every single article on the list (and many others) and only included the best.**

# ALL THE BELOW CHECKBOXES SHOULD BE DONE AND CHECKED AND THE ABOVE PLACEHOLDERS SHOULD BE FILLED IN BEFORE SUBMITTING A PULL REQUEST!

- [x] I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- [x] This pull request has a descriptive title. *(For example: `Add Node.js`)*
- The list I added
	- [ ] **has been around for at least 20 days,**
	- [x] is not a duplicate,
	- [x] only has awesome items with descriptions *(Awesome lists are curations of the best, not of everything)*,
	- [x] contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- [x] has a Table of Contents section named `Contents` as the first section,
	- [x] has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license) *(Meaning something like CC0, NOT a code licence like MIT, BSD, Apache, etc)*,
	- [x] has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- [x] has been checked for inconsistent formatting, spelling, and grammar *(This includes starting each link description with an uppercase character and ending it with a dot, and consistent naming)*,
	- [x] has been added at the bottom of the appropriate category.

### CODE REVIEW

**Comment by sindresorhus** [comment]
You need to update the email here: https://github.com/TalAter/awesome-progressive-web-apps/blob/master/code-of-conduct.md Same here: https://github.com/TalAter/awesome-service-workers/blob/master/code-of-conduct.md

**Comment by sindresorhus** [comment]
I would include some examples of great progressive web apps. Like https://www.pokedex.org/, https://jakearchibald.github.io/svgomg/, https://aerotwist.com/blog/guitar-tuner/, https://voice-memos.appspot.com/

And some tools: https://github.com/TalAter/UpUp (😎), https://github.com/NekR/offline-plugin, etc.

**Comment by TalAter** [comment]
Fixed the emails.

Great idea on the samples. Added.
👍

**Comment by jsynowiec** [comment]
There is already PWA list that is available longer: https://github.com/hemanth/awesome-pwa and that's why I didn't create a new one a few days ago and started contributing to awesome service-worker ;-)

**Pull request merged**
