### PR TITLE
Add LÖVE

### PR DESCRIPTION
**Pull request by rm-code**

### CODE REVIEW

**Comment by aleksandar-todorovic** [comment]
License?

**Comment by rm-code** [comment]
Will ask the maintainer to add one :+1:

**Comment by JanWerder** [comment]
Added a CC0 License for the list

**Comment by rm-code** [comment]
Done @aleksandar-todorovic - see https://github.com/JanWerder/awesome-love2d/commit/be63859b23658634d2ae166465bf67306581119e

Awesome badge has been added via https://github.com/JanWerder/awesome-love2d/commit/857d78fddc8aec59a0cd289aac3be973e7051382

**Comment by rm-code** [comment]
Thanks @JanWerder  :+1:

**Comment by davisonio** [comment]
Looks good, I've created a pull request at https://github.com/JanWerder/awesome-love2d/pull/44 which adds a link to the LÖVE website in the description :smile:

**Comment by JanWerder** [comment]
Added the link to love2d.org

**Comment by sindresorhus** [comment]
I'd like to see the list cover more than just libraries, like tutorials, articles, talks, and could use a [community section](https://github.com/sindresorhus/awesome-electron#community).

**Pull request closed without merging**
