### PR TITLE
Add Awesome Free Services List

### PR DESCRIPTION
**Pull request by hungle88**
**https://github.com/hungle88/awesome-free-services**

**A curated list of awesome free online services for startups and freelancers! Every service in the list offers at least a free plan.**

# ALL THE BELOW CHECKBOXES SHOULD BE DONE AND CHECKED AND THE ABOVE PLACEHOLDERS SHOULD BE FILLED IN BEFORE SUBMITTING A PULL REQUEST!

- [x] I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- [x] This pull request has a descriptive title. *(For example: `Add Node.js`)*
- The list I added
	- [x] **has been around for at least 20 days,**
	- [x] is a non-generated Markdown file in a GitHub repo,
	- [x] is not a duplicate,
	- [ ] only has awesome items with descriptions *(Awesome lists are curations of the best, not of everything)*,
	- [x] contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- [ ] has a Table of Contents section named `Contents` as the first section,
	- [x] has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license) *(Meaning something like CC0, NOT a code licence like MIT, BSD, Apache, etc)*,
	- [ ] has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- [x] has been checked for inconsistent formatting, spelling, and grammar *(This includes starting each link description with an uppercase character and ending it with a period `.`, and consistent naming)*,
	- [x] has been added at the bottom of the appropriate category.

A curated list of awesome free online services for startups and freelancers! Every service in the list offers at least a free plan.

### CODE REVIEW

**Comment by sindresorhus** [comment]
> ALL THE BELOW CHECKBOXES SHOULD BE DONE AND CHECKED AND THE ABOVE PLACEHOLDERS SHOULD BE FILLED IN BEFORE SUBMITTING A PULL REQUEST!

I've unchecked the one that are not done.

---

This is also a duplicate of https://github.com/ripienaar/free-for-dev

**Comment by hungle88** [comment]
Yeah, you might be right. Will update & open another PR later.

**Comment by aleksandar-todorovic** [comment]
There's no need to open another PR. If there already is an awesome list trying to accomplish the same thing (which, in this case, there is), you should make PRs to the existing list instead of trying to create your own. The whole point of awesome lists is to collaborate..

**Comment by hungle88** [comment]
@aleksandar-todorovic Makes sense!

**Pull request closed without merging**
