### PR TITLE
add Kendo UI

### PR DESCRIPTION
**Pull request by codylindley**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please read the [instructions](https://github.com/sindresorhus/awesome/blob/master/create-list.md) for creating a new list, [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

Especially this part:

> Wait at least a couple of weeks after creating a list before submitting to give it a chance to mature.

Ping me here in a few weeks and I'll reopen ;)

**Comment by codylindley** [comment]
Is this the only rule you believe I have broken?

**Comment by sindresorhus** [comment]
No

**Comment by codylindley** [comment]
I added a license. Is that what I missed?

**Comment by aleksandar-todorovic** [comment]
Contributing guidelines?

**Pull request closed without merging**
