### PR TITLE
Awesome Persian NLP/IR, Tools And Resources

### PR DESCRIPTION
**Pull request by mhbashari**
**https://github.com/mhbashari/awesome-persian-nlp-ir**

*The best resource and tools for natural language processing and information retrieval experts wanna to build Persian language based system or research about new methods and paradigms in that two (Persian NLP and Persian IR).Because of the rareness of data,corpus and easy-to-use tools in such fields, this curated list can accelerate the initial steps of research or developing. **

# ALL THE BELOW CHECKBOXES SHOULD BE DONE AND CHECKED AND THE ABOVE PLACEHOLDERS SHOULD BE FILLED IN BEFORE SUBMITTING A PULL REQUEST!

- [x] I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- [x] This pull request has a descriptive title. *(For example: `Add Node.js`)*
- The list I added
	- [x] **has been around for at least 20 days,**
	- [x] is a non-generated Markdown file in a GitHub repo,
	- [x] is not a duplicate,
	- [x] only has awesome items with descriptions *(Awesome lists are curations of the best, not of everything)*,
	- [x] contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- [x] has a Table of Contents section named `Contents` as the first section,
	- [x] has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license) *(Meaning something like CC0, NOT a code licence like MIT, BSD, Apache, etc)*,
	- [x] has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- [x] has been checked for inconsistent formatting, spelling, and grammar *(This includes starting each link description with an uppercase character and ending it with a period `.`, and consistent naming)*,
	- [x] has been added at the bottom of the appropriate category.

### CODE REVIEW

**Comment by sindresorhus** [comment]
> only has awesome items **with descriptions**

**Comment by sindresorhus** [comment]
Please actually read the following this time:

> ALL THE BELOW CHECKBOXES SHOULD BE DONE AND CHECKED AND **THE ABOVE PLACEHOLDERS SHOULD BE FILLED IN** BEFORE SUBMITTING A PULL REQUEST!

**Comment by mhbashari** [comment]
Descriptions added (as much as possible)
:)

**Comment by aleksandar-todorovic** [comment]
> This is the list of some popular attempts.

What?

> has been checked for inconsistent formatting, spelling, and grammar (This includes starting each link description with an uppercase character and ending it with a period ., and consistent naming),

No it hasn't. Example proving it:

> tok-tokTok-tok is a fast, simple, multilingual tokenizer(single .pl file).

>  only has awesome items with descriptions

No it doesn't.

**Comment by mhbashari** [comment]
Recheck Please...

**Comment by davisonio** [comment]
> Recheck Please...

There's still some inconsistencies, e.g. this line:
``` Mojgan Seraji Corpus - is a modified version of the Bijankhan corpus```
Should start with a capital and end with a dot.

Some descriptions like [this one](https://github.com/mhbashari/awesome-persian-nlp-ir#ir-crawling-and-linking-evaluation) could be more concise.

Also your links are rubbish, what's the URL shortener necessary for? This one for example does not even lead to the page and the iframe is broken http://mhbashari.ir/url/tok-tok

**Comment by mhbashari** [comment]
Original links replaced...

**Comment by mhbashari** [comment]
Hi!
Please open the issue or report probable problems.
Thank you very much.

**Comment by aleksandar-todorovic** [comment]
Still no consistency.

Example:

> polyglot (polarity) - Natural language pipeline that supports massive multilingual applications (Like Tokenization (165 Languages),Language detection (196 Languages), Named Entity Recognition (40 Languages),Part of Speech Tagging (16 Languages),Sentiment Analysis (136 Languages),Word Embeddings (137 Languages),Morphological analysis (135 Languages),Transliteration (69 Languages)).

* No idea why are these words capitalized.
* After some of the commas, there's a space character, after others, there is no space character.

**Comment by mhbashari** [comment]
In Addition to your request(Comma and Capitalization) the replicated "polylot" title is removed.

**Comment by mhbashari** [comment]
Please check again ...

**Comment by mhbashari** [comment]
Check again please...

**Pull request closed without merging**
