### PR TITLE
Add Grid Layout

### PR DESCRIPTION
**Pull request by simoneas02**
**[https://github.com/simoneas02/awesome-grid-layout](https://github.com/simoneas02/awesome-grid-layout)**

**A curated list of CSS Grid Layout Module or only Css Grid. Inspired by awesome-flexbox**

# By submitting this pull request I confirm I've read and complied with the below requirements.

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title.<br>For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
	- Be added at the bottom of the appropriate category.
- The list I'm submitting complies with these requirements:
	- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
	- It's the result of hard work and the best I could possibly produce.
	- Non-generated Markdown file in a GitHub repo.
	- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
	- Not a duplicate.
	- Only has awesome items. Awesome lists are curations of the best, not everything.
	- Includes a project logo/illustration whenever possible.
		- Placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
		- The image should link to the project website or any relevant website.
		- The image should be high-DPI. Set it to maximum half the width of the original image.
	- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
	- Has the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- Has a Table of Contents section.
		- Should be named `Contents`, not `Table of Contents`.
		- Should be the first section in the list.
	- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
		- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
		- If you use a license badge, it should be SVG, not PNG.
	- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
		- The file should be named `contributing.md`. Casing is up to you.
	- Has consistent formatting and proper spelling/grammar.
		- Each link description starts with an uppercase character and ends with a period.<br>Example: `- [AVA](…) - JavaScript test runner.`
		- Drop all the `A` / `An` prefixes in the descriptions.
		- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
	- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.
- Go to the top and read it again.

### CODE REVIEW

**Comment by Jogai** [comment]
This anchor doesnt work: https://github.com/simoneas02/awesome-grid-layout#polyfills

**Comment by simoneas02** [comment]
Hi Jogai,
The anchor was fixed: https://github.com/simoneas02/awesome-grid-layout/commit/6c856cdb83a63388632167f52a69e2984a9e373a

**Comment by legodude17** [comment]
Not followed:
* Entries have a description
* Doesn't include a Travis badge.
* Has an appropriate license. - That means something like CC0, not a code licence like MIT, BSD, Apache, etc.
* The repo should have awesome-list & awesome as GitHub topics. I encourage you to add more relevant topics.
* Has the Awesome badge **on the right side of the list heading**,

**Comment by simoneas02** [comment]
fixed: https://github.com/simoneas02/awesome-grid-layout/commit/9d97a2309063f23b01d54c1ecd5ba904e81fbe9a

**Comment by legodude17** [comment]
Not followed:
* Drop all the A / An prefixes in the descriptions.

Suggestions:
* LEARN ABOUT THE NEW WAYS TO DO LAYOUT IN CSS. -> Learn about the new ways to do layout in css.
* Describe why we should follow the people

**Comment by simoneas02** [comment]
@legodude17 fixed: https://github.com/simoneas02/awesome-grid-layout/commit/4e2fb39fb0836bc094c464719604e265b1d2f339

**Comment by sindresorhus** [comment]
Nice work! This looks like a useful resource.


---

> A curated list of CSS Grid Layout Module or only Css Grid.

It's not clear what "or only Css Grid" means. I think it can be dropped.

---

The `CSS Grid Layout` text in `A curated list of CSS Grid Layout Module or only Css Grid.` should link to somewhere people can read more about CSS Grid Layout.

---

The header image should be high-DPI. Set it to maximum half the width of the original image.

---

> Has a Table of Contents section. Should be named **`Contents`, not `Table of Contents`**.

---

`Specification and Working Group -` => `Specification and Working Group`

---

`css` => `CSS`

---

> Drop all the `A` / `An` prefixes in the descriptions.

---

The entries in the `Who to Follow` section needs a description/bio.

`Chris Coyier@chriscoyier` => `Chris Coyier @chriscoyier` (Same with some of the other entries)

**Comment by sindresorhus** [comment]
ping @simoneas02

**Comment by sindresorhus** [comment]
ping

**Pull request closed without merging**
