### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by steve-vincent**
link to P2P awesome list

### CODE REVIEW

**Comment by steve-vincent** [comment]
https://github.com/steve-vincent/awesome-decentralized

**Comment by sindresorhus** [comment]
Please read the [instructions](https://github.com/sindresorhus/awesome/blob/master/create-list.md) for creating a new list, [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

Especially this part:

> Wait at least a couple of weeks after creating a list before submitting to give it a chance to mature.

Ping me here in a few weeks and I'll reopen ;)

**Comment by sindresorhus** [comment]
> The pull request and commit should have a useful title.
> \- https://github.com/sindresorhus/awesome/blob/master/contributing.md

**Comment by sindresorhus** [comment]
Could use some more content. See https://github.com/kgryte/awesome-peer-to-peer for inspiration. Might be worth including who to follow on Twitter and stuff about it, blog posts, videos, etc.

**Comment by steve-vincent** [comment]
Ok, thanks I had not seen that link...

Will do.

**Comment by retrohacker** [comment]
Started a curated list here: https://github.com/retrohacker/awesome-decentralization.

The purpose of this list is to act as a jumping off point for people wanting to build decentralized applications w/ untrusted peers. It has a collection of libraries broken apart by programming language, a collection of platforms and services (databases, etc.), and a collection of research papers.

**Pull request closed without merging**
