### PR TITLE
Add nginx-security list

### PR DESCRIPTION
**Pull request by stepan-i**
https://github.com/wallarm/awesome-nginx-security

This is a full list of all the talks, modules, articles on application security practices that are related to NGINX web-server and load balancer.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Hey, sorry for the lack of response, please see #1363.

**Comment by secfigo** [comment]
Missing contributing.md :)

**Comment by francoism90** [comment]
Would it be possible to merge this to https://github.com/fcambus/nginx-resources instead?

**Comment by sindresorhus** [comment]
@stepan-i ping :)

**Comment by sindresorhus** [comment]
Closing for lack of response.

**Pull request closed without merging**
