### PR TITLE
Add Redux

### PR DESCRIPTION
**Pull request by brillout**
Follow up of https://github.com/sindresorhus/awesome/issues/714.
I'll do my best to maintain it.

**https://github.com/brillout/awesome-redux**

**Curated list of Redux resources**

- [x] I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- [x] This pull request has a descriptive title. *(For example: `Add Node.js`)*
- The list I added
	- [x] **has been around for at least 20 days,**
	- [x] is a non-generated Markdown file in a GitHub repo,
	- [x] is not a duplicate,
	- [x] only has awesome items with descriptions *(Awesome lists are curations of the best, not of everything)*,
	- [x] contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- [x] has a Table of Contents section named `Contents` as the first section,
	- [x] has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license) *(Meaning something like CC0, NOT a code licence like MIT, BSD, Apache, etc)*,
	- [x] has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- [x] has been checked for inconsistent formatting, spelling, and grammar *(This includes starting each link description with an uppercase character and ending it with a period `.`, and consistent naming)*,
	- [x] has been added at the bottom of the appropriate category.

https://github.com/brillout/awesome-redux

### CODE REVIEW

**Comment by sindresorhus** [comment]
Some feedback:

- Contribution guidelines should be in a separate file `contributing.md`, like all other lists does. See the one in this list for reference.
- Use `##` for sections and increase it by one `#` for further sub-sections. The current formatting is pretty weird.
- There should be a succinct description of what Redux is at the top.
- `redux` => `Redux`
- Include some links to some community places, like forums, chats, IRC, gitter, slack, reddit, etc.
- Include project logo in the top right, like e.g. https://github.com/sindresorhus/awesome-electron

**Comment by brillout** [comment]
- [x] Contribution guidelines should be in a separate file contributing.md, like all other lists does. See the one in this list for reference.
 
- [x] Use ## for sections and increase it by one # for further sub-sections. The current formatting is pretty weird.

- [x] There should be a succinct description of what Redux is at the top.

- [x] redux => Redux.

- [ ] Include some links to some community places, like forums, chats, IRC, gitter, slack, reddit, etc.

- [x] Include project logo in the top right, like e.g. https://github.com/sindresorhus/awesome-electron.


I couldn't find any forums, chats, IRC, gitter, slack, reddit. They don't seem to exist.


Thanks for the feedback.

**Comment by sindresorhus** [comment]
- Drop all the `A` and `An` from the descriptions. Sounds better without and is more consistent.
- Drop the `<br/>` after `## Contents`

> I couldn't find any forums, chats, IRC, gitter, slack, reddit. They don't seem to exist.

In less than 30 seconds, I found:

- Discord chat: https://github.com/reactjs/redux#discussion
- IRC, look at the badge at the top of the readme.
- Slack: http://slack.redux.io/
- Reddit: https://www.reddit.com/r/reduxjs/
- Gitter: https://gitter.im/reactjs/redux

**Comment by brillout** [comment]
- [x] Drop all the A and An from the descriptions. Sounds better without and is more consistent.

 - [x] Drop the \<br/\> after ## Contents

 - [x] Include some links to some community places, like forums, chats, IRC, gitter, slack, reddit, etc.

The awesome list looks much better now, thanks!

> In less than 30 seconds

I checked https://www.reddit.com/r/redux and since it doesn't exist I (wrongly) assumed there wouldn't be a redux subreddit. I checked both redux.js.org and the readme but overlooked the badges. I googled for "discord redux" and found Reactiflux but since it says "Open community for all things React"  I assumed it wouldn't be the right place for Redux. Googling "gitter reddit" didn't show https://gitter.im/reactjs/redux. I didn't think about Slack.
I should have searched more thoroughly though. Sorry about that and thanks for finding them all.

**Comment by sindresorhus** [comment]
> Find the Redux community on Reddit, Discord, Slack, Gitter, or #rackt on freenode.

Should just be placed like any other content in the list. See: https://github.com/sindresorhus/awesome-electron#community

**Comment by brillout** [comment]
- [x] Should just be placed like any other content in the list

**Pull request merged**
