### PR TITLE
Add Awesome Git Addons

### PR DESCRIPTION
**Pull request by stevemao**
A curated list of addons that extends git cli.

```
$ git bla
```

### CODE REVIEW

**Comment by arthurvr** [comment]
Make sure it follows https://github.com/sindresorhus/awesome/blob/master/awesome.md. It doesn't have a license, for example.

**Comment by sindresorhus** [comment]
Cool idea, but the formatting here is off: https://github.com/stevemao/awesome-git-addons#git-up---fetch-and-rebase-all-locally-tracked-remote-branches

Description shouldn't be in the header.

**Comment by sindresorhus** [comment]
Please read the [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

Especially this part:

> Wait at least a couple of weeks after creating a list before submitting to give it a chance to mature.

Ping me here in a few weeks and I'll reopen ;)

**Comment by stevemao** [comment]
I have changed the content five days ago and I can't think of anything else to improve. I mean the format 
```
$ git bla
boom!
```
is what I want. Feedback welcome :)

**Comment by sindresorhus** [comment]
These still need examples: https://github.com/stevemao/awesome-git-addons#imerge-continue

**Comment by stevemao** [comment]
I'm not familiar with `git-imerge`, I'll try it out sometime. Other than that it should be alright?

**Comment by sindresorhus** [comment]
Yes

**Comment by sindresorhus** [comment]
Landed.

And it's `Add-ons` not `Addons`.

**Comment by stevemao** [comment]
Thanks @sindresorhus , I thought about this but the name `awesome-git-addons` looks better than `awesome-git-add-ons` as it has one less hyphen.

**Pull request closed without merging**
