### PR TITLE
Adding incident response list to security category 

### PR DESCRIPTION
**Pull request by meirwah**
https://github.com/meirwah/awesome-incident-response

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please read the [instructions](https://github.com/sindresorhus/awesome/blob/master/create-list.md) for creating a new list, [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

Especially this part:

> Wait at least a couple of weeks after creating a list before submitting to give it a chance to mature.

Ping me here in a few weeks and I'll reopen ;)

**Comment by sindresorhus** [comment]
List generally looks good, but I would add a short introduction at the top on what the purpose of the list is and who it's for.

**Comment by meirwah** [comment]
Something like this:
```A curated list of tools and resources for security incident response, aimed to help security analysts and DFIR teams.```

**Comment by sindresorhus** [comment]
:+1: I would linkify `DFIR` to a place that explains it.

**Comment by meirwah** [comment]
@sindresorhus  can we reopen this?
I think the list has really matured since I opened this PR...

**Comment by sindresorhus** [comment]
Added.

**Pull request closed without merging**
