### PR TITLE
Add `Awesome Icons`

### PR DESCRIPTION
**Pull request by mrzmyr**
https://github.com/mrzmyr/awesome-icons

### CODE REVIEW

**Comment by arthurvr** [comment]
It's still a little light on content IMHO. Please check the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md), [`create-list.md`](https://github.com/sindresorhus/awesome/blob/master/create-list.md) and [the awesome manifesto](https://github.com/sindresorhus/awesome/blob/master/awesome.md). Also please don't remove that blank line.

**Comment by sindresorhus** [comment]
Yes, needs more content. The name is also very loose. You've chosen to cover icon fonts/packages, but it could also include articles on using icons, creating, etc.

**Comment by sindresorhus** [comment]
Closing for now. Ping me here in a few weeks and I'll reopen and reconsider.

**Comment by mrzmyr** [comment]
:+1: indeed, lets see in a few weeks.

**Pull request closed without merging**
