### PR TITLE
alphabetized all lists and headers

### PR DESCRIPTION
**Pull request by DrewWilson04**
Hey, how are you guys? In this PR, I alphabetized all the contents in the README file.

I alphabetized as stated below:
- the contents section stayed at the top
- the links in the contents header are all alphabetized
- headers themselves are in ABC order
- the lists in the header are alphabetized
- the sublists are also correctly alphabetized

If you noticed any problems with missing content/wrong alphabetization, please just leave a comment or [email me](mailto:hi@drew.cx) with the problem and I'll update it!

Thanks,
Drew

### CODE REVIEW

**Comment by sindresorhus** [comment]
Duplicate of #1109

**Comment by sindresorhus** [comment]
Thanks for the suggestion, but not interested in doing that.

**Comment by alechash** [comment]
I use this repo a lot, +1 for alphabetization. I think this should be reconsidered.

Or at least keep the headers alphabetized.

**Comment by Joramtech** [comment]
That's awesome

**Pull request closed without merging**
