### PR TITLE
Add Egocentric Vision

### PR DESCRIPTION
**Pull request by Sid2697**
[https://github.com/Sid2697/awesome-egocentric](https://github.com/Sid2697/awesome-egocentric)

This list contains papers and datasets related to the field of egocentric (first-person) vision. As the research community gains more interest in egocentric vision research, we believe this list will be a great reference for locating previous works and related resources.

Reviewed PRs:
- #1807
- #1797

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

## Requirements for your pull request

- **Don't waste my time.** Do a good job, adhere to all the guidelines, and be responsive.
- **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).**
	Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration. **Just commenting “looks good” or simply marking the pull request as approved does not count!** You have to actually point out mistakes or improvement suggestions.
- You have read and understood the [instructions for creating a list](create-list.md).
- This pull request has a title in the format `Add Name of List`.
	- ✅ `Add Swift`
	- ✅ `Add Software Architecture`
	- ❌ `Update readme.md`
	- ❌ `Add Awesome Swift`
	- ❌ `Add swift`
	- ❌ `Adding Swift`
	- ❌ `Added Swift`
- Your entry here should include a short description about the project/theme of the list. **It should not describe the list itself.** The first character should be uppercase and the description should end in a dot. It should be an objective description and not a tagline or marketing blurb.
	- ✅ `- [iOS](…) - Mobile operating system for Apple phones and tablets.`
	- ✅ `- [Framer](…) - Prototyping interactive UI designs.`
	- ❌ `- [iOS](…) - Resources and tools for iOS development.`
	- ❌ `- [Framer](…)`
	- ❌ `- [Framer](…) - prototyping interactive UI designs`
- Your entry should be added at the bottom of the appropriate category.
- The suggested Awesome list complies with the below requirements.

## Requirements for your Awesome list

- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
- Don't open a Draft / WIP pull request while you work on the guidelines. A pull request should be 100% ready and should adhere to all the guidelines when you open it.
- Run [`awesome-lint`](https://github.com/sindresorhus/awesome-lint) on your list and fix the reported issues. If there are false-positives or things that cannot/shouldn't be fixed, please [report it](https://github.com/sindresorhus/awesome-lint/issues/new).
- The default branch should be named [`main`, not `master`](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/).
- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- ✅ `Mobile operating system for Apple phones and tablets.`
	- ✅ `Prototyping interactive UI designs.`
	- ❌ `Resources and tools for iOS development.`
	- ❌ `Awesome Framer packages and tools.`
- It's the result of hard work and the best I could possibly produce.
	**If you have not put in considerable effort into your list, your pull request will be immediately closed.**
- The repo name of your list should be in lowercase slug format: `awesome-name-of-list`.
	- ✅ `awesome-swift`
	- ✅ `awesome-web-typography`
	- ❌ `awesome-Swift`
	- ❌ `AwesomeWebTypography`
- The heading title of your list should be in [title case](https://capitalizemytitle.com/) format: `# Awesome Name of List`.
	- ✅ `# Awesome Swift`
	- ✅ `# Awesome Web Typography`
	- ❌ `# awesome-swift`
	- ❌ `# AwesomeSwift`
- Non-generated Markdown file in a GitHub repo.
- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
- Not a duplicate. Please search for existing submissions.
- Only has awesome items. Awesome lists are curations of the best, not everything.
- Does not contain items that are unmaintained, has archived repo, deprecated, or missing docs. If you really need to include such items, they should be in a separate Markdown file.
- Includes a project logo/illustration whenever possible.
	- Either centered, fullwidth, or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
	- The image should link to the project website or any relevant website.
	- **The image should be high-DPI.** Set it to maximum half the width of the original image.
- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- Includes the [Awesome badge](awesome.md#awesome-badge).
	- Should be placed on the right side of the readme heading.
		- Can be placed centered if the list has a centered graphics header.
	- Should link back to this list.
- Has a Table of Contents section.
	- Should be named `Contents`, not `Table of Contents`.
	- Should be the first section in the list.
	- Should only have one level of [nested lists](https://commonmark.org/help/tutorial/10-nestedLists.html), preferably none.
- Has an appropriate license.
	- **We strongly recommend the [CC0 license](https://creativecommons.org/publicdomain/zero/1.0/), but any [Creative Commons license](https://creativecommons.org/choose/) will work.**
		- Tip: You can quickly add it to your repo by going to this URL: `https://github.com/<user>/<repo>/community/license/new?branch=master&template=cc0-1.0` (replace `<user>` and `<repo>` accordingly).
	- A code license like MIT, BSD, Apache, GPL, etc, is not acceptable. Neither are WTFPL and [Unlicense](https://unlicense.org).
	- Place a file named `license` or `LICENSE` in the repo root with the license text.
	- **Do not** add the license name or text to the readme. GitHub already shows the license name at the top of the repo.
	- To verify that you've read all the guidelines, please comment on your pull request with just the word `unicorn`.
- Has [contribution guidelines](awesome.md#include-contribution-guidelines).
	- The file should be named `contributing.md`. Casing is up to you.
- Has consistent formatting and proper spelling/grammar.
	- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
	- The description starts with an uppercase character and ends with a period.
	- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
- Doesn't use [hard-wrapping](https://stackoverflow.com/questions/319925/difference-between-hard-wrap-and-soft-wrap).
- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.
- Doesn't include an `Inspired by awesome-foo` or `Inspired by the Awesome project` kinda link at the top of the readme. The Awesome badge is enough.

**Go to the top and read it again.**

### CODE REVIEW

**Comment by Sid2697** [comment]
unicorn

**Comment by sindresorhus** [comment]
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

**Comment by Sid2697** [comment]
@JoseDeFreitas Thank you for your comments.
I agree with you, changing the name will make it clearer what the list is about. I'll make that change. Sure! I'll make sure to add a description on the `awesome-egocentric`  repo's page. However, I'm not sure if we are allowed to keep such a long description in the `awesome` repo's README.

@sindresorhus Thanks a lot for having a look at the repository! I tried my best to make sure to address all the points in the guidelines. It'll be great if you could let me know which specific point I'm missing. Thanks! @JoseDeFreitas can you please have a look at the repo once again and let me know the points I missed? Thanks!

**Comment by JoseDeFreitas** [comment]
@Sid2697 I reviewed your repository and everything in the list looks good according to the [guidelines](https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md), though I noticed this:

> Includes a project logo/illustration whenever possible.

Your list doesn't have a logo, but I've already seen lists without one so I'm not sure about this.

Also, I ran [`awesome-lint`](https://github.com/sindresorhus/awesome-lint) and I got 19 errors, all of them without a description, just pointing out some links you've written. I'm not sure why is your repository getting these errors. Maybe it's something about my set-up, I don't really know, so you should run `awesome-lint` by yourself and read through the errors.

**Comment by Sid2697** [comment]
@JoseDeFreitas Thanks a lot for having a look at the repository. Yeah, as adding the logo was optional (and egocentric vision is a concept), I did not create a logo. Which, I believe, should be fine.

For me also `awesome-lint` is generating 19 errors. But all of these errors are `double-link` warning. It is raised when we have links from the same website. For example, if you have added links to two different YouTube videos, then it'll raise this error as the website is same. There is an issue opened on the `awesome-lint` repository for fixing it. So, I believe that should also not be an issue in our case.

**Comment by margaretmz** [comment]
> For me also `awesome-lint` is generating 19 errors. But all of these errors are `double-link` warning. It is raised when we have links from the same website. For example, if you have added links to two different YouTube videos, then it'll raise this error as the website is same. There is an issue opened on the `awesome-lint` repository for fixing it. So, I believe that should also not be an issue in our case.

I found that links like this wouldn't be considered as dup: https://youtu.be/GBo4sFNzhtU while links like this would reported as dup by awesome-link: https://www.youtube.com/watch?v=L-73kgvrkho (by the way this video is private only). I fixed the links by going to each video and click on the Share button to get the youtu.be link.

**Comment by Sid2697** [comment]
@margaretmz Thanks for looking into the repository and sharing your thoughts. However, I don't think I have access to the second video that you shared. Thanks for the tip, I'll update the YouTube links. But there are links to lab's separate project pages which have same initial URL (as same lab). Do you have any idea how I can fix those? Apart from this, is there any other point that you think I'm missing? Thanks again for your time and help!

**Comment by margaretmz** [comment]
> Do you have any idea how I can fix those?

No I don't know how to fix the dup link issues. I also had a few dup links which were not possible to avoid. In the end I used a clunky solution: instead of embedding the actual link I used words to describe the search: _TensorFlow Hub - Set "Model format = TFLite" to find TFLite models._ That may not solve your particular problems though. 

Looking through [your awesome list](https://github.com/Sid2697/awesome-egocentric), I understand compiling links to papers and datasets will unavoidably result in dup links. Perhaps you could take this requirement up to the awesome owner? 

>Apart from this, is there any other point that you think I'm missing?
I found 2 other issues with your PR:
* "Your entry here should include a short description about the project/theme of the list. It should not describe the list itself." Your entry to the awesome list should describe what is egocentric vision, not what is the list about.
You have "Egocentric Vision - Resources for egocentric (first-person) vision." which should be "Egocentric Vision - A sub-field of computer vision that analyses image/video data obtained using a wearable camera simulating a person's visual field"

* "Your entry should be added at the bottom of the appropriate category." 
Right now your entry is under "Computer Science" and I think it's much more appropriate for it to be under "Computer Vision".

I'm also wondering whether you could help review my PR [1865](https://github.com/sindresorhus/awesome/pull/1865)? Thanks in advance.

**Comment by danforbes** [comment]
Fascinating topic and amazingly well-curated list of papers and datasets :exploding_head:

**Comment by Sid2697** [comment]
> No I don't know how to fix the dup link issues. I also had a few dup links which were not possible to avoid. In the end I used a clunky solution: instead of embedding the actual link I used words to describe the search: _TensorFlow Hub - Set "Model format = TFLite" to find TFLite models._ That may not solve your particular problems though.
> Looking through [your awesome list](https://github.com/Sid2697/awesome-egocentric), I understand compiling links to papers and datasets will unavoidably result in dup links. Perhaps you could take this requirement up to the awesome owner?

Sure, I'll try to dig more into this issue.

> * "Your entry here should include a short description about the project/theme of the list. It should not describe the list itself." Your entry to the awesome list should describe what is egocentric vision, not what is the list about.

Done! Thanks a lot for the suggestion.

> * "Your entry should be added at the bottom of the appropriate category."
>   Right now your entry is under "Computer Science" and I think it's much more appropriate for it to be under "Computer Vision".

This is a very valid suggestion. But, I was unable to find a dedicated "Computer Vision" tab on awesome's README. Is there a specific awesome list that you're referring to?

> I'm also wondering whether you could help review my PR [1865](https://github.com/sindresorhus/awesome/pull/1865)? Thanks in advance.

Sure! I'll review and add my comments on your PR.

@margaretmz Thanks a lot for your time.

@danforbes Thank you!

**Comment by margaretmz** [comment]
> I was unable to find a dedicated "Computer Vision" tab on awesome's README

"Computer Vision" is right below "Cryptography" - see below the screenshot.
image

> Sure! I'll review and add my comments on your PR.

Much appreciated! Looking forward to your feedback.

> @margaretmz Thanks a lot for your time.

You are welcome! I'm glad that I could help.

**Comment by Sid2697** [comment]
> "Computer Vision" is right below "Cryptography" - see below the screenshot.
> image

Yeah, I saw this one. But isn't it a topic in itself? And there is no other computer vision related awesome list under it. Will it be fine if I add mine there?

What I feel is, if there is a dedicated sub-heading on _Computer Vision_, where all the awesome lists related to various tasks are linked, could be great. What do you say?

**Comment by margaretmz** [comment]
> Yeah, I saw this one. But isn't it a topic in itself? And there is no other computer vision related awesome list under it. Will it
> be fine if I add mine there?

It's OK to be under an existing awesome list which becomes a sub-heading. In fact, all the other sub-heading are awesome lists themselves. Take a look at "Deep Learning" as an example. And it's OK if there is only one sub bullet point.

On a slightly different subject (of an existing entry) - in my opinion, "Deep Vision" should be under either "Computer Vision" or "Deep Learning" instead of on its own under "Computer Science".

> What I feel is, if there is a dedicated sub-heading on Computer Vision, where all the awesome lists related to various tasks > are linked, could be great. What do you say?

As I said above, the awesome list entry "Computer Vision" can also become a sub-heading so there is no need to create a dup for this purpose. Yes it would be great to have all the computer vision related entries there.

**Comment by Sid2697** [comment]
> It's OK to be under an existing awesome topic which becomes a sub-heading. In fact, all the other sub-heading are awesome lists themselves. Take a look at "Deep Learning" as an example. And it's OK if there is only one sub bullet point.

Yeah, this suggestion sounds great. I'll update the README according to it. 

> On a slightly different subject (of an existing entry) - in my opinion, "Deep Vision" should be under either "Computer Vision" or "Deep Learning" instead of on its own under "Computer Science".

The suggestion of adding "Deep Vision" under "Computer Vision" or "Deep Learning" also sounds good. I hope @sindresorhus could comment on that.

> As I said above, the awesome list entry "Computer Vision" can also become a sub-heading so there is no need to create a dup for this purpose. Yes it would be great to have all the computer vision related entries under it.

Noted. Will take care of it while updating.

I'm in the process of looking through your repository. Will comment by the end of this weekend. Thank you for your time and guidance.

**Comment by klaufel** [comment]
Hi, good list! 🤗

I think this `TODOs` section should not be there, you could include it as an issue. Will not meet the requirements.
https://github.com/Sid2697/awesome-egocentric-vision#todos

**Comment by Sid2697** [comment]
> Hi, good list! 🤗

Thank you!

> I think this `TODOs` section should not be there, you could include it as an issue. Will not meet the requirements.

Okay! I'll take care of that. Thank you for the suggestion.

**Comment by wernerkrauss** [comment]
Hi, I still get a bunch of duplicate link errors, when you first link to a "project page" or a "code" in an item, and later you have this project as a seperate item. You might disable the linting for this entries.

I understand that you want to provide extra value when linking to the projects from that papers, but are those awesome enough to be linked twice?

Also, there is one trailing dot missing in line 34....

```
$ awesome-lint https://github.com/Sid2697/awesome-egocentric-vision
- Linting(node:9980) ExperimentalWarning: The fs.promises API is experimental
× Linting

  README.md:70:301
  ×   34:179  List item description must end with proper punctuation          remark-lint:awesome-list-item
  ×   70:301  https://guiggh.github.io/publications/first-person-hands/       remark-lint:double-link
  ×   76:172  http://vision.cs.utexas.edu/projects/ego_snappoints/            remark-lint:double-link
  ×   76:243  http://vision.cs.utexas.edu/projects/ego_snappoints/#code       remark-lint:double-link
  ×  101:261  https://github.com/Mengmi/deepfuturegaze_gan                    remark-lint:double-link
  ×  116:336  https://iplab.dmi.unict.it/EgocentricShoppingCartLocalization/  remark-lint:double-link
  ×  134:217  http://vision.cs.utexas.edu/projects/egocentric/index.html      remark-lint:double-link
  ×  204:3    http://vision.cs.utexas.edu/projects/egocentric/index.html      remark-lint:double-link
  ×  207:3    https://github.com/Mengmi/deepfuturegaze_gan                    remark-lint:double-link
  ×  211:3    http://iplab.dmi.unict.it/EgocentricShoppingCartLocalization/   remark-lint:double-link
  ×  222:3    https://guiggh.github.io/publications/first-person-hands/       remark-lint:double-link

  11 errors
```

Reading your list, the "description" of an item is the author(s) and the year. While this is the academic citation standard, it's not an description of that awesome item.

Your contribution guidelines need some better explanation:

Quote: 
```
    Make sure you take care of this
    And this as well
    And don't forget to check this
```
Well, of _what_ should I take care?

**Comment by Sid2697** [comment]
@wernerkrauss Thank you for reviewing the list.

> I understand that you want to provide extra value when linking to the projects from that papers, but are those awesome enough to be linked twice?

Considering the level at which the community is, I feel that at this point it is important to keep these links. We can update them when the community grows bigger and there are a lot of awesome papers in the domain.

> Also, there is one trailing dot missing in line 34....

I have removed it. Thanks!

> Reading your list, the "description" of an item is the author(s) and the year. While this is the academic citation standard, it's not an description of that awesome item.

Thank you for pointing this out. Can you please give an example on how I should be updating the description?

> Your contribution guidelines need some better explanation.

Thank you for pointing it out. I have updated the contribution guidelines.

**Comment by sindresorhus** [comment]
Linkify in `Egocentric (first-person) vision` in `Egocentric (first-person) vision is a sub-field of computer vision that analyses image/video data obtained using a wearable camera simulating a person's visual field.` to https://en.wikipedia.org/wiki/Egocentric_vision

**Comment by sindresorhus** [comment]
> Entries have a description, unless the title is descriptive enough by itself. It rarely is though.

The paper entries need succinct summaries.

**Comment by sindresorhus** [comment]
Bump

**Pull request closed without merging**
