### PR TITLE
added WordPress awesome list under Platforms.

### PR DESCRIPTION
**Pull request by imknight**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Duplicate of https://github.com/sindresorhus/awesome/pull/385.

**Comment by jawshooah** [comment]
Not quite a dupe, as they are different lists maintained by different users.

**Comment by aleksandar-todorovic** [comment]
@jawshooah is right. This list is old enough and has a lot of content. Though, it is missing a license at the moment. Re-opening this for reconsideration.

**Comment by sindresorhus** [comment]
Happy to add it when @miziomon adds a license and reads the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

Closing for now. Happy to reopen when that's resolved.

**Pull request closed without merging**
