### PR TITLE
Add Tech Talks

### PR DESCRIPTION
**Pull request by fsjoyti**
Hello, this is my attempt to contribute to the awesome lists repo. 

https://github.com/fsjoyti/awesome-tech-talks

The objective of this list is to help people learn more about the various aspects of tech industry through tech conference videos. 

I went through the requirements and I think I got everything covered. Let me know what you think.

### CODE REVIEW

**Comment by fsjoyti** [comment]
Hello, this is my attempt to contribute to the awesome lists repo. 

https://github.com/fsjoyti/awesome-tech-talks

The objective of this list is to help people learn more about the various aspects of tech industry through tech conference videos. 

I went through the requirements and I think I got everything covered. Let me know what you think.

**Comment by akirak** [comment]
There is a list for [programming talks](https://github.com/hellerve/programming-talks), and its [software development](https://github.com/hellerve/programming-talks#software-development) subsection and [miscellenaous](https://github.com/hellerve/programming-talks#miscellaneous) section seem to have the similar purpose to your list. Have you ever considered contributing to the list? I'm afraid "tech" might be too broad. Perhaps you can create a list for specific subjects you are good at.

**Comment by ambster-public** [comment]
You should read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) again as your submission is obviously missing things and has numerous issues. Missing topics, table of contents, no idea of exactly what part of tech your selection is dedicated to, lack of structure, errors with awesome-lint, no contributions in the form of PR comments, no special comment intended to show you've actually at least read all the requirements, contribution guidelines linking to awesome-python's contribution guidelines, and more.

I'd recommend spending at least just a bit more time on working on this.

An even better idea is likely to be the following one: Consider researching [awesome](https://github.com/sindresorhus/awesome#readme) to find reps with talks and contributing there where you see fit.

**Comment by ravirupareliya** [comment]
There are few lint rules which are not followed. You can check [Requirements for your Awesome list](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md#requirements-for-your-awesome-list) and run [awesome-lint](https://github.com/sindresorhus/awesome-lint) on local machine to get all those errors.

**Comment by sindresorhus** [comment]
Closing for lack of response and the quality is not there yet.

**Pull request closed without merging**
