### PR TITLE
Add Biomarker and Blood Tests to Awesome

### PR DESCRIPTION
**Pull request by markwk**
**https://github.com/markwk/awesome-biomarkers**

**This is a list of biomarkers (in particularly blood) related to health and wellness. Includes intro to key biomarkers, some books, articles and technologies to better understand these.**

# By submitting this pull request I confirm I've read and complied with the below requirements.

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title.<br>For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
	- Be added at the bottom of the appropriate category.
- The list I'm submitting complies with these requirements:
	- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
	- It's the result of hard work and the best I could possibly produce.
	- Non-generated Markdown file in a GitHub repo.
	- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
	- Not a duplicate.
	- Only has awesome items. Awesome lists are curations of the best, not everything.
	- Includes a project logo/illustration whenever possible.
		- Either fullwidth or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
		- The image should link to the project website or any relevant website.
		- The image should be high-DPI. Set it to maximum half the width of the original image.
	- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
	- Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
		- Should be placed on the right side of the readme heading.
		- Should link back to this list.
	- Has a Table of Contents section.
		- Should be named `Contents`, not `Table of Contents`.
		- Should be the first section in the list.
		- Should only have one level of sub-lists, preferably none.
	- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
		- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
		- [WTFPL](http://www.wtfpl.net) and [Unlicense](http://unlicense.org) are not acceptable licenses.
		- If you use a license badge, it should be SVG, not PNG.
	- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
		- The file should be named `contributing.md`. Casing is up to you.
	- Has consistent formatting and proper spelling/grammar.
		- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
		- The description starts with an uppercase character and ends with a period.
		- Drop all the `A` / `An` prefixes in the descriptions.
		- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
	- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.
- Go to the top and read it again.

### CODE REVIEW

**Comment by legodude17** [comment]
Can you link all the items to more in-depth explanations?

**Comment by markwk** [comment]
Links added @legodude17. I have several articles I plan to add soon as well but this should cover the basic about major blood biomarkers.

**Comment by sindresorhus** [comment]
Hey, sorry for the lack of response, please see #1363.

**Comment by sindresorhus** [comment]
Can you fix the merge conflict?

**Comment by sindresorhus** [comment]
```
❯ awesome-lint https://github.com/markwk/awesome-biomarkers
✖ Linting

  readme.md:20:1
  ✖    1:1    License section must be at heading depth 2                    remark-lint:awesome/license
  ✖    1:1    Missing or invalid Table of Contents                          remark-lint:awesome/toc
  ✖    7:1    Don’t use multiple top level headings (1:1)                   remark-lint:no-multiple-toplevel-headings
  ✖   13:3    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   14:3    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   15:3    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   16:3    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   20:1    Don’t add a trailing : to headings                            remark-lint:no-heading-punctuation
  ✖   22:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   23:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   24:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   25:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   26:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   27:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   28:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   29:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   30:4    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   31:5    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   32:5    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   33:5    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   34:5    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   35:5    Invalid list item link                                        remark-lint:awesome/list-item
  ✖   37:1    Don’t add a trailing : to headings                            remark-lint:no-heading-punctuation
  ✖   39:66   List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖   40:64   List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖   41:66   List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖   42:67   List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖   44:1    Don’t add a trailing : to headings                            remark-lint:no-heading-punctuation
  ✖   48:52   List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖   49:66   List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖   50:58   List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖   51:61   List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖   52:67   List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖   53:60   List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖   54:82   List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖   56:64   List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖   58:64   List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖   60:85   List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖   61:98   List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖   62:102  List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖   64:63   List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖   69:1    Don’t add a trailing : to headings                            remark-lint:no-heading-punctuation
  ✖  100:64   List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖  101:140  List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖  102:176  List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖  106:3    Invalid list item link                                        remark-lint:awesome/list-item
  ✖  108:1    Don’t use multiple top level headings (1:1)                   remark-lint:no-multiple-toplevel-headings
  ✖  114:1    Don’t use multiple top level headings (1:1)                   remark-lint:no-multiple-toplevel-headings

  48 errors
```

https://github.com/sindresorhus/awesome-lint

**Comment by sindresorhus** [comment]
Closing for lack of response.

**Pull request closed without merging**
