### PR TITLE
Add Testing

### PR DESCRIPTION
**Pull request by TheJambo**
Should match all guidelines.

**https://github.com/TheJambo/awesome-testing**

**Software Testing resources and tools. Nothing like this except language-specific ones with developers in mind on your list currently.**

# By submitting this pull request I confirm I've read and complied with the below requirements.

Failure to properly do so will just result in the pull request being closed and everyone's time wasted. Please read it twice. Most people miss many things.

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title. For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should include a short description about the list project/theme (not the list itself), and should be added at the bottom of the appropriate category.
- The list I added
	- **has been around for at least 30 days,**
	- is the result of hard work and is the best I could possibly produce,
	- is a non-generated Markdown file in a GitHub repo,
	- is not a duplicate,
	- includes a succinct description of the project/theme at the top ([example](https://github.com/willempienaar/awesome-quantified-self)),
	- includes a project logo/illustration (whenever possible) at the top right of the readme ([example](https://github.com/sindresorhus/awesome-electron)). (The logo should link to the project website or any relevant website. The logo should be high-DPI, so set it to maximum half the width of the original image.),
	- only has awesome items **with descriptions** *(Awesome lists are curations of the best, not of everything)*,
	- contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- has a Table of Contents section **named `Contents`** as the first section,
	- has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license) *(Meaning something like CC0, NOT a code licence like MIT, BSD, Apache, etc)* *(If you use a license badge, it should be SVG, not PNG)*,
	- has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- doesn't include a Travis badge,
	- has been checked for inconsistent formatting, spelling, and grammar:
		- Each link description starts with an uppercase character and ends with a period.
		- Drop all the `A` / `An` prefixes in the descriptions.
		- Consistent naming. For example, `Node.js`, not `NodeJS` or `node.js`.

### CODE REVIEW

**Comment by sindresorhus** [comment]
> The entry in the Awesome list should include a short description about the list project/theme **(not the list itself)**, and should be added at the bottom of the appropriate category.

Please read this text carefully. It should be about what testing is, not what your list contains.

---

I don't think `Suggested Awesome Lists` should be first. The first thing the users sees shouldn't be references to other lists.

---

> Unicode - A great resource for learning how unicode works and the issues it can cause.

There should be an explanation how this is related to testing.

---

> Check All - Check all the checkboxes!

Needs a better description.

---

The items in the `Books` and `Training` sections doesn't seem related to "testing" at all.

**Comment by TheJambo** [comment]
The changes have been made to the list itself for the "Suggested awesome lists" section and reworking some of the descriptions.

Regarding the Books and Training section, Software testing training follows the same lines as software development for non-programming subjects. For example, you wouldn't read a Java 8 book to test a software package written in Java 8. However, to test a UI you might read "How to design a good UI". I have read the books myself and while they don't make testing clear in the title, they are well suited as a testing training tool.

Regarding the training sections, most testers are moving to Test Automation, which requires a certain level of Programming Language Training. 

I have also updated the Awesome List description to "Software Testing.". This is in line with similar size topics like "bots", you wouldn't want to write the dictionary definition of what a bot is because it's well known. For the same reason, I just put "Software" in there for clarity.

**Comment by sindresorhus** [comment]
> Regarding the Books and Training section, Software testing training follows the same lines as software development for non-programming subjects. For example, you wouldn't read a Java 8 book to test a software package written in Java 8. However, to test a UI you might read "How to design a good UI". I have read the books myself and while they don't make testing clear in the title, they are well suited as a testing training tool.

That's a good point and I don't disagree, but I think you should make it clear in their descriptions how they are related to testing. As someone that haven't read the books, I was wondering why they were included in the list.

> Regarding the training sections, most testers are moving to Test Automation, which requires a certain level of Programming Language Training.

Should also be made explicit. Was not clear. I think it would be better to just link to https://github.com/karlhorky/learn-to-program Seems out of scope of this list.

---

I think you should also make it clearer in the top short intro that this is about "quality assurance software testing", not "automated software (unit) testing". I was confused by that at first too.

---

Maybe include https://www.reddit.com/r/QualityAssurance/ ?

https://en.m.wikipedia.org/wiki/Software_quality_assurance ?

**Comment by TheJambo** [comment]
> > Regarding the Books and Training section, Software testing training follows the same lines as software development for non-programming subjects. For example, you wouldn't read a Java 8 book to test a software package written in Java 8. However, to test a UI you might read "How to design a good UI". I have read the books myself and while they don't make testing clear in the title, they are well suited as a testing training tool.
> 
> That's a good point and I don't disagree, but I think you should make it clear in their descriptions how they are related to testing. As someone that haven't read the books, I was wondering why they were included in the list.

Fair enough, I added the focus to each description.

> > Regarding the training sections, most testers are moving to Test Automation, which requires a certain level of Programming Language Training.
> Should also be made explicit. Was not clear. I think it would be better to just link to https://github.com/karlhorky/learn-to-program Seems out of scope of this list.

I added the awesome list to the training section and removed ones that are in the awesome list. The remaining programming training has been recommended by testers who found these particularly helpful, so I'm reluctant to remove them as they aren't in the list you linked.

>I think you should also make it clearer in the top short intro that this is about "quality assurance software testing", not "automated software (unit) testing". I was confused by that at first too.

Well, it does certainly need to be made more clear it seems! It's not about Unit testing as that is done by the developer role, but this is for Manual and Automated testers. The people who use this may not fall into the "Quality Assurance" title, but can fall under many such as "Software Tester", "Security Tester", "QA Engineer", "Automation Engineer" or "UX Tester". I added another quick sentence to the top of the page.

This list is targeted at anyone who does testing beyond the scope of the original developer. Unfortunately the only way to fully encompass all of these things is to just say it's "for testers".

> Maybe include https://www.reddit.com/r/QualityAssurance/ ?

I've been subscribed to that subreddit for a year and it's not very helpful. It's mostly people asking for help and getting bad replies and companies advertising their new crowd-sourcing testing platform. I did include a slack community which has a few thousand people and is open to questions if people have problems.

> https://en.m.wikipedia.org/wiki/Software_quality_assurance ?

The Wiki Page is even more confusing as that introduces "software design, coding, source code control" into the scope, which this list certainly doesn't cover!

**Pull request merged**
