### PR TITLE
Add Site Reliability Engineering

### PR DESCRIPTION
**Pull request by dastergon**
**https://github.com/dastergon/awesome-sre**

**The list contains useful resources (presentations, videos, articles, etc.) on Site Reliability Engineering.**

# ALL THE BELOW CHECKBOXES SHOULD BE DONE AND CHECKED AND THE ABOVE PLACEHOLDERS SHOULD BE FILLED IN BEFORE SUBMITTING A PULL REQUEST!

- [x] I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- [x] This pull request has a descriptive title. *(For example: `Add Node.js`)*
- The list I added
	- [x] **has been around for at least 20 days,**
	- [x] is not a duplicate,
	- [x] only has awesome items with descriptions *(Awesome lists are curations of the best, not of everything)*,
	- [x] contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- [x] has a `Table of Contents` as the first section,
	- [x] has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license) *(Meaning something like CC0, NOT a code licence like MIT, BSD, Apache, etc)*,
	- [x] has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- [x] has been checked for inconsistent formatting, spelling, and grammar *(This includes starting each link description with an uppercase character and ending it with a dot, and consistent naming)*,
	- [x] has been added at the bottom of the appropriate category.

The list contains useful resources (presentations, videos, articles, etc.) on Site Reliability Engineering.

### CODE REVIEW

**Comment by sindresorhus** [comment]
- Use `##` for the section headers, not `####`.
- There should be a succinct intro at the top about what `Site Reliability` and `Production Engineering resources` are, and those words should be linkified to a resource where the users can read more about it.
- The items in the `Blogs` and `Conferences` section should have a description.
- The items in the `Twitter` section should have description on who they are and why the user should care.
- Would be great if you could add some personal comments to some of the resources you've read/consumed with opinions/summary/etc.
- Totally optional, but would be cool to have an illustration at the top. Here's a good example: https://github.com/websemantics/awesome-synthetic-biology
- I can't really judge the content you've included in the list, but ensure all of it is awesome. Awesome lists are curations, not collections.

**Comment by dastergon** [comment]
@sindresorhus I have updated the content based on your recommendations.

**Comment by sindresorhus** [comment]
Thanks :)

One more thing: Be consistent about ending all descriptions in a `.`

**Comment by sindresorhus** [comment]
Added

**Comment by dastergon** [comment]
Thank you very much @sindresorhus!

**Pull request closed without merging**
