### PR TITLE
Add FFmpeg

### PR DESCRIPTION
**Pull request by transitive-bullshit**
[awesome-ffmpeg](https://github.com/transitive-bullshit/awesome-ffmpeg)

> A curated list of awesome ffmpeg resources with a focus on JavaScript.

FFmpeg is an extremely popular media editing tool that a lot of developers depend on.  I was pretty surprised to find that it didn't have an existing awesome list.

I have triple-checked the contributing guidelines and believe this list to be in conformance.

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

## Requirements for your pull request

- [x] I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- [x] This pull request has a descriptive title.<br>For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- [x] The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
	- Be added at the bottom of the appropriate category.
- [x] The list I'm submitting complies with these requirements:

## Requirements for your Awesome list

- [x] **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
- [x] It's the result of hard work and the best I could possibly produce.
- [x] Non-generated Markdown file in a GitHub repo.
- [x] **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
- [x] The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
- [x] Not a duplicate.
- [x] Only has awesome items. Awesome lists are curations of the best, not everything.
- [x] Includes a project logo/illustration whenever possible.
	- Either fullwidth or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
	- The image should link to the project website or any relevant website.
	- The image should be high-DPI. Set it to maximum half the width of the original image.
- [x] Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- [x] Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
	- Should be placed on the right side of the readme heading.
	- Should link back to this list.
- [x] Has a Table of Contents section.
	- Should be named `Contents`, not `Table of Contents`.
	- Should be the first section in the list.
	- Should only have one level of sub-lists, preferably none.
- [x] Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
	- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
	- [WTFPL](http://www.wtfpl.net) and [Unlicense](http://unlicense.org) are not acceptable licenses.
	- If you use a license badge, it should be SVG, not PNG.
- [x] Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
	- The file should be named `contributing.md`. Casing is up to you.
- [x] Has consistent formatting and proper spelling/grammar.
	- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
	- The description starts with an uppercase character and ends with a period.
	- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
- [x] Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.

Go to the top and read it again.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Hey, sorry for the lack of response, please see #1363.

**Comment by transitive-bullshit** [comment]
Hey @sindresorhus, thanks for all of your continued work on this project!

I've reviewed #1350 and #1330. I also made sure `awesome-ffmpeg` passes `awesome-lint` locally.

**Comment by sindresorhus** [comment]
You still need a description of FFmpeg in *your* readme too. Something like:

> FFmpeg is a cross-platform solution to record, convert and stream audio and video.

**Comment by sindresorhus** [comment]
Also note:

> Includes a project logo/illustration whenever possible.
> **The image should be high-DPI. Set it to maximum half the width of the original image.**

**Comment by sindresorhus** [comment]
We should also add `FFmpeg` to the spelling rule, as I see mixed use of `FFmpeg` and `ffmpeg`. It's fine to use `ffmpeg` when refering to the CLI, but I see many descriptions refering to the project as `ffmpeg` when it should be `FFmpeg`. Super nitpick though :p

**Comment by sindresorhus** [comment]
Maybe link to some FFmpeg communities/forums? And maybe also https://superuser.com/questions/tagged/ffmpeg

**Comment by transitive-bullshit** [comment]
Thanks for the in-depth feedback, Sindre. Just fixed most of these [here](https://github.com/transitive-bullshit/awesome-ffmpeg/commit/f433bcf4d526b44492950987bec84f5f39d8aab7).

> The image should be high-DPI. Set it to maximum half the width of the original image.

The current logo is an SVG image; wouldn't this be preferable to a high-DPI raster image?

I do think we could add an `awesome-lint` rule for this; just need to clarify the specific expectations.

> Maybe link to some FFmpeg communities/forums? 

Added.

**Comment by sindresorhus** [comment]
Oh sorry, I somehow missed that it was SVG.

**Comment by sindresorhus** [comment]
Tweet: https://twitter.com/awesome__re/status/1030087969644806144

**Comment by transitive-bullshit** [comment]
Thanks!

**Pull request merged**
