### PR TITLE
Update link to Grakn

### PR DESCRIPTION
**Pull request by vmax**
As we've going through the process of rebranding organisation (GraknLabs becomes Vaticle and Grakn becomes TypeDB), it makes sense to update the reference in Awesome Lists

### CODE REVIEW

**Comment by sindresorhus** [comment]
You're starting the rebranding in the wrong end. I expect the project website and Awesome list to be renamed first.

**Comment by d-wasserman** [comment]
Just checking on this to relate that Grakn still appears throughout the awesome-list.

**Comment by vmax** [comment]
@sindresorhus we've updated the branding on our side. Could you please revisit this PR?

**Comment by sindresorhus** [comment]
You need to fix the merge conflict.

**Pull request merged**
