### PR TITLE
Add Laravel Voyager List

### PR DESCRIPTION
**Pull request by marktopper**
https://github.com/larapack/awesome-voyager

Voyager is a popular admin panel system for Laravel which comes with lots of extensions and features. Therefor this list have been added.

> Please note, that according to the `doesn't include a Travis badge`, then why is it important that a awesome list does not include this Travis badge?

### CODE REVIEW

**Comment by marktopper** [comment]
Whoops: Haven't been around long enough.

**Comment by marktopper** [comment]
30 days later 😄

**Comment by davisonio** [comment]
If this is a popular admin system there should be lots more resources available: videos, tutorials, community, etc. would be cool to see a lot more content on this list (see others) :)

Please have a read through this, lots of things are not followed such as naming of 'Contents' and also the main header on the list is broken: https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md

**Comment by marktopper** [comment]
Cool 😎

**Pull request closed without merging**
