### PR TITLE
Add data visualization tools

### PR DESCRIPTION
**Pull request by fasouto**
Please let me know if something is wrong

### CODE REVIEW

**Comment by sindresorhus** [comment]
> Please let me know if something is wrong

You can easily do that yourself: https://github.com/sindresorhus/awesome/blob/master/contributing.md ;)

Also make sure you follow: https://github.com/sindresorhus/awesome/blob/master/awesome.md

**Comment by sindresorhus** [comment]
From a quick look; screenshots of the different charting libs would be nice. Hard to judge them just from the description.

**Comment by sindresorhus** [comment]
I think it's a good idea for a list, but gonna pass on it for now as we usually don't accept newly created lists, since they usually need some time to mature and it's a good way to make sure people are keep up maintaining it. Try submitting again in a month ;)

**Comment by fasouto** [comment]
I thought about adding screenshots but I think they are not a good way to compare the libraries. The real value resides in number of charts, interactivity, flexibility, customization ,ease of use... I think I'll just add a link to their example page.

I'll try in a month, thanks for your feedback :)

**Comment by sindresorhus** [comment]
> I thought about adding screenshots but I think they are not a good way to compare the libraries.

I agree it's not a good way to pick one, but it definitely helps with exclusion.

**Pull request closed without merging**
