### PR TITLE
Add Construct 2

### PR DESCRIPTION
**Pull request by armaldio**
**[https://github.com/armaldio/awesome-construct](https://github.com/armaldio/awesome-construct)**

**A curated list of tools, tutorials, examples, and much more, for the awesome game development engine Construct 2. Edit**

# By submitting this pull request I confirm I've read and complied with the below requirements.

Failure to properly do so will just result in the pull request being closed and everyone's time wasted. Please read it twice. Most people miss many things.

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title. For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should include a short description about the list project/theme (not the list itself), and should be added at the bottom of the appropriate category.
- The list I added
	- **has been around for at least 30 days,**
	- is the result of hard work and is the best I could possibly produce,
	- is a non-generated Markdown file in a GitHub repo,
	- is not a duplicate,
	- includes a succinct description of the project/theme at the top ([example](https://github.com/willempienaar/awesome-quantified-self)),
	- includes a project logo/illustration (whenever possible) at the top right of the readme ([example](https://github.com/sindresorhus/awesome-electron)). (The logo should link to the project website or any relevant website. The logo should be high-DPI, so set it to maximum half the width of the original image.),
	- only has awesome items **with descriptions** *(Awesome lists are curations of the best, not of everything)*,
	- contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- has a Table of Contents section **named `Contents`** as the first section,
	- has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license) *(Meaning something like CC0, NOT a code licence like MIT, BSD, Apache, etc)* *(If you use a license badge, it should be SVG, not PNG)*,
	- has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- doesn't include a Travis badge,
	- has been checked for inconsistent formatting, spelling, and grammar:
		- Each link description starts with an uppercase character and ends with a period.
		- Drop all the `A` / `An` prefixes in the descriptions.
		- Consistent naming. For example, `Node.js`, not `NodeJS` or `node.js`.

### CODE REVIEW

**Comment by sindresorhus** [comment]
> By submitting this pull request I confirm I've read and complied with the below requirements.

Please read it again. Many things not followed.

**Comment by armaldio** [comment]
@sindresorhus I think I've done the right fixes, thanks

**Comment by itsjtwright** [comment]
@armaldio might need to close this pr and make a new one

**Comment by davisonio** [comment]
- Youtube -> YouTube

Some of the links under `Other Sources` are not formatted correctly.

**Comment by armaldio** [comment]
Fixed :)

**Comment by sindresorhus** [comment]
> includes a succinct description of the project/theme at the top (example),

Missing.

> has contribution guidelines,

You just copy-pasted the ones from Awesome. That doesn't count. You should at least customize it for your list. For example, `Use the following format: [List Name](link)`, needs to be tweaked. The filename si wrong. It should be `contributing.md`, not `contribute.md`.

**Comment by armaldio** [comment]
Changes made, thanks

**Comment by sindresorhus** [comment]
Not all changes are done. Please read my whole comment.

**Comment by armaldio** [comment]
ok, fixed typos
Does the quote at the begining count as  a `succinct description` ?

Thanks

**Comment by sindresorhus** [comment]
> Does the quote at the begining count as a succinct description ?

Yes

**Pull request merged**
