### PR TITLE
Add Bug Bounty & Responsible Security Disclosure

### PR DESCRIPTION
**Pull request by djadmin**
A comprehensive curated list of available Bug Bounty & Disclosure Programs and write-ups by security researcher.
The repo is https://github.com/djadmin/awesome-bug-bounty

### CODE REVIEW

**Comment by aleksandar-todorovic** [comment]
Sorry, but I just don't see how listing of a bunch of bug bounty programs is beneficial to anyone. What makes them awesome? What is the criteria used here?

**Comment by djadmin** [comment]
Thanks for asking. For all the security researchers out there and the bug bounty hunters, this curated list is helpful in submitting any security vulnerability via the company's bug bounty program.

Each company will have their own set of rules and guidelines to participate in their bug bounty program and using this curated list, anyone can submit vulnerabilities via their bb program.

Some companies uses hackerone.com, bugcrowd.com, etc. and few have their own, so listing out all the  details under one roof is making it awesome.
Hope I'm clear.

**Comment by sindresorhus** [comment]
I think this list has potential, but the list of available programs is IMHO the least interesting and should be put at the bottom. The section with links to blogs is good. I would also like to see a curated section of good write-up blog posts. E.g. some of these: http://www.xsses.com/search/label/Google Would also be useful with link to some good talks on YouTube about the subject and other learning material for getting started with bug bounty'ing.

**Comment by sindresorhus** [comment]
In the "Write ups & authors" section I would simplify the blog link texts: `http://labs.detectify.com/` => `labs.detectify.com`

**Comment by sindresorhus** [comment]
Please read the [instructions](https://github.com/sindresorhus/awesome/blob/master/create-list.md) for creating a new list, [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md). You're missing something that are outlined in those, like not using MIT license and having a some good contributing guidelines.

**Comment by sindresorhus** [comment]
@djadmin ping :)

**Comment by djadmin** [comment]
Sorry for the delay. I'll make the required changes in a day and update it here :) 
@sindresorhus adding the talks related to bug bounty would be a great idea.

**Comment by sindresorhus** [comment]
Closing. Ping me here if it's ever resolved.

**Comment by djadmin** [comment]
Have updated [awesome-bug-bounty](https://github.com/djadmin/awesome-bug-bounty) with all the required changes like License, Contribution guidelines, Code of conduct. Also, I have included getting started with bug bounty links and have changed the order as suggested.
Please let me know if I've missed anything. @sindresorhus

**Comment by djadmin** [comment]
@sindresorhus thoughts? :)

**Comment by floSoX** [comment]
Hi,
Please, could you reconsider this awesome list?
Thank you! :-)

**Comment by davisonio** [comment]
There's still no good descriptions for the listed items. You need to explain why links are awesome enough to be included in this list.

Surprised that hackerone.com is not included and there's a few other bug bounty collection sites that would be good to add.

For example a line should look like this:
```
- The life of a bug bounty hunter - Describing the day to day life of a security researcher etc. etc.
```

**Comment by djadmin** [comment]
@davisonio Thanks for the inputs. I can try to make it more meaningful and of course, awesome.
> Surprised that hackerone.com is not included 

Most of the companies listed are running BB programs on hackerone. Though, I can consider adding hackerone, bugcrowd and similar platforms to a different sections.

**Comment by djadmin** [comment]
@sindresorhus ping :)

**Comment by djadmin** [comment]
@sindresorhus please let me know if there are changes required :)

**Comment by sindresorhus** [comment]
From https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md

---

> The entry in the Awesome list should include a short description about the project/theme of the list. **It should not describe the list itself.**
    Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.

---

> **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)

---

> The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.

---

> Has a Table of Contents section. Should be named `Contents`, not `Table of Contents`.

**Comment by sindresorhus** [comment]
You link to a lot of good blogs in the `Write Ups & Authors`, but it would be nice to have a blog post section with some of the best blog posts too. Not everyone has time to go through all those blogs.

**Comment by sindresorhus** [comment]
@djadmin ping

**Pull request closed without merging**
