### PR TITLE
List of Front-End grid solutions

### PR DESCRIPTION
**Pull request by MikhailTatsky**
**[https://github.com/FancyGrid/awesome-grid]**

**[A curated list of grid(table) libraries and resources that developers may find useful.]**

# ALL THE BELOW CHECKBOXES SHOULD BE DONE AND CHECKED AND THE ABOVE PLACEHOLDERS SHOULD BE FILLED IN BEFORE SUBMITTING A PULL REQUEST!

- [x] I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- [x] This pull request has a descriptive title. *(For example: `Add Node.js`)*
- The list I added
	- [x] **has been around for at least 20 days,**
	- [x] is a non-generated Markdown file in a GitHub repo,
	- [x] is not a duplicate,
	- [x] only has awesome items with descriptions *(Awesome lists are curations of the best, not of everything)*,
	- [x] contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- [x] has a Table of Contents section named `Contents` as the first section,
	- [x] has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license) *(Meaning something like CC0, NOT a code licence like MIT, BSD, Apache, etc)*,
	- [x] has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- [x] has been checked for inconsistent formatting, spelling, and grammar *(This includes starting each link description with an uppercase character and ending it with a dot, and consistent naming)*,
	- [x] has been added at the bottom of the appropriate category.

A curated list of grid(table) libraries and resources that developers may find useful

### CODE REVIEW

**Comment by sindresorhus** [comment]
From https://github.com/sindresorhus/awesome/pull/695:

> Happy to reopen **in a month** when you've had some chance to generally improve the list, including our feedback.

**Comment by sindresorhus** [comment]
Actually, I'm not sure how comfortable I am adding this. It seems it was only quickly and sloppily created to promote your own paid product [FancyGrid](http://www.fancygrid.com).

**Comment by MikhailTatsky** [comment]
Maybe it is better to write it, but not just to close?

**Comment by davisonio** [comment]
There's still quite a few typos and inconsistencies which can help to prove that it was just to promote your product, although it's a bit better now that isn't merged in the middle of the grid solutions.

e.g. `3-rd` -> `3rd`

`.Net` -> `.NET`

**Comment by MikhailTatsky** [comment]
`3-rd -> 3rd` - done
`.Net -> .NET` - done

**Comment by sindresorhus** [comment]
I'm going to pass on this.

**Pull request closed without merging**
