### PR TITLE
Add Track Awesome List

### PR DESCRIPTION
**Pull request by theowenyoung**
**https://www.trackawesomelist.com**

**This is another way to browse awesome repos, for example, https://www.trackawesomelist.com/sindresorhus/awesome/ , we can view it by time. It solved my needs, when I stared some awesome repos before, that's the thing. With this, I can get the latest updates of my favorite awesome repo. I wonder if you also need it. I think it's nice if this is listed at Related category**

I reviewed https://github.com/sindresorhus/awesome/pull/2010 , https://github.com/sindresorhus/awesome/pull/2035 

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

## Requirements for your pull request

- **Don't waste my time.** Do a good job, adhere to all the guidelines, and be responsive.
- **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).**
	Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration. **Just commenting “looks good” or simply marking the pull request as approved does not count!** You have to actually point out mistakes or improvement suggestions.
- You have read and understood the [instructions for creating a list](create-list.md).
- This pull request has a title in the format `Add Name of List`.
	- ✅ `Add Swift`
	- ✅ `Add Software Architecture`
	- ❌ `Update readme.md`
	- ❌ `Add Awesome Swift`
	- ❌ `Add swift`
	- ❌ `add Swift`
	- ❌ `Adding Swift`
	- ❌ `Added Swift`
- Your entry here should include a short description about the project/theme of the list. **It should not describe the list itself.** The first character should be uppercase and the description should end in a dot. It should be an objective description and not a tagline or marketing blurb.
	- ✅ `- [iOS](…) - Mobile operating system for Apple phones and tablets.`
	- ✅ `- [Framer](…) - Prototyping interactive UI designs.`
	- ❌ `- [iOS](…) - Resources and tools for iOS development.`
	- ❌ `- [Framer](…)`
	- ❌ `- [Framer](…) - prototyping interactive UI designs`
- Your entry should be added at the bottom of the appropriate category.
- The suggested Awesome list complies with the below requirements.

## Requirements for your Awesome list

- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
- Don't open a Draft / WIP pull request while you work on the guidelines. A pull request should be 100% ready and should adhere to all the guidelines when you open it.
- Run [`awesome-lint`](https://github.com/sindresorhus/awesome-lint) on your list and fix the reported issues. If there are false-positives or things that cannot/shouldn't be fixed, please [report it](https://github.com/sindresorhus/awesome-lint/issues/new).
- The default branch should be named [`main`, not `master`](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/).
- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- ✅ `Mobile operating system for Apple phones and tablets.`
	- ✅ `Prototyping interactive UI designs.`
	- ❌ `Resources and tools for iOS development.`
	- ❌ `Awesome Framer packages and tools.`
- It's the result of hard work and the best I could possibly produce.
	**If you have not put in considerable effort into your list, your pull request will be immediately closed.**
- The repo name of your list should be in lowercase slug format: `awesome-name-of-list`.
	- ✅ `awesome-swift`
	- ✅ `awesome-web-typography`
	- ❌ `awesome-Swift`
	- ❌ `AwesomeWebTypography`
- The heading title of your list should be in [title case](https://capitalizemytitle.com/) format: `# Awesome Name of List`.
	- ✅ `# Awesome Swift`
	- ✅ `# Awesome Web Typography`
	- ❌ `# awesome-swift`
	- ❌ `# AwesomeSwift`
- Non-generated Markdown file in a GitHub repo.
- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
- Not a duplicate. Please search for existing submissions.
- Only has awesome items. Awesome lists are curations of the best, not everything.
- Does not contain items that are unmaintained, has archived repo, deprecated, or missing docs. If you really need to include such items, they should be in a separate Markdown file.
- Includes a project logo/illustration whenever possible.
	- Either centered, fullwidth, or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
	- The image should link to the project website or any relevant website.
	- **The image should be high-DPI.** Set it to maximum half the width of the original image.
- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- Includes the [Awesome badge](awesome.md#awesome-badge).
	- Should be placed on the right side of the readme heading.
		- Can be placed centered if the list has a centered graphics header.
	- Should link back to this list.
- Has a Table of Contents section.
	- Should be named `Contents`, not `Table of Contents`.
	- Should be the first section in the list.
	- Should only have one level of [nested lists](https://commonmark.org/help/tutorial/10-nestedLists.html), preferably none.
	- Must not feature `Contributing` or `Footnotes` sections.
- Has an appropriate license.
	- **We strongly recommend the [CC0 license](https://creativecommons.org/publicdomain/zero/1.0/), but any [Creative Commons license](https://creativecommons.org/choose/) will work.**
		- Tip: You can quickly add it to your repo by going to this URL: `https://github.com/<user>/<repo>/community/license/new?branch=main&template=cc0-1.0` (replace `<user>` and `<repo>` accordingly).
	- A code license like MIT, BSD, Apache, GPL, etc, is not acceptable. Neither are WTFPL and [Unlicense](https://unlicense.org).
	- Place a file named `license` or `LICENSE` in the repo root with the license text.
	- **Do not** add the license name, text, or a `Licence` section to the readme. GitHub already shows the license name and link to the full text at the top of the repo.
	- To verify that you've read all the guidelines, please comment on your pull request with just the word `unicorn`.
- Has [contribution guidelines](awesome.md#include-contribution-guidelines).
	- The file should be named `contributing.md`. Casing is up to you.
	- It can optionally be linked from the readme in a dedicated section titled `Contributing`, positioned at the top or bottom of the main content.
	- The section should not appear in the Table of Contents.
- All non-important but necessary content (like extra copyright notices, hyperlinks to sources, pointers to expansive content, etc) should be grouped in a `Footnotes` section at the bottom of the readme. The section should not be present in the Table of Contents.
- Has consistent formatting and proper spelling/grammar.
	- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
	- The description starts with an uppercase character and ends with a period.
	- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
- Doesn't use [hard-wrapping](https://stackoverflow.com/questions/319925/difference-between-hard-wrap-and-soft-wrap).
- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.
- Doesn't include an `Inspired by awesome-foo` or `Inspired by the Awesome project` kinda link at the top of the readme. The Awesome badge is enough.

**Go to the top and read it again.**

### CODE REVIEW

**Comment by theowenyoung** [comment]
unicorn

**Comment by claui** [comment]
Not all requirements are going to apply here (we’re looking at an addition to the _Related_ section, not a list).

With that in mind:

- A site that tracks Awesome lists seems to be a worthy addition to the _Related_ section.
GitHub already has a _Watch_ feature, which allows users to track changes in a repository. Users need to enable that individually per-repository though. The unique thing about Track Awesome List is that you no longer have to do anything, you don’t even have to be signed into GitHub.

- Tracking doesn’t seem to be a feature of any other entry in the _Related_ section.

- I don’t know for how long the site has been around. But at least the data seems to go back for months so I’d say that counts.

A few nitpicks:

- The description should say _Awesome lists_ (with upper-case A), not _awesome repos._
It’s not a hard requirement but it would make the entry clash less with the neighboring entries in the _Related_ section.

- Remove the “by time” part. It makes the description easier to grasp, and “latest” already implies time.

Nitpicks about the site itself:

- The site would be a little easier to navigate if the side pane and the main content area didn’t have independent scrollbars.
Most browsers don’t show scrollbars by default so it’s difficult to get the sidebar to scroll properly.

- Grammar: “Recent Updated” should be “Recently Updated”

- It’s not immediately clear what the numbers in the sidebar mean.
They seem to refer to the number of GitHub stars. I feel the numbers are an unnecessary distraction next to the words in the sidebar.
Have you tried not displaying the number (but keep using it for ranking, which seems useful)?

- The site would be easier to navigate if the current page was highlighted in the sidebar.

Ideas for site features:

- Stars shouldn’t be the only metric for ranking. Activity is important, too. Example: https://github.com/terryum/awesome-deep-learning-papers has 23k stars but is currently unmaintained.

**Comment by theowenyoung** [comment]
@claui Thank you very much for taking the time to give me a lot of very useful advice. I have made some changes of this site for a better browsing experience, and changed the description. (Sorry for some grammar issues, I'm not a native speaker :) )

> I don’t know for how long the site has been around. But at least the data seems to go back for months so I’d say that counts.

This site has been released for 1 month now, It generates a chronological, easy-to-read list by analyzing the commit history of each awesome repo.

> The description should say Awesome lists (with upper-case A), not awesome repos.
It’s not a hard requirement but it would make the entry clash less with the neighboring entries in the Related section.

Done.

> Remove the “by time” part. It makes the description easier to grasp, and “latest” already implies time.

Done.

> The site would be a little easier to navigate if the side pane and the main content area didn’t have independent scrollbars.
Most browsers don’t show scrollbars by default so it’s difficult to get the sidebar to scroll properly.

For this suggestion, I would feel better keeping sticky and scrolling independently. I have tested the latest chrome, safari, Microsoft Edge browsers and they all display separate scrollbars by default. Which browser do you use? I'll see if there's any good way to fix the scrollbar problem. For many sites that require sidebar navigation, they have a similar design, for example: https://v3.vuejs.org/guide/introduction.html#what-is-vue-js , 
https://chakra-ui.com/docs/getting-started , so I decided to keep it the same here.

> Grammar: “Recent Updated” should be “Recently Updated”

Done.

> It’s not immediately clear what the numbers in the sidebar mean.
They seem to refer to the number of GitHub stars. I feel the numbers are an unnecessary distraction next to the words in the sidebar.
Have you tried not displaying the number (but keep using it for ranking, which seems useful)?

> Stars shouldn’t be the only metric for ranking. Activity is important, too. Example: https://github.com/terryum/awesome-deep-learning-papers has 23k stars but is currently unmaintained.

Great suggestion, I have added a star. icon next to the count, and yes, activity is important, so I've made two changes about activity. 

1. I moved the unmaintained repos which are not updated over two years to the last category `Unmaintained`. 
2. Show updated time next to the Awesome list name.

> The site would be easier to navigate if the current page was highlighted in the sidebar.

Great suggestion, Done.


I have deployed the whole site, check out https://www.trackawesomelist.com to see the latest updates.

Thank you again for your sincere advice.

**Comment by mat7ias** [comment]
This is cool but it isn't a "Non-generated Markdown file in a GitHub repo" as the requirements state.

**Comment by theowenyoung** [comment]
@mat7ias Thanks, well, I suppose "Non-generated Markdown file in a GitHub repo" may restrict a awesome repo, Track Awesome List is added to the related section.

**Comment by sindresorhus** [comment]
I would recommend removing the `www.` part from the URL. www-less URLs are nicer for users.

**Comment by theowenyoung** [comment]
Thanks, removing the `www.` is indeed  more simple, now I add a `301` redirect to `www`, but for some dns reason, resolving a cname type of root domain is not easy. I'll reconsider the decision. Thanks.

**Pull request merged**
