### PR TITLE
Fix Broken Link to Effective Altruism

### PR DESCRIPTION
**Pull request by stella-lu**
The link to Effective Altruism (under miscellaneous) was broken, but I found what I assume is the same thing here:
https://github.com/ShriSamson/awesome-effective-altruism

### CODE REVIEW

**Comment by sindresorhus** [comment]
@sheonhan ?

**Comment by sheonhan** [comment]
Sorry about this! That forked repository indeed shows the same content. If someone else is willing to maintain it, I'm willing to hand it over.

**Comment by alberthu16** [comment]
@sheonhan did you delete your awesome-effective-altruism repo?

**Comment by sheonhan** [comment]
@alberthu16 I made it private, and it all went astray

**Comment by sindresorhus** [comment]
I'd rather remove it than some just linking to a random unmaintained version of it.

**Pull request closed without merging**
