### PR TITLE
Awesome Mac Screensavers

### PR DESCRIPTION
**Pull request by aharris88**
I thought it would be cool to add my list of screensavers for mac. I couldn't find a list like this, so I made it.

https://github.com/aharris88/awesome-mac-screensavers

### CODE REVIEW

**Comment by sindresorhus** [comment]
Visual stuff like this would benefit from screenshots.

See https://github.com/sindresorhus/quick-look-plugins for inspiration.

**Comment by aharris88** [comment]
Ok, I'll work on that. Thanks.

**Comment by aharris88** [comment]
Ok, I added screenshots.

**Comment by sindresorhus** [comment]
Oh, and the repo name should be `awesome-osx-screensavers`, not `awesome-mac-screensavers`. Mac is the hardware, OS X is the platform.

**Comment by sindresorhus** [comment]
I would also use sub-heading for each item rather than a list.

`-` → `###`

**Comment by aharris88** [comment]
Ok, I renamed it and changed the lists to sub-headings.

**Comment by sindresorhus** [comment]
Perfect :)

**Pull request closed without merging**
