### PR TITLE
Add Unicode Code Points

### PR DESCRIPTION
**Pull request by Boldewyn**
The suggested list is a curated set of Unicode codepoints, that happen to possess unusual features. The purpose is _not_ to simply list a bunch of emoji, but to give an insight in some of the inner mechanics of Unicode by way of presenting the relevant characters.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Very cool idea and thanks for being one of the few that actually bothers to read the contributing guidelines :D

Shouldn't it be `Code points`, not `Codepoints`? → https://en.wikipedia.org/wiki/Code_point

**Comment by sindresorhus** [comment]
// @mathiasbynens You might find this interesting.

**Comment by mathiasbynens** [comment]
Neat, @Boldewyn!

+1 on “code points” (which is what the Unicode Standard uses) vs. “codepoints”.

**Comment by dthree** [comment]
:+1:

**Comment by Boldewyn** [comment]
Updated the list to read `code points`. Thanks for the comments :smile:.

**Pull request closed without merging**
