### PR TITLE
Added Licence file (public domain)

### PR DESCRIPTION
**Pull request by LostArchives**
Hello,
As I said in the issue #824 , I added a licence a file for the public domain if you are interested as it wasn't present in the project :) Your project is great !
#824 

**[Explain what this list is all about and why it should be included here.]**

# ALL THE BELOW CHECKBOXES SHOULD BE DONE AND CHECKED AND THE ABOVE PLACEHOLDERS SHOULD BE FILLED IN BEFORE SUBMITTING A PULL REQUEST!

- [ x] I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- [x ] This pull request has a descriptive title. *(For example: `Add Node.js`)*
- The list I added
	- [ ] **has been around for at least 20 days,**
	- [ ] is a non-generated Markdown file in a GitHub repo,
	- [ ] is not a duplicate,
	- [ ] only has awesome items with descriptions *(Awesome lists are curations of the best, not of everything)*,
	- [ ] contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- [ ] has a Table of Contents section named `Contents` as the first section,
	- [ ] has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license) *(Meaning something like CC0, NOT a code licence like MIT, BSD, Apache, etc)*,
	- [ ] has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- [ ] has been checked for inconsistent formatting, spelling, and grammar *(This includes starting each link description with an uppercase character and ending it with a period `.`, and consistent naming)*,
	- [ ] has been added at the bottom of the appropriate category.

### CODE REVIEW

**Comment by lholznagel** [comment]
At the bottom of the page there is the license

**Comment by LostArchives** [comment]
Yes but not in a separated file and with the complete text. I think it's clearer to proceed like that.

**Comment by aleksandar-todorovic** [comment]
The [Unlicense](http://unlicense.org/) and [Creative Commons Zero](https://creativecommons.org/publicdomain/zero/1.0/) are two separate licenses. The Unlicense is mostly used for software, while CC0 is used for projects like this, and, since the license button at the bottom of the README file actually redirects to the CC0 page, you've added the text of the wrong license. :)

**Comment by sindresorhus** [comment]
I don't see the point in including it. This is not a distributable software package. It's already linked to from the readme.

**Comment by cdman** [comment]
@sindresorhus - if I might chime in with a different point of view: having a LICENSE file is a de-facto standard on GitHub and it also allows GitHub to display the license icon at the top of the repository (next to XX contributors). I think it would be useful to have.

**Pull request closed without merging**
