### PR TITLE
Add Building Blocks for Web Apps

### PR DESCRIPTION
**Pull request by thisismydesign**
https://github.com/componently-com/awesome-building-blocks-for-web-apps

Standalone features to be integrated into web applications. It should be included because it's awesome not having to code the same functionality over and over again.

### By submitting this pull request I confirm I've read and complied with the requirements 🖖

### CODE REVIEW

**Comment by thisismydesign** [comment]
Lint: https://github.com/componently-com/awesome-building-blocks-for-web/runs/740112407#step:4:1

**Comment by thisismydesign** [comment]
Reviewed PRs:
- https://github.com/sindresorhus/awesome/pull/1787#pullrequestreview-424728426
- https://github.com/sindresorhus/awesome/pull/1788#pullrequestreview-424722941

**Comment by thisismydesign** [comment]
unicorn

**Comment by sindresorhus** [comment]
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

**Comment by thisismydesign** [comment]
@sindresorhus Adjusted the name and description.

**Comment by sindresorhus** [comment]
I decided to rename `master` branch to `main`, and apparently that permanently closes all PRs. Ugh. Sorry about that. Can you reopen this PR targeting the `main` branch?

**Pull request closed without merging**
