### PR TITLE
Added beatiful docs page.

### PR DESCRIPTION
**Pull request by dthree**
Stumbled on this site:

https://github.com/PharkMillups/beautiful-docs

I think it definitely deserves to be on the awesome list.

### CODE REVIEW

**Comment by sindresorhus** [comment]
@PharkMillups It needs a license and contributing guidelines. Read: https://github.com/sindresorhus/awesome/blob/master/awesome.md

Bonus points for the commentary on each item, though I think a visual resource like that would be a lot more useful with screenshots. Also the `(contributed by xxx)` text is unessecary noise and makes the list a lot harder to read. Contributing credit is already in the git history. If you really want it in the readme, at least put it at the bottom of the readme.

**Comment by arthurvr** [comment]
Friendly ping @dthree.

**Comment by dthree** [comment]
Hi @arthurvr . Looks like @PharkMillups needs to make some changes on his list before this goes in. I sent him a ping / issue, but it doesn't look like he visits github very often.

**Comment by dthree** [comment]
He said he'll pass for now.

**Pull request closed without merging**
