### PR TITLE
Add Chatbots

### PR DESCRIPTION
**Pull request by JStumpp**
https://github.com/jstumpp/awesome-chatbots

This list is about chatbots. We list services and open source projects in this area to help newcomers to find the required resources.

- [x] I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- [x] This pull request has a descriptive title. *(For example: `Add Node.js`)*
- The list I added
	- [x] **has been around for at least 20 days,**
	- [x] is a non-generated Markdown file in a GitHub repo,
	- [x] is not a duplicate,
	- [x] only has awesome items with descriptions *(Awesome lists are curations of the best, not of everything)*,
	- [x] contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- [x] has a Table of Contents section named `Contents` as the first section,
	- [x] has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license) *(Meaning something like CC0, NOT a code licence like MIT, BSD, Apache, etc)*,
	- [x] has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- [x] has been checked for inconsistent formatting, spelling, and grammar *(This includes starting each link description with an uppercase character and ending it with a period `.`, and consistent naming)*,
	- [x] has been added at the bottom of the appropriate category.

Thanks!

### CODE REVIEW

**Comment by sindresorhus** [comment]
Seems like a slight duplicate of https://github.com/hackerkid/bots.

**Comment by JStumpp** [comment]
😢 I did not see this before. Probably add it anyway because people search for chatbots, like I did?

**Comment by sindresorhus** [comment]
Maybe you could co-operate with @hackerkid?

**Comment by JStumpp** [comment]
Yep, first come first serve. That is life.
Thanks anyway.

**Pull request closed without merging**
