### PR TITLE
Add Awesome Refinery CMS

### PR DESCRIPTION
**Pull request by bricesanchez**

### CODE REVIEW

**Comment by shinnn** [comment]
Why so strict license? https://github.com/refinerycms-contrib/awesome-refinerycms#license

**Comment by bricesanchez** [comment]
@shinnn Bad copy/paste from https://github.com/leekelleher/awesome-umbraco, it's now fixed and far better in public domain :)

**Comment by sindresorhus** [comment]
Please read the [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

-

I noticed it's missing a contributing.md (see above links)

-

The list doesn't have much content. I think you should work on it some more. Ping me here in a month and I'll reconsider ;)

**Comment by bricesanchez** [comment]
@sindresorhus No problem, i wil :)

**Comment by bricesanchez** [comment]
Hello @sindresorhus ! Could you reconsider my PR ? I've made some upgrades : https://github.com/refinerycms-contrib/awesome-refinerycms

**Pull request closed without merging**
