### PR TITLE
Add Gideros

### PR DESCRIPTION
**Pull request by stetso**
**https://github.com/stetso/awesome-gideros **

**This is a list of resources for the Gideros Game Engine which is a Lua-scripted C++-based engine with great support for plugins and a fast development workflow on mobile, desktop and web **

# By submitting this pull request I confirm I've read and complied with the below requirements.

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title.<br>For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
	- Be added at the bottom of the appropriate category.
- The list I'm submitting complies with these requirements:
	- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
	- It's the result of hard work and the best I could possibly produce.
	- Non-generated Markdown file in a GitHub repo.
	- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
	- Not a duplicate.
	- Only has awesome items. Awesome lists are curations of the best, not everything.
	- Includes a project logo/illustration whenever possible.
		- Placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
		- The image should link to the project website or any relevant website.
		- The image should be high-DPI. Set it to maximum half the width of the original image.
	- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
	- Has the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- Has a Table of Contents section.
		- Should be named `Contents`, not `Table of Contents`.
		- Should be the first section in the list.
	- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
		- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
		- If you use a license badge, it should be SVG, not PNG.
	- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
		- The file should be named `contributing.md`. Casing is up to you.
	- Has consistent formatting and proper spelling/grammar.
		- Each link description starts with an uppercase character and ends with a period.<br>Example: `- [AVA](…) - JavaScript test runner.`
		- Drop all the `A` / `An` prefixes in the descriptions.
		- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
	- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.
- Go to the top and read it again.

### CODE REVIEW

**Comment by sindresorhus** [comment]
> Each link description starts with an uppercase character and ends with a period.
Example: `- [AVA](…) - JavaScript test runner.`

**Comment by stetso** [comment]
Apologies!!! It is fixed now :)

**Comment by legodude17** [comment]
I would suggest unquoting the description.

**Comment by stetso** [comment]
Alright, done! Thanks for the suggestions.

**Comment by sindresorhus** [comment]
- The top logo should be half the size of its actual size. Right now it's a little bit blurry on retina screens.
- In the top description, `Gideros Game Development Framework` should be linkified to the official website.
- `Download and Getting Started` => `Getting Started`
- `General Tutorials and Tips` => `Tutorials and Tips`
- `3d` => `3D`
- `general Lua libraries` => `General Lua libraries`
- `Related Awesome-Lists` => `Related Awesome Lists`
- In the TOC, many of the links are broken.
- In the TOC, `Gideros Resources` => `Resources`

> Drop all the A / An prefixes in the descriptions.

:arrow_up:

> The repo should have awesome-list & awesome as GitHub topics. I encourage you to add more relevant topics.

:arrow_up:

**Comment by sindresorhus** [comment]
ping @stetso

**Comment by stetso** [comment]
@sindresorhus Thanks for the wake-up call. I was a bit busy so the issue slipped my mind. Sorry about that. I fixed and changed the list according to your suggestions. Hope it is fine now, otherwise, let me know. And thanks for the help!

**Comment by sindresorhus** [comment]
> Download and Getting Started => Getting Started
General Tutorials and Tips => Tutorials and Tips

Not fixed

**Comment by stetso** [comment]
Argh, you are absolutely right. I unfixed it, when fixing the TOC -.- Thanks anyway! Should be fine now.

**Pull request merged**
