### PR TITLE
Add Blazor

### PR DESCRIPTION
**Pull request by AdrienTorris**
https://github.com/AdrienTorris/awesome-blazor

Blazor is a new product from Microsoft and the 'Awesome Blazor' repository is considered as the official community website, see the official Blazor's website: https://dotnet.microsoft.com/apps/aspnet/web-apps/client (section 'Active community').

[Blazor](https://dotnet.microsoft.com/apps/aspnet/web-apps/client) is a feature of ASP.NET, the popular web development framework that extends the .NET developer platform with tools and libraries for building web apps. It lets you build interactive web UIs using C# instead of JavaScript. Blazor apps are composed of reusable web UI components implemented using C#, HTML, and CSS. Both client and server code is written in C#, allowing you to share code and libraries.

Appropriate category: Front-End Development

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

## Requirements for your pull request

- **Don't waste my time.** Do a good job, adhere to all the guidelines, and be responsive.
- **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).**
	Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration.
- You have read and understood the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a title in the format `Add Name of List`.
	- ✅ `Add Swift`
	- ✅ `Add Software Architecture`
	- ❌ `Update readme.md`
	- ❌ `Add Awesome Swift`
	- ❌ `Add swift`
	- ❌ `Adding Swift`
	- ❌ `Added Swift`
- Your entry here should include a short description about the project/theme of the list. **It should not describe the list itself.** The first character should be uppercase and the description should end in a dot. It should be an objective description and not a tagline or marketing blurb.
	- ✅ `- [iOS](…) - Mobile operating system for Apple phones and tablets.`
	- ✅ `- [Framer](…) - Prototyping interactive UI designs.`
	- ❌ `- [iOS](…) - Resources and tools for iOS development.`
	- ❌ `- [Framer](…)`
	- ❌ `- [Framer](…) - prototyping interactive UI designs`
- Your entry should be added at the bottom of the appropriate category.
- The suggested Awesome list complies with the below requirements.

## Requirements for your Awesome list

- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
- Don't open a Draft / WIP pull request while you work on the guidelines. A pull request should be 100% ready and should adhere to all the guidelines when you open it.
- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- ✅ `Mobile operating system for Apple phones and tablets.`
	- ✅ `Prototyping interactive UI designs.`
	- ❌ `Resources and tools for iOS development.`
	- ❌ `Awesome Framer packages and tools.`
- It's the result of hard work and the best I could possibly produce.
	**If you have not put in considerable effort into your list, your pull request will be immediately closed.**
- The heading title of your list should be in the following format: `# Awesome Name of List`
	- ✅ `# Awesome Swift`
	- ✅ `# Awesome Web Typography`
	- ❌ `# awesome-swift`
	- ❌ `# `
- Non-generated Markdown file in a GitHub repo.
- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
- Not a duplicate. Please search for existing submissions.
- Only has awesome items. Awesome lists are curations of the best, not everything.
- Includes a project logo/illustration whenever possible.
	- Either centered, fullwidth, or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
	- The image should link to the project website or any relevant website.
	- **The image should be high-DPI.** Set it to maximum half the width of the original image.
- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
	- Should be placed on the right side of the readme heading.
		- Can be placed centered if the list has a centered graphics header.
	- Should link back to this list.
- Has a Table of Contents section.
	- Should be named `Contents`, not `Table of Contents`.
	- Should be the first section in the list.
	- Should only have one level of [nested lists](https://commonmark.org/help/tutorial/10-nestedLists.html), preferably none.
- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
	- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
	- [WTFPL](http://www.wtfpl.net) and [Unlicense](http://unlicense.org) are not acceptable licenses.
	- **If you use a license badge, it should be SVG, not PNG.**
	- To verify that you've read all the guidelines, please add comment with just the word `unicorn`.
- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
	- The file should be named `contributing.md`. Casing is up to you.
- Has consistent formatting and proper spelling/grammar.
	- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
	- The description starts with an uppercase character and ends with a period.
	- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.
- Doesn't include an `Inspired by awesome-foo` or `Inspired by the Awesome project` kinda link at the top of the readme. The Awesome badge is enough.

### CODE REVIEW

**Comment by AdrienTorris** [comment]
Related to #1256 and #1257.

**Comment by sindresorhus** [comment]
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

**Comment by AdrienTorris** [comment]
Ok, I'll read the guidelines again.

**Comment by AdrienTorris** [comment]
unicorn

**Comment by AdrienTorris** [comment]
Logo and 'awesome' tag added.

**Comment by AdrienTorris** [comment]
Comment posted to this PR to help the DB2 Awesome list to be better : https://github.com/sindresorhus/awesome/pull/1490

**Comment by AdrienTorris** [comment]
I search another comment to post on a PR but there are only 7 active PRs.

**Comment by eselkin** [comment]
- List items should be - not *
- It's pretty comprehensive.. I like that.

**Comment by AdrienTorris** [comment]
Thanks

**Comment by AdrienTorris** [comment]
https://github.com/sindresorhus/awesome/pull/1585#issuecomment-513466423

**Comment by sindresorhus** [comment]
```
❯ awesome-lint https://github.com/AdrienTorris/awesome-blazor
✖ Linting

  README.md:165:3
  ✖    1:19   Invalid badge source                                                                                                                                        remark-lint:awesome/badge
  ✖   50:56   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖   58:54   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖   58:56   Link to http://githubbadges.com/star.svg?user=thangchung&repo=blog-core&style=flat is dead                                                                  remark-lint:no-dead-urls
  ✖   59:54   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖   61:62   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖   61:64   Link to http://githubbadges.com/star.svg?user=aesalazar&repo=AsteroidsWasm&style=flat is dead                                                               remark-lint:no-dead-urls
  ✖   62:58   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖   71:63   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖   72:56   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖   75:91   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖   76:65   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖   77:98   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖   77:112  Found reference to undefined definition                                                                                                                     remark-lint:no-undefined-references
  ✖   78:56   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖   79:58   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖   80:62   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖   81:63   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖   82:70   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖   83:57   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖   84:70   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖   85:69   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖   86:77   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖   87:70   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖   88:42   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖   89:45   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖   90:47   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖   91:66   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖   92:71   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖   93:78   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖   94:70   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖   95:61   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖   96:69   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖   96:105  Link to https://lupblazordemos.z13.web.core.windows.net/WebSocketPage is dead                                                                               remark-lint:no-dead-urls
  ✖   97:67   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖   98:63   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖   99:71   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  100:73   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  101:69   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  102:68   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  104:63   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  135:70   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  138:73   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  146:74   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  153:52   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  154:55   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  155:51   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  156:71   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  157:55   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  158:75   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  159:65   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  160:83   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  161:68   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  162:54   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  163:70   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  164:54   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  165:3    Incorrect indentation before bullet: remove 1 space                                                                                                         remark-lint:list-item-bullet-indent
  ✖  165:99   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  166:62   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  167:3    Incorrect indentation before bullet: remove 1 space                                                                                                         remark-lint:list-item-bullet-indent
  ✖  167:79   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  168:79   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  169:76   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  170:60   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  171:52   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  172:62   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  173:3    Incorrect indentation before bullet: remove 1 space                                                                                                         remark-lint:list-item-bullet-indent
  ✖  173:64   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  174:3    Incorrect indentation before bullet: remove 1 space                                                                                                         remark-lint:list-item-bullet-indent
  ✖  174:66   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  175:57   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  176:57   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  177:69   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  180:3    Incorrect indentation before bullet: remove 1 space                                                                                                         remark-lint:list-item-bullet-indent
  ✖  181:3    Incorrect indentation before bullet: remove 1 space                                                                                                         remark-lint:list-item-bullet-indent
  ✖  182:3    Incorrect indentation before bullet: remove 1 space                                                                                                         remark-lint:list-item-bullet-indent
  ✖  183:3    Incorrect indentation before bullet: remove 1 space                                                                                                         remark-lint:list-item-bullet-indent
  ✖  184:3    Incorrect indentation before bullet: remove 1 space                                                                                                         remark-lint:list-item-bullet-indent
  ✖  190:61   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  191:57   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  192:62   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  193:57   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  194:57   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  195:70   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  196:63   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  197:49   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  198:61   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  199:58   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  200:69   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  201:64   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  202:79   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  202:93   Found reference to undefined definition                                                                                                                     remark-lint:no-undefined-references
  ✖  203:59   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  204:89   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  205:72   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  206:68   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  207:77   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  208:83   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  209:76   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  210:67   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  222:68   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  224:69   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  225:47   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  226:58   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  227:57   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  228:82   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  229:83   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  230:78   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  231:71   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  307:3    Link to http://lightswitchhelpwebsite.com/Blog/tabid/61/EntryId/4318/Server-Side-Blazor-Reading-And-Inserting-Data-Into-A-Database-End-To-End.aspx is dead  remark-lint:no-dead-urls
  ✖  309:3    Link to http://lightswitchhelpwebsite.com/Blog/tabid/61/EntryId/4336/What-Is-Blazor.aspx is dead                                                            remark-lint:no-dead-urls
  ✖  339:3    Link to https://coderethinked.com/data-binding-in-blazor/ is dead                                                                                           remark-lint:no-dead-urls
  ✖  344:3    Link to http://lightswitchhelpwebsite.com/Blog/tabid/61/EntryId/4331/Creating-a-Database-Driven-Module-For-Blazor-Oqtane.aspx is dead                       remark-lint:no-dead-urls
  ✖  345:3    Link to http://lightswitchhelpwebsite.com/Blog/tabid/61/EntryId/4330/Creating-a-Hello-World-Module-For-Blazor-Oqtane.aspx is dead                           remark-lint:no-dead-urls
  ✖  351:3    Link to https://coderethinked.com/unable-to-find-debuggable-browser-tab-in-blazor/ is dead                                                                  remark-lint:no-dead-urls
  ✖  391:3    Link to http://lightswitchhelpwebsite.com/Blog/tabid/61/EntryId/4323/Google-Authentication-in-Server-Side-Blazor-Razor-Components.aspx is dead              remark-lint:no-dead-urls
  ✖  416:122  List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  426:90   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  428:73   List item link and description must be separated with a dash                                                                                                remark-lint:awesome/list-item
  ✖  446:3    Link to https://twitter.com/awesomeblazor is dead                                                                                                           remark-lint:no-dead-urls
  ✖  449:3    Link to https://lightswitchhelpwebsite.com/Blog/tabid/61/tagid/66/Blazor.aspx is dead                                                                       remark-lint:no-dead-urls
  ✖  453:3    Link to https://twitter.com/hashtag/blazor is dead                                                                                                          remark-lint:no-dead-urls
  ✖  457:47   Found reference to undefined definition                                                                                                                     remark-lint:no-undefined-references
  ✖  458:37   Found reference to undefined definition                                                                                                                     remark-lint:no-undefined-references
  ✖  459:79   Found reference to undefined definition                                                                                                                     remark-lint:no-undefined-references
  ✖  460:92   Found reference to undefined definition                                                                                                                     remark-lint:no-undefined-references
  ✖  461:91   Found reference to undefined definition                                                                                                                     remark-lint:no-undefined-references

  127 errors
```

https://github.com/sindresorhus/awesome-lint

**Comment by AdrienTorris** [comment]
The errors with the dashes is because of the stars display.

**Comment by AdrienTorris** [comment]
✖  446:3    Link to https://twitter.com/awesomeblazor is dead                                                                                                           remark-lint:no-dead-urls
  ✖  449:3    Link to https://lightswitchhelpwebsite.com/Blog/tabid/61/tagid/66/Blazor.aspx is dead                                                                       remark-lint:no-dead-urls
  ✖  453:3    Link to https://twitter.com/hashtag/blazor is dead 

The links are not dead

**Comment by AdrienTorris** [comment]
✖   61:64   Link to http://githubbadges.com/star.svg?user=aesalazar&repo=AsteroidsWasm&style=flat
  ✖   58:56   Link to http://githubbadges.com/star.svg?user=thangchung&repo=blog-core&style=flat is dead

We changed the star counter provider to a more stable one.

**Comment by CompSciLauren** [comment]
> The errors with the dashes is because of the stars display.

You should go ahead and do a replace-all to make the stars into dashes. It doesn't impact the look of the readme, it's a really quick fix, and it'll solve the awesome-lint errors.

In the future maybe the linter will allow stars, but since it doesn't right now I think it's better to just resolve the errors given the above reasons.

**Comment by CompSciLauren** [comment]
There are more awesome-lint errors that still need to be addressed besides the star/dash ones.

**Comment by AdrienTorris** [comment]
All the links errors others than _githubbadges_ which has been replaced are false negatives.

**Comment by AdrienTorris** [comment]
indentation errors has been fixed too.

**Comment by AdrienTorris** [comment]
Awesome badge replaced.

**Comment by AdrienTorris** [comment]
All the errors may be fixed now.

**Comment by sindresorhus** [comment]
Tweet: https://twitter.com/awesome__re/status/1156652199428186112

**Pull request merged**
