### PR TITLE
Add Open Source Supporters

### PR DESCRIPTION
**Pull request by zachflower**
https://github.com/zachflower/awesome-open-source-supporters

The Open Source Supporters awesome list highlights companies that offer their tools and services for free to Open Source and public projects. It is important to note that some companies offer standard free tiers (such as Slack, for example), however this list focuses _specifically_ on companies that have made an overt commitment to the Open Source community.

# By submitting this pull request I confirm I've read and complied with the below requirements.

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title.<br>For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
	- Be added at the bottom of the appropriate category.
- The list I'm submitting complies with these requirements:
	- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
	- It's the result of hard work and the best I could possibly produce.
	- Non-generated Markdown file in a GitHub repo.
	- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
	- Not a duplicate.
	- Only has awesome items. Awesome lists are curations of the best, not everything.
	- Includes a project logo/illustration whenever possible.
		- Placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
		- The image should link to the project website or any relevant website.
		- The image should be high-DPI. Set it to maximum half the width of the original image.
	- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
	- Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
		- Should be placed on the right side of the readme heading.
		- Should link back to this list.
	- Has a Table of Contents section.
		- Should be named `Contents`, not `Table of Contents`.
		- Should be the first section in the list.
		- Should only have one level of sub-lists, preferably none.
	- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
		- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
		- If you use a license badge, it should be SVG, not PNG.
	- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
		- The file should be named `contributing.md`. Casing is up to you.
	- Has consistent formatting and proper spelling/grammar.
		- Each link description starts with an uppercase character and ends with a period.<br>Example: `- [AVA](…) - JavaScript test runner.`
		- Drop all the `A` / `An` prefixes in the descriptions.
		- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
	- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.
- Go to the top and read it again.

### CODE REVIEW

**Comment by shlomif** [comment]
Hi Zachary!

On Sat, 19 Aug 2017 12:43:56 -0700
Zachary Flower <notifications@github.com> wrote:

> 
> 
> 
> 
> 
> https://github.com/zachflower/awesome-freeforopensource
> 

Since https://en.wikipedia.org/wiki/Free_software is related to open source and
there also is https://en.wikipedia.org/wiki/Free_and_open-source_software
(FOSS) and it means free-as-in-speech rather than
https://en.wiktionary.org/wiki/costless or
https://en.wiktionary.org/wiki/gratis , then I find your list (which seems
useful and desirable) to be awkwardly and confusingly phrased. Please consider
renaming it.

Regards,

	Shlomi
-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Stop Using MSIE - http://www.shlomifish.org/no-ie/

Only three things are infinite: the universe, human stupidity, and the amount
of patience that Windows Update requires.
    — http://www.shlomifish.org/humour/bits/facts/Windows-Update/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by zachflower** [comment]
That's a super good point, and a confusion I hadn't really considered... Thoughts on something like "Open Source Supporters"?

**Comment by zachflower** [comment]
@shlomif your suggestion made a lot of sense, so I went ahead and just ran with it. Open Source Supporters feels a lot less ambiguous than the original title.

**Comment by shlomif** [comment]
@zachflower : you're welcome.

**Comment by sindresorhus** [comment]
Sorry about the slow review time. Looks great and cool idea! :)

**Pull request merged**
