### PR TITLE
Add Userscripts

### PR DESCRIPTION
**Pull request by brunocvcunha**
UserScripts can improve browsing experience a lot, and I really missed an awesome list when searching for new scripts.

PR to include https://github.com/brunocvcunha/awesome-userscripts

Thanks!

### CODE REVIEW

**Comment by brunocvcunha** [comment]
Read some instructions, will wait a few weeks and improve it first.

**Comment by pokeball99** [comment]
@brunocvcunha make sure just to reply back on this to remind sindresorhus about it, instead of opening a new issue :)

**Comment by brunocvcunha** [comment]
Reopening. cc @sindresorhus

**Comment by sindresorhus** [comment]
- I would like to see more than just user scripts. Include some blog posts, tutorials, links to community resources (Example: https://github.com/sindresorhus/awesome-electron#community), videos, boilerplates, etc.
- Inconsistent naming of `Userscripts` (This is the correct naming AFAIK).
- `Youtube` => `YouTube`.
- Your table of contents should have a heading. Follow the format of other lists. No need to include `Awesome UserScripts` in the table of contents.

There are also lots of great Userscripts out there. Your list is very short. I think you should work on it some more. Awesome lists are hard work. Try again in a month ;)

**Comment by brunocvcunha** [comment]
Reopening. cc @sindresorhus 

----------------

- [x] I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- [x] This pull request has a descriptive title.
- The list I added
	- [x] **has been around for at least 20 days,**
	- [x] is not a duplicate,
	- [x] only has awesome items with descriptions,
	- [x] contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- [x] has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license),
	- [x] has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- [x] has been checked for inconsistent formatting, spelling and grammar, and
	- [x] has been added at the bottom of the appropriate category.

**Comment by brunocvcunha** [comment]
@sindresorhus: hi! can you review it again, by any chance? thank you!

**Comment by sindresorhus** [comment]
`Table of Contents` => `Contents`

**Comment by sindresorhus** [comment]
Otherwise looks good, though I'd like to see some more content.

**Pull request merged**
