### PR TITLE
Add MicroPython

### PR DESCRIPTION
**Pull request by ikuamike**
https://github.com/ikuamike/Awesome_Micropython

A list of good resources, tutorials and talks about Micropython.

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

## Requirements for your pull request

- **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).** Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration.
- I have read and understood the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title in the format `Add Name of List` (Example: `Add Swift`), not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
	- Be added at the bottom of the appropriate category.
- The list I'm submitting complies with the below requirements.

## Requirements for your Awesome list

- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
- It's the result of hard work and the best I could possibly produce.
- Non-generated Markdown file in a GitHub repo.
- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
- Not a duplicate.
- Only has awesome items. Awesome lists are curations of the best, not everything.
- Includes a project logo/illustration whenever possible.
	- Either fullwidth or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
	- The image should link to the project website or any relevant website.
	- The image should be high-DPI. Set it to maximum half the width of the original image.
- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
	- Should be placed on the right side of the readme heading.
	- Should link back to this list.
- Has a Table of Contents section.
	- Should be named `Contents`, not `Table of Contents`.
	- Should be the first section in the list.
	- Should only have one level of sub-lists, preferably none.
- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
	- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
	- [WTFPL](http://www.wtfpl.net) and [Unlicense](http://unlicense.org) are not acceptable licenses.
	- If you use a license badge, it should be SVG, not PNG.
- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
	- The file should be named `contributing.md`. Casing is up to you.
- Has consistent formatting and proper spelling/grammar.
	- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
	- The description starts with an uppercase character and ends with a period.
	- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.

Go to the top and read it again.

### CODE REVIEW

**Comment by uraimo** [comment]
```
> awesome-lint

  README.md:1:1

  ✖   1:1   Missing newline character at end of file                                  final-newline
  ✖  21:3   Invalid list item                                                         awesome/list-item
  ✖  21:3   Missing Awesome badge after the main heading                              awesome/badge
  ✖  24:5   Link to http://micropython.org/resources/docs/en/latest/wipy/ is dead     no-dead-urls
  ✖  25:5   Link to http://micropython.org/resources/docs/en/latest/esp8266/ is dead  no-dead-urls
  ✖  28:3   Invalid list item                                                         awesome/list-item
  ✖  28:3   Missing Awesome badge after the main heading                              awesome/badge
  ✖  40:51  List item description must end with proper punctuation                    awesome/list-item
  ✖  45:83  List item description must end with proper punctuation                    awesome/list-item
  ✖  48:89  List item description must end with proper punctuation                    awesome/list-item
  ✖  59:10  Remove empty section: "Blogs"                                             no-empty-sections
  ✖  63:63  List item link and description must be separated with a dash              awesome/list-item
  ✖  64:54  List item link and description must be separated with a dash              awesome/list-item
  ✖  65:85  List item link and description must be separated with a dash              awesome/list-item
  ✖  66:70  List item link and description must be separated with a dash              awesome/list-item
  ✖  67:70  List item link and description must be separated with a dash              awesome/list-item
  ✖  68:76  List item link and description must be separated with a dash              awesome/list-item
  ✖  69:62  List item link and description must be separated with a dash              awesome/list-item
  ✖  70:70  List item link and description must be separated with a dash              awesome/list-item
  ✖  71:70  List item link and description must be separated with a dash              awesome/list-item
  ✖  72:76  List item link and description must be separated with a dash              awesome/list-item
  ✖  73:73  List item link and description must be separated with a dash              awesome/list-item
  ✖  79:4   Text "github" should be written as "GitHub"                               awesome/spell-check
  ✖  89:2   License image must be SVG                                                 awesome/license

  24 errors
```

**Comment by sindresorhus** [comment]
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

**Comment by ikuamike** [comment]
Thanks for the feedback i'll update it to meet requirements

**Comment by ikuamike** [comment]
Fixed linting issues, is it ready to be merged?

**Comment by sindresorhus** [comment]
```
❯ awesome-lint https://github.com/ikuamike/Awesome_Micropython
✖ Linting

  README.md:78:3
  ✖  78:3  Link to https://www.pi4iot.com/doku.php?id=sbc:esp8266 is dead  remark-lint:no-dead-urls

  1 error
```

https://github.com/sindresorhus/awesome-lint

**Comment by sindresorhus** [comment]
Can you fix the merge conflict?

**Comment by sindresorhus** [comment]
> Includes a project logo/illustration whenever possible.
> **The image should be high-DPI. Set it to maximum half the width of the original image.**

**Comment by sindresorhus** [comment]
Instead of having `Official Link: MicroPython Homepage`, just linkify the `MicroPython` word at the start of the list intro.

**Comment by sindresorhus** [comment]
Some of the entries are missing a description.

**Comment by sindresorhus** [comment]
The contribution guidelines should be customized for your list and not just copy-pasted from the Awesome repo.

**Comment by ikuamike** [comment]
I will make the suggested changes thank you.

**Comment by sindresorhus** [comment]
Bump

**Pull request closed without merging**
