### PR TITLE
add brunch list

### PR DESCRIPTION
**Pull request by denar90**

### CODE REVIEW

**Comment by davisonio** [comment]
Thanks for the suggestion. :smiley:
Please have a read through of the [instructions](https://github.com/sindresorhus/awesome/blob/master/create-list.md) for creating/adding a new list.

> Wait at least a couple of weeks after creating a list before submitting to this list to give it a chance to mature.

Once the list has matured I can reopen this, just let me know here. :raised_hands:

**Comment by denar90** [comment]
Sorry, forgot about it.

**Comment by denar90** [comment]
@davisonio can you reopen PR?

**Comment by denar90** [comment]
Fixed merge conflicts

**Comment by sindresorhus** [comment]
> Fixed merge conflicts

Not correctly. Please look at the diff.

**Comment by sindresorhus** [comment]
This list needs more work. I would like to see more than just libraries. Include more blog posts, tutorials, videos of talks, book, learning material, etc. You've included way too many boilerplates, pick the best ones. Items needs descriptions. `Unlicense` is not a real licence, please read the awesome manifest for recommendations. Look at some of the other awesome lists for inspiration. Keep in mind that awesome lists are hard work. Try again in a few months when you've worked on it some more.

**Comment by denar90** [comment]
Ok, thanks)

**Pull request closed without merging**
