### PR TITLE
Add Git Tips

### PR DESCRIPTION
**Pull request by stevemao**
https://github.com/git-tips/tips
This list is similar to Git Cheat Sheet but I think it lists something that don't exist in Git Cheat Sheet.

### CODE REVIEW

**Comment by sindresorhus** [comment]
It's missing a license.

// @hemanth

**Comment by hemanth** [comment]
Done. :+1:

**Comment by sindresorhus** [comment]
Please read: https://github.com/sindresorhus/awesome/blob/master/awesome.md

MIT is not a good license for text content.

Would also be cool if you could add the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).

**Comment by hemanth** [comment]
`CC0 1.0` makes sense, will change it soon.

**Pull request merged**
