### PR TITLE
Add PowerShell

### PR DESCRIPTION
**Pull request by vors**
Follow-up from #783, with addressed feedback.

**https://github.com/janikvonrotz/awesome-powershell**

**PowerShell is a cross-platform object-oriented shell and scripting language. It was originally developed by Microsoft for Windows and went open-source and cross-platform in 2016. This list contains a delighful packages and resources for PowerShell**

# ALL THE BELOW CHECKBOXES SHOULD BE DONE AND CHECKED AND THE ABOVE PLACEHOLDERS SHOULD BE FILLED IN BEFORE SUBMITTING A PULL REQUEST!

- [x] I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- [x] This pull request has a descriptive title. *(For example: `Add Node.js`)*
- The list I added
	- [x] **has been around for at least 20 days,**
	- [x] is a non-generated Markdown file in a GitHub repo,
	- [x] is not a duplicate,
	- [x] only has awesome items with descriptions *(Awesome lists are curations of the best, not of everything)*,
	- [x] contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- [x] has a Table of Contents section named `Contents` as the first section,
	- [x] has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license) *(Meaning something like CC0, NOT a code licence like MIT, BSD, Apache, etc)*,
	- [x] has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- [x] has been checked for inconsistent formatting, spelling, and grammar *(This includes starting each link description with an uppercase character and ending it with a period `.`, and consistent naming)*,
	- [x] has been added at the bottom of the appropriate category.

--------------------------

PowerShell team and community spent a lot of time contributing to the list in the [past few months](https://github.com/janikvonrotz/awesome-powershell/issues/2). We think it's pretty solid right now and we hope it would serve as a useful community resource for people who recently start look into PowerShell. 

Also, PowerShell has it's 10th Anniversary on Monday, November 14th. 🎉 🎉 🎉

### CODE REVIEW

**Comment by vors** [comment]
Ping

**Comment by sindresorhus** [comment]
All my feedback in https://github.com/sindresorhus/awesome/pull/783#issuecomment-251886304 is not resolved.

**Comment by vors** [comment]
Yes, I was not sure what to do about 

> There should be a succinct summary at the top about the project.

I checked few lists that are already included in awesome and "A curated list of delightful PowerShell packages and resources" seems along the lines of what other lists provide.
I think it describes the project (awesome-powershell) well.

I think the elaborated description about what is PowerShell would be useful.
Was it what you mean by "about the project"? Not awesome-powershell, but powershell itself?

**Comment by sindresorhus** [comment]
> Did you mean that by "about the project"? Not awesome-powershell, but powershell itself?

Yes

**Comment by vors** [comment]
Ok, PR with project description is merged.

**Comment by sindresorhus** [comment]
Looks good now. Thanks for your cooperation :)

**Comment by vors** [comment]
Thank you!

**Pull request merged**
