### PR TITLE
Added Awesome Functional Programming to the CS Category

### PR DESCRIPTION
**Pull request by lucasviola**

### CODE REVIEW

**Comment by lucasviola** [comment]
Let me know it it is still too early to propose this list, or if the category is wrong or anything! :)

**Comment by sindresorhus** [comment]
Please read the [instructions](https://github.com/sindresorhus/awesome/blob/master/create-list.md) for creating a new list, [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

Especially this part:

> Wait at least a couple of weeks after creating a list before submitting to give it a chance to mature.

Ping me here in a few weeks and I'll reopen ;)

**Comment by lucasviola** [comment]
Could you tell me what exactly is missing? Content? Something that is not attending the awesome criteria?

**Comment by sindresorhus** [comment]
I didn't say anything was missing. Just asking you to read those documents.

**Comment by lucasviola** [comment]
Yes, I understood that. But this is my second attempt at adding this specific list to the awesome project. In the first one you gave me the same message and also more specific feedback (which I very much appreciated). This time I really didn't get what I should focus on.

Thanks anyway. I will wait a couple of weeks and try again :)

**Comment by sindresorhus** [comment]
> But this is my second attempt at adding this specific list to the awesome project.

You should have mentioned that in the PR description. I can't possibly remember all previous contributions.

> This time I really didn't get what I should focus on.

Maybe following instructions. Looking at your last PR a week ago I cleary said:

> **Ping me here** in a **few weeks** and I'll reopen ;)

Neither was followed...

**Comment by lucasviola** [comment]
Ok. Now I know exactly what I've done wrong. Thank you very much.

**Pull request closed without merging**
