### PR TITLE
Add Generative AI Companies

### PR DESCRIPTION
**Pull request by AlexChalakov**
https://github.com/AlexChalakov/awesome-generative-ai-companies

It is a thoroughly researched list of companies that indulge in Generative AI with over $5MM raised as of August 2023. It is useful for the following few reasons:
- People would be able to keep informed regarding new intriguing and exciting Generative AI projects.
- People would be able to "job hunt" through this list and see if there is a company that matches their interests.
- The Industry is evolving and changing rapidly, so it would be useful to have somewhere where all of those companies could be monitored and listed.

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

## Requirements for your pull request

- [x] Don't open a Draft / WIP pull request while you work on the guidelines. A pull request should be 100% ready and should adhere to all the guidelines when you open it. **Instead use [#2242](https://github.com/sindresorhus/awesome/issues/2242) for incubation visibility**.
- [x] **Don't waste my time.** Do a good job, adhere to all the guidelines, and be responsive.
- [x] **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).**
	Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration. **Just commenting “looks good” or simply marking the pull request as approved does not count!** You have to actually point out mistakes or improvement suggestions. Comments pointing out lint violation are allowed, but does **not** count as a review.

- https://github.com/sindresorhus/awesome/pull/2731#issuecomment-1678623907
- https://github.com/sindresorhus/awesome/pull/2737#issuecomment-1678545588

- [x] You have read and understood the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/main/create-list.md).
- [x] This pull request has a title in the format `Add Name of List`. It should not contain the word `Awesome`.
	- ✅ `Add Swift`
	- ✅ `Add Software Architecture`
	- ❌ `Update readme.md`
	- ❌ `Add Awesome Swift`
	- ❌ `Add swift`
	- ❌ `add Swift`
	- ❌ `Adding Swift`
	- ❌ `Added Swift`
- [x] Your entry here should include a short description about the project/theme of the list. **It should not describe the list itself.** The first character should be uppercase and the description should end in a dot. It should be an objective description and not a tagline or marketing blurb.
	- ✅ `- [iOS](…) - Mobile operating system for Apple phones and tablets.`
	- ✅ `- [Framer](…) - Prototyping interactive UI designs.`
	- ❌ `- [iOS](…) - Resources and tools for iOS development.`
	- ❌ `- [Framer](…)`
	- ❌ `- [Framer](…) - prototyping interactive UI designs`
- [x] Your entry should be added at the bottom of the appropriate category.
- [x] The title of your entry should be title-cased and the URL to your list should end in `#readme`.
	- Example: `- [Software Architecture](https://github.com/simskij/awesome-software-architecture#readme) - The discipline of designing and building software.`
- [x] No blockchain-related lists.
- [x] The suggested Awesome list complies with the below requirements.

## Requirements for your Awesome list

- [x] **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
- [x] Run [`awesome-lint`](https://github.com/sindresorhus/awesome-lint) on your list and fix the reported issues. If there are false-positives or things that cannot/shouldn't be fixed, please [report it](https://github.com/sindresorhus/awesome-lint/issues/new).
- [x] The default branch should be named [`main`, not `master`](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/).
- [x] **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- ✅ `Mobile operating system for Apple phones and tablets.`
	- ✅ `Prototyping interactive UI designs.`
	- ❌ `Resources and tools for iOS development.`
	- ❌ `Awesome Framer packages and tools.`
- [x] It's the result of hard work and the best I could possibly produce.
	**If you have not put in considerable effort into your list, your pull request will be immediately closed.**
- [x] The repo name of your list should be in lowercase slug format: `awesome-name-of-list`.
	- ✅ `awesome-swift`
	- ✅ `awesome-web-typography`
	- ❌ `awesome-Swift`
	- ❌ `AwesomeWebTypography`
- [x] The heading title of your list should be in [title case](https://capitalizemytitle.com/) format: `# Awesome Name of List`.
	- ✅ `# Awesome Swift`
	- ✅ `# Awesome Web Typography`
	- ❌ `# awesome-swift`
	- ❌ `# AwesomeSwift`
- [x] Non-generated Markdown file in a GitHub repo.
- [x] The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
- [x] Not a duplicate. Please search for existing submissions.
- [x] Only has awesome items. Awesome lists are curations of the best, not everything.
- [x] Does not contain items that are unmaintained, has archived repo, deprecated, or missing docs. If you really need to include such items, they should be in a separate Markdown file.
- [x] Includes a project logo/illustration whenever possible.
	- Either centered, fullwidth, or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
	- The image should link to the project website or any relevant website.
	- **The image should be high-DPI.** Set it to maximum half the width of the original image.
- [x] Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- [x] Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/main/awesome.md#awesome-badge).
	- Should be placed on the right side of the readme heading.
		- Can be placed centered if the list has a centered graphics header.
	- Should link back to this list.
- [x] Has a Table of Contents section.
	- Should be named `Contents`, not `Table of Contents`.
	- Should be the first section in the list.
	- Should only have one level of [nested lists](https://commonmark.org/help/tutorial/10-nestedLists.html), preferably none.
	- Must not feature `Contributing` or `Footnotes` sections.
- [x] Has an appropriate license.
	- **We strongly recommend the [CC0 license](https://creativecommons.org/publicdomain/zero/1.0/), but any [Creative Commons license](https://creativecommons.org/choose/) will work.**
		- Tip: You can quickly add it to your repo by going to this URL: `https://github.com/<user>/<repo>/community/license/new?branch=main&template=cc0-1.0` (replace `<user>` and `<repo>` accordingly).
	- A code license like MIT, BSD, Apache, GPL, etc, is not acceptable. Neither are WTFPL and [Unlicense](https://unlicense.org).
	- Place a file named `license` or `LICENSE` in the repo root with the license text.
	- **Do not** add the license name, text, or a `Licence` section to the readme. GitHub already shows the license name and link to the full text at the top of the repo.
	- To verify that you've read all the guidelines, please comment on your pull request with just the word `unicorn`.
- [x] Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/main/awesome.md#include-contribution-guidelines).
	- The file should be named `contributing.md`. Casing is up to you.
	- It can optionally be linked from the readme in a dedicated section titled `Contributing`, positioned at the top or bottom of the main content.
	- The section should not appear in the Table of Contents.
- [x] All non-important but necessary content (like extra copyright notices, hyperlinks to sources, pointers to expansive content, etc) should be grouped in a `Footnotes` section at the bottom of the readme. The section should not be present in the Table of Contents.
- [x] Has consistent formatting and proper spelling/grammar.
	- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
	- The description starts with an uppercase character and ends with a period.
	- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
- [x] Does not use [hard-wrapping](https://stackoverflow.com/questions/319925/difference-between-hard-wrap-and-soft-wrap).
- [x] Does not include a CI (e.g. GitHub Actions) badge.<br>You can still use a CI for linting, but the badge has no value in the readme.
- [x] Does not include an `Inspired by awesome-foo` or `Inspired by the Awesome project` kinda link at the top of the readme. The Awesome badge is enough.

**Go to the top and read it again.**

### CODE REVIEW

**Comment by AlexChalakov** [comment]
unicorn

**Comment by donBarbos** [comment]
Lint is passing
```sh
➜  ~ npx awesome-lint https://github.com/AlexChalakov/awesome-generative-ai-companies
✔ Linting
```
**But**
1. you don't need to store the `.DS_Store` file in the repository
2. you use hard-wrapping in [readme file from line 5 to 7](https://github.com/AlexChalakov/awesome-generative-ai-companies/blob/db2d6c644bc9967a35d1e1be809c49228b2a9ec8/readme.md?plain=1#L5)

**Comment by AlexChalakov** [comment]
> i checked the requirements including linter and lint is passing
> 
> ```shell
> ➜  ~ npx awesome-lint https://github.com/AlexChalakov/awesome-generative-ai-companies
> ✔ Linting
> ```
> 
> **But**
> 
> 1. you don't need to store the `.DS_Store` file in the repository
> 2. you use hard-wrapping in [readme file from line 5 to 7](https://github.com/AlexChalakov/awesome-generative-ai-companies/blob/db2d6c644bc9967a35d1e1be809c49228b2a9ec8/readme.md?plain=1#L5) and check other markdown files hard-wrapping

**Comment by donBarbos** [comment]
I think it's worth re-reading what hard-wrapping is. I found a lot more hard-wrapping in your files.

Check all the lines yourself, here are just a few of them: `readme.md` - [194](https://github.com/AlexChalakov/awesome-generative-ai-companies/blob/main/readme.md?plain=1#L194), [588](https://github.com/AlexChalakov/awesome-generative-ai-companies/blob/1ba3fe9a843547a5ec9e65a67849650973efaf85/readme.md?plain=1#L588), [635](https://github.com/AlexChalakov/awesome-generative-ai-companies/blob/1ba3fe9a843547a5ec9e65a67849650973efaf85/readme.md?plain=1#L635) lines, `contributing.md` - [3-5](https://github.com/AlexChalakov/awesome-generative-ai-companies/blob/1ba3fe9a843547a5ec9e65a67849650973efaf85/contributing.md?plain=1#L3), [20-25](https://github.com/AlexChalakov/awesome-generative-ai-companies/blob/1ba3fe9a843547a5ec9e65a67849650973efaf85/contributing.md?plain=1#L20) lines,
almost the entire `code-of-conduct.md` (although [`sindresorhus/awesome/code-of-conduct.md`](https://github.com/sindresorhus/awesome/blob/main/code-of-conduct.md?plain=1) also has a lot of line transfers, so I think the main thing is that the readme shouldn't have)

Why are you quoting the description? In your case they have no value, it's better to do without them.
I also advise you to move the line `Fundraised around ... according to ...` to brackets so as not to spoil the list
from this:
```md
- [Grammarly]() - "Digital writing assistant."

Fundraised $400M according to Crunchbase and DealRoom
```
make this:
```md
- [Grammarly]() - Digital writing assistant, [$400M](Crunchbase link).
or
- [Grammarly]() - Digital writing assistant ([$400M](Crunchbase link)).
```
it also makes no sense to group by the amount of raised money, since they are arranged in ascending order anyway

**Comment by AlexChalakov** [comment]
> I think it's worth re-reading what hard-wrapping is. I found a lot more hard-wrapping in your files.
> 
> Check all the lines yourself, here are just a few of them: `readme.md` - [194](https://github.com/AlexChalakov/awesome-generative-ai-companies/blob/main/readme.md?plain=1#L194), [588](https://github.com/AlexChalakov/awesome-generative-ai-companies/blob/1ba3fe9a843547a5ec9e65a67849650973efaf85/readme.md?plain=1#L588), [635](https://github.com/AlexChalakov/awesome-generative-ai-companies/blob/1ba3fe9a843547a5ec9e65a67849650973efaf85/readme.md?plain=1#L635) lines, `contributing.md` - [3-5](https://github.com/AlexChalakov/awesome-generative-ai-companies/blob/1ba3fe9a843547a5ec9e65a67849650973efaf85/contributing.md?plain=1#L3), [20-25](https://github.com/AlexChalakov/awesome-generative-ai-companies/blob/1ba3fe9a843547a5ec9e65a67849650973efaf85/contributing.md?plain=1#L20) lines, almost the entire `code-of-conduct.md` (although [`sindresorhus/awesome/code-of-conduct.md`](https://github.com/sindresorhus/awesome/blob/main/code-of-conduct.md?plain=1) also has a lot of line transfers, so I think the main thing is that the readme shouldn't have)
> 
> Why are you quoting the description? In your case they have no value, it's better to do without them. I also advise you to move the line `Fundraised around ... according to ...` to brackets so as not to spoil the list from this:
> 
> ```
> - [Grammarly]() - "Digital writing assistant."
> 
> Fundraised $400M according to Crunchbase and DealRoom
> ```
> 
> make this:
> 
> ```
> - [Grammarly]() - Digital writing assistant, [$400M](Crunchbase link).
> or
> - [Grammarly]() - Digital writing assistant ([$400M](Crunchbase link)).
> ```
> 
> it also makes no sense to group by the amount of raised money, since they are arranged in ascending order anyway

Thank you for the feedback. I will go through all of the files and check for hard wrapping again. I have to say the the code-of-conduct.md file does not necessarily fall under this, since it is copy and pasted from sindresorhus's repository.

Regarding the other comments, I can't say I really agree with them. I find value in quoting the descriptions of the company because those descriptions are directly taken from their websites/social media profiles/other pages, so it is not my thought or saying, but rather their own description of who they are. I think this is better presenting someone else's thoughts and does not put liability on me in case something is wrong.

Regarding the format of the list, it consists of hundreds of companies and is increasing by the minute, so except mandatory, I would refrain from switching its format and would just leave the 'Fundraised around ... according to ...' part.

Finally, at least to me it makes sense for the companies to be grouped by the amount of raised money. Those are important thresholds and I believe it's vital for some people to be able to select just the right category they want to go through. It's cleaner and more organised this way.

**Comment by donBarbos** [comment]
there is a specific requirement in [pull_request_template.md](https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md?plain=1#L96):

> The description starts with an uppercase character and ends with a period.

**Comment by mozher** [comment]
1800 : AT!BAND=03,"1800",0,4
2100 : AT!BAND=04,"2100",0,1
700  : AT!BAND=05,"700",0,8000000
1800 + 700: AT!BAND=06,"1800 +700",0,8000004
1800 + 2100: AT!BAND=07,"1800 +2100",0,5
2100 + 700 : AT!BAND=08,"2100 +700",0,8000001
1800 + 2100 + 700: AT!BAND=09,"1800 +2100 +700",0,8000005
1800 + 2100 + 2300: 8000000005
1800 + 2300: 8000000004
2300: 8000000000
2100 + 2300: 8000000001
700 + 2300: 8008000000
700 + 2100 + 2300: 8008000001
700 + 1800 + 2300: 8008000004

اكواد ترددات Mobily:
800 : 80000
1800 : AT!BAND=03,"1800",0,4
2100 : AT!BAND=04,"2100",0,1
2500 : AT!BAND=05,"2500",0,10000000000
2600 : AT!BAND=06,"2600",0,2000000000
1800 + 2100: AT!BAND=07,"1800 +2100",0,5
2500 + 2600: AT!BAND=08,"2500 +2600",0,12000000000
1800 + 2100 + 800: AT!BAND=09,"1800 +2100 +800",0,80005
1800 + 2100 + 2500: 10000000005
2100 + 2600 : 2000000001
1800 + 2500 : 10000000004
1800 + 2600 : 2000000004
2100 + 2500 : 10000000001
1800 + 2100 + 2600 : 2000000005
1800 + 2500 + 2600 : 12000000004
2100 + 2500 + 2600 : 12000000001

اكواد ترددات Zain:
1800 : AT!BAND=03,"1800",0,4
2100 : AT!BAND=04,"2100",0,1
900  : AT!BAND=05,"900",0,80
1800 + 900: AT!BAND=06,"1800 +900",0,84
1800 + 2100: AT!BAND=07,"1800 +2100",0,5
2100 + 900: AT!BAND=08,"2100 +900",0,81
1800 + 2100 + 900: AT!BAND=09,"1800 +2100 vgv+900",0,85
800 : 80000
2600 : 2000000000

**Review by mozher — APPROVED** [review]
130.168.5.145

**Comment by mozher** [comment]
https://nodejs.org/dist/v18.17.1/node-v18.17.1.pkg

**Comment by sir-kokabi** [comment]
Regarding the list, I would recommend not using quotation marks around the descriptions. It's a common convention to present descriptions in lists without them, and it can make the content appear cleaner and more streamlined.

I mean, instead of this::

> [Replika](https://replika.com/) - "Developing digital copy of the human in the form of a chat-bot."

use this:

> [Replika](https://replika.com/) - Developing digital copy of the human in the form of a chat-bot.

**Comment by Proffindustries** [comment]
https://youtu.be/zQD2b_0frL8?si=1lwN49LzGKTofq20

**Review by 0220tiezo1323 — CHANGES_REQUESTED** [review]
N

**Comment by Horlabraing** [comment]
[“Blockchain#037b10c4fcd6b7c846de9e7a8d4e7f7f2759eb37a516fb826b4f4dd608d60241:”$27500&$1647——87%Blockchair,10024092843393.28%—£5,920!0.216BTC_$5,920:bc1q0024ly09apa2frg8p4az3d3krf9vqysfhfd3ga.•4,october,2023.11:15:10!#.Bit.pay]

**Comment by sindresorhus** [comment]
Bump

**Comment by herrjemand** [comment]
LGTM

**Review by tien142009 — APPROVED** [review]

**Comment by ggbetz** [comment]
Hi! Very interesting and helpful list. My suggestion: add together.ai.

**Review by kmk142789 — APPROVED** [review]

**Pull request closed without merging**
