### PR TITLE
Add Unity

### PR DESCRIPTION
**Pull request by caioteixeira**

### CODE REVIEW

**Comment by sindresorhus** [comment]
I'll add it if @RyanNielson follows the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md) ;)

**Comment by RyanNielson** [comment]
Consider it done @sindresorhus. :D

**Comment by sindresorhus** [comment]
Would you mind adding a license? See: https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license

And would be cool if you would add the awesome badge: https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge

At the bottom of your listen to mention `awesome-awesomeness`. https://github.com/RyanNielson/awesome-unity#other-awesome-lists You might want to remove that as that list is no longer maintained https://github.com/bayandin/awesome-awesomeness/issues/194

**Comment by RyanNielson** [comment]
I added the CC0 license along with the awesome badge. Let me know if you think I'm missing anything else.

**Comment by sindresorhus** [comment]
Thanks. Looks good now.

**Pull request closed without merging**
