### PR TITLE
add awesome-powershell

### PR DESCRIPTION
**Pull request by chantisnake**
**https://github.com/janikvonrotz/awesome-powershell**

**adding the awesome-powershell to `development environment` sector**

# ALL THE BELOW CHECKBOXES SHOULD BE DONE AND CHECKED AND THE ABOVE PLACEHOLDERS SHOULD BE FILLED IN BEFORE SUBMITTING A PULL REQUEST!

- [x] I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- [x] This pull request has a descriptive title. *(For example: `Add Node.js`)*
- The list I added
	- [x] **has been around for at least 20 days,**
	- [x] is a non-generated Markdown file in a GitHub repo,
	- [x] is not a duplicate,
	- [x] only has awesome items with descriptions *(Awesome lists are curations of the best, not of everything)*,
	- [x] contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- [ ] has a Table of Contents section named `Contents` as the first section,
	- [x] has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license) *(Meaning something like CC0, NOT a code licence like MIT, BSD, Apache, etc)*,
	- [x] has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- [ ] has been checked for inconsistent formatting, spelling, and grammar *(This includes starting each link description with an uppercase character and ending it with a period `.`, and consistent naming)*,
	- [ ] has been added at the bottom of the appropriate category.

### CODE REVIEW

**Comment by daviwil** [comment]
Hey @chantisnake, can you update the item to use the proper casing "PowerShell"?  Thanks!

**Comment by sindresorhus** [comment]
@chantisnake Don't check checkboxes that are clearly not done... I've unchecked the ones that are invalid.

**Comment by chantisnake** [comment]
I will fix all the cases, grammar and contents issue. and then create a new pull request

@sindresorhus I think the reason that the list is small is because there is not that many people know about this list... I think putting this list in you awesome list will solve this problem, and `Awesome-PowerShell` can get more people to contribute.

**Comment by chantisnake** [comment]
@sindresorhus  I see you have unchecked:
> has been added at the bottom of the appropriate category.

Why PowerShell doesn't belongs in `Development Environment`?

**Comment by lholznagel** [comment]
@chantisnake you have to add it to under the last item of this section. The list is not alphabetically sorted

**Comment by chantisnake** [comment]
okay, that makes sense.

**Comment by sindresorhus** [comment]
> I think the reason that the list is small is because there is not that many people know about this list... I think putting this list in you awesome list will solve this problem, and Awesome-PowerShell can get more people to contribute.

No, the reason it's small is because you haven't worked on it long and hard enough. Great awesome lists are hard work. You shouldn't expect to be able to just put up a quick list and have contributors do your job. Awesome lists are awesome from the start. External contributors are useful later on for contributing things you couldn't find.

**Pull request closed without merging**
