### PR TITLE
Added JSON Datasets to Miscellaneous

### PR DESCRIPTION
**Pull request by jdorfman**

### CODE REVIEW

**Comment by aleksandar-todorovic** [comment]
Please read [The awesome manifesto](https://github.com/sindresorhus/awesome/blob/master/awesome.md) and make sure your list complies to it.

**Comment by sindresorhus** [comment]
Generally looks good, but I think each item in this section could use a description: https://github.com/jdorfman/awesome-json-datasets#sources

**Comment by jdorfman** [comment]
@sindresorhus since all of the links go directly to the JSON endpoint I wanted to give credit to the sites hence the `Sources` section.  Since this is a unique case and not in the manifesto should I just remove that section?

**Comment by sindresorhus** [comment]
A random list of links isn't very useful. I would either add a description to each item or remove the section.

**Comment by jdorfman** [comment]
I agree.  Removed the section all together.  Thanks for the feedback.

**Comment by sindresorhus** [comment]
Ok, looks good. Can you fix the merge conflict?

**Comment by jdorfman** [comment]
@sindresorhus sure I will just close this PR and resubmit.

**Pull request closed without merging**
