### PR TITLE
Add Persian NLP

### PR DESCRIPTION
**Pull request by mhbashari**
**https://github.com/mhbashari/awesome-persian-nlp-ir**

**[Explain what this list is about and why it should be included here.]**

# By submitting this pull request I confirm I've read and complied with the below requirements.

Failure to properly do so will just result in the pull request being closed and everyone's time wasted. Please read it twice. Most people miss many things.

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title. For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should include a short description about the list project/theme (not the list itself), and should be added at the bottom of the appropriate category.
- The list I added
	- **has been around for at least 30 days,**
	- is the result of hard work and is the best I could possibly produce,
	- is a non-generated Markdown file in a GitHub repo,
	- is not a duplicate,
	- includes a succinct description of the project/theme at the top ([example](https://github.com/willempienaar/awesome-quantified-self)),
	- includes a project logo/illustration (whenever possible) at the top right of the readme ([example](https://github.com/sindresorhus/awesome-electron)). (The logo should link to the project website or any relevant website. The logo should be high-DPI, so set it to maximum half the width of the original image.),
	- only has awesome items **with descriptions** *(Awesome lists are curations of the best, not of everything)*,
	- contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- has a Table of Contents section **named `Contents`** as the first section,
	- has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license) *(Meaning something like CC0, NOT a code licence like MIT, BSD, Apache, etc)* *(If you use a license badge, it should be SVG, not PNG)*,
	- has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- doesn't include a Travis badge,
	- has been checked for inconsistent formatting, spelling, and grammar:
		- Each link description starts with an uppercase character and ends with a period.
		- Drop all the `A` / `An` prefixes in the descriptions.
		- Consistent naming. For example, `Node.js`, not `NodeJS` or `node.js`.

### CODE REVIEW

**Comment by aleksandar-todorovic** [comment]
> has been checked for inconsistent formatting, spelling, and grammar:
> * Each link description starts with an uppercase character and ends with a period.
> * Drop all the A / An prefixes in the descriptions.
> * Consistent naming. For example, Node.js, not NodeJS or node.js.

Please check your list for this. There's Ruby written in lowercase, a dash in the term "open source", some descriptions start with "A-", "An-" and "The-", there's... well, `text!.replace` for whatever reason, "cleaning" spelled with two "n"s etc.

Also, this is like sixth time you've opened a new PR. Please, don't do that and ping us on the existing one. If we're not answering, that means that you haven't fixed some of the issues we had with your list (and are still present, sixth time you've submitted your list).

**Comment by davisonio** [comment]
Did you get permission from ACL WEB to use their content and publish under public domain?

- Replace `This list is curation of the best, not of everything. Please participate in its development.Thanks to ACL WEB.` with a description about Persian NLP.
- Remove the new lines in the contents
- Contents should be as `## Contents `

The list still needs a lot more work there's typos such as ` Light Weight` -> `lightweight`. **Please don't open a new PR!**

**Comment by sindresorhus** [comment]
ping @mhbashari

**Comment by sindresorhus** [comment]
Closing for lack of response. There's no point in resubmitting at a later point as you've lost the chance to be included in the Awesome list.

**Pull request closed without merging**
