### PR TITLE
Add Corda

### PR DESCRIPTION
**Pull request by akegaviar**
- [Corda](https://github.com/chainstack/awesome-corda#readme) - Open source blockchain platform designed for business.

This list is very useful for people working with Corda. It's the only list too, and I've had the Corda community get involved with it.

By submitting this pull request I confirm I've read and complied with [the awesome list requirements](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) 🖖

PRs reviewed: #1682, #1677, #1681, #1679. Only commented on the ones that had issues previously unreported.

### CODE REVIEW

**Comment by akegaviar** [comment]
unicorn

**Comment by GustavBertram** [comment]
You should be able to approve PRs if they look good to you, rather that just commenting on the problems. Otherwise, looks great to me!

**Comment by sindresorhus** [comment]
- I don't think you should have both the text and image header. They both say the same thing. Pick one.
- The header image should be linked to the Corda website.
- Link `Corda` in `Corda is an open-source blockchain platform.` to its website.
- I think the top of the readme should elaborate a little bit more on what Corda is.

**Comment by akegaviar** [comment]
> I don't think you should have both the text and image header. They both say the same thing. Pick on.
Done.

> The header image should be linked to the Corda website.
Done.

> Link Corda in Corda is an open-source blockchain platform. to its website.
Done.

> I think the top of the readme should elaborate a little bit more on what Corda is.
Done.

**Comment by sindresorhus** [comment]
Tweet: https://twitter.com/awesome__re/status/1219503310215901184

**Pull request merged**
