### PR TITLE
awesome-jvm, languages, tools and other resources for the JVM

### PR DESCRIPTION
**Pull request by krisskross**
The list is small since awesome-jvm was started a few minutes ago. Intend to expand the list as time goes on.

### CODE REVIEW

**Comment by aleksandar-todorovic** [comment]
Please read the `awesome.md` file and make sure your list complies to it. Currently, your list doesn't contain contributing guidelines nor a license.

**Comment by sindresorhus** [comment]
There's also almost no content in the list. Give it some weeks to mature and improve it. Ping me here at that time and I'll reopen.

https://github.com/sindresorhus/awesome/blob/master/contributing.md
https://github.com/sindresorhus/awesome/blob/master/awesome.md

**Comment by krisskross** [comment]
No problem. Ill get back to you.

**Comment by krisskross** [comment]
The list is coming along. What do you think?

**Comment by sindresorhus** [comment]
> Give it some weeks to mature and improve it.

**Comment by krisskross** [comment]
Few more weeks?

**Comment by sindresorhus** [comment]
Landed. Looks good. Thanks for your patience.

**Comment by krisskross** [comment]
Cheers dude!

**Pull request closed without merging**
