### PR TITLE
Add TensorFlow

### PR DESCRIPTION
**Pull request by jtoy**

### CODE REVIEW

**Comment by sindresorhus** [comment]
My feedback in the previous pull request https://github.com/sindresorhus/awesome/pull/596 is not resolved.

> The list could use some improving when it comes to formatting and grammar. **You've pretty much have 5 different ways of writing TensorFlow in there. Please keep it consistent.** Same with ending an item description in a . or not. It's GitHub, not Github.

> **With TensorFlow Libraries, the TensorFlow prefix is moot.**

**Comment by sindresorhus** [comment]
Even the repo description is inconsistent:

> **TensorFlow** - A curated list of resources dedicated to **tensorflow**

Also no need to mention TensorFlow twice there.

**Comment by sindresorhus** [comment]
> more info here: http://tensorflow.org

`More`

**Comment by sindresorhus** [comment]
- Move the `Contributions` section to the bottom. It should also link to the `contributing.md` file.
- The Table of Contents is out of sync with the content.
- Would be nice to add a TensorFlow logo/graphics to the readme. See https://github.com/websemantics/awesome-synthetic-biology and https://github.com/sindresorhus/awesome-npm
- Add a `Community` section. E.g. https://github.com/sindresorhus/awesome-electron#community Could find some here: https://www.tensorflow.org/versions/r0.8/resources/index.html

**Comment by jtoy** [comment]
@sindresorhus think I got everything :)

**Comment by sindresorhus** [comment]
Ok. Looks good now. Added :)

**Comment by sindresorhus** [comment]
You missed the mailinglist: https://groups.google.com/a/tensorflow.org/forum/#!forum/discuss

And would like to see:

> Would be nice to add a TensorFlow logo/graphics to the readme. See https://github.com/websemantics/awesome-synthetic-biology and https://github.com/sindresorhus/awesome-npm

**Pull request merged**
