### PR TITLE
Adds a link to @cv awesome-geek-podcasts

### PR DESCRIPTION
**Pull request by bltavares**
Adds a link to @cv [awesome-geek-podcasts](https://github.com/cv/awesome-geek-podcasts)

### CODE REVIEW

**Comment by sindresorhus** [comment]
Not very useful when it's just a list of links. Add a succinct description to each of them. Bonus points if you add commentary on why they're awesome. Happy to include it when that's done ;)

**Comment by bltavares** [comment]
@sindresorhus That really makes sense. The repo has been updated with descriptions of the podcast. Should this PR be reopened?

**Comment by sindresorhus** [comment]
Better, but some of the descriptions feels awkwardly copy-pasted.

Also:

> A curated list of podcasts **we like to listen to**.

Why? - Is my first question when looking at the items. I can Google "geek podcasts" and get a similar lists. I want to know why I should bother listen to them.

**Comment by sindresorhus** [comment]
Added.

https://github.com/cv/awesome-geek-podcasts/issues/22

@cv Would be cool if you could link back here in your list so users can easily discover more awesome lists ;)

**Pull request closed without merging**
