### PR TITLE
Add CircuitPython

### PR DESCRIPTION
**Pull request by TheKitty**
Request to add the Adafruit Industries curated awesome list devoted to CircuitPython, a microcontroller based version of Python, to the Python category. The Adafruit CircuitPython awesome list is at https://github.com/adafruit/awesome-circuitpython
[https://github.com/adafruit/awesome-circuitpython]
[Request to add the Adafruit Industries curated awesome list devoted to CircuitPython, a microcontroller based version of Python, to the Python category.]

We have read the guidelines multiple times and have tried to ensure every single item is covered.

**[https://github.com/adafruit/awesome-circuitpython]**

**[Request to add the Adafruit Industries curated awesome list devoted to CircuitPython, a microcontroller based version of Python, to the Python category.]**

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

## Requirements for your pull request

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title.<br>For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
	- Be added at the bottom of the appropriate category.
- The list I'm submitting complies with these requirements:

## Requirements for your Awesome list

- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
- It's the result of hard work and the best I could possibly produce.
- Non-generated Markdown file in a GitHub repo.
- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
- Not a duplicate.
- Only has awesome items. Awesome lists are curations of the best, not everything.
- Includes a project logo/illustration whenever possible.
	- Either fullwidth or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
	- The image should link to the project website or any relevant website.
	- The image should be high-DPI. Set it to maximum half the width of the original image.
- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
	- Should be placed on the right side of the readme heading.
	- Should link back to this list.
- Has a Table of Contents section.
	- Should be named `Contents`, not `Table of Contents`.
	- Should be the first section in the list.
	- Should only have one level of sub-lists, preferably none.
- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
	- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
	- [WTFPL](http://www.wtfpl.net) and [Unlicense](http://unlicense.org) are not acceptable licenses.
	- If you use a license badge, it should be SVG, not PNG.
- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
	- The file should be named `contributing.md`. Casing is up to you.
- Has consistent formatting and proper spelling/grammar.
	- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
	- The description starts with an uppercase character and ends with a period.
	- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.

Go to the top and read it again.

### CODE REVIEW

**Comment by legodude17** [comment]
Is there any reason you opened this and close #1326 instead of responding to the feedback?

**Comment by TheKitty** [comment]
Yes, in the first submission a month ago, I did not receive feedback. I looked over your guidelines about git and I do not have a command line version running at this time, so I took the route proposed in #7 along with prior experience to make the changes. I apologize if this was not the best course of action.

**Comment by TheKitty** [comment]
@legodude17 - please?

**Comment by legodude17** [comment]
@TheKitty AFAICT it fulfills the requirements, but I do not have push access and am not an official maintainer.

**Comment by TheKitty** [comment]
Ok, who would I ask politely to consider a merge?

**Comment by legodude17** [comment]
That would be @sindresorhus, but as he said in https://github.com/sindresorhus/awesome/issues/1323#issuecomment-394338501, he is burnt out on this project right now.

**Comment by TheKitty** [comment]
@sindresorhus - this one passes the new readme requirement and is ready. Thanks for your hard work, Mike

**Comment by TheKitty** [comment]
My boss asked me why I haven't got the list on after 5 weeks. I didn't have an answer. :(

**Comment by sindresorhus** [comment]
@TheKitty You can send your boss a link to #1363. I'm only one person. I have 100+ PRs to go through. Many of which requires a lot of work.

**Comment by sindresorhus** [comment]
I've done a PR with some improvements: https://github.com/adafruit/awesome-circuitpython/pull/2

**Comment by TheKitty** [comment]
Adafruit really appreciates @sindresorhus improvements posted to https://github.com/adafruit/awesome-circuitpython - the PR was merges this morning. Cheers!

**Comment by TheKitty** [comment]
Per new guidelines, Adafruit has reviewed the following PRs:
https://github.com/sindresorhus/awesome/pull/1160
and
https://github.com/sindresorhus/awesome/pull/1127
and provided substantive comments as to getting them to meet the guidelines. 

@sindresorhus - is that sufficient? Thank you.

**Comment by sindresorhus** [comment]
Tweet: https://twitter.com/awesome__re/status/1025240714718797824

**Comment by ladyada** [comment]
awesome! 😎

**Review by syeikhan-azlin — APPROVED** [review]

**Pull request merged**
