### PR TITLE
Add Discord

### PR DESCRIPTION
**Pull request by jacc**
https://github.com/jacc/awesome-discord

This list contains useful resources for Discord things, such as bots, servers, and development languages.

# By submitting this pull request I confirm I've read and complied with the below requirements.

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title.<br>For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
	- Be added at the bottom of the appropriate category.
- The list I'm submitting complies with these requirements:
	- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
	- It's the result of hard work and the best I could possibly produce.
	- Non-generated Markdown file in a GitHub repo.
	- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
	- Not a duplicate.
	- Only has awesome items. Awesome lists are curations of the best, not everything.
	- Includes a project logo/illustration whenever possible.
		- Either fullwidth or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
		- The image should link to the project website or any relevant website.
		- The image should be high-DPI. Set it to maximum half the width of the original image.
	- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
	- Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
		- Should be placed on the right side of the readme heading.
		- Should link back to this list.
	- Has a Table of Contents section.
		- Should be named `Contents`, not `Table of Contents`.
		- Should be the first section in the list.
		- Should only have one level of sub-lists, preferably none.
	- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
		- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
		- [WTFPL](http://www.wtfpl.net) and [Unlicense](http://unlicense.org) are not acceptable licenses.
		- If you use a license badge, it should be SVG, not PNG.
	- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
		- The file should be named `contributing.md`. Casing is up to you.
	- Has consistent formatting and proper spelling/grammar.
		- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
		- The description starts with an uppercase character and ends with a period.
		- Drop all the `A` / `An` prefixes in the descriptions.
		- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
	- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.
- Go to the top and read it again.

### CODE REVIEW

**Comment by vitalkanev** [comment]
> less than 30 days

**Comment by jacc** [comment]
@vitalkanev by <4 days? could I close then reopen to re apply? I figured I was so close it didn't matter

**Comment by jacc** [comment]
pinging @sindresorhus

**Comment by jacc** [comment]
@sindresorhus are you waiting until the 30 day mark to add/critique? just looking for tips on what I need to add

**Comment by jacc** [comment]
@sindresorhus ping2, should I just close it?

**Comment by ugurozturk** [comment]
@jacc i think you should wait lil more :) if he doesn't like it, he just closing it to make this Awesome

**Comment by jacc** [comment]
@sindresorhus 👀

**Comment by sindresorhus** [comment]
The header looks great! :)

**Comment by sindresorhus** [comment]
The "Community" link in "Contents" doesn't work

---

The description starts with an uppercase character and **ends with a period.**

---

Has an appropriate license.
That means something like CC0, not a code licence like MIT, BSD, Apache, etc.

---

You have just copy-pasted the contributing.md from the Awesome list. It should be customized for your list. Probably better to copy and customize from a list like https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md

---

`URLS` is not a good title.

---

It's not clear what `Discord Nitro`. It should have a description.

---

In `Popular Servers`, can you add some more than just Reddit servers?

---

I'd like to see more tutorials/blog posts about making Discord bots and other related dev resources.

For example: https://medium.com/@renesansz/tutorial-creating-a-simple-discord-bot-9465a2764dc0

**Comment by sindresorhus** [comment]
Ping. Please also see #1363.

**Comment by yudataguy** [comment]
❌ subreddit section link not working
❌ Missing license info in readme.md
❌ Lack of description in community resource section

**Comment by jacc** [comment]
Hey Sindre!
I’ll go ahead and review some other projects before resubmitting. My project has come a long way since I first applied.
Thanks so much for all you do for the community!

**Comment by sindresorhus** [comment]
Ping :)

**Comment by sindresorhus** [comment]
You also need to fix the merge conflict.

**Comment by jacc** [comment]
Sorry man, I'll look at this when I can. School has become overwhelming :(

**Comment by jacc** [comment]
I’ll be closing this for now and I’ll reopen this weekend.

**Pull request closed without merging**
