### PR TITLE
Add k6

### PR DESCRIPTION
**Pull request by simskij**
https://github.com/k6io/awesome-k6

This list contains resources about the popular open-source, developer-centric performance monitoring and load testing solution k6.

### CODE REVIEW

**Comment by simskij** [comment]
ybucirb

**Comment by simskij** [comment]
https://github.com/sindresorhus/awesome/pull/1720

**Comment by sindresorhus** [comment]
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

**Comment by simskij** [comment]
@sindresorhus, unsure what that would be? It passes awesome-lint, has a detected license, CoC and contribution file.

**Comment by radek-sprta** [comment]
Just couple things I've noticed:
This line does not end with a period: - [k6-typescript-framework](https://github.com/go-automate/k6-typescript-framework) - Example of a k6 load testing framework written in TypeScript
Includes seemingly empty repository: https://github.com/loadimpact/k6-gitlab-example

**Comment by simskij** [comment]
Thank you for the pointers! Adjusted.

**Comment by ltchris** [comment]
I see a few `k6` and `K6` , the guideline wants consistent naming:
> Consistent and correct naming. For example, Node.js, not NodeJS or node.js.

**Comment by simskij** [comment]
> I see a few `k6` and `K6` , the guideline wants consistent naming:
> 
> > Consistent and correct naming. For example, Node.js, not NodeJS or node.js.

The actual name is k6, but the linter prevents me from using that in the header, unfortunately, due to title casing rules. That is also the only place where it's not k6, so no - there are no inconsistencies in naming.

**Comment by sindresorhus** [comment]
> The actual name is k6, but the linter prevents me from using that in the header, unfortunately

You can ignore linter rules when they're wrong: https://github.com/sindresorhus/awesome-lint#special-comments

**Comment by sindresorhus** [comment]
> The image should be high-DPI. Set it to maximum half the width of the original image. - https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md

**Comment by simskij** [comment]
> > The image should be high-DPI. Set it to maximum half the width of the original image. - https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md

Fixed! Thanks for the feedback!

**Comment by simskij** [comment]
> > The actual name is k6, but the linter prevents me from using that in the header, unfortunately
> 
> You can ignore linter rules when they're wrong: https://github.com/sindresorhus/awesome-lint#special-comments

Fixed! Thanks for the feedback!

**Comment by sindresorhus** [comment]
Tweet: https://twitter.com/awesome__re/status/1236975875049963520

**Pull request merged**
