### PR TITLE
New in Development Environment - vcs tools list link

### PR DESCRIPTION
**Pull request by yn-coder**
New in Development Environment - vcs tools list link

I've add the curated list in Development Environment - list of Git/SVN/HG clients and tools

**https://github.com/postpdm/awesome-vcs-tools**

**It's a list of VCS clients and diff tools. Please, approve**

# By submitting this pull request I confirm I've read and complied with the below requirements.

Failure to properly do so will just result in the pull request being closed and everyone's time wasted. Please read it twice. Most people miss many things.

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title. For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should include a short description about the list project/theme (not the list itself), and should be added at the bottom of the appropriate category.
- The list I added
	- **has been around for at least 30 days,**
	- is the result of hard work and is the best I could possibly produce,
	- is a non-generated Markdown file in a GitHub repo,
	- is not a duplicate,
	- includes a succinct description of the project/theme at the top ([example](https://github.com/willempienaar/awesome-quantified-self)),
	- includes a project logo/illustration (whenever possible) at the top right of the readme ([example](https://github.com/sindresorhus/awesome-electron)). (The logo should link to the project website or any relevant website. The logo should be high-DPI, so set it to maximum half the width of the original image.),
	- only has awesome items **with descriptions** *(Awesome lists are curations of the best, not of everything)*,
	- contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- has a Table of Contents section **named `Contents`** as the first section,
	- has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license) *(Meaning something like CC0, NOT a code licence like MIT, BSD, Apache, etc)* *(If you use a license badge, it should be SVG, not PNG)*,
	- has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- doesn't include a Travis badge,
	- has been checked for inconsistent formatting, spelling, and grammar:
		- Each link description starts with an uppercase character and ends with a period.
		- Drop all the `A` / `An` prefixes in the descriptions.
		- Consistent naming. For example, `Node.js`, not `NodeJS` or `node.js`.

New in Development Environment - vcs tools list link

### CODE REVIEW

**Comment by egeerardyn** [comment]
While the topic of the list is certainly interesting, your list is very far from being awesome at the moment (which is normal after just 3 hours of work).

> I have read and understood the contribution guidelines and the instructions for creating a list.
Please **attentively read the guidelines and instructions**, that should make most problems in your list clear.

**Comment by yn-coder** [comment]
@egeerardyn 
Can you help to improve the https://github.com/postpdm/awesome-vcs-tools ? :)
3 hours - it's just the time to write the list, Data I have got from my existing file. :)

**Comment by aleksandar-todorovic** [comment]
> By submitting this pull request I confirm I've read and complied with the below requirements.

I don't even know where to start with pointing out what it doesn't follow, so I'm just going to close this.

**Comment by egeerardyn** [comment]
@yn-coder: maybe when your list has matured for a week or two and you have fixed some of the obvious flaws, then I can put some time of mine into that list. 
But first priority for you is to make sure your list complies with the guidelines.

**Comment by yn-coder** [comment]
Ok

**Pull request closed without merging**
