### PR TITLE
Add link to awesome-vulkan

### PR DESCRIPTION
**Pull request by vinjn**
Vulkan is the new graphics API.

### CODE REVIEW

**Comment by n1trux** [comment]
merged, but it's pretty short. Considering Vulkan only released today, I hope it grows in size very soon ;)

**Comment by sindresorhus** [comment]
@n1trux This was a bit premature.

**Comment by sindresorhus** [comment]
Please read the [instructions](https://github.com/sindresorhus/awesome/blob/master/create-list.md) for creating a new list, [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

Especially this part:

> Wait at least a couple of weeks after creating a list before submitting to give it a chance to mature.

Try again in a few weeks ;)

**Comment by sindresorhus** [comment]
Would be useful to include this https://pbs.twimg.com/media/CbUg4_5WEAANwhc.jpg:orig

And https://renderdoc.org/vulkan-in-30-minutes.html

**Comment by n1trux** [comment]
oh, sorry @sindresorhus, I just thought that this technology in particular would be awesome to have on our list, since it'll probably gain momentum soon and people will be searching for it.

**Comment by sindresorhus** [comment]
@n1trux Sure, but the guidelines are equal for everyone. The two weeks is also used as a test for whether people are actually interested in running a list or just want some short-lived famous points. Lots of now unmaintained lists never ended up here because of this, which is a good thing.

**Comment by vinjn** [comment]
Thanks guys, I can wait for some weeks :)

**Comment by janisozaur** [comment]
I am one of observers of this repository (awesome, not awesome-vulkan), in case you want to hear some external opinion, here's my 2c:

I find pull requests to be a staging area. While those few weeks are a valid period of time for verifying the list in question and I wouldn't change it, submitting a PR will reach broader audience (~30k stars, ~2k watchers), which in turn will help bettering the list, so when PR is to get merged, the list will hopefully matured a little since the PR was opened.

Thank you for maintaining this list.

**Comment by sindresorhus** [comment]
@janisozaur I would usually agree, but in this case it would make the PR issue tracker very noisy and I honestly think it's the job of the maintainer to create a good starting point before other people start contributing. A lot of submitted lists here only contain a few links and looks like it's put together in 5 min, with missing contributing guidelines and license. Is it really fair to expose potential contributors to this?

**Pull request merged**
