### PR TITLE
Add Colorful

### PR DESCRIPTION
**Pull request by Siddharth11**
A curated list of awesome resources to choose your next color scheme. 

> Ping me here in a few weeks and I'll reopen ;)

Since then, it hasn't changed much, but as per your advice I've re-opened it :)

### CODE REVIEW

**Comment by sindresorhus** [comment]
Some feedback:

- Use `##` type headings for Table of Contents, Tools and Articles.
- The Tools section should be split up. Web based tools, libraries, etc.
- Are there any communities like Slack channels, gitter rooms, forums, IRC channels, etc, where people can discuss colors? If yes, link to it.
- Totally optional, but would be cool to have an illustration at the top. Here's a good example: https://github.com/websemantics/awesome-synthetic-biology You could have some color scheme illustration or something.

**Comment by Siddharth11** [comment]
@sindresorhus thanks for all the suggestions. It does look better now.

**Comment by Siddharth11** [comment]
- [x] I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- [x] This pull request has a descriptive title.
- The list I added
	- [x] is not a duplicate,
	- [x] has been around for a few weeks,
	- [x] only has awesome items with descriptions,
	- [x] contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- [x] has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license),
	- [x] has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- [x] has been checked for inconsistent formatting, spelling and grammar, and
	- [x] has been added at the bottom of the appropriate category.

**Comment by sindresorhus** [comment]
I think an illustration would work better than just a random (in this case, boring) stock photo. Also drop the `<br>` between sections.

**Pull request closed without merging**
