### PR TITLE
Add Home Assistant

### PR DESCRIPTION
**Pull request by frenck**
**https://github.com/frenck/awesome-home-assistant#readme**

This list is for Home Assistant. Home Assistant is an open source Home Automation system/hub which allows a user to automate every aspect of their home fully. It is currently the largest open source project in its category.

The list itself is now a month old and snowballed. It had some contributions and got a surprisingly large amount of stars on GitHub, which caused it to be a trending repository on GitHub in the month it was published.

> :speech_balloon: _I've tried to be as accurate as possible with this PR, by adding checkmarks and comments on each requirement in the PR template. I'm really curious to find out what you think!_

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

:white_check_mark: **Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

> :speech_balloon: _Read it at least 10 times! And added checkboxes to checked each one off, one by one._

> :speech_balloon: _@sindresorhus, I really appreciate the time and effort you've put into this, nevertheless, the PR template conflicts with your own maintained lists (and multiple others). IMHO this is unfair (no hard feelings, just noticed it)._

## Requirements for your pull request

- :white_check_mark: **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).** Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration.

  > :speech_balloon: _Reviewed: [#1079](https://github.com/sindresorhus/awesome/pull/1079#pullrequestreview-151629159) and [#1389](https://github.com/sindresorhus/awesome/pull/1389#pullrequestreview-151630735)_

- :white_check_mark: I have read and understood the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- :white_check_mark: This pull request has a descriptive title in the format `Add Name of List` (Example: `Add Swift`), not `Update readme.md` or `Add awesome list`.
- :white_check_mark: The entry in the Awesome list should:
    - :white_check_mark: Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
    - :white_check_mark: Be added at the bottom of the appropriate category.
- :white_check_mark: The list I'm submitting complies with the below requirements.

## Requirements for your Awesome list

- :white_check_mark: **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.

  > :speech_balloon: _The list has been in private development for months (link collection, perfecting the setup). [The first public commit](https://github.com/frenck/awesome-home-assistant/commit/aeb30e8db6d7d47d6154b91466afca59561242a8) was 30 July 2018 and [announced the list publicly](https://twitter.com/Frenck/status/1024694967372079104) on 1 August 2018._
  
- :white_check_mark: It's the result of hard work and the best I could possibly produce.

  > :speech_balloon: _Hard work: for sure. The best I could produce: I'm my own worst critic, perfectionist and never satisfied with the result. So no. I do, however, strongly believe in making continuous improvements._

- :white_check_mark: Non-generated Markdown file in a GitHub repo.
  
  > :speech_balloon: _The list is not generated, however, this list format is transformed into a website: [awesome-ha.com](https://www.awesome-ha.com)._
  
- :white_check_mark: **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
- :white_check_mark: The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.

  > :speech_balloon: _First to on the topics lists! Added a bunch of related and relevant topics as well._
  
- :white_check_mark: Not a duplicate.

  > :speech_balloon: _It is not a duplicate. I did [find another repo](https://github.com/mishbahr/awesome-home-assistant), that suggest of doing the same thing, but it has been empty for a while now._

- :white_check_mark: Only has awesome items. Awesome lists are curations of the best, not everything.

  > :speech_balloon: _Awesome should be awesome. I'm not perfect, but at least there is "me" in "awesome"._
  
- :white_check_mark: Includes a project logo/illustration whenever possible.
  
  > :speech_balloon: _Created a mashup with the Home Assistant logo and the Awesome logo in SVG format._

    - :heavy_exclamation_mark: Either fullwidth or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
    
      > :speech_balloon: _Took @sindresorhus main Awesome list as an example, and placed it top center. This is also done by multiple other lists, e.g., [Node.js](https://github.com/sindresorhus/awesome-nodejs#readme) and [iOS](https://github.com/vsouza/awesome-ios#readme)_
    
    - :white_check_mark: The image should link to the project website or any relevant website.

      > :speech_balloon: _It links to the website version of the list: <https://www.awesome-ha.com>_

    - :white_check_mark: The image should be high-DPI. Set it to maximum half the width of the original image.

      > :speech_balloon: _It is an SVG, which always renders nicely._
      
- :white_check_mark: Entries have a description, unless the title is descriptive enough by itself. It rarely is though.

  > :speech_balloon: _All entries have a description, even most categories have a small description._

- :white_check_mark: Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
    - :heavy_exclamation_mark: Should be placed on the right side of the readme heading.
    
      > :speech_balloon: _It has been placed prominently under the list logo. as done by other big lists, e.g., @sindresorhus his own [Node.js](https://github.com/sindresorhus/awesome-nodejs#readme) list._
    
    - :white_check_mark: Should link back to this list.
    
- :white_check_mark: Has a Table of Contents section.
    - :white_check_mark: Should be named `Contents`, not `Table of Contents`.
    - :heavy_exclamation_mark: Should be the first section in the list.
     
      > :speech_balloon: _Conflicting rule: `description of the project/theme at the top`. So there is an about section first, Contents second._
     
    - :question: Should only have one level of sub-lists, preferably none.

      > :speech_balloon: _The definition of "sub-list" is nowhere to be found, therefore, unable to know if the list adheres to this rule._

- :white_check_mark: Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
  
  > :speech_balloon: _Distributed under the Creative Commons Attribution 4.0 license. See [LICENSE](https://github.com/frenck/awesome-home-assistant/blob/master/LICENSE.md) for the complete license. No license badge is used._
  
  > :speech_balloon: _The list has an additional [Trademark Legal Notice](https://github.com/frenck/awesome-home-assistant#trademark-legal-notice) section, which IMHO should be added to this Awesome list PR template._

    - :white_check_mark: That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
    - :white_check_mark: [WTFPL](http://www.wtfpl.net) and [Unlicense](http://unlicense.org) are not acceptable licenses.
    - :white_check_mark: If you use a license badge, it should be SVG, not PNG.

- :white_check_mark: Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).

  > :speech_balloon: _It has: [Awesome Home Assistant - Contribution guidelines](https://github.com/frenck/awesome-home-assistant/blob/master/CONTRIBUTING.md)._
  
    - :white_check_mark: The file should be named `contributing.md`. Casing is up to you.
- :white_check_mark: Has consistent formatting and proper spelling/grammar.
    - :white_check_mark: The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
    - :white_check_mark: The description starts with an uppercase character and ends with a period.
    - :white_check_mark: Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
- :white_check_mark: Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.

  > :speech_balloon: _The list uses `awesome_bot` and `DangerCI` to validate the list and PRs. See [`.travis.yml`](https://github.com/frenck/awesome-home-assistant/blob/master/.travis.yml). However, no badges are added._

:repeat: Go to the top and read it again.
> :speech_balloon: _I've been stuck in this infinite loop for a month!_ :unamused:

### CODE REVIEW

**Comment by frenck** [comment]
Thank you @hsluoyz for the review.
I will correct 3 of those.

The `Should be the first section in the list.` was mentioned by me already and I was not planning on changing that.

**Comment by frenck** [comment]
@hsluoyz, I've processed your review by making the following changes:

- Made the descriptions of the mentioned links more informative.
- Fixed `Pythons` -> `Python` spelling error
- Renamed `Content` to `Contents`
- Placed the `Contents` second in its own main chapter right under the descriptions of the list itself.

Thanks again for taking the time to review the list. That is really appreciated.

**Comment by uraimo** [comment]
I'd say this is ready (and already receiving some PRs).

**Comment by frenck** [comment]
Thanks for taking the time to look into it @uraimo! That is really appreciated.

**Comment by frenck** [comment]
Resolved merge conflict, caused by another list that got merged in.

**Comment by frenck** [comment]
Rebased.

**Comment by sindresorhus** [comment]
> > Should be the first section in the list.

> 💬 Conflicting rule: description of the project/theme at the top. So there is an about section first, Contents second.

Just remove the `About` section title. You don't need a section title for that. It's normal that the first text in documents are intro/about.

---

>  ✖  260:3   Link to https://skalavala.github.io/camera/ is dead                 no-dead-urls

>   ✖  305:59  List item description must end with proper punctuation              awesome/list-item

>  ✖  308:64  Text "NodeJS" should be written as "Node.js"                        awesome/spell-check

**Comment by frenck** [comment]
Thank you for taking my comments on the guidelines positively 👍

Also, thanks for the review @sindresorhus, that is really much appreciated.

I've processed your review comments (PR's are linked to this PR).

Judging by your comment, I suspect you are using a tool to check these things. It is available? I would love to extend/improve the CI on the list. Currently, I'm using `awesome_bot` & Danger CI, who both missed some?! 😢

**Comment by sindresorhus** [comment]
@frenck Yes, https://github.com/sindresorhus/awesome-lint, but it's mature enough to be in CI. It has a lot of false-positives.

**Comment by sindresorhus** [comment]
Looks good now. Thanks for doing such a great job with the list and following the PR guidelines. 🙌

**Pull request merged**
