### PR TITLE
 add maintained fork of awesome-pentest that consists of various useful penetration testing resources

### PR DESCRIPTION
**Pull request by techgaun**
The original repo is: https://github.com/enaqx/awesome-pentest

I have updated link to new fork
https://github.com/techgaun/awesome-pentest

Will be happy to keep it updated until @enaqx shows interest. I would be happy to give the lead to original author.

### CODE REVIEW

**Comment by davisonio** [comment]
They still seem active on GitHub, @enaqx would you be able to continue updating the awesome list or perhaps you could add @techgaun as a collaborator if not?

**Comment by enaqx** [comment]
Hey guys. I'll update pentest list and review current PRs if it the matter of community demand :). Also if anyone is interested, I can give commiters rights.

**Comment by techgaun** [comment]
@enaqx awesome, I would be interested to contribute to the list.

**Comment by enaqx** [comment]
@techgaun I've added you to colaborators. You can change this PR to original on reviewing and updating list. Maybe @sindresorhus will add it then.

**Comment by techgaun** [comment]
thanks @enaqx .. will re-open new PR after some updates.

**Pull request closed without merging**
