### PR TITLE
Add Video Channels

### PR DESCRIPTION
**Pull request by L1Cafe**
https://github.com/L1Cafe/Awesome-Video-Channels

This is not just a list of videos, but entire channels dedicated to teaching different things, from politics, to computer science, technology, mathematics, and so on.

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

## Requirements for your pull request

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title.<br>For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
	- Be added at the bottom of the appropriate category.
- The list I'm submitting complies with these requirements:

## Requirements for your Awesome list

- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
- It's the result of hard work and the best I could possibly produce.
- Non-generated Markdown file in a GitHub repo.
- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
- Not a duplicate.
- Only has awesome items. Awesome lists are curations of the best, not everything.
- Includes a project logo/illustration whenever possible.
	- Either fullwidth or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
	- The image should link to the project website or any relevant website.
	- The image should be high-DPI. Set it to maximum half the width of the original image.
- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
	- Should be placed on the right side of the readme heading.
	- Should link back to this list.
- Has a Table of Contents section.
	- Should be named `Contents`, not `Table of Contents`.
	- Should be the first section in the list.
	- Should only have one level of sub-lists, preferably none.
- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
	- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
	- [WTFPL](http://www.wtfpl.net) and [Unlicense](http://unlicense.org) are not acceptable licenses.
	- If you use a license badge, it should be SVG, not PNG.
- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
	- The file should be named `contributing.md`. Casing is up to you.
- Has consistent formatting and proper spelling/grammar.
	- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
	- The description starts with an uppercase character and ends with a period.
	- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.

Go to the top and read it again.

### CODE REVIEW

**Comment by L1Cafe** [comment]
Hi @legodude17 thanks for the suggestion. I'm trying to list only the best channels I can find, which is actually one of the requirements in the pull requests. If you know more high quality content, then, by all means, contribute to the list!

I'm not entirely sure about PragerU not being social science, as they don't seem to produce any content outside of social sciences. But again, if you believe there's a more fitting category, then, you're free to contribute 😄

**Comment by sindresorhus** [comment]
Hey, sorry for the lack of response, please see #1363.

**Comment by L1Cafe** [comment]
Thanks for your hard work @sindresorhus, and thanks for your response. I will try to get it done as soon as possible. Cheers.

**Comment by DovAmir** [comment]
this is a pull request review

1) no need for "" in descriptions
2) section font size is not consistent, use indentation for subsections

please review
https://github.com/sindresorhus/awesome/pull/1331

**Comment by L1Cafe** [comment]
Thanks for your review @DovAmir.

Regarding your first point, the quotes are in place because they are actual quotes. That is: I pasted text from these channels’ descriptions, instead of writing something myself that might have been a bit more subjective. It is perfectly valid English to place quotes surrounding paraphrased text.

The section size is very consistent because there are super and sub-sections, and I did use indentation for subsections (check out the table of contents at the source code level). Adding white space to the left of the actual entries is a waste of screen real-estate in my opinion, as the styling of the title items already make the hierarchy clear. This is used in other accepted and merged “awesome” lists such as this one 
https://github.com/leekelleher/awesome-umbraco (notice how only the TOC is indented, and not the actual content per super/sub-section).

**Comment by sindresorhus** [comment]
I think you should work on adapting the quotes to descriptions.

For example `"Your ultimate channel for all things chemistry."` => `All things chemistry.`.

`"Your #1 source for Photoshop tutorials."` => `Photoshop tutorials.`

**Comment by sindresorhus** [comment]
> Has a Table of Contents section.
**Should be named Contents, not Table of Contents.**

**Comment by sindresorhus** [comment]
> Has contribution guidelines.

You have just copy-pasted the one from Awesome. The contribution guidelines should be customized for your list.

**Comment by sindresorhus** [comment]
I think this list is a good idea, but you need to put more work into it.

**Comment by sindresorhus** [comment]
Closing for lack of response and quality of the list.

**Pull request closed without merging**
