### PR TITLE
Added Open Source Society under CS section

### PR DESCRIPTION
**Pull request by Kikobeats**

### CODE REVIEW

**Comment by arthurvr** [comment]
Please check the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md), [`create-list.md`](https://github.com/sindresorhus/awesome/blob/master/create-list.md) and [the awesome manifesto](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

**Comment by aleksandar-todorovic** [comment]
I thought about this yesterday. It doesn't comply with standards we set for other lists, but it kind of _is_ an awesome list. I have no idea what to do with this one.

**Comment by Kikobeats** [comment]
@aleksandar-todorovic all the elements in the list need to be awesome lists?

Close if you think that is not valid

**Comment by sindresorhus** [comment]
It's a stretch, but such a cool idea, so I'm adding it.

**Comment by sindresorhus** [comment]
@ericdouglas Totally optional, but would be awesome if you would add the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) ;)

**Comment by ericdouglas** [comment]
@sindresorhus thank you for add our guide in the awesome list!

I [added](https://github.com/open-source-society/computer-science) the awesome badge too! :sunglasses:

**Comment by sindresorhus** [comment]
:beers:

**Pull request closed without merging**
