### PR TITLE
Add Electric Guitar Specifications

### PR DESCRIPTION
**Pull request by gitfrage**
https://github.com/gitfrage/guitarspecs
This is a "top-down checklist" for the assembly of a solid-body electric guitar. 
It can help you to build a guitar with specific sound and playability characteristics.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please read the [instructions](https://github.com/sindresorhus/awesome/blob/master/create-list.md) for creating a new list, [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

Especially this part:

> Wait at least a couple of weeks after creating a list before submitting to give it a chance to mature.

Ping me here in a few weeks and I'll reopen ;)

**Comment by sindresorhus** [comment]
Very cool! Happy to merge it in a couple of weeks :)

**Comment by sindresorhus** [comment]
@gitfrage Could you fix the merge conflict?

**Comment by gitfrage** [comment]
@sindresorhus: thanks

**Pull request merged**
