### PR TITLE
Add Waves

### PR DESCRIPTION
**Pull request by msmolyakov**
https://github.com/msmolyakov/awesome-waves

Waves is an open source blockchain platform and development toolset for Web 3.0 applications and decentralized solutions.

By submitting this pull request I confirm I've read and complied with the below requirements 🖖

PRs reviewed: #1725, #1738, #1747.

### CODE REVIEW

**Comment by msmolyakov** [comment]
unicorn

**Comment by msmolyakov** [comment]
By the way, [awesome-lint](sindresorhus/awesome-lint) reports an error

> List item description must start with valid casing

because it does not take into account that there are no capital letters in Hindi.

I created a bug report for this: sindresorhus/awesome-lint#100

**Comment by msmolyakov** [comment]
I guess, that with PR everything is fine. @sindresorhus could you check please?

**Comment by sindresorhus** [comment]
Tweet: https://twitter.com/awesome__re/status/1252638945428426752

**Pull request merged**
