### PR TITLE
Add Book Authoring

### PR DESCRIPTION
**Pull request by TalAter**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please read the [instructions](https://github.com/sindresorhus/awesome/blob/master/create-list.md) for creating a new list, [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

Especially this part:

> Wait at least a couple of weeks after creating a list before submitting to give it a chance to mature.

Ping me here in a few weeks and I'll reopen ;)

**Comment by TalAter** [comment]
Hey @sindresorhus.

I think it's ready :)

**Comment by sindresorhus** [comment]
You're very inconsistent about the title of the list.

I would go with `Book Authoring` as just `Authoring` is too vague. You can author anything. If you agree, please update the repo title, readme title and this PR.

**Comment by sindresorhus** [comment]
Not a lot of content. Like, is there really only on `Must Read` book?

Don't indent `  ### Advance` in the readme. It makes the formatting look weird.

What about talk? Are there any good ones on YouTube on this topic?

Blog posts about the experience of writing a technical book would also be interesting.

**Comment by TalAter** [comment]
Thanks, I took your advice and implemented.

As for the scarcity of resources on the list... I do prefer awesome lists that are highly curated to only feature the truly awesome resources. I am constantly adding and editing, and hope to get more input from others when they discover the list.

**Comment by sindresorhus** [comment]
Added.

**Pull request closed without merging**
