### PR TITLE
Add Web Design

### PR DESCRIPTION
**Pull request by nicolesaidy**
**https://github.com/nicolesaidy/awesome-web-design**

**A curated list of awesome resources for digital designers.**

# By submitting this pull request I confirm I've read and complied with the below requirements.

Failure to properly do so will just result in the pull request being closed and everyone's time wasted. Please read it twice. Most people miss many things.

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title. For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should include a short description about the list project/theme (not the list itself), and should be added at the bottom of the appropriate category.
- The list I added
	- **has been around for at least 30 days,**
	- is the result of hard work and is the best I could possibly produce,
	- is a non-generated Markdown file in a GitHub repo,
	- is not a duplicate,
	- includes a succinct description of the project/theme at the top ([example](https://github.com/willempienaar/awesome-quantified-self)),
	- includes a project logo/illustration (whenever possible) at the top right of the readme ([example](https://github.com/sindresorhus/awesome-electron)). (The logo should link to the project website or any relevant website. The logo should be high-DPI, so set it to maximum half the width of the original image.),
	- only has awesome items **with descriptions** *(Awesome lists are curations of the best, not of everything)*,
	- contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- has a Table of Contents section **named `Contents`** as the first section,
	- has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license) *(Meaning something like CC0, NOT a code licence like MIT, BSD, Apache, etc)* *(If you use a license badge, it should be SVG, not PNG)*,
	- has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- doesn't include a Travis badge,
	- has been checked for inconsistent formatting, spelling, and grammar:
		- Each link description starts with an uppercase character and ends with a period.
		- Drop all the `A` / `An` prefixes in the descriptions.
		- Consistent naming. For example, `Node.js`, not `NodeJS` or `node.js`.

### CODE REVIEW

**Comment by davisonio** [comment]
> has an appropriate license (Meaning something like CC0, NOT a code licence like MIT, BSD, Apache, etc) (If you use a license badge, it should be SVG, not PNG),

Would you consider changing to CC0? MIT is a license designed for software.

> has contribution guidelines,

This hasn't been added, you can use the one from this repo as a template.

Also:
- medium link at top is broken
- GoodUI link is broken

**Comment by nicolesaidy** [comment]
@davisonio all fixed, thanks!

**Comment by sindresorhus** [comment]
> The Next Web: International technology news, business & culture.

I don't see how this is web design related.

> Medium: A community of readers and writers offering unique perspectives on ideas large and small.

Medium has anything. I would be more specific: https://medium.com/tag/web-design

---

I would also add https://www.designernews.co/

There are also some relevant Reddit communities:

- https://www.reddit.com/r/web_design/
- https://www.reddit.com/r/css/

---

> has an appropriate license (Meaning something like CC0, NOT a code licence like MIT, BSD, Apache, etc) **(If you use a license badge, it should be SVG, not PNG),**

See the readme here for which the badge to use.

---

https://github.com/nicolesaidy/awesome-web-design/blob/master/CONTRIBUTION.md should be named `CONTRIBUTING.md`, so GitHub picks it up. It should be customized to your list. This one is just copy-pasted. See https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md for a good start (You probably want to remove many of the requirements).

**Comment by nicolesaidy** [comment]
@sindresorhus all fixed.

**Comment by sindresorhus** [comment]
> See the readme here for which the badge to use.

This is the badge image URL you want to use: http://mirrors.creativecommons.org/presskit/buttons/88x31/svg/cc-zero.svg

---

The `Contributor Code of Conduct` link in https://github.com/nicolesaidy/awesome-web-design/blob/master/CONTRIBUTING.md doesn't work.

**Comment by sindresorhus** [comment]
Added :)

**Pull request merged**
