### PR TITLE
Move GitHub related lists under GitHub

### PR DESCRIPTION
**Pull request by davisonio**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks for helping out. I added you to the repo :)

**Comment by davisonio** [comment]
> Thanks for helping out. I added you to the repo :)

Thank you very much! :smiley:

**Comment by sindresorhus** [comment]
Sure, just commit directly. Also feel free to respond to pull requests and making sure they follow the contribution guidelines and awesome manifest. All I ask I that I get the final say in merging list additions.

**Comment by sindresorhus** [comment]
Suggestions/commits for any other improvements to the list welcome! :)

**Comment by davisonio** [comment]
Great, I'll keep that in mind :)

**Pull request merged**
