### PR TITLE
Add Elixir Books

### PR DESCRIPTION
**Pull request by sger**
**https://github.com/sger/ElixirBooks**

**A list about Elixir books**

# ALL THE BELOW CHECKBOXES SHOULD BE DONE AND CHECKED AND THE ABOVE PLACEHOLDERS SHOULD BE FILLED IN BEFORE SUBMITTING A PULL REQUEST!

- [x] I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- [x] This pull request has a descriptive title. *(For example: `Add Node.js`)*
- The list I added
	- [x] **has been around for at least 20 days,**
	- [x] is a non-generated Markdown file in a GitHub repo,
	- [x] is not a duplicate,
	- [x] only has awesome items with descriptions *(Awesome lists are curations of the best, not of everything)*,
	- [x] contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- [x] has a Table of Contents section named `Contents` as the first section,
	- [x] has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license) *(Meaning something like CC0, NOT a code licence like MIT, BSD, Apache, etc)*,
	- [x] has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- [x] has been checked for inconsistent formatting, spelling, and grammar *(This includes starting each link description with an uppercase character and ending it with a period `.`, and consistent naming)*,
	- [x] has been added at the bottom of the appropriate category.

### CODE REVIEW

**Comment by nagygergo** [comment]
The following are unmet for sure: 
- [ ]  has a Table of Contents section named `Contents` as the first section (Can be useful if someone wants to parse it imho),
- [ ] has an appropriate license (Meaning something like CC0, NOT a code licence like MIT, BSD, Apache, etc),
- [ ] has been added at the bottom of the appropriate category.(It's on the top of the books category)

**Comment by nagygergo** [comment]
Looking at more and more repos seems the Table of Contents rule isn't always enforced. So it's up to @sindresorhus to decide.

**Comment by sger** [comment]
thanks @sindresorhus my format is the same as https://github.com/dariubs/GoBooks

**Comment by sindresorhus** [comment]
> Looking at more and more repos seems the Table of Contents rule isn't always enforced.

It is, just not for older lists.

-

Some feedback:

- `Table of Contents` => `Contents`
- Drop the Travis badge.
- Readme is missing a title.
- The `Resources` section should be a list, not headings.
- the `Resources` section should have a link to the main Elixir awesome list: https://github.com/h4cc/awesome-elixir

-

The Elixir Awesome list already has a Books section: https://github.com/h4cc/awesome-elixir#books 
Maybe you could collaborate with @h4cc somhow?

**Comment by sger** [comment]
thanks @sindresorhus

**Comment by sindresorhus** [comment]
Why did you close?

**Comment by sger** [comment]
@sindresorhus new pull request.

**Comment by sindresorhus** [comment]
Why?... Useless new PRs just litters the issue tracker for no good reason.

**Comment by sindresorhus** [comment]
You also didn't link to the previous PR to keep the history, not preserve the correct PR title.

**Comment by sger** [comment]
sorry my mistake

**Pull request closed without merging**
