### PR TITLE
Add Bioinformatics

### PR DESCRIPTION
**Pull request by erictleung**
Adds a curated list of [Awesome Bioinformatics](https://github.com/danielecook/Awesome-Bioinformatics) software, resources, and libraries used in analyzing various genomics data.

/cc: @danielecook

### CODE REVIEW

**Comment by sindresorhus** [comment]
I would like to see more non-library resources. Include some more blog posts, tutorials, videos of talks, book, learning material, etc.

Can you fix the merge conflict? (Don't open a new PR, just update this one)

Title: `Awesome-Bioinformatics` => `Awesome Bioinformatics`

At the top it would be nice to have a couple of sentences about bioinformatics is and a link to read more.

**Comment by erictleung** [comment]
@sindresorhus thanks for the feedback and consideration! I'll try to update the repo with your suggestions and then update this PR accordingly.

**Comment by sindresorhus** [comment]
ping :)

**Comment by erictleung** [comment]
@sindresorhus thanks for keeping up with the PR! 😄  I've made the small changes of the hyphen and just added a small definition. Still working on the non-library resources at the end.

**Comment by mejine** [comment]
and libraries used in analyzing various genomics data.?

**Comment by sindresorhus** [comment]
Any updates?

**Comment by erictleung** [comment]
@sindresorhus we've added a handful of non-library resources since your suggestion. I can think of a few more additions to it. Let me know if you still think there needs to be more.

**Comment by sindresorhus** [comment]
Looks good :)

**Pull request merged**
