### PR TITLE
Add Cloudflare

### PR DESCRIPTION
**Pull request by irazasyed**
https://github.com/irazasyed/awesome-cloudflare

> Curated list of [Cloudflare](https://www.cloudflare.com) worker recipes, open-source projects, guides, blogs, and other resources.

Unicorn 🦄

PRs Reviewed:
- https://github.com/sindresorhus/awesome/pull/1579#issuecomment-515718762
- https://github.com/sindresorhus/awesome/pull/1582#issuecomment-515718228
- https://github.com/sindresorhus/awesome/pull/1589#issuecomment-515718627
- https://github.com/sindresorhus/awesome/pull/1592#issuecomment-516107011

### CODE REVIEW

**Comment by CompSciLauren** [comment]
Looks awesome! The way you positioned the logo looks cool to me. Running awesome-lint gave me the following error:
```
readme.md:23:3
×  23:3  Link to https://twitter.com/cloudflare is dead  remark-lint:no-dead-urls
1 error
```
It looks like the link works though, so you might [report it](https://github.com/sindresorhus/awesome-lint/issues/new) if it's a false positive.

**Comment by irazasyed** [comment]
Thanks, and yes, it's some issue with the linter and I get the same error. Tried with other repos too and its the same thing.

At first, I thought it could be my network issue but looks like it is not.

I've reported the issue now: https://github.com/sindresorhus/awesome-lint/issues/88 Thanks for the suggestion.

**Comment by davisonio** [comment]
Had a review of this and looks good to me!

**Comment by sindresorhus** [comment]
> Examples Collection - Collection of Recipes.

Don't use title casing for the descriptions. Same applies to many other descriptions too.

**Comment by sindresorhus** [comment]
> Includes a succinct description of the project/theme at the top of the readme. (Example) - https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md

Not done

**Comment by irazasyed** [comment]
@sindresorhus Updated. Do I need to also lowercase company names and short-forms (Ex: PHP/Facebook or Google)?

**Comment by irazasyed** [comment]
@sindresorhus Is there anything else I can do to get this merged? Please let me know. Thanks!

**Comment by sindresorhus** [comment]
> Do I need to also lowercase company names and short-forms (Ex: PHP/Facebook or Google)?

No

**Comment by sindresorhus** [comment]
Tweet: https://twitter.com/awesome__re/status/1157656030924464128

**Comment by irazasyed** [comment]
Thank you 👍 :)

**Pull request merged**
