### PR TITLE
Add Firebase

### PR DESCRIPTION
**Pull request by jthegedus**
[awesome-firebase](https://github.com/jthegedus/awesome-firebase)

This is the awesome-list I wanted to exist for the Firebase platform.

My two PR reviews:
* https://github.com/sindresorhus/awesome/pull/1491
* https://github.com/sindresorhus/awesome/pull/1434

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

I've read this so many times I doubt myself now so just going to PR this haha.

### CODE REVIEW

**Comment by angrykoala** [comment]
Hi @jthegedus just a recommendation to improve the PR:

* The link should be https://github.com/jthegedus/awesome-firebase#readme (note the #readme at the end)

**Comment by sindresorhus** [comment]
> Includes a succinct description of the project/theme at the top of the readme. - https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md#requirements-for-your-awesome-list

---

I would linkify `Firebase` in `The most up to date list of Firebase docs, talks, tools, examples` to the Firebase website.

**Comment by jthegedus** [comment]
@sindresorhus I've added the link. Does that description suffice in general?

**Comment by sindresorhus** [comment]
> Does that description suffice in general?

No, there's should be a description at the top of your readme that explains what **Firebase** is.

**Comment by jthegedus** [comment]
Right, I was just following the style of the AWS awesome list as this was the most similar list. I will update it.

**Comment by sindresorhus** [comment]
I would shorten the description to `Firebase is an application developmnet platform built on the Google Cloud Platform providing services and cross-platform SDKs`. The last part is just marketing junk.

`developmnet` => `development`

`application` => `app` (to make it shorter to fit on one line)

**Comment by sindresorhus** [comment]
Tweet: https://twitter.com/awesome__re/status/1098838443113668613

**Comment by jthegedus** [comment]
@sindresorhus Thanks for the advice and the merge! Love your work :heart:

**Pull request merged**
