### PR TITLE
Add Economics

### PR DESCRIPTION
**Pull request by antontarasenko**
https://github.com/antontarasenko/awesome-economics

### CODE REVIEW

**Comment by davisonio** [comment]
Thanks for the suggestion. :smiley:
Please have a read through of the [instructions](https://github.com/sindresorhus/awesome/blob/master/create-list.md) for creating/adding a new list.

> Wait at least a couple of weeks after creating a list before submitting to this list to give it a chance to mature.

Once the list has matured I can reopen this, just let me know here. :raised_hands:

**Comment by antontarasenko** [comment]
@davisonio Thanks! The list was created on Apr 1, 2016: https://github.com/antontarasenko/awesome-economics/commits/default

Should we wait for two more days? )

**Comment by antontarasenko** [comment]
@davisonio Just reminding that it's been two weeks since creating :) Is the repo eligible now?

**Comment by sindresorhus** [comment]
Please read and adhere to the [contributing guidelines](../blob/master/contributing.md).

**Comment by antontarasenko** [comment]
@sindresorhus I did. What's wrong?

**Comment by KapuzenSohn** [comment]
This point: `The pull request and commit should have a useful title.`

**Comment by antontarasenko** [comment]
An updated request: https://github.com/sindresorhus/awesome/pull/624

**Comment by antontarasenko** [comment]
done

**Comment by antontarasenko** [comment]
@sindresorhus Let me know if you saw the previous message here.

**Comment by sindresorhus** [comment]
Ca you fix the merge conflict? (Don't open a new PR, just update this one)

**Comment by sindresorhus** [comment]
- The items in the `Economists` section needs a bio and why you should follow them.
- The items in the `Literature by Field` section needs to be linkified to somewhere you can read more about the book, maybe Goodreads.
- Be consistent about ending all descriptions in a `.`
- Totally optional, but would be cool to have an illustration at the top. Here's a good example: https://github.com/websemantics/awesome-synthetic-biology

**Comment by antontarasenko** [comment]
@sindresorhus Thanks for the comments.

1. Which of your suggestions are mandatory?
2. How to fix the conflict w/o opening a new request?

**Comment by sindresorhus** [comment]
1. The last one.
2. http://blog.michelemattioni.me/2013/01/29/what-do-i-do-when-my-pull-request-does-not-merge-automatically-in-master/

**Comment by antontarasenko** [comment]
@sindresorhus 

1. Fixed: https://github.com/antontarasenko/awesome-economics
2. That seems to be way beyond what I can. I'm just an economist. Can I just submit a new request, if no one dies from it?

**Comment by sindresorhus** [comment]
Why remove all of this? https://github.com/antontarasenko/awesome-economics/commit/72142fe16d9338eababcd80e07736c24107412c2#diff-0730bb7c2e8f9ea2438b52e419dd86c9L176 Mistake?

**Comment by sindresorhus** [comment]
> That seems to be way beyond what I can. I'm just an economist. Can I just submit a new request, if no one dies from it?

No worries. I fixed it for you and merged it. Thanks :)

**Comment by antontarasenko** [comment]
Thanks a lot!

**Pull request closed without merging**
