### PR TITLE
Add "Coding Style Conventions and Standards" to "Miscellaneous"

### PR DESCRIPTION
**Pull request by SalGnt**

### CODE REVIEW

**Comment by sindresorhus** [comment]
How is this different from https://github.com/RichardLitt/awesome-styleguides which is already in the list?

**Comment by SalGnt** [comment]
They are pretty similar. Is that a problem?

**Comment by sindresorhus** [comment]
Yes, I try very hard not to have duplicate lists.

**Comment by SalGnt** [comment]
It is the first time that I see this list, tell me if I have to remove the awesome badge and I'll do it.

**Comment by sindresorhus** [comment]
Maybe you and @RichardLitt could try to collaborate ;)

**Comment by RichardLitt** [comment]
To be fair, @SalGnt's list has had more eyes on it than mine. We could combine; it looks like we both have the same ObjC sections, added en masse. 

There are more than a few other styleguide lists. I have an other list section; I've added SalGnt's https://github.com/RichardLitt/awesome-styleguides#other-styleguide-lists. I created mine because there wasn't an `awesome-` one.

**Pull request closed without merging**
