### PR TITLE
Add description to CakePHP and Laravel entries

### PR DESCRIPTION
**Pull request by inventinto**
Related to issue #928

### CODE REVIEW

**Comment by sindresorhus** [comment]
Needs to follow the existing format.

**Comment by inventinto** [comment]
Do you mean that the desciptions needed a hyphen at the beginning? If not, could you explain me what is the existing format?

**Comment by inventinto** [comment]
Just a quick question on how GitHub works. This is the first time I update a PR and I tried to do it following option 1 of this write up: https://github.com/RichardLitt/knowledge/blob/master/amending-a-commit-guide.md. When I pushed upstream I got this messages: 

remote: Permission to sindresorhus/awesome.git denied to inventinto.
fatal: unable to access 'https://github.com/sindresorhus/awesome.git/': The requested URL returned error: 403

The commit I made end up in the PR anyway. I'm not really sure why. Why did I get this messages? Is this the correct way to update a PR? I'm also not sure if this is the right place to ask this question  :grimacing:

**Comment by sindresorhus** [comment]
> Do you mean that the desciptions needed a hyphen at the beginning?

Yes

> This is the first time I update a PR and I tried to do it following option 1 of this write up: [RichardLitt/knowledge:amending-a-commit-guide.md@`master`](https://github.com/RichardLitt/knowledge/blob/master/amending-a-commit-guide.md). When I pushed upstream I got this messages:

You need to push to the remote branch in your fork, not this repo. You get message since you don't have access to this repo.

**Comment by sindresorhus** [comment]
You had a merge conflict that I fixed for you.

There are some good guides here: https://guides.github.com/activities/forking/

**Comment by inventinto** [comment]
Thank you!

**Pull request merged**
