### PR TITLE
Add awesome-npm-scripts

### PR DESCRIPTION
**Pull request by RyanZim**
**https://github.com/RyanZim/awesome-npm-scripts**

**I couldn't find an awesome list relating to npm scripts and using npm as a build tool, so I wrote one.**

- [x] I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- [x] This pull request has a descriptive title. *(For example: `Add Node.js`)*
- The list I added
	- [x] **has been around for at least 20 days,**
	- [x] is a non-generated Markdown file in a GitHub repo,
	- [x] is not a duplicate,
	- [x] only has awesome items with descriptions *(Awesome lists are curations of the best, not of everything)*,
	- [x] contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- [x] has a Table of Contents section named `Contents` as the first section,
	- [x] has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license) *(Meaning something like CC0, NOT a code licence like MIT, BSD, Apache, etc)*,
	- [x] has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- [x] has been checked for inconsistent formatting, spelling, and grammar *(This includes starting each link description with an uppercase character and ending it with a period `.`, and consistent naming)*,
	- [x] has been added at the bottom of the appropriate category.

Let me know if you would prefer this to be added under a different category, I'll be glad to change it.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Good start, but currently too minimal content-wise to be included. Work on it some more and try again in a few months ;) I've starred it to help get some traction.

There are lots of great tools to use with npm run-scripts to could be included:

- https://github.com/kentcdodds/p-s
- https://github.com/sindresorhus/cpy-cli
- https://github.com/dthree/cash
- https://github.com/sindresorhus/del-cli
- https://github.com/sindresorhus/clear-cli
- https://github.com/sindresorhus/opn-cli
- https://github.com/sindresorhus/gzip-size-cli

// @kentcdodds Any other useful npm run-script things?

**Comment by RyanZim** [comment]
@sindresorhus Thanks for the suggestions and **thanks** for the star. :star2:  I've got plenty of traction now!

Will look into your suggestions ASAP.

**Comment by kentcdodds** [comment]
I'm also really lke: npm-run-all, npm-quick-run, cross-env

**Comment by RyanZim** [comment]
@kentcdodds Thanks for the suggestions, I have npm-run-all, just added cross-env a few days ago. Do you want to submit a PR for npm-quick-run, or shall I add it?

**Comment by kentcdodds** [comment]
Thanks, you go ahead :-)

**Comment by RyanZim** [comment]
@kentcdodds Added, thanks!

**Pull request closed without merging**
