### PR TITLE
Add Mermaid

### PR DESCRIPTION
**Pull request by SCBbestof**
Added Mermaid - Generation of diagram and flowchart from text in a similar manner as markdown

**https://github.com/knsv/mermaid**

**A pretty cool diagram editor that can be used with **

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

## Requirements for your pull request

- **Don't waste my time.** Do a good job, adhere to all the guidelines, and be responsive.
- **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).**
	Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration.
- You have read and understood the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a title in the format `Add Name of List`.
	- ✅ `Add Swift`
	- ✅ `Add Software Architecture`
	- ❌ `Update readme.md`
	- ❌ `Add Awesome Swift`
	- ❌ `Add swift`
	- ❌ `Adding Swift`
	- ❌ `Added Swift`
- Your entry here should include a short description about the project/theme of the list. **It should not describe the list itself.** The first character should be uppercase and the description should end in a dot. It should be an objective description and not a tagline or marketing blurb.
	- ✅ `- [iOS](…) - Mobile operating system for Apple phones and tablets.`
	- ✅ `- [Framer](…) - Prototyping interactive UI designs.`
	- ❌ `- [iOS](…) - Resources and tools for iOS development.`
	- ❌ `- [Framer](…)`
	- ❌ `- [Framer](…) - prototyping interactive UI designs`
- Your entry should be added at the bottom of the appropriate category.
- The suggested Awesome list complies with the below requirements.

### CODE REVIEW

**Comment by caufieldjh** [comment]
This does not appear to be an Awesome list or a list at all, but rather a tool in its own right

**Comment by uabua** [comment]
This is not an Awesome list, - it is a software.

I suggest you add the tool in its relevant type of Awesome list in another repository and then maybe include that Awesome list in this project.

**Comment by matheusgmaia** [comment]
Not an awsome list. Maybe you should add this on a tools or open projects awesome list.

**Comment by SCBbestof** [comment]
Oh. My bad. I don't know why, but I thought this repo is a collection of Awesome lists AND software. :D Sorry for wasting your time. I'll add it to the appropriate list.

Thanks!

**Comment by NewAlexandria** [comment]
I'd suggest adding it to here: https://github.com/fasouto/awesome-dataviz#readme

**Comment by SCBbestof** [comment]
Thanks @NewAlexandria ! I added it there 😁

**Pull request closed without merging**
