### PR TITLE
Add Authentication & Authorization

### PR DESCRIPTION
**Pull request by hsluoyz**
https://github.com/casbin/awesome-auth

awesome auth is a curated list of authentication & authorization software and libraries . And this list exists because it benefits many groups of people — system administrators, security researchers and the developers who care about the security of their systems.

# By submitting this pull request I confirm I've read and complied with the below requirements.

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title.<br>For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
	- Be added at the bottom of the appropriate category.
- The list I'm submitting complies with these requirements:
	- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
	- It's the result of hard work and the best I could possibly produce.
	- Non-generated Markdown file in a GitHub repo.
	- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
	- Not a duplicate.
	- Only has awesome items. Awesome lists are curations of the best, not everything.
	- Includes a project logo/illustration whenever possible.
		- Placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
		- The image should link to the project website or any relevant website.
		- The image should be high-DPI. Set it to maximum half the width of the original image.
	- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
	- Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
		- Should be placed on the right side of the readme heading.
		- Should link back to this list.
	- Has a Table of Contents section.
		- Should be named `Contents`, not `Table of Contents`.
		- Should be the first section in the list.
		- Should only have one level of sub-lists, preferably none.
	- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
		- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
		- If you use a license badge, it should be SVG, not PNG.
	- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
		- The file should be named `contributing.md`. Casing is up to you.
	- Has consistent formatting and proper spelling/grammar.
		- Each link description starts with an uppercase character and ends with a period.<br>Example: `- [AVA](…) - JavaScript test runner.`
		- Drop all the `A` / `An` prefixes in the descriptions.
		- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
	- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.
- Go to the top and read it again.

### CODE REVIEW

**Comment by sindresorhus** [comment]
> By submitting this pull request I confirm I've read and complied with the below requirements.

Please read the guidelines more thoroughly.

---

Also light on content.

**Comment by sindresorhus** [comment]
@hsluoyz ping :)

**Comment by hsluoyz** [comment]
I read the guidelines once again, but doesn't know where's wrong :(

**Comment by sindresorhus** [comment]
From a quick look, I noticed these are not done:

> The entry in the Awesome list should:
Include a short description about the project/theme of the list. **It should not describe the list itself.**

:arrow_up:

> Includes a succinct description of the project/theme at the top of the readme. (Example)

:arrow_up:

> Has an appropriate license.
That means something like CC0, not a code licence like MIT, BSD, Apache, etc.

:arrow_up: You're using Apache.

> Drop all the A / An prefixes in the descriptions.

:arrow_up:

**Comment by hsluoyz** [comment]
Fixed:)

**Comment by hsluoyz** [comment]
@sindresorhus

**Comment by aleksandar-todorovic** [comment]
> Has contribution guidelines. 

Not followed.

You still have a reference to the Apache license at the bottom of the repo.

**Comment by hsluoyz** [comment]
@aleksandar-todorovic oh, I forgot it. Fixed:)

**Comment by hsluoyz** [comment]
@erictleung I have fixed the wrong places. But my original repo is missing (I don't know if there's a recovery method). So I have to create a new PR here: https://github.com/sindresorhus/awesome/pull/1364

**Comment by erictleung** [comment]
@hsluoyz looks good to me now! :+1: I'd go ahead and close this PR if you've gone ahead and created a new one.

**Comment by hsluoyz** [comment]
@erictleung OK. Thanks!

**Pull request closed without merging**
