### PR TITLE
Add Kotlin

### PR DESCRIPTION
**Pull request by IRus**
Kotlin is great language for JVM.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please read the [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

Especially this part:

> Wait at least a couple of weeks after creating a list before submitting to give it a chance to mature.

Ping me here in a few weeks and I'll reopen ;)

**Comment by sindresorhus** [comment]
The list is also a bit light on content.

**Comment by IRus** [comment]
Okay, no problem :)

**Comment by GuillaumeLeclerc** [comment]
Thank you for your PR, I just discovered this language :) I hope it will be merged soon

**Comment by IRus** [comment]
@sindresorhus Current status of Awesome Kotlin:
:white_check_mark: Add an awesome badge to the top of your list, right to the title.
:white_check_mark: Comment on why something is awesome
:white_check_mark: Make it clear what the list is about
:white_check_mark: Pay attention to grammar
:white_check_mark: Choose an appropriate license
:white_large_square: Include contribution guidelines
:white_check_mark: Stylize your list properly
:white_check_mark: Accept other people's opinion
:white_check_mark: Discovery

*I doesn't include contributing guidelines because list is not mature as this list, and doesn't have so much contributions to it.*

**Comment by aleksandar-todorovic** [comment]
Trust me, making good contributing guidelines is one of the crucial steps to attract more contributors to your list.

**Comment by arthurvr** [comment]
> I doesn't include contributing guidelines because list is not mature as this list, and doesn't have so much contributions to it.

Maybe you don't get much contributions just because people don't know when and how to contribute ;)

**Comment by IRus** [comment]
So contribution should contain *how to* instead of *rules*?

**Comment by arthurvr** [comment]
@IRus It's called "contribution guidelines", not "contribution rules". I guess it's a little of both. I see it more as *how you'd like people to contribute*. This is a good example: https://github.com/sindresorhus/awesome/blob/master/contributing.md.

**Comment by IRus** [comment]
Hi! I just added "contribution guidelines" in repository, and also we have nice website: https://javaby.github.io/awesome-kotlin/

**Comment by IRus** [comment]
cc @sindresorhus

**Comment by sindresorhus** [comment]
You're making it too hard to contribute. Contributing should just be to edit the readme.md file.

> For now any link to repository that contains > 20 stars will be 100% approved.

Please no. I call this the "star fallacy". Stars are rarely a metric of quality. You should review every entry equally.

**Comment by IRus** [comment]
@sindresorhus i completely agree with you, i change our guidelines. But this awesome list can't get rid of js file as main source for adoc document and website. So i pay more attention on it in guidelines, and allow people to just create issues. Also i added ToC (asciidoctor is awesome for this)

**Comment by sindresorhus** [comment]
> But this awesome list can't get rid of js file as main source for adoc document and website.

I disagree. You could easily parse the markdown.

-

I'm gonna reluctantly accept, but how you're doing things will definitely impact how much contributions you'll get.

**Pull request closed without merging**
