### PR TITLE
Add Competitive Programming

### PR DESCRIPTION
**Pull request by lnishan**
This is a curated list of awesome competitive programming resources which covered a wide variety of aspects. It's aimed to be a useful list for all.

[Competitive Programming - Wikipedia](https://en.wikipedia.org/wiki/Competitive_programming)

I do realize there's a list under a similar name (Competitive Coding).  
However, I believe competitive programming isn't just about coding (think [Linear programming - Wikipedia](https://en.wikipedia.org/wiki/Linear_programming) for example). On top of that, I believe that there's more than just knowledge. It's also about the community that revolves around it.  
In addition, I do not think it's quite possible to cover everything awesome with a one-article-link layout. There are way more sites with awesome resources.

I've been in the competitive programming scene for more than 10 years, and have also been digging good information for roughly the same time. I sincerely feel that my list would indeed be able to connect people to information.

This list I created also receives positive feedbacks.  
[An awesome list for competitive programming! - Codeforces](http://codeforces.com/blog/entry/23054)

Current entry (Competitive Coding): [awesome-competitive-coding - Codeforces](http://codeforces.com/blog/entry/21182), [Topic wise Coding Resources - Codeforces](http://codeforces.com/blog/entry/23204)

### CODE REVIEW

**Comment by aleksandar-todorovic** [comment]
First of all, I'm not really thrilled with the content in `awesome-competitive-coding`.

Second of all, words `programming` and `coding` are considered to be synonyms by a huge chunk of the population and I don't see the reason why we should make any difference between these two words.

Third of all, I absolutely do not see any point in having both of these lists here. We should definitely decide on one of them. 

---

Now, in my own opinion, I do think that your list is better suited to be included here, _however_, I don't think you played fair by telling your concerns here instead of first reporting them in the `awesome-competitive-coding` and at least trying to expand that list before you've decided to create your own version of a similar thing. I believe that you should have at least tried to make an agreement with @hkirat.

**Comment by lnishan** [comment]
He actually reached out to me when I was making my list (through Codeforces PMs).

I responded nicely and expressed my concern for the fact our contents are organized very differently. An initial agreement was reached 2 weeks ago. We agreed to add referral links to our repos (ie. He adds one to mine, and I add one to his) - which he didn't comply.

Here is the link to the [screenshot of our conversation](http://imgur.com/xyAjd6H).

**Comment by imcaffrey** [comment]
Hi.
I am the other guy if you would say like that. I also have a list on this with my own ideas.
Honestly, these two lists(by @lnishan and @hkirat ) actually cover different sides of competitive programming, and in my opinion they are both awesome enough to be added into this list.

Competitive programming is a big subject and the lists actually did provided different details.

**Comment by hkirat** [comment]
Well if you go through the conversation properly I mentioned that both the repos would do better together
But @lnishan turned the conversation to the direction of separation and adding referral links.
I am still up for a merge of both these repos.
There is no point of awesome-competitive-coding and awesome-competitive-programming
And @lnishan you did not approach me before making the repo it was only after you made it that I got in touch with you for merging the two

**Comment by imcaffrey** [comment]
@sindresorhus I agree with you.
But the situation here is that the two lists are quite different in details.
If you take a further look, you'll see that @hkirat provides info on each single subject while @lnishan only takes broader view into concern.

**Comment by lnishan** [comment]
I'd rather not going into the details.

I said adding links **for a start** because I think it takes time for a real collaboration as the contents are vastly different. You didn't even follow our initial agreement. How would I expect you to do more?

The more serious part. You said you're still up for a merge, but I do not see any activity on your repo. If you bother looking through literally anything on my knowledge section, you'll notice you have **so many**  more resources to add. I can name lots of topics you didn't managed to cover: bipartite graphs, planar graphs, matchings, linear programming, strongly/biconnected components. You also have many links pointing to the same website with simply a different keyword search.

But the real point I'm making here is, it's just not possible to cover it all. Let's also take [awesome-algorithms](https://github.com/tayllan/awesome-algorithms), [awesome-datascience](https://github.com/okulbilisim/awesome-datascience) for example (as these 2 are closely related to competitive programming). None of them categorize their contents by methods, because there are simply  too many.  Now it's true that competitive programming covers only a portion of them, but the same applies.

**Comment by hkirat** [comment]
I am no one to force this merger on you and you are no one to question the activity of my repo @lnishan .
If you wan't to continue with different repositories it is fine by me.But don't put forward futile points to make it look that we actually do need two repositories.
The whole point of open source is collaboration. The final call is yours.
And on weather or not this should be added to the awesome listing, I leave the decision with @sindresorhus

**Comment by lnishan** [comment]
@hkirat , Don't get me wrong. From the very beginning, I have always been willing to collaborate.

This is also one of my first attempts at contributing to the open source community, so I do try to be as careful and as cooperative as possible.

One of the reasons that prompted me to work on this new list is that: there is already a good amount of information available on the Internet. Before @hkirat 's list, there are other awesome curated lists already (See my [Knowledge](https://github.com/lnishan/awesome-competitive-programming#knowledge) and [Open Courses](https://github.com/lnishan/awesome-competitive-programming#knowledge) section). All of these are trying to cover the knowledge required in this scene.

Oftentimes I would feel that there's more to know (Some sites didn't teach something while some others do) or perhaps Site A explains something better than Site B (not to mention this is personal preference). Therefore, there really is a need for a list to collect all the awesome resources.

I'm not sure what your aim is, but to really see what I mean, you can consider reading problems from regions around the world (ACM-ICPC). Europe in general lays emphasis more on mathematical foundations and thinking, whereas China focuses more on advanced data structures and algorithms. In the end, not even a website like [GeeksforGeeks](http://www.geeksforgeeks.org/fundamentals-of-algorithms/) can cover all the knowledge necessary in the competitive programming scene.

I have been in the competitive programming scene for more than 10 years and have accumulated quite a few years of teaching experience (also me always being the team captain). Imagine you're a beginner who wants to step foot in competitive programming, which is in fact me 10 years ago. One without guidance would wander around not knowing where to start. In this case, it would probably be better to include easier contents. However, with the case of a reasonably seasoned person, he/she might find the list common sense. There's a seemingly impossible imbalance (if you will) if the aim is to have a list for the general public.

One major flaw I just spotted, you list flow as the third item, and even put graph (DFS, BFS) beneath. Usually maximum flow and [Max-flow min-cut theorem](https://en.wikipedia.org/wiki/Max-flow_min-cut_theorem) is lectured in the very end of an algorithm course because it is not easy.

**Comment by hkirat** [comment]
It is alphabetically sorted @lnishan :)

**Comment by lnishan** [comment]
Okay, then this would be an issue depending on what you're aiming for as far as I'm concerned.

It doesn't make much sense unless we're aiming for a database/archive. Also, there are data structures with multiple names (eg. [Fenwick tree](https://en.wikipedia.org/wiki/Fenwick_tree) is also known as Binary indexed tree). There are also extensions such as [Persistent segment tree](http://blog.anudeep2011.com/persistent-segment-trees-explained-with-spoj-problems/). It would make much more sense to at least keep similar topics together.

**Comment by hkirat** [comment]
They are sorted so that people can easily find the topics they wish to study upon
It is a common practice followed by a lot of people working on awesome listings :)

**Comment by lnishan** [comment]
I would argue that's not the case.

It wouldn't make any difference with a quick Ctrl + F (Command + F in OSX) in the browser. Besides, you have a Table of Contents just for that.

**Comment by hkirat** [comment]
Create an issue...Let's discuss it over there :)

**Comment by lnishan** [comment]
Following this direction, @hkirat 's list would probably turn into an organized version of [this](https://discuss.codechef.com/questions/48877/data-structures-and-algorithms). It would probably not be a list to get people started.

My honest opinion (no offense): There are still many other issues (eg. casings, wordings, inaccurate/inadequate descriptions, insufficient resources to support ... etc.) left to point out. I would suggest @hkirat to do a bit more research into the scene outside his nation first. As of now, there are at least twice as many contents needed to mentioned. A conservative estimate would be months. I frankly do not have the time to do all of this. It would be kind of like creating another list ...

**Comment by sindresorhus** [comment]
Landed this in favor of @lnishan's list (sorry!). As a totally objective person on this topic, this list is just more approachable, comprehensive and better structured.

**Pull request closed without merging**
