### PR TITLE
Add Streaming

### PR DESCRIPTION
**Pull request by manuzhang**
Add a curated list of awesome streaming (stream processing) frameworks, applications, readings and other resources

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks for the suggestion. Would you mind reading the [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md) :)

**Comment by manuzhang** [comment]
Thanks, I've added a contributing guide to the repo.

**Comment by sindresorhus** [comment]
In the top description, I would linkify "stream processing" to an article like maybe https://en.wikipedia.org/wiki/Stream_processing.

**Comment by sindresorhus** [comment]
Added.

**Comment by manuzhang** [comment]
Great! Thanks!

**Pull request closed without merging**
