### PR TITLE
Add Awesome Command Line Apps

### PR DESCRIPTION
**Pull request by herrbischoff**
Adding a not-quite-ready-for-primetime-yet sister list to [Awesome OS X Command Line](https://github.com/herrbischoff/awesome-osx-command-line). Just so you know I'm working on it. ;)

### CODE REVIEW

**Comment by sindresorhus** [comment]
There are some good ones here if you need inspiration: https://github.com/sindresorhus/awesome-nodejs#command-line-apps

**Comment by herrbischoff** [comment]
Sweet! Thanks a lot. I'm looking into them.

**Comment by herrbischoff** [comment]
Also, on a side note, I just realized that you're the author of `pageres`. I've been using it for quite some time and found it *very* useful.

**Comment by mischah** [comment]
@herrbischoff 
Sorry that I have to say this: This is still kinda lame and it gets worse.

You started this list yesterday and you know since yesterday that @aharris88 is working (with me) to enhance [awesome-cli-app](https://github.com/aharris88/awesome-cli-app) to reopen the PR to add his list to sindresorhus/awesome --> https://github.com/sindresorhus/awesome/pull/379

For reference:
* https://github.com/herrbischoff/awesome-osx-command-line/issues/81#issuecomment-154499399
* https://github.com/aharris88/awesome-cli-apps/issues/7

**Comment by herrbischoff** [comment]
You should seriously lighten up a little, @mischah.

**Comment by mischah** [comment]
You know exactly that it takes a minute or two :kissing_heart:

**Comment by sindresorhus** [comment]
Closing in favor of #379.

I would suggest you instead contribute to the existing list @herrbischoff ;)

**Comment by herrbischoff** [comment]
Nah, with the main contributor now being this rather annoying person, I'm sticking to my guns. I also don't believe that just because someone was "first" it means it's the best suited approach. For my taste, the list would need to be rebuilt from scratch anyway and I don't feel like doing someone else's work for them. Thanks anyway.

**Comment by sindresorhus** [comment]
We don't go for the first, but right now both of your lists are pretty young, so there's no clear winner. Let's reconsider sometime in the future. Gonna go with the first one for now.

**Comment by herrbischoff** [comment]
Fair enough. The other list was apparently submitted some time ago so I can see your reasoning. Going to keep working on mine.

**Pull request closed without merging**
