### PR TITLE
Add Python in Learning

### PR DESCRIPTION
**Pull request by Danix421**
**[Python in Learning](https://github.com/quobit/awesome-python-in-education)**

**Python in learning is a list of Python learning resources, like tutorials, webpages and others, game engines, like Ursina Engine, Panda3D and others, and more!**

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

## Requirements for your pull request

- **Don't waste my time.** Do a good job, adhere to all the guidelines, and be responsive.
- **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).**
	Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration. **Just commenting “looks good” or simply marking the pull request as approved does not count!** You have to actually point out mistakes or improvement suggestions.
- You have read and understood the [instructions for creating a list](create-list.md).
- This pull request has a title in the format `Add Name of List`.
	- ✅ `Add Swift`
	- ✅ `Add Software Architecture`
	- ❌ `Update readme.md`
	- ❌ `Add Awesome Swift`
	- ❌ `Add swift`
	- ❌ `add Swift`
	- ❌ `Adding Swift`
	- ❌ `Added Swift`
- Your entry here should include a short description about the project/theme of the list. **It should not describe the list itself.** The first character should be uppercase and the description should end in a dot. It should be an objective description and not a tagline or marketing blurb.
	- ✅ `- [iOS](…) - Mobile operating system for Apple phones and tablets.`
	- ✅ `- [Framer](…) - Prototyping interactive UI designs.`
	- ❌ `- [iOS](…) - Resources and tools for iOS development.`
	- ❌ `- [Framer](…)`
	- ❌ `- [Framer](…) - prototyping interactive UI designs`
- Your entry should be added at the bottom of the appropriate category.
- The suggested Awesome list complies with the below requirements.

## Requirements for your Awesome list

- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
- Don't open a Draft / WIP pull request while you work on the guidelines. A pull request should be 100% ready and should adhere to all the guidelines when you open it.
- Run [`awesome-lint`](https://github.com/sindresorhus/awesome-lint) on your list and fix the reported issues. If there are false-positives or things that cannot/shouldn't be fixed, please [report it](https://github.com/sindresorhus/awesome-lint/issues/new).
- The default branch should be named [`main`, not `master`](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/).
- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- ✅ `Mobile operating system for Apple phones and tablets.`
	- ✅ `Prototyping interactive UI designs.`
	- ❌ `Resources and tools for iOS development.`
	- ❌ `Awesome Framer packages and tools.`
- It's the result of hard work and the best I could possibly produce.
	**If you have not put in considerable effort into your list, your pull request will be immediately closed.**
- The repo name of your list should be in lowercase slug format: `awesome-name-of-list`.
	- ✅ `awesome-swift`
	- ✅ `awesome-web-typography`
	- ❌ `awesome-Swift`
	- ❌ `AwesomeWebTypography`
- The heading title of your list should be in [title case](https://capitalizemytitle.com/) format: `# Awesome Name of List`.
	- ✅ `# Awesome Swift`
	- ✅ `# Awesome Web Typography`
	- ❌ `# awesome-swift`
	- ❌ `# AwesomeSwift`
- Non-generated Markdown file in a GitHub repo.
- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
- Not a duplicate. Please search for existing submissions.
- Only has awesome items. Awesome lists are curations of the best, not everything.
- Does not contain items that are unmaintained, has archived repo, deprecated, or missing docs. If you really need to include such items, they should be in a separate Markdown file.
- Includes a project logo/illustration whenever possible.
	- Either centered, fullwidth, or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
	- The image should link to the project website or any relevant website.
	- **The image should be high-DPI.** Set it to maximum half the width of the original image.
- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- Includes the [Awesome badge](awesome.md#awesome-badge).
	- Should be placed on the right side of the readme heading.
		- Can be placed centered if the list has a centered graphics header.
	- Should link back to this list.
- Has a Table of Contents section.
	- Should be named `Contents`, not `Table of Contents`.
	- Should be the first section in the list.
	- Should only have one level of [nested lists](https://commonmark.org/help/tutorial/10-nestedLists.html), preferably none.
	- Must not feature `Contributing` or `Footnotes` sections.
- Has an appropriate license.
	- **We strongly recommend the [CC0 license](https://creativecommons.org/publicdomain/zero/1.0/), but any [Creative Commons license](https://creativecommons.org/choose/) will work.**
		- Tip: You can quickly add it to your repo by going to this URL: `https://github.com/<user>/<repo>/community/license/new?branch=main&template=cc0-1.0` (replace `<user>` and `<repo>` accordingly).
	- A code license like MIT, BSD, Apache, GPL, etc, is not acceptable. Neither are WTFPL and [Unlicense](https://unlicense.org).
	- Place a file named `license` or `LICENSE` in the repo root with the license text.
	- **Do not** add the license name, text, or a `Licence` section to the readme. GitHub already shows the license name and link to the full text at the top of the repo.
	- To verify that you've read all the guidelines, please comment on your pull request with just the word `unicorn`.
- Has [contribution guidelines](awesome.md#include-contribution-guidelines).
	- The file should be named `contributing.md`. Casing is up to you.
	- It can optionally be linked from the readme in a dedicated section titled `Contributing`, positioned at the top or bottom of the main content.
	- The section should not appear in the Table of Contents.
- All non-important but necessary content (like extra copyright notices, hyperlinks to sources, pointers to expansive content, etc) should be grouped in a `Footnotes` section at the bottom of the readme. The section should not be present in the Table of Contents.
- Has consistent formatting and proper spelling/grammar.
	- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
	- The description starts with an uppercase character and ends with a period.
	- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
- Doesn't use [hard-wrapping](https://stackoverflow.com/questions/319925/difference-between-hard-wrap-and-soft-wrap).
- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.
- Doesn't include an `Inspired by awesome-foo` or `Inspired by the Awesome project` kinda link at the top of the readme. The Awesome badge is enough.

**Go to the top and read it again.**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

**Comment by Danix421** [comment]
> Thanks for making an Awesome list! 
> 
> It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

Thanks, Sindre Sorhus! I will view it, but i have to say something: the list is not mine. In my first menssage i say it, "in colaboration with quobit". quobit is the creator of this list, i'm only, with his permission, making this pull request. If the list breaks your guidelines that is the problem of his creator. If this pull request is the thing that breaks you guidelines, please, let's me know it.

**Comment by Danix421** [comment]
I recommend contact the list creator in [this issue](https://github.com/quobit/awesome-python-in-education/issues/36), why here is where i'm advise the changes with this pull request.

**Comment by lodthe** [comment]
> > Thanks for making an Awesome list!
> > It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.
> 
> Thanks, Sindre Sorhus! I will view it, but i have to say something: the list is not mine. In my first menssage i say it, "in colaboration with quobit". quobit is the creator of this list, i'm only, with his permission, making this pull request. If the list breaks your guidelines that is the problem of his creator. If this pull request is the thing that breaks you guidelines, please, let's me know it.

Hi Danix. If you want this pull request to be merged, the repository you suggest must meet the [requirements](https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md). Awesome-lint can help to find some things to fix:
```
[$] awesome-lint https://github.com/quobit/awesome-python-in-education
✖ Linting

  README.md:454:185
  ✖    1:1    Main heading must be in title case                                               remark-lint:awesome-heading
  ✖    1:1    Forbidden license section found                                                  remark-lint:awesome-license
  ✖    1:32   Invalid badge source                                                             remark-lint:awesome-badge
  ✖   11:1    ToC missing item for "License"                                                   remark-lint:awesome-toc
  ✖   20:3    ToC item "Academic Papers" does not match corresponding heading "Reference"      remark-lint:awesome-toc
  ✖   28:3    ToC item "IDEs" does not match corresponding heading "Hosted Jupyter notebooks"  remark-lint:awesome-toc
  ✖   43:3    ToC item "Pyboard" does not match corresponding heading "PyBoard"                remark-lint:awesome-toc
  ✖   49:80   "’" is used without matching "‘"                                                 remark-lint:match-punctuation
  ✖   50:143  List item description must start with valid casing                               remark-lint:awesome-list-item
```

**Comment by Danix421** [comment]
> > > Thanks for making an Awesome list!
> > > It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.
> > 
> > 
> > Thanks, Sindre Sorhus! I will view it, but i have to say something: the list is not mine. In my first menssage i say it, "in colaboration with quobit". quobit is the creator of this list, i'm only, with his permission, making this pull request. If the list breaks your guidelines that is the problem of his creator. If this pull request is the thing that breaks you guidelines, please, let's me know it.
> 
> Hi Danix. If you want this pull request to be merged, the repository you suggest must meet the [requirements](https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md). Awesome-lint can help to find some things to fix:
> 
> ```
> [$] awesome-lint https://github.com/quobit/awesome-python-in-education
> ✖ Linting
> 
>   README.md:454:185
>   ✖    1:1    Main heading must be in title case                                               remark-lint:awesome-heading
>   ✖    1:1    Forbidden license section found                                                  remark-lint:awesome-license
>   ✖    1:32   Invalid badge source                                                             remark-lint:awesome-badge
>   ✖   11:1    ToC missing item for "License"                                                   remark-lint:awesome-toc
>   ✖   20:3    ToC item "Academic Papers" does not match corresponding heading "Reference"      remark-lint:awesome-toc
>   ✖   28:3    ToC item "IDEs" does not match corresponding heading "Hosted Jupyter notebooks"  remark-lint:awesome-toc
>   ✖   43:3    ToC item "Pyboard" does not match corresponding heading "PyBoard"                remark-lint:awesome-toc
>   ✖   49:80   "’" is used without matching "‘"                                                 remark-lint:match-punctuation
>   ✖   50:143  List item description must start with valid casing                               remark-lint:awesome-list-item
> ```

Thanks, but, i have to say again, i'm __not__ the creator of Awesome Python in Learning, i'm colaborating with his creator to put it in awesome. But thanks.

**Comment by Danix421** [comment]
I will wait for a review of sindresorhus for know if he contacted the list creator.

**Comment by Kikobeats** [comment]
@Danix421 you should rename the `master` branch to `main`

Screen Shot 2021-03-09 at 22 32 08

**Comment by Danix421** [comment]
It looks like he is not available for contact, so it's possible that this request will be closed why the list don't meets the guidelines

**Comment by Kikobeats** [comment]
@Danix421 what if you fork the list?

**Comment by Danix421** [comment]
> @Danix421 what if you fork the list?

I can do it, but the list owner is now busy, it can't respond the menssages

**Comment by Vmongst243** [comment]
@Danix421 ghhzj

**Comment by Danix421** [comment]
> @Danix421 ghhzj

What?

**Comment by Jogai** [comment]
You need to read the contribution guidelines very carefully, and execute them to the letter. The problem is not only that the list isn't completely following the standards, but also this PR.

You can fork the list and fix the problems and make a PR to the list. Its not an issue that you are not the author. Github is about collaboration (and its even better that you are not the author, because its at least not self promotion).
After you and the author get the list into shape, then you can adjust this PR to meet the PR standards.

**Comment by Danix421** [comment]
> You need to read the contribution guidelines very carefully, and execute them to the letter. The problem is not only that the list isn't completely following the standards, but also this PR.
> 
> You can fork the list and fix the problems and make a PR to the list. Its not an issue that you are not the author. Github is about collaboration (and its even better that you are not the author, because its at least not self promotion).
> After you and the author get the list into shape, then you can adjust this PR to meet the PR standards.

Ok, i already made a pull request to "try" to fix an error but the list creator is not available. So, i will only fix the errors in this pull request.

**Comment by Danix421** [comment]
Ok, @sindresorhus, i think it is know fixed. The list creator has fixed the master branch error, and others things. If i looked good, there is an error in my pull request: the name of it. I already fixed it and well, i will review the others pull requests. So, i think i don't have to change the pull request first comment, why already has passed to much time, but if its neccesary i will do it. So, i hope that all the things are good.

**Comment by Jogai** [comment]
I think you have to use the template: https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md
Read every line of it, we can tell you didn't do that yet because you didn't use the secret word yet.. :smile:

**Comment by Danix421** [comment]
O

> I think you have to use the template: https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md
> Read every line of it, we can tell you didn't do that yet because you didn't use the secret word yet..

Ok, i will do it

**Comment by Danix421** [comment]
Ok, @Jogai, i already do it

**Comment by Jogai** [comment]
I'm not trying to annoy you, but you still didn't follow every point on the list. Just using the template isn't enough, you have to actually follow it.

**Comment by Danix421** [comment]
I know it and i'm trying to do it, even if the list is not mine. And, i think that my pull request don't have any errors, if it have, i waiting for @sindresorhus.

**Comment by Jogai** [comment]
I know, that's why I'm trying to help you. I don't even have a PR open for which I have to do this.

**Comment by Danix421** [comment]
> I know, that's why I'm trying to help you. I don't even have a PR open for which I have to do this.

Well, thanks!

**Comment by Danix421** [comment]
Well, i think this pull request has to be closed, why it have too much time active and i don't know if i'm breaking an Awesome rule

**Pull request closed without merging**
