### PR TITLE
Add UI Styleguides

### PR DESCRIPTION
**Pull request by kevinwuhoo**
Followup to #209. Added a readme to the project and linked it instead of the webpage.

That's weird that it was janky, I've only tested it in chrome. I reduced the size of images anyway, so it would kill less browsers.

Thanks!

### CODE REVIEW

**Comment by arthurvr** [comment]
IMHO the list doesn't really have much content at this point.

> That's weird that it was janky, I've only tested it in chrome. I reduced the size of images anyway, so it would kill less browsers.

It was janky in chrome too.

It was way more than just reducing the size of your images. Check out the work me and Sam have been doing over at https://github.com/kevinwuhoo/ui-styleguides/issues/2.

**Comment by sindresorhus** [comment]
What @arthurvr said. It could use a succinct description for each item and commentary of why it's there. A screenshot for each item like in the webpage would also be nice.

Additionally you currently require users to edit the data file. This makes it a lot harder to contribute as users will now how to edit both that one and the readme. I think the readme should be the source of truth and if you insist on having a website it should be something you generate from the readme or manually update yourself.

See: https://github.com/sindresorhus/awesome/issues/207

**Comment by kevinwuhoo** [comment]
I see, sounds good. I'll refactor this so that the readme is the data source and add extra descriptions and commentary.

**Comment by n1trux** [comment]
>See: #207

Also see: #212 ;)

You could separate the web code from the repository containing the readme completely and instead refactor the code so you can use it for every awesome list out there.

That'd be awesome, imho :)

**Comment by arthurvr** [comment]
What's the conclusion here? Close it till the list matured a little (and till the site/readme stuff is figured out)?

**Comment by n1trux** [comment]
I think so, yes.

**Pull request closed without merging**
