### PR TITLE
Awesome Robotics

### PR DESCRIPTION
**Pull request by Kiloreux**
Added the awesome Robotics to the list

### CODE REVIEW

**Comment by aleksandar-todorovic** [comment]
No license, no contributing guidelines, brand new list...

Please read `[awesome.md](https://github.com/sindresorhus/awesome/blob/master/awesome.md)`. Once your list complies to it:

> Wait at least a couple of weeks after creating a list before submitting to this list to give it a chance to mature.

After a few weeks, ping us here and we'll reopen this PR if the issues are fixed.

**Comment by Kiloreux** [comment]
@aleksandar-todorovic , https://github.com/numetriclabz/awesome-db, this doesn't seem to complie to what you just said, might wanna check ?

**Comment by aleksandar-todorovic** [comment]
@Kiloreux Thanks for letting me know! I have submitted this as an issue in that repository, so we'll see how it goes.

**Comment by Kiloreux** [comment]
@aleksandar-todorovic mind checking it for me now ?

**Pull request closed without merging**
