### PR TITLE
Add iOS and Mac OS Security

### PR DESCRIPTION
**Pull request by ashishb**
**[Insert URL to the list here]**

https://github.com/ashishb/osx-and-ios-security-awesome

**[Explain what this list is about and why it should be included here]**

It is about iOS and Mac OS security tools

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

## Requirements for your pull request

- **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).** Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration.
- I have read and understood the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title in the format `Add Name of List` (Example: `Add Swift`), not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
	- Be added at the bottom of the appropriate category.
- The list I'm submitting complies with the below requirements.

## Requirements for your Awesome list

- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
- It's the result of hard work and the best I could possibly produce.
- Non-generated Markdown file in a GitHub repo.
- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
- Not a duplicate.
- Only has awesome items. Awesome lists are curations of the best, not everything.
- Includes a project logo/illustration whenever possible.
	- Either centered, fullwidth, or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
	- The image should link to the project website or any relevant website.
	- The image should be high-DPI. Set it to maximum half the width of the original image.
- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
	- Should be placed on the right side of the readme heading.
		- Can be placed centered if the list has a centered graphics header.
	- Should link back to this list.
- Has a Table of Contents section.
	- Should be named `Contents`, not `Table of Contents`.
	- Should be the first section in the list.
	- Should only have one level of [nested lists](https://commonmark.org/help/tutorial/10-nestedLists.html), preferably none.
- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
	- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
	- [WTFPL](http://www.wtfpl.net) and [Unlicense](http://unlicense.org) are not acceptable licenses.
	- If you use a license badge, it should be SVG, not PNG.
- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
	- The file should be named `contributing.md`. Casing is up to you.
- Has consistent formatting and proper spelling/grammar.
	- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
	- The description starts with an uppercase character and ends with a period.
	- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.

Go to the top and read it again.

### CODE REVIEW

**Comment by teoga** [comment]
```
➜  ~ awesome-lint https://github.com/ashishb/osx-and-ios-security-awesome
✖ Linting

  README.md:1:1
  ✖   1:1  Missing or invalid Table of Contents          remark-lint:awesome/toc
  ✖   1:1  Headings should use atx                       remark-lint:heading-style
  ✖   1:1  Text "OSX" should be written as "macOS"       remark-lint:awesome/spell-check
  ✖   1:1  Missing Awesome badge after the main heading  remark-lint:awesome/badge
  ✖   1:1  Missing License section                       remark-lint:awesome/license
  ✖   1:1  Missing file contributing.md                  remark-lint:awesome/contributing
  ✖   4:4  Text "OSX" should be written as "macOS"       remark-lint:awesome/spell-check
  ✖   4:4  Text "github" should be written as "GitHub"   remark-lint:awesome/spell-check
  ✖   5:1  Marker should be 2, was 3                     remark-lint:ordered-list-marker-value
  ✖   5:4  Text "github" should be written as "GitHub"   remark-lint:awesome/spell-check
  ✖   5:4  Text "OSX" should be written as "macOS"       remark-lint:awesome/spell-check
  ✖   6:1  Marker should be 3, was 28                    remark-lint:ordered-list-marker-value
  ✖   6:5  Text "github" should be written as "GitHub"   remark-lint:awesome/spell-check
  ✖   7:1  Marker should be 4, was 2                     remark-lint:ordered-list-marker-value
  ✖   7:4  Text "github" should be written as "GitHub"   remark-lint:awesome/spell-check
  ✖   8:1  Marker should be 5, was 4                     remark-lint:ordered-list-marker-value
  ✖   8:4  Text "github" should be written as "GitHub"   remark-lint:awesome/spell-check
  ✖   9:1  Marker should be 6, was 5                     remark-lint:ordered-list-marker-value
  ✖   9:4  Text "github" should be written as "GitHub"   remark-lint:awesome/spell-check
  ✖  10:1  Marker should be 7, was 6                     remark-lint:ordered-list-marker-value
  ✖  11:1  Marker should be 8, was 7                     remark-lint:ordered-list-marker-value
  ✖  11:4  Text "MacOS" should be written as "macOS"     remark-lint:awesome/spell-check
  ✖  11:4  Text "github" should be written as "GitHub"   remark-lint:awesome/spell-check
  ✖  12:1  Marker should be 9, was 8                     remark-lint:ordered-list-marker-value
  ✖  12:4  Text "github" should be written as "GitHub"   remark-lint:awesome/spell-check
  ✖  13:1  Marker should be 10, was 8                    remark-lint:ordered-list-marker-value
  ✖  14:1  Marker should be 11, was 9                    remark-lint:ordered-list-marker-value
  ✖  14:4  Text "github" should be written as "GitHub"   remark-lint:awesome/spell-check
  ✖  15:1  Marker should be 12, was 10                   remark-lint:ordered-list-marker-value
  ✖  15:5  Text "OS X" should be written as "macOS"      remark-lint:awesome/spell-check
  ✖  15:5  Text "github" should be written as "GitHub"   remark-lint:awesome/spell-check
  ✖  16:1  Marker should be 13, was 11                   remark-lint:ordered-list-marker-value
  ✖  16:5  Text "OSX" should be written as "macOS"       remark-lint:awesome/spell-check
  ✖  16:5  Text "github" should be written as "GitHub"   remark-lint:awesome/spell-check
  ✖  17:1  Marker should be 14, was 12                   remark-lint:ordered-list-marker-value
  ✖  17:5  Text "github" should be written as "GitHub"   remark-lint:awesome/spell-check
  ✖  18:1  Marker should be 15, was 13                   remark-lint:ordered-list-marker-value
  ✖  18:5  Text "OSX" should be written as "macOS"       remark-lint:awesome/spell-check
  ✖  18:5  Text "github" should be written as "GitHub"   remark-lint:awesome/spell-check
  ✖  19:1  Marker should be 16, was 14                   remark-lint:ordered-list-marker-value
  ✖  19:5  Text "github" should be written as "GitHub"   remark-lint:awesome/spell-check
  ✖  20:1  Marker should be 17, was 15                   remark-lint:ordered-list-marker-value
  ✖  20:5  Text "MacOS" should be written as "macOS"     remark-lint:awesome/spell-check
  ✖  20:5  Text "github" should be written as "GitHub"   remark-lint:awesome/spell-check
  ✖  21:1  Marker should be 18, was 16                   remark-lint:ordered-list-marker-value
  ✖  22:1  Marker should be 19, was 17                   remark-lint:ordered-list-marker-value
  ✖  23:1  Marker should be 20, was 18                   remark-lint:ordered-list-marker-value
  ✖  24:1  Marker should be 21, was 19                   remark-lint:ordered-list-marker-value
  ✖  25:1  Marker should be 22, was 20                   remark-lint:ordered-list-marker-value
  ✖  25:5  Text "github" should be written as "GitHub"   remark-lint:awesome/spell-check
  ✖  26:1  Marker should be 23, was 21                   remark-lint:ordered-list-marker-value
  ✖  27:1  Marker should be 24, was 22                   remark-lint:ordered-list-marker-value
  ✖  28:1  Marker should be 25, was 23                   remark-lint:ordered-list-marker-value
  ✖  29:1  Marker should be 26, was 24                   remark-lint:ordered-list-marker-value
  ✖  30:1  Marker should be 27, was 25                   remark-lint:ordered-list-marker-value
  ✖  31:1  Marker should be 28, was 26                   remark-lint:ordered-list-marker-value
  ✖  32:1  Marker should be 29, was 27                   remark-lint:ordered-list-marker-value
  ✖  34:1  Headings should use atx                       remark-lint:heading-style
  ✖  34:1  Don’t use multiple top level headings (1:1)   remark-lint:no-multiple-toplevel-headings
  ✖  39:4  Text "github" should be written as "GitHub"   remark-lint:awesome/spell-check
  ✖  40:4  Text "github" should be written as "GitHub"   remark-lint:awesome/spell-check
  ✖  42:4  Text "github" should be written as "GitHub"   remark-lint:awesome/spell-check
  ✖  43:4  Text "github" should be written as "GitHub"   remark-lint:awesome/spell-check
  ✖  45:4  Text "github" should be written as "GitHub"   remark-lint:awesome/spell-check
  ✖  49:1  Headings should use atx                       remark-lint:heading-style
  ✖  49:1  Don’t use multiple top level headings (1:1)   remark-lint:no-multiple-toplevel-headings
  ✖  56:1  Don’t use multiple top level headings (1:1)   remark-lint:no-multiple-toplevel-headings
  ✖  57:1  Text "github" should be written as "GitHub"   remark-lint:awesome/spell-check
  ✖  60:1  Don’t use multiple top level headings (1:1)   remark-lint:no-multiple-toplevel-headings

  69 errors
```

**Comment by teoga** [comment]
The following points are missing or are not as per guidelines.

----

* **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
Includes a project logo/illustration whenever possible.
* Either centered, fullwidth, or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
* The image should link to the project website or any relevant website.
* The image should be high-DPI. Set it to maximum half the width of the original image.
Has a Table of Contents section.
* Should be named `Contents`, not `Table of Contents`.
* Should be the first section in the list.
* Should only have one level of [nested lists](https://commonmark.org/help/tutorial/10-nestedLists.html), preferably none.
* Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
  * That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
  * [WTFPL](http://www.wtfpl.net) and [Unlicense](http://unlicense.org) are not acceptable licenses.
  * If you use a license badge, it should be SVG, not PNG.
* Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
  * The file should be named `contributing.md`. Casing is up to you.
* Has consistent formatting and proper spelling/grammar.
  * The link and description are separated by a dash. Example: `- [AVA](…) - JavaScript test runner.`
  * The description starts with an uppercase character and ends with a period.
  * Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.

**Comment by streichsbaer** [comment]
In addition to what teoga said, this one is also missing:

- Be added at the bottom of the appropriate category.

**Comment by ashishb** [comment]
> Be added at the bottom of the appropriate category.

I am adding immediately after the Android security link and it seems like the best place to me. 

@streichsbaer

**Comment by ashishb** [comment]
I fixed all the issues except the following

```
awesome-lint
✖ Linting

  README.md:1:1
  ✖   1:1  Missing Awesome badge after the main heading  remark-lint:awesome/badge
  ✖  11:5  Text "OSX" should be written as "macOS"       remark-lint:awesome/spell-check
  ✖  12:5  Text "OSX" should be written as "macOS"       remark-lint:awesome/spell-check

  3 errors
```

I am not sure why "Missing Awesome badge after the main heading  remark-lint:awesome/badge" is happening when I have the badge. For the other two errors, I cannot change "OS X" to "macOS" since those two product names use "OS X" in their respective names.

**Comment by dend** [comment]
Not sure how jailbreak links relate to iOS/Mac security tools in the list - something to consider.

**Comment by ashishb** [comment]
> Not sure how jailbreak links relate to iOS/Mac security tools in the list - something to consider.

Why do you think so, wouldn't security researchers be interested in jailbreaking tools as well?

**Comment by dend** [comment]
@ashishb IMO it's not directly related to security tools, but again - personal opinion.

**Comment by Dvergar** [comment]
As of today the log of awesome-lint is
```
  README.md:1:1
  ×   1:1  License was not detected by GitHub                           remark-lint:awesome/github
  ×   1:1  The repository should have "awesome-list" as a GitHub topic  remark-lint:awesome/github
  ×   1:1  The repository should have "awesome" as a GitHub topic       remark-lint:awesome/github
  ×   1:1  Missing Awesome badge after the main heading                 remark-lint:awesome/badge
  ×  11:5  Text "OSX" should be written as "macOS"                      remark-lint:awesome/spell-check
  ×  12:5  Text "OSX" should be written as "macOS"                      remark-lint:awesome/spell-check
```
To answer your badge question, it's probably because you're using an old or different badge link.
Using `[Awesome](https://awesome.re)` doesn't trigger the error.

**Comment by ashishb** [comment]
@Dvergar Thanks for the review.

>  ×   1:1  License was not detected by GitHub                           remark-lint:awesome/github
Added `LICENSE` file
>   ×   1:1  The repository should have "awesome-list" as a GitHub topic  remark-lint:awesome/github
I addressed this

>   ×   1:1  The repository should have "awesome" as a GitHub topic       remark-lint:awesome/github
I addressed this

>   ×   1:1  Missing Awesome badge after the main heading                 remark-lint:awesome/badge
I addressed this. Thanks for the right badge URL.
  
> ×  11:5  Text "OSX" should be written as "macOS"                      remark-lint:awesome/spell-check
I cannot choose whatever package name I want, this package is called OSXCollector - https://github.com/Yelp/OSXCollector

 >  ×  12:5  Text "OSX" should be written as "macOS"                      remark-lint:awesome/spell-check
This package is called OSXAuditor - https://github.com/jipegit/OSXAuditor

**Comment by sindresorhus** [comment]
There are still many things in the guidelines that are not followed.

**Comment by ashishb** [comment]
> There are still many things in the guidelines that are not followed.

@sindresorhus This isn't very helpful. If you spotted something you might as point it out here in the comments.

**Comment by missmatsuko** [comment]
Missing requirements I noticed:
- [ ] You have to review at least 2 other open pull requests. If you already did, please link them here.
- [ ] This pull request has a title in the format Add Name of List (e.g. "Add Swift"). The name in the PR and the name in the repo are not consistent.
- [ ] Includes a succinct description of the project/theme at the top of the readme.
- [ ] The heading title of your list should be in the following format: # Awesome Name of List
- [ ] To verify that you've read all the guidelines, please add comment with just the word unicorn.
- [ ] Your awesome list should be named awesome-list-name

**Comment by sindresorhus** [comment]
> This isn't very helpful. If you spotted something you might as point it out here in the comments.

It's not very helpful that nobody properly reads the guidelines either. I've spent countless of hours on them and I still have to mostly just copy-paste half of it as comments in every single PR.

**Pull request closed without merging**
