### PR TITLE
switch awesome-c's repository

### PR DESCRIPTION
**Pull request by inet56**
This one is actively maintained and mirror of original the one. Although it has more commits than it's source (https://notabug.org/koz.ross/awesome-c).

### CODE REVIEW

**Comment by sindresorhus** [comment]
The new list needs to conform to the guidelines: https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md

**Comment by sindresorhus** [comment]
Please see https://github.com/sindresorhus/awesome/issues/167

**Comment by inet56** [comment]
> The new list needs to conform to the guidelines: https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md

This is not a new list. It is an actively maintained version.

**Comment by inet56** [comment]
https://retro-freedom.nz/pages/stuff-i-made.html

**Comment by inet56** [comment]
>This list was previously maintained by @kozross. He decided to switch the list to a new platform, so I've decided to fork it so we could keep it on GitHub.

https://github.com/inputsh/awesome-c#awesome-c-

**Comment by inet56** [comment]
I don't understand what's the reason.

**Pull request closed without merging**
