### PR TITLE
Add Virtual Reality (VR) list.

### PR DESCRIPTION
**Pull request by cjroth**
**URL to the list here.**

**Explain what this list is all about and why it should be included here.**

- [x] I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- [x] This pull request has a descriptive title.
- The list I added
	- [x] is not a duplicate,
	- [ ] has been around for a few weeks,
	- [x] only has awesome items with descriptions,
	- [x] contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- [ ] has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license),
	- [ ] has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- [x] has been checked for inconsistent formatting, spelling and grammar, and
	- [x] has been added at the bottom of the appropriate category.

### CODE REVIEW

**Comment by cjroth** [comment]
@sindresorhus could you give a reason for closing?

**Comment by egeerardyn** [comment]
You should reread the contribution guidelines and then what you have written in your PR above.

**Comment by cjroth** [comment]
Sorry that's why I hadn't checked all of the boxes.

I guess you're not a fan of in-progress pull requests?

On Thursday, June 16, 2016, Egon Geerardyn <notifications@github.com> wrote:

> You should reread the contribution guidelines and then what you have
> written in your PR above.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sindresorhus/awesome/pull/688#issuecomment-226385281>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAjh8sjuu5KwjEJlZFm9FXRQ_YSpXSBGks5qMNC7gaJpZM4I21B0>
> .
>


-- 
Chris Roth
    cjroth.com <http://www.cjroth.com>

**Comment by aleksandar-todorovic** [comment]
Nope. The noise to signal ratio is way too low. We only accept pull requests once everything from the contributing guidelines has been completed.

**Comment by cjroth** [comment]
Ok fair enough, will re-submit once complete.

On Saturday, June 18, 2016, Aleksandar Todorović (r3bl) <
notifications@github.com> wrote:

> Nope. The noise to signal ratio is way too low. We only accept pull
> requests once everything from the contributing guidelines has been
> completed.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sindresorhus/awesome/pull/688#issuecomment-226970070>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAjh8tBAoIdsEzh1cBAOOsSMcIZaOI6hks5qNHuzgaJpZM4I21B0>
> .
>


-- 
Chris Roth
    cjroth.com <http://www.cjroth.com>

**Pull request closed without merging**
