### PR TITLE
fix a typo for the product ColdFusion

### PR DESCRIPTION
**Pull request by cfjedimaster**
**[URL to the list here.]**

**[Explain what this list is all about and why it should be included here.]**

# ALL THE BELOW CHECKBOXES SHOULD BE DONE AND CHECKED AND THE ABOVE PLACEHOLDERS SHOULD BE FILLED IN BEFORE SUBMITTING A PULL REQUEST!

- [ ] I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- [ ] This pull request has a descriptive title. *(For example: `Add Node.js`)*
- The list I added
	- [ ] **has been around for at least 20 days,**
	- [ ] is not a duplicate,
	- [ ] only has awesome items with descriptions *(Awesome lists are curations of the best, not of everything)*,
	- [ ] contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- [ ] has a `Table of Contents` as the first section,
	- [ ] has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license) *(Meaning something like CC0, NOT a code licence like MIT, BSD, Apache, etc)*,
	- [ ] has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- [ ] has been checked for inconsistent formatting, spelling, and grammar *(This includes starting each link description with an uppercase character and ending it with a dot, and consistent naming)*,
	- [ ] has been added at the bottom of the appropriate category.

The F in ColdFusion needs to be capitalized.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you please use a descriptive PR title.

**Comment by cfjedimaster** [comment]
Wow.... really? I mean I get the reason but... wow.

**Comment by cfjedimaster** [comment]
Done.

**Comment by sindresorhus** [comment]
> Wow.... really? I mean I get the reason but... wow.

?

**Comment by cfjedimaster** [comment]
Sorry - I was being a bit snippy about you asking me to edit the PR title for such a minor typo fix. ;)

**Comment by sindresorhus** [comment]
It's a minor typo fix, true, but `Update readme.md` is totally useless in a git history and will waste people's time down the line.

**Comment by cfjedimaster** [comment]
Fair enough. As it stands - I just took the defaults Git provided me when I hit the edit button.

**Pull request merged**
