### PR TITLE
Add Japanese Language

### PR DESCRIPTION
**Pull request by yudataguy**
**https://github.com/yudataguy/awesome-japanese**

**A curated list of Japanese language learning resources. It's been up for about one year, with 120:star:. I've read carefully about the guideline, and finally submit this to the master list.**

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

## Requirements for your pull request

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title.<br>For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
	- Be added at the bottom of the appropriate category.
- The list I'm submitting complies with these requirements:

## Requirements for your Awesome list

- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
- It's the result of hard work and the best I could possibly produce.
- Non-generated Markdown file in a GitHub repo.
- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
- Not a duplicate.
- Only has awesome items. Awesome lists are curations of the best, not everything.
- Includes a project logo/illustration whenever possible.
	- Either fullwidth or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
	- The image should link to the project website or any relevant website.
	- The image should be high-DPI. Set it to maximum half the width of the original image.
- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
	- Should be placed on the right side of the readme heading.
	- Should link back to this list.
- Has a Table of Contents section.
	- Should be named `Contents`, not `Table of Contents`.
	- Should be the first section in the list.
	- Should only have one level of sub-lists, preferably none.
- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
	- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
	- [WTFPL](http://www.wtfpl.net) and [Unlicense](http://unlicense.org) are not acceptable licenses.
	- If you use a license badge, it should be SVG, not PNG.
- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
	- The file should be named `contributing.md`. Casing is up to you.
- Has consistent formatting and proper spelling/grammar.
	- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
	- The description starts with an uppercase character and ends with a period.
	- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.

Go to the top and read it again.

### CODE REVIEW

**Comment by Jogai** [comment]
Awesome to have awesome lists for languages!

There is a typo on your list. Vocaulary instead of Vocabulary (too small for a pr/im too lazy for a pr)

**Comment by yudataguy** [comment]
Typo fixed.

**Comment by ZYSzys** [comment]
Maybe you can attempt to create a repo which called awesome-languages and put awesome-Japanese, awesome-English,awesome-Chinese and etc. to it.
Just a suggestion~

**Comment by yudataguy** [comment]
Good idea! Let me think about how to start. Def need others to contribute on making it successful.

**Comment by Jogai** [comment]
https://github.com/yvoronoy/awesome-english already exists

**Comment by sindresorhus** [comment]
Hey, sorry for the lack of response, please see #1363.

**Comment by yudataguy** [comment]
@sindresorhaius
I have reviewed #1139 and #1321 
As well as my own list, and it's ready to be merged.

**Comment by sindresorhus** [comment]
```
❯ awesome-lint https://github.com/yudataguy/awesome-japanese
✖ Linting

  readme.md:1:1
  ✖    1:1   Missing newline character at end of file                                                            remark-lint:final-newline
  ✖    1:21  Invalid badge source                                                                                remark-lint:awesome/badge
  ✖    7:1   ToC item "Awesome Japanese" does not match corresponding heading "Emoji Description"                remark-lint:awesome/toc
  ✖    8:5   Incorrect indentation before bullet: remove 2 spaces                                                remark-lint:list-item-bullet-indent
  ✖    9:5   Incorrect indentation before bullet: remove 2 spaces                                                remark-lint:list-item-bullet-indent
  ✖   10:5   Incorrect indentation before bullet: remove 2 spaces                                                remark-lint:list-item-bullet-indent
  ✖   11:5   Incorrect indentation before bullet: remove 2 spaces                                                remark-lint:list-item-bullet-indent
  ✖   12:5   Incorrect indentation before bullet: remove 2 spaces                                                remark-lint:list-item-bullet-indent
  ✖   13:5   Incorrect indentation before bullet: remove 2 spaces                                                remark-lint:list-item-bullet-indent
  ✖   14:5   Incorrect indentation before bullet: remove 2 spaces                                                remark-lint:list-item-bullet-indent
  ✖   15:5   Incorrect indentation before bullet: remove 2 spaces                                                remark-lint:list-item-bullet-indent
  ✖   16:5   Incorrect indentation before bullet: remove 2 spaces                                                remark-lint:list-item-bullet-indent
  ✖   17:5   Incorrect indentation before bullet: remove 2 spaces                                                remark-lint:list-item-bullet-indent
  ✖   18:5   Incorrect indentation before bullet: remove 2 spaces                                                remark-lint:list-item-bullet-indent
  ✖   19:5   Incorrect indentation before bullet: remove 2 spaces                                                remark-lint:list-item-bullet-indent
  ✖   26:24  Cell should be compact                                                                              remark-lint:table-cell-padding
  ✖   26:25  Misaligned table fence                                                                              remark-lint:table-pipe-alignment
  ✖   26:57  Cell should be compact                                                                              remark-lint:table-cell-padding
  ✖   26:58  Misaligned table fence                                                                              remark-lint:table-pipe-alignment
  ✖   26:90  Cell should be compact                                                                              remark-lint:table-cell-padding
  ✖   26:91  Misaligned table fence                                                                              remark-lint:table-pipe-alignment
  ✖   27:24  Cell should be compact                                                                              remark-lint:table-cell-padding
  ✖   27:25  Misaligned table fence                                                                              remark-lint:table-pipe-alignment
  ✖   27:57  Misaligned table fence                                                                              remark-lint:table-pipe-alignment
  ✖   27:84  Misaligned table fence                                                                              remark-lint:table-pipe-alignment
  ✖   28:23  Misaligned table fence                                                                              remark-lint:table-pipe-alignment
  ✖   28:39  Misaligned table fence                                                                              remark-lint:table-pipe-alignment
  ✖   28:65  Misaligned table fence                                                                              remark-lint:table-pipe-alignment
  ✖   32:3   Strong should use * as a marker                                                                     remark-lint:strong-marker
  ✖   36:2   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖   37:2   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖   38:2   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖   39:2   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖   40:2   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖   41:2   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖   57:1   Don’t add a trailing : to headings                                                                  remark-lint:no-heading-punctuation
  ✖   62:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖   63:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖   64:2   Don’t pad emphasis with inner spaces                                                                remark-lint:no-inline-padding
  ✖   67:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖   68:4   Don’t pad link with inner spaces                                                                    remark-lint:no-inline-padding
  ✖   70:1   Don’t add a trailing : to headings                                                                  remark-lint:no-heading-punctuation
  ✖   75:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖   76:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖   77:2   Don’t pad emphasis with inner spaces                                                                remark-lint:no-inline-padding
  ✖   86:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖   86:67  List item description must end with proper punctuation                                              remark-lint:awesome/list-item
  ✖   87:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖   87:49  List item description must end with proper punctuation                                              remark-lint:awesome/list-item
  ✖   88:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖   88:42  List item description must end with proper punctuation                                              remark-lint:awesome/list-item
  ✖   94:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖   95:2   Don’t pad emphasis with inner spaces                                                                remark-lint:no-inline-padding
  ✖   97:2   Don’t pad emphasis with inner spaces                                                                remark-lint:no-inline-padding
  ✖   99:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  100:2   Don’t pad emphasis with inner spaces                                                                remark-lint:no-inline-padding
  ✖  102:2   Don’t pad emphasis with inner spaces                                                                remark-lint:no-inline-padding
  ✖  104:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  105:2   Don’t pad emphasis with inner spaces                                                                remark-lint:no-inline-padding
  ✖  107:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  112:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  113:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  114:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  115:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  115:40  List item description must end with proper punctuation                                              remark-lint:awesome/list-item
  ✖  116:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  117:2   Don’t pad emphasis with inner spaces                                                                remark-lint:no-inline-padding
  ✖  119:2   Don’t pad emphasis with inner spaces                                                                remark-lint:no-inline-padding
  ✖  124:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  125:4   List item description must end with proper punctuation                                              remark-lint:awesome/list-item
  ✖  126:3   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  127:3   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  128:3   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  129:3   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  130:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  130:38  List item description must end with proper punctuation                                              remark-lint:awesome/list-item
  ✖  134:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  134:73  List item description must end with proper punctuation                                              remark-lint:awesome/list-item
  ✖  135:3   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  136:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  137:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  137:87  List item description must start with valid casing                                                  remark-lint:awesome/list-item
  ✖  138:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  139:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  140:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  141:2   Don’t pad emphasis with inner spaces                                                                remark-lint:no-inline-padding
  ✖  144:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  144:68  List item description must end with proper punctuation                                              remark-lint:awesome/list-item
  ✖  148:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  148:52  List item description must end with proper punctuation                                              remark-lint:awesome/list-item
  ✖  149:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  149:63  List item description must end with proper punctuation                                              remark-lint:awesome/list-item
  ✖  150:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  150:67  List item description must end with proper punctuation                                              remark-lint:awesome/list-item
  ✖  151:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  151:50  List item description must end with proper punctuation                                              remark-lint:awesome/list-item
  ✖  152:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  152:29  List item description must end with proper punctuation                                              remark-lint:awesome/list-item
  ✖  153:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  154:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  154:49  List item description must end with proper punctuation                                              remark-lint:awesome/list-item
  ✖  155:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  159:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  160:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  161:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  162:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  163:2   Don’t pad emphasis with inner spaces                                                                remark-lint:no-inline-padding
  ✖  165:2   Don’t pad emphasis with inner spaces                                                                remark-lint:no-inline-padding
  ✖  171:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  171:62  List item description must end with proper punctuation                                              remark-lint:awesome/list-item
  ✖  172:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  173:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  173:31  List item description must end with proper punctuation                                              remark-lint:awesome/list-item
  ✖  174:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  175:2   Don’t pad emphasis with inner spaces                                                                remark-lint:no-inline-padding
  ✖  178:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  178:42  List item description must end with proper punctuation                                              remark-lint:awesome/list-item
  ✖  182:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  183:2   Don’t pad emphasis with inner spaces                                                                remark-lint:no-inline-padding
  ✖  185:3   Don’t pad emphasis with inner spaces                                                                remark-lint:no-inline-padding
  ✖  188:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  189:2   Don’t pad emphasis with inner spaces                                                                remark-lint:no-inline-padding
  ✖  191:2   Don’t pad emphasis with inner spaces                                                                remark-lint:no-inline-padding
  ✖  193:2   Don’t pad emphasis with inner spaces                                                                remark-lint:no-inline-padding
  ✖  195:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  196:2   Don’t pad emphasis with inner spaces                                                                remark-lint:no-inline-padding
  ✖  198:2   Don’t pad emphasis with inner spaces                                                                remark-lint:no-inline-padding
  ✖  200:2   Don’t pad emphasis with inner spaces                                                                remark-lint:no-inline-padding
  ✖  206:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  207:2   Don’t pad emphasis with inner spaces                                                                remark-lint:no-inline-padding
  ✖  209:2   Don’t pad emphasis with inner spaces                                                                remark-lint:no-inline-padding
  ✖  211:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  212:2   Don’t pad emphasis with inner spaces                                                                remark-lint:no-inline-padding
  ✖  214:2   Don’t pad emphasis with inner spaces                                                                remark-lint:no-inline-padding
  ✖  215:45  Text "MacOS X" should be written as "macOS"                                                         remark-lint:awesome/spell-check
  ✖  218:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  219:2   Don’t pad emphasis with inner spaces                                                                remark-lint:no-inline-padding
  ✖  222:1   Marker style should be -                                                                            remark-lint:unordered-list-marker-style
  ✖  223:2   Don’t pad emphasis with inner spaces                                                                remark-lint:no-inline-padding
  ✖  225:2   Don’t pad emphasis with inner spaces                                                                remark-lint:no-inline-padding
  ✖  227:3   Don’t pad emphasis with inner spaces                                                                remark-lint:no-inline-padding
  ✖  227:5   Link to https://chrome.google.com/webstore/detail/rikaigu/gmgccdlimakdipjjogccblkaoipdklcb is dead  remark-lint:no-dead-urls
  ✖  229:3   Don’t pad emphasis with inner spaces                                                                remark-lint:no-inline-padding

  143 errors
```

https://github.com/sindresorhus/awesome-lint

**Comment by sindresorhus** [comment]
Can you fix the merge conflict?

**Comment by sindresorhus** [comment]
Closing for lack of response.

**Pull request closed without merging**
