### PR TITLE
Add Pixel Art

### PR DESCRIPTION
**Pull request by Siilwyn**
**https://github.com/Siilwyn/awesome-pixel-art**

**A curated list of amazingly awesome things regarding pixel art.**

# By submitting this pull request I confirm I've read and complied with the below requirements.

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title.<br>For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
	- Be added at the bottom of the appropriate category.
- The list I'm submitting complies with these requirements:
	- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
	- It's the result of hard work and the best I could possibly produce.
	- Non-generated Markdown file in a GitHub repo.
	- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
	- Not a duplicate.
	- Only has awesome items. Awesome lists are curations of the best, not everything.
	- Includes a project logo/illustration whenever possible.
		- Placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
		- The image should link to the project website or any relevant website.
		- The image should be high-DPI. Set it to maximum half the width of the original image.
	- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
	- Has the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- Has a Table of Contents section.
		- Should be named `Contents`, not `Table of Contents`.
		- Should be the first section in the list.
	- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
		- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
		- If you use a license badge, it should be SVG, not PNG.
	- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
		- The file should be named `contributing.md`. Casing is up to you.
	- Has consistent formatting and proper spelling/grammar.
		- Each link description starts with an uppercase character and ends with a period.<br>Example: `- [AVA](…) - JavaScript test runner.`
		- Drop all the `A` / `An` prefixes in the descriptions.
		- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
	- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.
- Go to the top and read it again.

### CODE REVIEW

**Comment by kevva** [comment]
I think even without the descriptions, it needs some time to mature. I think there's a lot more to this topic than what's on the list atm. Also, I think there should be descriptions. I have no idea what FEZ or Hyper Light Drifter is.

Same goes for the artists and the tools. Why should I follow that artist? Why should I use that tool?

**Comment by Siilwyn** [comment]
Good idea will describe the games and artists. As for the tools it's hard to do without being opinionated but will do my best.
I don't agree with the maturing part as the list is not being noticed now since it's pretty niche too. Thus I get no feedback > list can't mature. By putting it in the awesome list I hope to break this cycle.

**Comment by legodude17** [comment]
Suggestions:
* The descriptions should be about what it is, like describe the feel of the games, describe what makes the artists awesome
* Awesome pixel art -> Awesome Pixel Art
* Use CC0 instead of Unlicense

**Comment by Siilwyn** [comment]
@legodude17 
- Descriptions are in progress, [game descriptions](https://github.com/Siilwyn/awesome-pixel-art/tree/add-game-descriptions).
- I'm not a fan of capitalizing words because of aesthetics so unless it's a rule I'll keep it this way.
- Why?

**Comment by legodude17** [comment]
* Good
* In titles it is a good idea to capitalize all words
* https://softwareengineering.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense

**Comment by Siilwyn** [comment]
:wave: Changed the licenses and described the games and artists.

I'm having a hard time describing the tools though, they're all pixel art editors and it's up to personal preference what to choose.

**Comment by Siilwyn** [comment]
Done!

:wave: Changed the licenses and described the games and artists.

**Comment by sindresorhus** [comment]
> I'm not a fan of capitalizing words because of aesthetics so unless it's a rule I'll keep it this way.

Me neither, but for headlines and titles, it makes sense. Also for consistency as all other Awesome lists do this.

---

> *   Includes a project logo/illustration whenever possible.

Seeing as this is about something visual, it would be nice to include some kind of pixel art graphic. Maybe this one https://www.google.no/search?q=pixel+art&source=lnms&tbm=isch&sa=X&ved=0ahUKEwifh-TekZ3VAhWlCJoKHSL2DJoQ_AUICigB&biw=1440&bih=799#imgrc=Mgus4_3xSI8qlM:

**Comment by Siilwyn** [comment]
Thanks! Capitalized the title and shortened the description to match the one here.

As for the logo would love to have a nice one. I'm thinking about including an animated timelapse, thoughts on this one?
https://68.media.tumblr.com/57c0a7b2f4f908713b295c9f28d90926/tumblr_oszt9scpKL1qd11zvo1_250.gif

**Comment by sindresorhus** [comment]
> As for the logo would love to have a nice one. I'm thinking about including an animated timelapse as a logo to show the progress of creating a small sprite from scratch, thoughts on this one?

👍

**Comment by Siilwyn** [comment]
:) ready for review!

**Comment by sindresorhus** [comment]
Looks good :)

**Pull request merged**
