### PR TITLE
Add Starcounter

### PR DESCRIPTION
**Pull request by warpech**
https://github.com/starcounter/awesome-starcounter

Starcounter is a revolutionary software platform that combines an in-memory application engine with a built-in web server.

The list should be included in https://github.com/sindresorhus/awesome because I want to match the level of quality of other prominent lists featured here. Starcounter is focused on community building and a good awesome list is one of great tools to achieve that.

# By submitting this pull request I confirm I've read and complied with the below requirements.

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title.<br>For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
	- Be added at the bottom of the appropriate category.
- The list I'm submitting complies with these requirements:
	- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
	- It's the result of hard work and the best I could possibly produce.
	- Non-generated Markdown file in a GitHub repo.
	- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
	- Not a duplicate.
	- Only has awesome items. Awesome lists are curations of the best, not everything.
	- Includes a project logo/illustration whenever possible.
		- Either fullwidth or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
		- The image should link to the project website or any relevant website.
		- The image should be high-DPI. Set it to maximum half the width of the original image.
	- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
	- Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
		- Should be placed on the right side of the readme heading.
		- Should link back to this list.
	- Has a Table of Contents section.
		- Should be named `Contents`, not `Table of Contents`.
		- Should be the first section in the list.
		- Should only have one level of sub-lists, preferably none.
	- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
		- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
		- [WTFPL](http://www.wtfpl.net) and [Unlicense](http://unlicense.org) are not acceptable licenses.
		- If you use a license badge, it should be SVG, not PNG.
	- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
		- The file should be named `contributing.md`. Casing is up to you.
	- Has consistent formatting and proper spelling/grammar.
		- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
		- The description starts with an uppercase character and ends with a period.
		- Drop all the `A` / `An` prefixes in the descriptions.
		- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
	- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.
- Go to the top and read it again.

### CODE REVIEW

**Comment by vitalkanev** [comment]
> https://github.com/Starcounter/awesome-starcounter/commit/d0fc3589ce2c580ccb82378a722ec0334e91582a (Initial commit) was 8 days ago, but awesome requires around 30 days

**Comment by warpech** [comment]
Thank you. Looking at the number of open pull requests, I assumed that it will be more than 30 days at the time when @sindresorhus gets a chance to review it.

**Comment by legodude17** [comment]
> Apps that implement the blending, etc 

What do you mean by "the blending"?

**Comment by warpech** [comment]
Blending is a Starcounter feature of merging multiple UIs. More on it [here](https://docs.starcounter.io/v/2.4/topic-guides/blendable-web-apps).

**Comment by legodude17** [comment]
Ah, it might be nice to explain that with a link to that website.

**Comment by warpech** [comment]
Did that, thanks for the tip!

**Comment by sindresorhus** [comment]
Hey, sorry for the lack of response, please see #1363.

**Comment by sindresorhus** [comment]
Can you fix the merge conflict?

**Comment by sindresorhus** [comment]
```
❯ awesome-lint https://github.com/starcounter/awesome-starcounter
✖ Linting

  README.md:49:1
  ✖  20:89   List item description must end with proper punctuation                                remark-lint:awesome/list-item
  ✖  21:288  List item description must end with proper punctuation                                remark-lint:awesome/list-item
  ✖  25:53   List item description must end with proper punctuation                                remark-lint:awesome/list-item
  ✖  26:91   List item description must end with proper punctuation                                remark-lint:awesome/list-item
  ✖  27:121  List item description must end with proper punctuation                                remark-lint:awesome/list-item
  ✖  28:88   List item description must end with proper punctuation                                remark-lint:awesome/list-item
  ✖  29:51   List item description must end with proper punctuation                                remark-lint:awesome/list-item
  ✖  33:66   List item description must end with proper punctuation                                remark-lint:awesome/list-item
  ✖  34:154  List item description must end with proper punctuation                                remark-lint:awesome/list-item
  ✖  35:143  List item link and description must be separated with a dash                          remark-lint:awesome/list-item
  ✖  36:3    Link to https://addons.mozilla.org/en-US/firefox/addon/starcounter-devtools/ is dead  remark-lint:no-dead-urls
  ✖  36:117  List item link and description must be separated with a dash                          remark-lint:awesome/list-item
  ✖  38:124  List item description must end with proper punctuation                                remark-lint:awesome/list-item
  ✖  39:137  List item description must end with proper punctuation                                remark-lint:awesome/list-item
  ✖  40:144  List item description must end with proper punctuation                                remark-lint:awesome/list-item
  ✖  44:84   List item description must end with proper punctuation                                remark-lint:awesome/list-item
  ✖  45:40   List item description must end with proper punctuation                                remark-lint:awesome/list-item
  ✖  46:84   List item description must end with proper punctuation                                remark-lint:awesome/list-item
  ✖  47:54   List item description must end with proper punctuation                                remark-lint:awesome/list-item
  ✖  49:1    Do not use upper-case characters in definition labels                                 remark-lint:definition-case
  ✖  51:1    Rules should use ---                                                                  remark-lint:rule-style

  21 errors
```

https://github.com/sindresorhus/awesome-lint

**Comment by warpech** [comment]
Thank you @sindresorhus for the suggestion. I will continue in a new PR #1535 because the merge looked rather ugly.

I have installed `awesome-lint` and fixed the errors. Very nice tool!

**Comment by sindresorhus** [comment]
> I will continue in a new PR #1535 because the merge looked rather ugly.

Then you just start from scratch and force push to **this** PR branch. There's *never* any need to open a new PR. That just creates needless noise in the issue tracker.

**Comment by warpech** [comment]
> Then you just start from scratch and force push to this PR branch. There's never any need to open a new PR. That just creates needless noise in the issue tracker.

Sorry, that was not in `contributing.md`. I would never do a force push without consulting with the maintainer, because that's a distructive action. Many maintainers would argue that there's _never_ a need for a force push ¯\\_(ツ)_/¯.

**Pull request closed without merging**
