### PR TITLE
Added awesome-subreddits

### PR DESCRIPTION
**Pull request by iCHAIT**
[awesome-subreddits](https://github.com/iCHAIT/awesome-subreddits)

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please read the [instructions](https://github.com/sindresorhus/awesome/blob/master/create-list.md) for creating a new list, [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

Especially this part:

> Wait at least a couple of weeks after creating a list before submitting to give it a chance to mature.

Ping me here in a few weeks and I'll reopen ;)

**Comment by iCHAIT** [comment]
> Your list is a bunch of subreddits with no context of why they're awesome.

I was thinking of adding a description but I felt that almost all subreddits name are self explanatory, should I still be adding a description to that?

**Comment by sindresorhus** [comment]
I dunno, maybe for those that are not so clear, like `tinycode`.

I know `/r/` is the typical subreddit prefix, but it's very distracting in this context, so I would drop it for readability.

**Comment by iCHAIT** [comment]
I totally agree on that, but adding a description to some of the subs and not adding to other made the list a bit inconsistent, so eventually I decided to drop descriptions for all. What would be the best approach in such a case?

> I know /r/ is the typical subreddit prefix, but it's very distracting in this context, so I would drop it for readability.

Thanks for the advice, will update that.

**Comment by iCHAIT** [comment]
@sindresorhus I guess this maybe ready for a second review?

**Pull request closed without merging**
