### PR TITLE
Add Awesome PEP8

### PR DESCRIPTION
**Pull request by walidsa3d**
A curated list of PEP8 tools and guides

### CODE REVIEW

**Comment by sindresorhus** [comment]
Not a lot of content yet. Work some more on it and ping me in a few weeks and I'll reopen.

**Comment by sindresorhus** [comment]
Feedback:

- Place the badge on the right side of the heading, not description. Looks better.
- Would like to see some more blog posts about using PEP8. Like: http://docs.python-guide.org/en/latest/writing/style/
- https://atom.io/packages/linter-pep8

**Comment by sindresorhus** [comment]
Please read the [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

Especially the part about which license to use.

**Comment by walidsa3d** [comment]
ok thanks for the feedback

**Pull request closed without merging**
