### PR TITLE
Add Web Agencies Under Miscellaneous

### PR DESCRIPTION
**Pull request by kjbrum**
Hopefully others find this as useful as I do.

https://github.com/kjbrum/awesome-web-agencies

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks for the suggestion, but this is more of a plain list and doesn't really fit into the awesome format.

**Comment by kjbrum** [comment]
What do you mean by "plain list" and "awesome format"?

**Comment by killmenot** [comment]
@kjbrum It seems @sindresorhus wants to see a plain structure instead of nested (just compare with other repositories) and who can prove that companies in the provided list are really awesome? What criteria to be added there?

**Comment by sindresorhus** [comment]
An awesome lists is a curation of the best in some category. Your list seem to just list web agencies.

**Comment by sindresorhus** [comment]
Look at some other awesome lists for inspiration.

**Comment by kjbrum** [comment]
I get the idea, but isn't including the "best" subjective? What you think is the best and what others think is the best could be completely different, how do you decide that?

**Comment by Hrxn** [comment]
Well, with open source resources, for example, everyone can try it for himself.

How do you do that with a web agency? Should everyone just hire them?

**Comment by kjbrum** [comment]
I mean but even with that there can still be plenty who think a resource isn't "awesome" that's on a list, but I get it. All well, sa'll good.

**Pull request closed without merging**
