### PR TITLE
added Blockchain Books and Development Documentations.

### PR DESCRIPTION
**Pull request by ShubhamTatvamasi**
https://github.com/BlockchainBooks/blockchainbooks.github.io

Blockchain Books and Development Documentations.

# By submitting this pull request I confirm I've read and complied with the below requirements.

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title.<br>For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
	- Be added at the bottom of the appropriate category.
- The list I'm submitting complies with these requirements:
	- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
	- It's the result of hard work and the best I could possibly produce.
	- Non-generated Markdown file in a GitHub repo.
	- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
	- Not a duplicate.
	- Only has awesome items. Awesome lists are curations of the best, not everything.
	- Includes a project logo/illustration whenever possible.
		- Either fullwidth or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
		- The image should link to the project website or any relevant website.
		- The image should be high-DPI. Set it to maximum half the width of the original image.
	- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
	- Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
		- Should be placed on the right side of the readme heading.
		- Should link back to this list.
	- Has a Table of Contents section.
		- Should be named `Contents`, not `Table of Contents`.
		- Should be the first section in the list.
		- Should only have one level of sub-lists, preferably none.
	- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
		- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
		- [WTFPL](http://www.wtfpl.net) and [Unlicense](http://unlicense.org) are not acceptable licenses.
		- If you use a license badge, it should be SVG, not PNG.
	- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
		- The file should be named `contributing.md`. Casing is up to you.
	- Has consistent formatting and proper spelling/grammar.
		- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
		- The description starts with an uppercase character and ends with a period.
		- Drop all the `A` / `An` prefixes in the descriptions.
		- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
	- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.
- Go to the top and read it again.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

**Comment by ShubhamTatvamasi** [comment]
I have updated the changes in the repo, I also have the "https://github.com/AwesomeBlockchain/awesomeblockchain.github.io" this repo if you want I can shift my books repo to there also

**Comment by legodude17** [comment]
Not done:
 * Has contribution guidelines.
 * Has a Table of Contents section named Contents.
 * Has a license.

Suggestions / Questions:
 * Why are all the links to google drive?
 * Describe the books, not blockchain itself

**Comment by ShubhamTatvamasi** [comment]
I have done all the things mentioned above, These are google links because these are books and documentations. All the name are as it is on the books.

**Comment by ShubhamTatvamasi** [comment]
I have done all the things mentioned above, These are google links because these are books and documentations. All the name are as it is on the books.

**Comment by sindresorhus** [comment]
Hey, sorry for the lack of response, please see #1363.

**Comment by ShubhamTatvamasi** [comment]
Merge is resolved.

**Comment by sindresorhus** [comment]
```
❯ awesome-lint https://github.com/BlockchainBooks/blockchainbooks.github.io
✖ Linting

  README.md:13:1
  ✖    1:1   Missing License section                                                                 remark-lint:awesome/license
  ✖    1:1   Missing or invalid Table of Contents                                                    remark-lint:awesome/toc
  ✖    1:29  Invalid badge source                                                                    remark-lint:awesome/badge
  ✖    5:4   Invalid list item link URL                                                              remark-lint:awesome/list-item
  ✖    6:1   Marker should be 2, was 1                                                               remark-lint:ordered-list-marker-value
  ✖    6:4   Invalid list item link URL                                                              remark-lint:awesome/list-item
  ✖    7:1   Marker should be 3, was 1                                                               remark-lint:ordered-list-marker-value
  ✖    7:4   Invalid list item link URL                                                              remark-lint:awesome/list-item
  ✖    8:1   Marker should be 4, was 1                                                               remark-lint:ordered-list-marker-value
  ✖    8:4   Invalid list item link URL                                                              remark-lint:awesome/list-item
  ✖    9:1   Marker should be 5, was 1                                                               remark-lint:ordered-list-marker-value
  ✖    9:4   Invalid list item link URL                                                              remark-lint:awesome/list-item
  ✖   10:1   Marker should be 6, was 1                                                               remark-lint:ordered-list-marker-value
  ✖   10:4   Invalid list item link URL                                                              remark-lint:awesome/list-item
  ✖   13:1   Headings should use atx                                                                 remark-lint:heading-style
  ✖   22:5   Link to https://drive.google.com/file/d/1_7djN3CU0OC-mK68s12_D0JXxeDFy_hX/view is dead  remark-lint:no-dead-urls
  ✖   40:5   Link to https://drive.google.com/file/d/1X7K3QAUaTczrbZd_7lZ1J08D2NHGlA_d/view is dead  remark-lint:no-dead-urls
  ✖   77:1   Headings should use atx                                                                 remark-lint:heading-style
  ✖   80:5   Link to https://drive.google.com/file/d/1OYQzFxTnaFLYHOeNVJw-AUeYcfueg_Es/view is dead  remark-lint:no-dead-urls
  ✖   86:5   Link to https://drive.google.com/file/d/1WiXzYgqxfqybfd_KEzWNN0AQ62EcRrBN/view is dead  remark-lint:no-dead-urls
  ✖   92:5   Link to https://drive.google.com/file/d/1DbGswXn6wm3ywhgnd8WH7iTJDgq2UzLo/view is dead  remark-lint:no-dead-urls
  ✖   98:5   Link to https://drive.google.com/file/d/0B81TNkQfgbpESjBjWHFDOS05ZWc/view is dead       remark-lint:no-dead-urls
  ✖  110:5   Link to https://drive.google.com/file/d/1Ik7r4LNsEcWWWh5VOz7C1l_c5vIX6cvK/view is dead  remark-lint:no-dead-urls
  ✖  152:1   Headings should use atx                                                                 remark-lint:heading-style
  ✖  162:1   Headings should use atx                                                                 remark-lint:heading-style
  ✖  165:5   Link to https://drive.google.com/file/d/1Bg7j_oUS0D0fTsiI8cHqv0vIZHp4-FSI/view is dead  remark-lint:no-dead-urls
  ✖  184:1   Headings should use atx                                                                 remark-lint:heading-style
  ✖  230:1   Headings should use atx                                                                 remark-lint:heading-style

  28 errors
```

https://github.com/sindresorhus/awesome-lint

**Comment by sindresorhus** [comment]
> These are google links because these are books and documentations.

That doesn't answer @legodude17's question. Are all the books books free? If not, that's piracy and not welcome here.

**Comment by sindresorhus** [comment]
Can you fix the merge conflict?

**Comment by sindresorhus** [comment]
Closing for lack of response.

**Pull request closed without merging**
