### PR TITLE
Add Deep Learning Education

### PR DESCRIPTION
**Pull request by guillaume-chevalier**
**https://github.com/guillaume-chevalier/awesome-deep-learning-resources**

**Hi there! I have built an "awesome list" on how to learn to do Deep Learning learning. I also give this list a more "personal" flavor where users can take my list as a template. By personalized, I mean that they put their name on it in a way that they have very carefully reviewed (and found useful) all the content they have listed on their own sub-list (like I did - only awesome things are found in my list). I encourage forks and contribution to the awesome ecosystem. Also, on top of all I believe that the subject of deep learning is important, just take a look at how much "Machine Learning" and "Deep Learning" are trendy compared to "Computer Programming" on the Google Trends, it's through the roof! And it is promising (see link below). You could probably soon even have a complete section dedicated to `Artificial Intelligence` (that is including `Machine Learning`, `Quantum Machine Learning`, `Deep Learning`, `Computer Vision`, `Speech and Natural Language Processing`, and also this almost includes `Data Science`) - in fact the `Computer Science` title (under which I have put my new awesome list) could almost be renamed `Artificial Intelligence` if it wasn't of a few of those sub-lists which are not exactly about that. See https://www.google.ca/trends/explore?date=all&q=machine%20learning,deep%20learning,data%20science,computer%20programming**

# By submitting this pull request I confirm I've read and complied with the below requirements.

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title.<br>For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
	- Be added at the bottom of the appropriate category.
- The list I'm submitting complies with these requirements:
	- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
	- It's the result of hard work and the best I could possibly produce.
	- Non-generated Markdown file in a GitHub repo.
	- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
	- Not a duplicate.
	- Only has awesome items. Awesome lists are curations of the best, not everything.
	- Includes a project logo/illustration whenever possible.
		- Placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
		- The image should link to the project website or any relevant website.
		- The image should be high-DPI. Set it to maximum half the width of the original image.
	- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
	- Has the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- Has a Table of Contents section.
		- Should be named `Contents`, not `Table of Contents`.
		- Should be the first section in the list.
	- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
		- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
		- If you use a license badge, it should be SVG, not PNG.
	- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
		- The file should be named `contributing.md`. Casing is up to you.
	- Has consistent formatting and proper spelling/grammar.
		- Each link description starts with an uppercase character and ends with a period.<br>Example: `- [AVA](…) - JavaScript test runner.`
		- Drop all the `A` / `An` prefixes in the descriptions.
		- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
	- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.
- Go to the top and read it again.

### CODE REVIEW

**Comment by legodude17** [comment]
Not followed:
* Has an appropriate license.
* Includes a succinct description of the project/theme at the top of the readme.

Suggestions:
> To make your own personalized awesome list (or to make a general list where everyone can contribute to) on GitHub from this template, please read contributing.md carefully.

Delete this

Also, improve the descriptions.

> Very worth reading.

That is not a good description

**Comment by guillaume-chevalier** [comment]
I followed your suggestions and changed the required things. I removed the sentence linking to `contributing.md` and I edited the bad description to " - Thought provoking article about the future of the brain and brain-computer interfaces". 

Could you detail more about "Has appropriate license"? I have the CC0 license located in the "LICENSE" file of the repo and which is recognised by GitHub in the license section of my repo (see header on top of the file) : https://github.com/guillaume-chevalier/awesome-deep-learning-resources/blob/master/LICENSE 
I believe the license is right.

**Comment by aleksandar-todorovic** [comment]
Yup, it has the appropriate license. @legodude17 probably didn't see it in the README and thought otherwise.

I'm still seeing some descriptions that I'm not satisfied with, like:

> Awesome videos

...and some content that I don't see how it belongs there, like a link to Quora's homepage. I also couldn't figure out why I should click on this:

> Siraj's YouTube Channel - Siraj has some entertaining videos

...and how does it relate to the topic. Something more descriptive would be appreciated.

Other than that, I'd say that this is really useful. In fact, it seems even more useful to me than the one listed here at the moment. :+1:

**Comment by legodude17** [comment]
I would suggest you at least put a link to the LICENSE or just the text "CC0 1.0 Universal" on the README. If it is already there, can you point me too it?

**Comment by guillaume-chevalier** [comment]
Thanks for the suggestions, I reviewed every single description and I changed most just to be sure that it relates properly, this did a good clean. I also added the license badge like it is in some of the other awesome repositories. I am thinking about keeping my list rather than merging with another one. In fact, this list really reflects how I have learned deep learning from scratch as an undergrad student. The resources listed there got me from complete noob to someone up to date with actual research and I only listed what I experienced to be the best content. 

To not repeat what's contained in other awesome lists, I would suggest that we link to my list as `Trends`, or something like that under the `Deep Learning` title. We could also probably link to my list with a name referring more to `Learning` how does deep learning work, or a name like `Roadmap to Deep Learning`. The content added to my list will be reviewed by me for sure in the future. What I like about my list is that it is concise in terms of how picky I have been about choosing everything listed. 

Would you have any idea of a title that could be good for the current pull request? I would say that my list is really about learning resources for trendy deep learning, so finding a proper title has not been easy considering the nature of the list. 

By the way, I think that the `Computer Science` title in https://github.com/sindresorhus/awesome could be split into a "true" computer science section and also into a new `Artificial Intelligence` section since most of the awesome-lists under `Computer Science` already refers to AI. Else the few links not about AI could be moved to the `Miscellaneous` so much the new `Computer Science` section would be tiny. The field of Artificial Intelligence is growing at a fast exponential rate so I think a section deserved to that would be something worth to have. What do you think?

**Comment by sindresorhus** [comment]
Maybe call it "Deep Learning Education"? There are some other sub-lists called this for other themes that also focuses on learning.

**Comment by sindresorhus** [comment]
> Each link description starts with an uppercase character and ends with a period.
Example: `- [AVA](…) - JavaScript test runner.`

:arrow_up:

---

> If you use a license badge, it should be SVG, not PNG.

:arrow_up:

---

The image in the Trends section should be set to half its real size so it looks good on high-DPI screens.

**Comment by guillaume-chevalier** [comment]
- I'm O.K. with "Deep Learning Education". I would not change the URL of the list since it has many inbound links already, except if there is a permanent way to redirect the traffic. 
- I edited each link description to start with an uppercase character and to end with a period. 
- I added a backlink to the main awesome list on the SVG badge. 
- I have set a different size for the image in the trends section. Making it smaller would make the text too small on regular displays. At least now the text size should be the same as the text size in the image.

By the way @sindresorhus , I would suggest that you make compulsory to have a backlink on the badge for everyone. Or it could be on anything else than the badge, such as specific, targeted text. All links in GitHub's readme files generated with the `[]()` syntax are links that do count for SEO (they are not "nofollow" links if you inspect the HTML code generated), so your "main" list would be even more visible on search engines with the page rank algorithm, making it more central.

If this is O.K. to you I will finalize things by changing the list's title and changing the commit to be ready for merging the pull request.

**Comment by sindresorhus** [comment]
> except if there is a permanent way to redirect the traffic.

GitHub automatically redirects renamed repos.

> I would suggest that you make compulsory to have a backlink on the badge for everyone. Or it could be on anything else than the badge, such as specific, targeted text. 

I assumed it was a given since I provide the copy-paste-able Markdown code for the badge, but I've made it more explicit: https://github.com/sindresorhus/awesome/commit/817989930b505a633779bd29042a762bde88d5d7

**Comment by guillaume-chevalier** [comment]
Thinking twice, I think I will not rename the list. Limiting the title to "Education" would be limiting for this list that - yes contains educational stuff - but has a wider reach. Thought, I would be O.K. with having my list named as being for "Education", "Resources" or maybe something else in your repository.

**Comment by sindresorhus** [comment]
> Thinking twice, I think I will not rename the list. Limiting the title to "Education" would be limiting for this list that - yes contains educational stuff - but has a wider reach. Thought, I would be O.K. with having my list named as being for "Education", "Resources" or maybe something else in your repository.

I'm ok with that too.

**Comment by sindresorhus** [comment]
> > If you use a license badge, it should be SVG, not PNG.

> :arrow_up:

:arrow_up:

---

> Has contribution guidelines.
The file should be named contributing.md. Casing is up to you.

:arrow_up:

**Comment by guillaume-chevalier** [comment]
Hi Sindre, I added the changes you asked for.

I also updated the picture for the trends, which is now neatly taken at a regular 100% zoom. For the SVG badge, it was already in SVG format. I link to the SVG badge the very same way other recently accepted lists already do (for example, like the most recent one on action script 3). Thanks.

**Comment by sindresorhus** [comment]
> For the SVG badge, it was already in SVG format.

It is clearly not. You're linking to http://i.creativecommons.org/p/zero/1.0/88x31.png, which is a PNG.

**Comment by sindresorhus** [comment]
> I also updated the picture for the trends, which is now neatly taken at a regular 100% zoom.

Images should be high-DPI, meaning they should be set to half the width of their actual width. That means either taking the screenshot on a computer with a Retina screen or zooming in 200%.

**Comment by guillaume-chevalier** [comment]
I see. I had the pink glasses badge in mind all the time: https://github.com/sindresorhus/awesome/blob/master/media/badge.svg

Fixed - thanks for noticing. The DPI issue too. This is neat.

**Comment by sindresorhus** [comment]
Thank you :)

**Pull request merged**
