### PR TITLE
add ruby events (conferences, meetups, etc.)

### PR DESCRIPTION
**Pull request by geraldb**
Hello,
  First thanks for your inspiring awesome list.  For your consideration I've collected (curated) a list of world-wide Ruby events (e.g. conferences, camps, meetups, etc.).  Would be great to see it included. Cheers.

### CODE REVIEW

**Comment by n1trux** [comment]
imho, the naming of the list is a bit off. You could name it ruby-events. Wouldn't it fit better on this list?:

https://github.com/markets/awesome-ruby#resources

**Comment by geraldb** [comment]
> mho, the naming of the list is a bit off. You could name it ruby-events. 

Thanks for the suggestions. The name is planetruby/awesome-events  ,thus, to avoid duplication and keep the repo name (shorter) it's planetruby/awesome-events.

> Wouldn't it fit better on this list?  [ed. awesome-ruby]

The idea is to be an inspiration for other languages (as far as I know it's the first awesome event list) and the event list is actually longer than the package list!  Thus, it's not really just another (sub)section for awesome-ruby.

**Comment by sindresorhus** [comment]
Added.

**Comment by geraldb** [comment]
Thanks! Cheers.

**Pull request closed without merging**
