### PR TITLE
Add Network Automation

### PR DESCRIPTION
**Pull request by itdependsnetworks**
Curated list of awesome about Network Automation

**[Insert URL to the list here]**
https://github.com/itdependsnetworks/awesome-network-automation

**[Explain what this list is about and why it should be included here]**

It addresses network automation which is a growing market. Over a hundred stars, and been up over 30 days. 

# By submitting this pull request I confirm I've read and complied with the below requirements.

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title.<br>For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
	- Be added at the bottom of the appropriate category.
- The list I'm submitting complies with these requirements:
	- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
	- It's the result of hard work and the best I could possibly produce.
	- Non-generated Markdown file in a GitHub repo.
	- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
	- Not a duplicate.
	- Only has awesome items. Awesome lists are curations of the best, not everything.
	- Includes a project logo/illustration whenever possible.
		- Either fullwidth or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
		- The image should link to the project website or any relevant website.
		- The image should be high-DPI. Set it to maximum half the width of the original image.
	- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
	- Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
		- Should be placed on the right side of the readme heading.
		- Should link back to this list.
	- Has a Table of Contents section.
		- Should be named `Contents`, not `Table of Contents`.
		- Should be the first section in the list.
		- Should only have one level of sub-lists, preferably none.
	- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
		- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
		- If you use a license badge, it should be SVG, not PNG.
	- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
		- The file should be named `contributing.md`. Casing is up to you.
	- Has consistent formatting and proper spelling/grammar.
		- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
		- The description starts with an uppercase character and ends with a period.
		- Drop all the `A` / `An` prefixes in the descriptions.
		- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
	- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.
- Go to the top and read it again.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) more closely. Multiple points not followed from it. Try going through the list point for point and check that you follow it. :)

**Comment by itdependsnetworks** [comment]
I have updated the 3 sections as shown below. If any do not meet the criteria, please let me know, as a few of them are subjective.

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md). **YES**
- This pull request has a descriptive title.<br>For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`. **YES**
- The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`. **What?**
	- Be added at the bottom of the appropriate category. **YES**
- The list I'm submitting complies with these requirements:
	- **Has been around for at least 30 days.** **YES**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent. **YES**
	- It's the result of hard work and the best I could possibly produce. **Subjective but I say YES**
	- Non-generated Markdown file in a GitHub repo. **YES**
	- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self) **YES** - Updated, apologies, I looked at top of github page, but not the top of readme. 
	- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics. **YES** - Updated, apologies, did not get this one
	- Not a duplicate. **YES**
	- Only has awesome items. Awesome lists are curations of the best, not everything. **Subjective but I say YES**
	- Includes a project logo/illustration whenever possible. **N/A**
	- Entries have a description, unless the title is descriptive enough by itself. It rarely is though. **Subjective, but of the 7 that do not, I feel they are self explanatory** 
	- Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge). **YES**
		- Should be placed on the right side of the readme heading. **YES**
		- Should link back to this list. **YES**
	- Has a Table of Contents section. **YES**
		- Should be named `Contents`, not `Table of Contents`. **YES**
		- Should be the first section in the list. **YES**
		- Should only have one level of sub-lists, preferably none. **YES**
	- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license). **YES**
		- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.** **YES - Apache**
		- If you use a license badge, it should be SVG, not PNG. **N/A**
	- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines). **YES**
		- The file should be named `contributing.md`. Casing is up to you. **YES**
	- Has consistent formatting and proper spelling/grammar. **As far as I can tell YES**
		- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.` **All but the previously stated 7**
		- The description starts with an uppercase character and ends with a period. **Updated, many were missing YES**
		- Drop all the `A` / `An` prefixes in the descriptions. **Updated, (not a fan of this, it reads awkward) YES**
		- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`. **I believe so** 
	- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme. **YES**

**Comment by itdependsnetworks** [comment]
Any chance to get another look? I have went line by line and left comments, so hopefully that addresses everything.

**Comment by itdependsnetworks** [comment]
ping.

**Comment by sindresorhus** [comment]
Thanks for your patience :)

---

> Include a short description about the project/theme of the list. It should not describe the list itself.
Example: - [Fish](…) - User-friendly shell., not - [Fish](…) - Resources for Fish.. What?

How is it not clear? Just curious.

It needs to describe the topic "Network Automation" succinctly. Look at the other descriptions.

> That means something like CC0, not a code licence like MIT, BSD, Apache, etc. YES - Apache

You misread this statement. Is says **not** a code license like Apache.

---

The `Awesome Network Automation` entry in the `Contents` section is moot and should be removed.

---

In `Network Automation is cross between two disciplines of Infrastructure Networks and Programming`, can you linkify `Network Automation` to a good resource where people can read more about the topic?

**Comment by sindresorhus** [comment]
Ping. Please also see #1363.

**Comment by sindresorhus** [comment]
Closing for lack of response.

**Pull request closed without merging**
