### PR TITLE
Add Cheminformatics

### PR DESCRIPTION
**Pull request by hsiaoyi0504**
Add another list focuses on different aspect of informatics.
I placed it under bioinformatics because it is closely related.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

**Comment by hsiaoyi0504** [comment]
@sindresorhus Thanks for notifying me. I updated the list again. Can you take a look again ?

**Comment by legodude17** [comment]
Suggestions:
 * Add a description to this list's entry
 * Remove `A` / `An` from descriptions
 * Make sure all of the descriptions have the same formatting (`[thing] - [description]`)
 * Maybe add a LICENSE file?
 * Check your grammar and spacing

**Comment by hsiaoyi0504** [comment]
Hi @legodude17 Thanks for the suggestion.
I will make it better, but for adding a LICENSE file, it seems to me that the license has already included in the end of the page (a license badge).

**Comment by hsiaoyi0504** [comment]
@legodude17 I updated a lot. Can you review again ?

**Comment by legodude17** [comment]
Are there any books or other courses you can find? Also, a general expansion would be great.

**Comment by hsiaoyi0504** [comment]
@legodude17 I added one book that I think it's good. Unfortunately, the cheminformatics is a field that hasn't been popular. One reason I want add this to awesome list is that make more people see it and try to expand the knowledge of this field.

**Comment by sindresorhus** [comment]
Hey, sorry for the lack of response, please see #1363.

**Comment by hsiaoyi0504** [comment]
Rebase first and I will start reviewing some PRs.

**Comment by hsiaoyi0504** [comment]
@sindresorhus I have reviewed #1383 and #1387. Can you consider adding this list ?

**Comment by sindresorhus** [comment]
```
❯ awesome-lint https://github.com/hsiaoyi0504/awesome-cheminformatics
✖ Linting

  README.md:123:3
  ✖    1:28   Invalid badge source                                                          remark-lint:awesome/badge
  ✖   10:3    ToC item "Visualization" does not match corresponding heading "Visulization"  remark-lint:awesome/toc
  ✖   14:3    ToC item "General Purpose" link "#lib-general" not found                      remark-lint:awesome/toc
  ✖   28:1    ToC should not contain section "License"                                      remark-lint:awesome/toc
  ✖   80:148  List item description must end with proper punctuation                        remark-lint:awesome/list-item
  ✖  119:77   Text "youtube" should be written as "YouTube"                                 remark-lint:awesome/spell-check
  ✖  123:3    Link to https://opensourcemolecularmodeling.github.io/ is dead                remark-lint:no-dead-urls
  ✖  133:53   Link to https://chembioinfo.com/cv/ is dead                                   remark-lint:no-dead-urls
  ✖  137:5    Link to http://cheminformist2.itmol.com/ is dead                              remark-lint:no-dead-urls
  ✖  138:5    Link to http://cheminformist.itmol.com/TEST/ is dead                          remark-lint:no-dead-urls
  ✖  148:111  List item description must end with proper punctuation                        remark-lint:awesome/list-item

  11 errors
```

https://github.com/sindresorhus/awesome-lint

**Comment by sindresorhus** [comment]
Can you fix the merge conflict?

**Comment by hsiaoyi0504** [comment]
@sindresorhus I have fixed the merge conflict and fix linting errors.
However, following linting errors seems to be weired.
It's because some of the headers are defined by HTML like `<a id="lib-general"></a>`

```
awesome-lint https://github.com/hsiaoyi0504/awesome-cheminformatics
✖ Linting

  README.md:10:3
  ✖  10:3  ToC item "Visualization" link "#app-visualization" not found  remark-lint:awesome/toc
  ✖  14:3  ToC item "General Purpose" link "#lib-general" not found      remark-lint:awesome/toc

  2 errors
```

**Comment by sindresorhus** [comment]
You didn't fix the merge conflict correctly: https://github.com/sindresorhus/awesome/pull/1286/files

**Comment by hsiaoyi0504** [comment]
@sindresorhus Sorry, I fixed again. Please check. Thanks !

**Comment by sindresorhus** [comment]
Tweet: https://twitter.com/awesome__re/status/1126368689962414080

**Pull request merged**
