### PR TITLE
added Youtube Channels about Programming

### PR DESCRIPTION
**Pull request by epoyraz**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please read the [instructions](https://github.com/sindresorhus/awesome/blob/master/create-list.md) for creating a new list, [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

Especially this part:

> Wait at least a couple of weeks after creating a list before submitting to give it a chance to mature.

Ping me here in a few weeks and I'll reopen ;)

**Comment by epoyraz** [comment]
sure ! I just thought, it will get more contributions if it is exposed here.

**Comment by epoyraz** [comment]
Ping !

**Comment by sindresorhus** [comment]
> Ping me here in a **few weeks** and I'll reopen ;)

**Comment by epoyraz** [comment]
3 weeks ! PING !

**Comment by sindresorhus** [comment]
Still not compliant. Please take the time to actually read what I asked:

> Please read the [instructions](https://github.com/sindresorhus/awesome/blob/master/create-list.md) for creating a new list, [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

**Pull request closed without merging**
