### PR TITLE
Add Awesome Github to the Miscellaneous category

### PR DESCRIPTION
**Pull request by phillipadsmith**
Awesome Github is a curated list of Github's awesomeness.

### CODE REVIEW

**Comment by sindresorhus** [comment]
How is it different from https://github.com/tiimgreen/github-cheat-sheet?

**Comment by phillipadsmith** [comment]
@sindresorhus It's different because it's not about using Github for development, it's about how Github is changing the way we work.

It's also for an entirely difference audience -- an audience that is not necessarily interested in "developing with Github," but using Github for publishing data, writing books or, for example, [organizing a giant conference](https://github.com/mozilla/mozfest-program/issues). It's about unexpected and non-technical uses of Github, i.e., all the ways in which Github is awesome.

Hope that helps.

**Comment by sindresorhus** [comment]
Good stuff. Maybe try to cross-link with https://github.com/tiimgreen/github-cheat-sheet ;)

**Comment by phillipadsmith** [comment]
@sindresorhus It's already in there! ;)  Thanks for adding. Appreciated & keep up the Awesome work!

**Pull request closed without merging**
