### PR TITLE
Add Functional Programming

### PR DESCRIPTION
**Pull request by lucasviola**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please read the [instructions](https://github.com/sindresorhus/awesome/blob/master/create-list.md) for creating a new list, [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

Especially this part:

> Wait at least a couple of weeks after creating a list before submitting to give it a chance to mature.

Ping me here in a few weeks and I'll reopen ;)

**Comment by sindresorhus** [comment]
It will also need more content. I'm sure you can find more than one good blog post and tool ;)

**Comment by lucasviola** [comment]
Cool. OK!

**Comment by lucasviola** [comment]
Pinging you here! Also referring to the discussion we had on #404. Let me know is there is something else I can do.

**Comment by sindresorhus** [comment]
Still not very much content in that list, but better.

**Comment by sindresorhus** [comment]
Added :)

**Pull request closed without merging**
