### PR TITLE
Update README URLs based on HTTP redirects

### PR DESCRIPTION
**Pull request by m1guelpf**
### GitHub Corrected URLs 
Was | Now 
--- | --- 
https://github.com/Neueda4j/awesome-neo4j | https://github.com/neueda/awesome-neo4j 
https://github.com/Symfonisti/awesome-symfony-education | https://github.com/pehapkari/awesome-symfony-education 
https://github.com/brainblowjob/awesome-asm | https://github.com/jaspergould/awesome-asm 
https://github.com/candelibas/awesome-ionic2 | https://github.com/candelibas/awesome-ionic 
https://github.com/feross/awesome-standard | https://github.com/standard/awesome-standard 
https://github.com/fisherman/awesome-fish | https://github.com/jbucaran/awesome-fish 
https://github.com/gmontalvoriv/awesome-katas | https://github.com/gamontalvo/awesome-katas 
https://github.com/jaredmichaelsmith/awesome-vehicle-security | https://github.com/jaredthecoder/awesome-vehicle-security 
https://github.com/okulbilisim/awesome-datascience | https://github.com/bulutyazilim/awesome-datascience 
https://github.com/sergeyklay/awesome-phalcon | https://github.com/phalcon/awesome-phalcon 
https://github.com/vhf/free-programming-books | https://github.com/EbookFoundation/free-programming-books 
https://github.com/vinkla/awesome-educational-games | https://github.com/yrgo/awesome-eg 
https://github.com/vinkla/share-links | https://github.com/vinkla/awesome-share 
https://github.com/willempienaar/awesome-quantified-self | https://github.com/woop/awesome-quantified-self 

### Other Corrected URLs 
Was | Now 
--- | --- 
http://sindresorhus.com | https://sindresorhus.com/

### CODE REVIEW

**Comment by davisonio** [comment]
Can you remove the extra readme you added?

**Comment by m1guelpf** [comment]
Done!

**Comment by davisonio** [comment]
Also awesome.re and awesomeweekly.co should stay as they are.

**Comment by m1guelpf** [comment]
Also done.

**Pull request merged**
