### PR TITLE
Add awesome-minecraft to the list

### PR DESCRIPTION
**Pull request by Armored-Dragon**
I have created an new awesome list for the game Minecraft.

### CODE REVIEW

**Comment by aharris88** [comment]
Please read the [instructions for creating a new list](https://github.com/sindresorhus/awesome/blob/master/create-list.md), [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

**Comment by Armored-Dragon** [comment]
I have, and the list has been updated to provide some solid content.

**Comment by aharris88** [comment]
Looks better, but this is in the main thing I wanted to point out in the instructions:

> Wait at least a couple of weeks after creating a list before submitting to this list to give it a chance to mature.

**Comment by sindresorhus** [comment]
:arrow_up:

Ping me here in a few weeks and I'll reopen ;)

**Comment by sindresorhus** [comment]
The list could use some more content. I imagine it would be cool to cover some awesome Twitch minecraft videos, blog post on modding, crazy things people have done with Minecraft, etc.

**Pull request closed without merging**
