### PR TITLE
Adding Free Paid Software List

### PR DESCRIPTION
**Pull request by leog**
A curated list of paid software offering free-of-charge pricing option to support open-source projects.

### CODE REVIEW

**Comment by davisonio** [comment]
How's this different from https://github.com/ripienaar/free-for-dev?

**Comment by leog** [comment]
The focus for this list is not to include free software per se. This list is about paid software without any free tier that offers a "charity" option in order to support open source projects with full functionalities.

Should I make that clearer? 

Thanks.

**Comment by sindresorhus** [comment]
Please read the [instructions](https://github.com/sindresorhus/awesome/blob/master/create-list.md) for creating a new list, [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

Especially this part:

> Wait at least a couple of weeks after creating a list before submitting to give it a chance to mature.

**Comment by sindresorhus** [comment]
The list is also not very comprehensive. Awesome lists are hard work. Just putting a few links isn't very useful. Put some more work into it. Take a look at some other lists and see how they do it. E.g. https://github.com/sindresorhus/awesome-electron https://github.com/sindresorhus/awesome-npm Work on it some more and try again in a month.

**Pull request closed without merging**
