### PR TITLE
Add JavaScript Learning

### PR DESCRIPTION
**Pull request by mischah**
# Addition
[Awesome JavaScript learning resources ](https://github.com/micromata/awesome-javascript-learning-resources)

This list is about JavaScript – the language. Not about APIs, tooling, frameworks or other aspects of todays JavaScript ecosystem.

Therefore the list is small and focused to the best resources. Reason: We don’t want to frustrate people who like to learn JavaScript with a list that:

- is too long to get through it
- offers too many possibilities

# By submitting this pull request I confirm I've read and complied with the below requirements.

Failure to properly do so will just result in the pull request being closed and everyone's time wasted. Please read it twice. Most people miss many things.

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title. For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should include a short description about the list project/theme (not the list itself), and should be added at the bottom of the appropriate category.
- The list I added
	- **has been around for at least 30 days,**
	- is the result of hard work and is the best I could possibly produce,
	- is a non-generated Markdown file in a GitHub repo,
	- is not a duplicate,
	- includes a succinct description of the project/theme at the top ([example](https://github.com/willempienaar/awesome-quantified-self)),
	- includes a project logo/illustration (whenever possible) at the top right of the readme ([example](https://github.com/sindresorhus/awesome-electron)). (The logo should link to the project website or any relevant website. The logo should be high-DPI, so set it to maximum half the width of the original image.),
	- only has awesome items **with descriptions** *(Awesome lists are curations of the best, not of everything)*,
	- contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- has a Table of Contents section **named `Contents`** as the first section,
	- has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license) *(Meaning something like CC0, NOT a code licence like MIT, BSD, Apache, etc)* *(If you use a license badge, it should be SVG, not PNG)*,
	- has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- doesn't include a Travis badge,
	- has been checked for inconsistent formatting, spelling, and grammar:
		- Each link description starts with an uppercase character and ends with a period.
		- Drop all the `A` / `An` prefixes in the descriptions.
		- Consistent naming. For example, `Node.js`, not `NodeJS` or `node.js`.

### CODE REVIEW

**Comment by mischah** [comment]
Hej, is there something I can help with to get a review? 😘 

Thanks, Michael

**Comment by sindresorhus** [comment]
Generally looks good.

Readme title: `Awesome JavaScript learning resources` => `Awesome JavaScript Learning Resources`

Why "JavaScript Learning Resources" and not just "JavaScript Learning" or "Learn JavaScript"? The "Resources" part feels moot as all lists are resources for some subject.

I would include a blogs section, and this blog: http://www.2ality.com/ It's IMHO the best JS blog out there. Everything is explained very well.

**Comment by mischah** [comment]
Thanks for the review 😘

> Readme title: Awesome JavaScript learning resources => Awesome JavaScript Learning Resources

Done. Get rid of »Resources« though.

>Why "JavaScript Learning Resources" and not just "JavaScript Learning" or "Learn JavaScript"? The "Resources" part feels moot as all lists are resources for some subject.

Your absolutely right. Changed to »Awesome JavaScript learning«.
This was because the list started in our inhouse wiki system before it made it to Github as awesome list 😉 

> I would include a blogs section, and this blog: http://www.2ality.com/ It's IMHO the best JS blog out there. Everything is explained very well.

Good idea. Done. Added »Pony Foo« as well. That’s all I come up with for now.

---

I know that you’re a busy person. But do you mind giving some feedback on this PR of mine? https://github.com/micromata/awesome-javascript-learning/pull/6

Thanks Michael

**Comment by mischah** [comment]
I think I’m ready to get this one merged 😗 

Let me know if you spot anything else that is improvable.

**Comment by sindresorhus** [comment]
Looks good :)

**Pull request merged**
