### PR TITLE
 Add Technical Topics

### PR DESCRIPTION
**Pull request by Mahmoudz**
[https://github.com/Mahmoudz/awesome-topics](https://github.com/Mahmoudz/awesome-topics)

Added this new [Awesome Topics](https://github.com/Mahmoudz/awesome-topics) repository under the Learn section.

It contains a list of technical topics from the software world, explained concisely for all levels of expertise.

_This repository goes beyond mere link lists, delivering concise information for tech enthusiasts of all levels._

> Despite being just few days old and not meeting the 30-days rule, my track record of 7 years in maintaining other successful [repos](https://github.com/Mahmoudz#my-open-source-projects) ensures my dedication to its long-term upkeep.

Thanks for your awesome work `unicorn!`

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

**Comment by hlaueriksson** [comment]
A good starting point would be to run the linter. I found 61 errors.

**Comment by gokayfem** [comment]
You should put awesome badge next to main heading
```
# Awesome Topics 😎 [![Awesome](https://awesome.re/badge-flat2.svg)](https://awesome.re)
```

**Review by gokayfem — COMMENTED** [review]
Better not to contain word "awesome" in the description.

**Comment by sindresorhus** [comment]
Closing for lack of response from OP and also the PR and list not following the guidelines.

**Pull request closed without merging**
