### PR TITLE
Add Django

### PR DESCRIPTION
**Pull request by wsvincent**
Adds Django web framework to bottom of Back-End Development section.

https://github.com/wsvincent/awesome-django

Django is a back-end web application framework written in Python.

## Yes, I have read and complied with the requirements for a PR. ##

### CODE REVIEW

**Comment by sindresorhus** [comment]
An entry has broken rendering: `- [Project Website](djangoproject.com) - Official Django website.`

**Comment by sindresorhus** [comment]
I never got a response the last time you submitted this list: https://github.com/sindresorhus/awesome/pull/1497

**Comment by sindresorhus** [comment]
> Yes, I have read and complied with the requirements for a PR.

You have not. If you had read through the whole thing, you would have seen:

> To verify that you've read all the guidelines, please comment on your pull request with just the word unicorn.

**Comment by sindresorhus** [comment]
> You have to review at least 2 other open pull requests. Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration. Just commenting “looks good” or simply marking the pull request as approved does not count! You have to actually point out mistakes or improvement suggestions.

**Comment by sindresorhus** [comment]
> The image should link to the project website or any relevant website. - https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md

**Comment by sindresorhus** [comment]
> If your back-end and front-end are on different servers, you need this.

Descriptions should succinctly describe what an entry is, not be a marketing tagline.

Same here:

> Creating delicious APIs for Django apps since 2010.

**Comment by sindresorhus** [comment]
> django-ninja - Django Ninja

Not sure why the name is repeated here.

**Comment by sindresorhus** [comment]
`wysiwyg` => `WYSIWYG`

`django-quill-editor - django-quill-editor makes` => `django-quill-editor - Makes`

`django-tinymce - TinyMCE integration for Django`, should end in a dot.

`saleor - GraphQL-based Django E-Commerce Platform.`, descriptions should not be in title-case.

Etc

In general, a lot of the descriptions needs more work.

**Comment by wsvincent** [comment]
Ok. I appreciate the prompt feedback. I won't take up your time further on the matter.

**Comment by deronnax** [comment]
@wsvincent if your are willing accept the changes suggested by sindresorhus, I am willing to do the work and open the PR  awesome-django so it can be added to this list. Are you?

**Pull request closed without merging**
