### PR TITLE
Added SamyPesse's greatest book about making operating system in C++

### PR DESCRIPTION
**Pull request by Guricopperfield**

### CODE REVIEW

**Comment by sindresorhus** [comment]
This a list of lists, not a list of things.

**Comment by Guricopperfield** [comment]
What if I change Gitbook link into Github repository link of this book? SamyPesse also have Github repository.

**Comment by aleksandar-todorovic** [comment]
I think that this should go in https://github.com/vhf/free-programming-books. Try submitting a pull request there.

**Comment by Guricopperfield** [comment]
Thank you a lot.

**Comment by Guricopperfield** [comment]
Thank you a lot.

**Pull request closed without merging**
