### PR TITLE
add awesome Ruby-on-Rails-Learning-Resources

### PR DESCRIPTION
**Pull request by Khwilo**
Link is at [Ruby-on-Rails-Learning-Resources](https://github.com/CodementorIO/Ruby-on-Rails-Learning-Resources)

### CODE REVIEW

**Comment by sindresorhus** [comment]
Doesn't look very well maintained. Last commit a year ago.

// @RosieChiu

**Comment by Khwilo** [comment]
Alright then. Now do I have to look for another resource or close the PR?

**Comment by sindresorhus** [comment]
If you think it's a good resource, you could offer to maintain it for them and get added there, or fork and maintain a fork and I could link to that instead.

**Comment by Khwilo** [comment]
Alright I'll try to maintain it myself.

**Pull request closed without merging**
