### PR TITLE
Added SharePoint to CMS section

### PR DESCRIPTION
**Pull request by sergey-tihon**
**https://github.com/BSUG/awesome-sharepoint**

**A collection of awesome libraries, tools, frameworks, and software for SharePoint**

- [x] I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- [x] This pull request has a descriptive title.
- The list I added
	- [x] is not a duplicate,
	- [x] has been around for a few weeks,
	- [x] only has awesome items with descriptions,
	- [x] contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- [ ] has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license),
	- [x] has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- [x] has been checked for inconsistent formatting, spelling and grammar, and
	- [x] has been added at the bottom of the appropriate category.

### CODE REVIEW

**Comment by sergey-tihon** [comment]
@dmitryrogozhny @Hatallia We have to decide something about licence for awesome-sharepoint

**Comment by dmitryrogozhny** [comment]
@sergey-tihon @hatallia It seems to me that the CC0 (https://creativecommons.org/publicdomain/zero/1.0/) should work fine in our case. 

This is basically No copyright statement and anyone can reuse it without asking for permissions.

**Comment by sergey-tihon** [comment]
@sindresorhus Why you closed this PR?

**Comment by aleksandar-todorovic** [comment]
Still has no license I presume.

**Pull request closed without merging**
