### PR TITLE
Added MATLAB list

### PR DESCRIPTION
**Pull request by mikecroucher**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please read the [instructions](https://github.com/sindresorhus/awesome/blob/master/create-list.md) for creating a new list, [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

Especially this part:

> Wait at least a couple of weeks after creating a list before submitting to give it a chance to mature.

Ping me here in a few weeks and I'll reopen ;)

**Comment by mikecroucher** [comment]
will do, thanks :)

**Comment by mikecroucher** [comment]
Hi, 3 weeks later and we are up to 120+ commits and 7 contributors. 

I admit that its still early days but do you think we are awesome enough for inclusion yet?

**Comment by egeerardyn** [comment]
@sindresorhus How about including this?

**Comment by sindresorhus** [comment]
@egeerardyn The author has yet to read and follow the [instructions](https://github.com/sindresorhus/awesome/blob/master/create-list.md) for creating a new list. Happy to add it when it becomes compliant.

The formatting needs some consistency tweaks. Ensure all descriptions starts with a capital letter and ends with a `.`. And the awesome badge should be at the right side of the title.

**Pull request closed without merging**
