### PR TITLE
add awesome Polymer link

### PR DESCRIPTION
**Pull request by Granze**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Repo needs a license. For inspiration see the bottom of the readme in this repo.

**Comment by Granze** [comment]
License added. Thanks for pointing this out.

**Comment by sindresorhus** [comment]
Would be cool if you could link back here in your list so users can easily discover more awesome lists ;)

**Comment by Granze** [comment]
done! :)

**Comment by sindresorhus** [comment]
:beers:

**Pull request merged**
