### PR TITLE
Add Windows Subsystem for Linux

### PR DESCRIPTION
**Pull request by sirredbeard**
https://github.com/sirredbeard/Awesome-WSL

**[Insert URL to the list here]**

https://github.com/sirredbeard/Awesome-WSL

**[Explain what this list is about and why it should be included here]**

This list is about Windows Subsystem for Linux. It includes the best choices for getting started with WSL and advanced tools. WSL popularity is growing.

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

## Requirements for your pull request

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title.<br>For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
	- Be added at the bottom of the appropriate category.
- The list I'm submitting complies with these requirements:

## Requirements for your Awesome list

- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
- It's the result of hard work and the best I could possibly produce.
- Non-generated Markdown file in a GitHub repo.
- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
- Not a duplicate.
- Only has awesome items. Awesome lists are curations of the best, not everything.
- Includes a project logo/illustration whenever possible.
	- Either fullwidth or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
	- The image should link to the project website or any relevant website.
	- The image should be high-DPI. Set it to maximum half the width of the original image.
- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
	- Should be placed on the right side of the readme heading.
	- Should link back to this list.
- Has a Table of Contents section.
	- Should be named `Contents`, not `Table of Contents`.
	- Should be the first section in the list.
	- Should only have one level of sub-lists, preferably none.
- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
	- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
	- [WTFPL](http://www.wtfpl.net) and [Unlicense](http://unlicense.org) are not acceptable licenses.
	- If you use a license badge, it should be SVG, not PNG.
- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
	- The file should be named `contributing.md`. Casing is up to you.
- Has consistent formatting and proper spelling/grammar.
	- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
	- The description starts with an uppercase character and ends with a period.
	- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.

Go to the top and read it again.

### CODE REVIEW

**Comment by sirredbeard** [comment]
@sindresorhus 
I have left some comments on other pending PRs.

@transitive-bullshit 
I am installing npm and awesome-lint to see what it says. Because there may be non-technical users contributing to these, and the project creator wants there to be more non-technical lists, it may be helpful in the future to copy and paste the awesome-lint output. Thanks again.

**Comment by sirredbeard** [comment]
@transitive-bullshit 
I installed awesome-lint and reduced the 100+ errors to a few that I am not sure what to do about:

  README.md:1:1                                                                                                           
✖   1:1   Missing Awesome badge after the main heading   awesome/badge                                                  
✖   6:11  Don’t use literal URLs without angle brackets  no-literal-urls                                                
✖  11:3   Code blocks should be fenced                   code-block-style                                               
✖  16:3   Code blocks should be fenced                   code-block-style                                              
✖  22:3   Code blocks should be fenced                   code-block-style                                                                                                                                                                       5 errors


I have an Awesome badge. I am not using code blocks on those locations. Not sure about literal URL either. Thanks.

**Comment by sindresorhus** [comment]
```
❯ awesome-lint https://github.com/sirredbeard/Awesome-WSL
✖ Linting

  README.md:108:3
  ✖    1:1    Missing License section                                                                                remark-lint:awesome/license
  ✖    1:1    Missing file contributing.md                                                                           remark-lint:awesome/contributing
  ✖    1:1    Missing Awesome badge after the main heading                                                           remark-lint:awesome/badge
  ✖   15:1    ToC item "Supported WSL Distributions" does not match corresponding heading "Supported Distributions"  remark-lint:awesome/toc
  ✖   63:128  List item link and description must be separated with a dash                                           remark-lint:awesome/list-item
  ✖   64:102  List item link and description must be separated with a dash                                           remark-lint:awesome/list-item
  ✖   65:88   List item link and description must be separated with a dash                                           remark-lint:awesome/list-item
  ✖   66:126  List item link and description must be separated with a dash                                           remark-lint:awesome/list-item
  ✖   67:136  List item link and description must be separated with a dash                                           remark-lint:awesome/list-item
  ✖   68:82   List item link and description must be separated with a dash                                           remark-lint:awesome/list-item
  ✖   69:98   List item link and description must be separated with a dash                                           remark-lint:awesome/list-item
  ✖   70:86   List item link and description must be separated with a dash                                           remark-lint:awesome/list-item
  ✖   71:85   List item link and description must be separated with a dash                                           remark-lint:awesome/list-item
  ✖   77:198  List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖   93:118  List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖   95:89   List item link and description must be separated with a dash                                           remark-lint:awesome/list-item
  ✖  103:136  List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  106:173  List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  107:143  List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  108:3    Link to http://jessicadeen.com/tech/badass-terminal-wsl-macos-and-ubuntu-dotfiles-update/ is dead      remark-lint:no-dead-urls
  ✖  119:123  List item link and description must be separated with a dash                                           remark-lint:awesome/list-item
  ✖  120:183  List item link and description must be separated with a dash                                           remark-lint:awesome/list-item
  ✖  128:174  Link to https://www.linuxfoundation.org/blog/7-steps-to-start-your-linux-sysadmin-career/ is dead      remark-lint:no-dead-urls
  ✖  143:79   List item link and description must be separated with a dash                                           remark-lint:awesome/list-item
  ✖  144:79   List item link and description must be separated with a dash                                           remark-lint:awesome/list-item
  ✖  145:78   List item link and description must be separated with a dash                                           remark-lint:awesome/list-item
  ✖  146:76   List item link and description must be separated with a dash                                           remark-lint:awesome/list-item
  ✖  153:79   List item link and description must be separated with a dash                                           remark-lint:awesome/list-item
  ✖  154:75   List item link and description must be separated with a dash                                           remark-lint:awesome/list-item
  ✖  155:89   List item link and description must be separated with a dash                                           remark-lint:awesome/list-item
  ✖  156:98   List item link and description must be separated with a dash                                           remark-lint:awesome/list-item
  ✖  162:79   List item link and description must be separated with a dash                                           remark-lint:awesome/list-item
  ✖  163:79   List item link and description must be separated with a dash                                           remark-lint:awesome/list-item
  ✖  164:145  List item link and description must be separated with a dash                                           remark-lint:awesome/list-item
  ✖  165:136  List item link and description must be separated with a dash                                           remark-lint:awesome/list-item
  ✖  166:95   List item link and description must be separated with a dash                                           remark-lint:awesome/list-item
  ✖  172:79   List item link and description must be separated with a dash                                           remark-lint:awesome/list-item
  ✖  173:86   List item link and description must be separated with a dash                                           remark-lint:awesome/list-item
  ✖  183:85   List item link and description must be separated with a dash                                           remark-lint:awesome/list-item
  ✖  190:63   List item link and description must be separated with a dash                                           remark-lint:awesome/list-item
  ✖  198:71   List item link and description must be separated with a dash                                           remark-lint:awesome/list-item
  ✖  205:135  List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  206:66   List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  207:67   List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  209:205  List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  210:114  List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  211:281  List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  228:78   List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  229:128  List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  230:86   List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  233:170  List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  234:70   List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  239:107  List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  240:213  List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  241:87   List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  245:109  List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  246:158  List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  247:110  List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  248:111  List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  249:161  List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  250:188  List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  254:171  List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  259:250  List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  260:140  List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  261:90   List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  262:164  List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  263:125  List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  264:232  List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  265:191  List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  272:144  List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  276:86   List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  280:75   List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  287:77   List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  288:134  List item description must end with proper punctuation                                                 remark-lint:awesome/list-item
  ✖  308:572  Link to https://www.linkedin.com/in/russalex is dead                                                   remark-lint:no-dead-urls
  ✖  309:38   List item link and description must be separated with a dash                                           remark-lint:awesome/list-item

  76 errors
```
https://github.com/sindresorhus/awesome-lint

**Comment by sindresorhus** [comment]
> ✖ 1:1 Missing Awesome badge after the main heading awesome/badge

This is clearly defined in the guidelines:

> Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
**Should be placed on the right side of the readme heading.**

**Comment by sindresorhus** [comment]
The sublists in the `Contents` sections are using incorrect formatting. (Notice how GitHub doesn't render them as props list items)

**Comment by sindresorhus** [comment]
> * **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)

**Comment by sindresorhus** [comment]
The https://raw.githubusercontent.com/sirredbeard/Awesome-WSL/master/github-icon.png icon is blurry on retina screens.

**Comment by sindresorhus** [comment]
> Awesome Command Line Apps Awesome github project

Don't include the awesome badge in this item description. It's just noise.

**Comment by sindresorhus** [comment]
Closing for lack of response.

**Pull request closed without merging**
