### PR TITLE
Add Building Blocks for Web Apps

### PR DESCRIPTION
**Pull request by thisismydesign**
Reopened from https://github.com/sindresorhus/awesome/pull/1789 (PR to `master`)

https://github.com/componently-com/awesome-building-blocks-for-web-apps

Standalone features to be integrated into web applications. It should be included because it's awesome not having to code the same functionality over and over again.

### By submitting this pull request I confirm I've read and complied with the requirements 🖖

### CODE REVIEW

**Comment by thisismydesign** [comment]
Reopened from https://github.com/sindresorhus/awesome/pull/1789

Lint: https://github.com/componently-com/awesome-building-blocks-for-web/runs/740112407#step:4:1

Reviewed PRs:
- https://github.com/sindresorhus/awesome/pull/1787#pullrequestreview-424728426
- https://github.com/sindresorhus/awesome/pull/1788#pullrequestreview-424722941

**Comment by thisismydesign** [comment]
unicorn

**Comment by sindresorhus** [comment]
I feel like the list is too much of an ad for Componently right now. It's fine to link to Componently of course, but I think it should be made clear what it is. For example, I don't think the repo link should be to Componently as it's not the website for the list itself.

**Comment by sindresorhus** [comment]
The descriptions for items needs more work. It's not good enough that it's just copy-pasted from a project's repo. Many projects have bad descriptions/taglines. I saw both typos and titlecased descriptions just from a quick look.

**Comment by sindresorhus** [comment]
Some examples of not useful descriptions:

- Grow your business with honest marketing.
- Ship faster and prove value with less risk.

And remove words like easy/simple/beautiful. They are overused words.

**Comment by thisismydesign** [comment]
Thanks for the feedback. Removed the link from the repo description, will review item descriptions.

**Comment by dbartholomae** [comment]
@sindresorhus  The descriptions are now also updated to be more helpful. Anything else you would change? :)

**Comment by sindresorhus** [comment]
> componently.com is a marketplace where developers can search, compare and integrate web application building blocks.

This still feels like an ad. Try to make it more relevant. Something like this:

> By the way, if you like web building blocks, you'll love componently.com, which [(how it solves the problem of building blocks) blah blah...].

---

> Curated list of standalone features to be integrated into web applications.

I'd like to see a more verbose description that describes why building blocks (components) are awesome and what problem they solve.

**Comment by sindresorhus** [comment]
Tweet: https://twitter.com/awesome__re/status/1274245557297397760

**Comment by dbartholomae** [comment]
> This still feels like an ad. Try to make it more relevant. Something like this:
> 
> > By the way, if you like web building blocks, you'll love componently.com, which [(how it solves the problem of building blocks) blah blah...].
> 
> I'd like to see a more verbose description that describes why building blocks (components) are awesome and what problem they solve.

Both very good points! I've edited the list around it :)

**Pull request merged**
