### PR TITLE
Add OpenResty

### PR DESCRIPTION
**Pull request by bungle**
Here is one addition to this list:
- [OpenResty](https://github.com/bungle/awesome-resty)

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please read and adhere to the [contributing guidelines](../blob/master/contributing.md).

**Comment by bungle** [comment]
[x] Search previous suggestions before making a new one, as yours may be a duplicate.
[x] Make sure the list is useful before submitting. That implies it has enough content and every item has a good succinct description.
[x] Make an individual pull request for each suggestion.
[x] Use title-casing (AP style).
[x] Use the following format: [List Name](link)
[ ] Link additions should be added to the bottom of the relevant category. NOTE: this is closely related to Nginx, so it is better to be close to Nginx
[ ] New categories or improvements to the existing categorization are welcome. NOTE: fits fine on the category
[x] Check your spelling and grammar.
[x] Make sure your text editor is set to remove trailing whitespace.
[x] The pull request and commit should have a useful title.
[x] The body of your commit message should contain a link to the repository. NOTE: just edited.

**Comment by sindresorhus** [comment]
Some feedback:

- No point in mentioning the repo name in the description.
- Would be nice to have a one or two sentence description of what OpenResty is at the top of the readme.
- Section, `Contents` => `Table of Contents`
- End all descriptions in a `.`
- Needs a contributing.md file. Example: https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md

**Comment by bungle** [comment]
1. No point in mentioning the repo name in the description.

There is a point. People might do `find` on page to search if their lib is already included.

I will add a description, although it is quite obvious, as there are links at the top of the page to official documentation. I'm not sure it is grammatically correct to end everything with dot on such lists. There is already instructions on the page itself about the contributing, but I can add another page as well, but doesn't seem to make sense to me: https://github.com/bungle/awesome-resty#how-to-contribute-on-this-list

**Comment by sindresorhus** [comment]
> No point in mentioning the repo name in the description.

I mean the main readme description. Not each item. This one:

> awesome-resty is a list of OpenResty / Nginx modules, Lua libraries, and related resources.

**Comment by bungle** [comment]
Ah, ok... I will correct it.

**Comment by bungle** [comment]
`awesome-resty` removed from description. Added "What is OpenResty" section.

**Comment by sindresorhus** [comment]
ping :)

**Comment by bungle** [comment]
Pong,

Changed Contents => Table of Contents.

What else do I need to do? I mean, I'm not sure if it worth my time to spend hours on this to adjust _MY_ list to your liking only to add OpenResty to your list.

**Comment by sindresorhus** [comment]
> Changed Contents => Table of Contents. (I really dislike having "Table of" there, everyone sees it is a "table", infact it isn't even a table).

Good point. Just wanted it for consistency, but `Contents` works too.

**Comment by sindresorhus** [comment]
> I'm not sure if it worth my time to spend hours on this to adjust MY list to your liking only to add OpenResty (one word) to your list.

Don't then.

**Comment by bungle** [comment]
Okay, fair, you didn't even tell me what's still missing.

**Pull request closed without merging**
