### PR TITLE
feat: action lint double link in readme

### PR DESCRIPTION
**Pull request by Scrum**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you fill out the PR description field?

**Comment by Scrum** [comment]
> Can you fill out the PR description field?

My request does not belong to the `awesome` list, it adds `github action` which checks PR for duplication of links in yours `readme.md`

**Comment by sindresorhus** [comment]
I said "field", not "template", as in just writing a description of the PR as it was not immediately clear what it was about. A PR description field should rarely be blank.

**Comment by sindresorhus** [comment]
This looks useful, but I think it would be better to integrate the check into `awesome-lint` instead and then get https://github.com/sindresorhus/awesome/pull/1794 done.

Ideally, the check would be a [`remark-lint`](https://github.com/remarkjs/remark-lint), so the Markdown doesn't have to be parsed multiple times.

**Comment by Scrum** [comment]
@sindresorhus First step is done https://github.com/remarkjs/remark-lint/pull/241

**Pull request closed without merging**
