### PR TITLE
Add Chess

### PR DESCRIPTION
**Pull request by hkirat**
Adding awesome chess, list of chess related links.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Use proper titles for entries, rather than `BOT 1`, `talk 1`, etc.

**Comment by hkirat** [comment]
Done!
Any other suggestion would be most valuable.

**Comment by sindresorhus** [comment]
From the awesome manifest:

> Creative Commons licenses are perfect for this purpose. We would recommend CC0. **Code licenses like MIT, BSD, GPL, and so forth are not recommended.**

**Comment by sindresorhus** [comment]
Added.

**Comment by hkirat** [comment]
Thanks!
Modified the Licence.

**Pull request closed without merging**
