### PR TITLE
Add MLonCode

### PR DESCRIPTION
**Pull request by vmarkovtsev**
**https://github.com/src-d/awesome-machine-learning-on-source-code**

Machine Learning on Source Code is a subdomain of Machine Learning which studies source code and related things like GitHub mining. Besides, it intersects with general AI problems. This field is young yet many people are interested. E.g. https://github.com/Jason-Rev/vscode-spell-checker/issues/207#issuecomment-386121516

The main contribution is the curated, classified list of research papers which were carefully read by the researchers.
The link is included in https://github.com/collections/machine-learning

I have carefully studied the requirements below and state that my awesome list conforms to them↴

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

## Requirements for your pull request

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title.<br>For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
	- Be added at the bottom of the appropriate category.
- The list I'm submitting complies with these requirements:

## Requirements for your Awesome list

- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
- It's the result of hard work and the best I could possibly produce.
- Non-generated Markdown file in a GitHub repo.
- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
- Not a duplicate.
- Only has awesome items. Awesome lists are curations of the best, not everything.
- Includes a project logo/illustration whenever possible.
	- Either fullwidth or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
	- The image should link to the project website or any relevant website.
	- The image should be high-DPI. Set it to maximum half the width of the original image.
- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
	- Should be placed on the right side of the readme heading.
	- Should link back to this list.
- Has a Table of Contents section.
	- Should be named `Contents`, not `Table of Contents`.
	- Should be the first section in the list.
	- Should only have one level of sub-lists, preferably none.
- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
	- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
	- [WTFPL](http://www.wtfpl.net) and [Unlicense](http://unlicense.org) are not acceptable licenses.
	- If you use a license badge, it should be SVG, not PNG.
- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
	- The file should be named `contributing.md`. Casing is up to you.
- Has consistent formatting and proper spelling/grammar.
	- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
	- The description starts with an uppercase character and ends with a period.
	- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.

Go to the top and read it again.

### CODE REVIEW

**Comment by marnovo** [comment]
Hi @sindresorhus, since this checks the requirements it should be good to go, no?

**Comment by legodude17** [comment]
> Entries have a description, unless the title is descriptive enough by itself. It rarely is though.

Not done

**Comment by vmarkovtsev** [comment]
@legodude17 Thanks, fixed.

@sindresorhus Anything else missed?

**Comment by legodude17** [comment]
I meant the descriptions of entries in your list.

**Comment by vmarkovtsev** [comment]
Oops haha. All right.

@marnovo This will take us ages. Better to close the PR, what do you think?

**Comment by marnovo** [comment]
@legodude17 thanks for clarifying!

Given the requirement:

> - Entries have a description, unless the title is descriptive enough by itself. It rarely is though.

The [Awesome Machine Learning on Source Code](https://github.com/src-d/awesome-machine-learning-on-source-code) list consists of mostly conferences, academic papers, blog posts, talks, and tools/libraries:

- The entries for conferences, papers, blog posts and talks very self-explanative titles; in a way, by design.
- The entries for tools/libraries have careful detailed descriptions along the title.
- The very few entries I can see missing a descriptive title/description are [now fixed by this PR](https://github.com/src-d/awesome-machine-learning-on-source-code/pull/69).

**Comment by marnovo** [comment]
@sindresorhus / @legodude17 just following up on this given the update above. Thanks.

**Comment by sindresorhus** [comment]
Hey, sorry for the lack of response, please see #1363.

**Comment by myshov** [comment]
Hi, Vadim! There is linter for awesome lists https://github.com/sindresorhus/awesome-lint. Here is its output: https://gist.github.com/myshov/bb9e5e14f4bbd852318e12347c1591eb

**Comment by myshov** [comment]
There are other issues also:

-----
> Has a Table of Contents section.
> Should only have one level of sub-lists, preferably none.

In your case, you use a spoiler, but you'll get two level of sub-lists eventually :)

-----
You have to add descriptions to items in this sections:
https://github.com/src-d/awesome-machine-learning-on-source-code#posts
https://github.com/src-d/awesome-machine-learning-on-source-code#talks

**Comment by sindresorhus** [comment]
Closing for lack of response.

**Comment by sindresorhus** [comment]
// @m09 @EgorBu

**Comment by m09** [comment]
Thanks for the notice. I tried to estimate how much work it would take to comply to your set of rules and it won't be feasible for us (it would require too much effort).

**Pull request closed without merging**
