### PR TITLE
Add MicroPython

### PR DESCRIPTION
**Pull request by mcauser**
https://github.com/mcauser/awesome-micropython/

Libraries, frameworks, tools and resources for MicroPython running on microcontrollers.

By submitting this pull request I confirm I've read and complied with the below requirements 🖖

`awesome-lint` passed without error, except for false positives `no-dead-urls`.
I hit each failing url independently and confirm they are not 404ing.

PRs reviewed: #1775, #1760, #1720, #1699

### CODE REVIEW

**Comment by mcauser** [comment]
unicorn

**Comment by sindresorhus** [comment]
I think you should drop the text heading `Awesome MicroPython` as it's only shown in the header image. Looks weird to have both.

**Comment by mcauser** [comment]
I put it up there to follow your contrib guidelines.
Can roll it back so just the badge is below the header image

**Comment by mcauser** [comment]
Hi @sindresorhus thanks for the feedback.
Updated: https://github.com/mcauser/awesome-micropython

**Comment by sindresorhus** [comment]
Tweet: https://twitter.com/awesome__re/status/1261945320008593409

**Pull request merged**
