### PR TITLE
Add Awesome OS X Command Line

### PR DESCRIPTION
**Pull request by herrbischoff**
Hopefully this is in the correct category. Let me know if you want it changed or even a new one.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please read the [instructions](https://github.com/sindresorhus/awesome/blob/master/create-list.md) for creating a new list, [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

Especially this part:

> Wait at least a couple of weeks after creating a list before submitting to give it a chance to mature.

Ping me here in a few weeks and I'll reopen ;)

-

The list will also need more contents before being accepted.

**Comment by herrbischoff** [comment]
Alright, will do! Thanks for your comment.

**Comment by herrbischoff** [comment]
@sindresorhus: I'd like you to check my submission again. Maybe now it's ready to be included. ;)

**Comment by sindresorhus** [comment]
Looks good now. Nice work :)

**Comment by herrbischoff** [comment]
Thanks, I'm continually adding more useful content as I come along it. Should you have any OS X command line tricks up your sleeve, feel free to let me know. :)

**Comment by sindresorhus** [comment]
Lots of good ones in https://github.com/mathiasbynens/dotfiles/blob/master/.osx and https://github.com/mathiasbynens/dotfiles/blob/master/.aliases ;)

**Pull request closed without merging**
