### PR TITLE
Add Static Analysis & Code Quality

### PR DESCRIPTION
**Pull request by mre**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please read the [instructions](https://github.com/sindresorhus/awesome/blob/master/create-list.md) for creating a new list, [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

Especially this part:

> Wait at least a couple of weeks after creating a list before submitting to give it a chance to mature.

Ping me here in a few weeks and I'll reopen ;)

**Comment by sindresorhus** [comment]
`Javascript` => `JavaScript`

**Comment by mre** [comment]
Hi. Maybe you can have another look at this pull request. I think the list is quite mature quite now. :-)

**Comment by sindresorhus** [comment]
Added :)

Would be awesome if you could add the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) to your readme :D

**Comment by mre** [comment]
Sure. :-) Added the badge. And thanks for merging!

**Pull request closed without merging**
