### PR TITLE
Add CSS Frameworks

### PR DESCRIPTION
**Pull request by troxler**
https://github.com/troxler/awesome-css-frameworks

The repository is a collection of CSS frameworks (e.g. from CSS resets to complete general purpose frameworks like Bootstrap). The collection is categorized and sorted by the number of GitHub stars. Each project has a description and links to a demo, documentation, and repository (if applicable). The goal of the collection is to provide a suitable styling for different web projects and to show the diversity of such frameworks.

# By submitting this pull request I confirm I've read and complied with the below requirements.

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title.<br>For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
	- Be added at the bottom of the appropriate category.
- The list I'm submitting complies with these requirements:
	- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
	- It's the result of hard work and the best I could possibly produce.
	- Non-generated Markdown file in a GitHub repo.
	- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
	- Not a duplicate.
	- Only has awesome items. Awesome lists are curations of the best, not everything.
	- Includes a project logo/illustration whenever possible.
		- Either fullwidth or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
		- The image should link to the project website or any relevant website.
		- The image should be high-DPI. Set it to maximum half the width of the original image.
	- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
	- Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
		- Should be placed on the right side of the readme heading.
		- Should link back to this list.
	- Has a Table of Contents section.
		- Should be named `Contents`, not `Table of Contents`.
		- Should be the first section in the list.
		- Should only have one level of sub-lists, preferably none.
	- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
		- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
		- If you use a license badge, it should be SVG, not PNG.
	- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
		- The file should be named `contributing.md`. Casing is up to you.
	- Has consistent formatting and proper spelling/grammar.
		- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
		- The description starts with an uppercase character and ends with a period.
		- Drop all the `A` / `An` prefixes in the descriptions.
		- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
	- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.
- Go to the top and read it again.

### CODE REVIEW

**Comment by vitalkanev** [comment]
> Has contribution guidelines.
> The file should be named contributing.md. Casing is up to you.

**Comment by troxler** [comment]
@vitalkanev See here https://github.com/troxler/awesome-css-frameworks/blob/master/.github/CONTRIBUTING.md

**Comment by troxler** [comment]
Ping @sindresorhus

**Comment by legodude17** [comment]
Is there any benefit to putting it in `.github` over the root?

**Comment by troxler** [comment]
@legodude17 It is mostly about avoiding clutter in the root directory (e.g. see [here](https://blog.github.com/2016-02-17-issue-and-pull-request-templates/)). In this case, it does not really matter yet as there is only one file in the directory. But I might add more templates in the future.

**Comment by sindresorhus** [comment]
Hey, sorry for the lack of response, please see #1363.

**Comment by troxler** [comment]
@sindresorhus I just removed the awesome badge from the list. I can re-add it should you ever actually consider to merge this PR.

**Comment by sindresorhus** [comment]
```
❯ awesome-lint https://github.com/troxler/awesome-css-frameworks
✖ Linting

  readme.md:71:3
  ✖    1:1  Missing Awesome badge after the main heading                remark-lint:awesome/badge
  ✖    1:1  Missing file contributing.md                                remark-lint:awesome/contributing
  ✖    1:1  Missing License section                                     remark-lint:awesome/license
  ✖    1:1  Missing or invalid Table of Contents                        remark-lint:awesome/toc
  ✖    8:3  Invalid list item link URL                                  remark-lint:awesome/list-item
  ✖    9:3  Invalid list item link URL                                  remark-lint:awesome/list-item
  ✖   10:3  Invalid list item link URL                                  remark-lint:awesome/list-item
  ✖   11:3  Invalid list item link URL                                  remark-lint:awesome/list-item
  ✖   12:3  Invalid list item link URL                                  remark-lint:awesome/list-item
  ✖   13:3  Invalid list item link URL                                  remark-lint:awesome/list-item
  ✖   14:3  Invalid list item link URL                                  remark-lint:awesome/list-item
  ✖   19:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖   24:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖   29:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖   34:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖   39:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖   49:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖   56:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖   62:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖   69:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖   71:3  Link to http://minicss.org/modules is dead                  remark-lint:no-dead-urls
  ✖   75:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖   81:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖   86:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖   92:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖   97:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  103:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  111:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  119:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  126:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  133:3  Link to http://foundation.zurb.com is dead                  remark-lint:no-dead-urls
  ✖  133:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  135:3  Link to http://zurb.com/responsive is dead                  remark-lint:no-dead-urls
  ✖  136:3  Link to http://foundation.zurb.com/sites/docs/ is dead      remark-lint:no-dead-urls
  ✖  140:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  147:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  153:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  155:3  Link to http://primercss.io/scaffolding/ is dead            remark-lint:no-dead-urls
  ✖  159:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  166:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  173:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  175:3  Link to http://getbase.org/docs/ is dead                    remark-lint:no-dead-urls
  ✖  179:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  185:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  187:3  Link to http://turretcss.com/docs/demo/ is dead             remark-lint:no-dead-urls
  ✖  188:3  Link to http://turretcss.com/docs/getting-started/ is dead  remark-lint:no-dead-urls
  ✖  192:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  201:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  208:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  215:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  221:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  230:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  236:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  242:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  248:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  253:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  265:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  272:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  288:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  294:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  300:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  305:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  309:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  313:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  319:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  323:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  327:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  333:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  339:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  345:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  349:4  Invalid list item link                                      remark-lint:awesome/list-item
  ✖  355:4  Invalid list item link                                      remark-lint:awesome/list-item

  72 errors
```

https://github.com/sindresorhus/awesome-lint

**Comment by sindresorhus** [comment]
The Awesome badge is required.

**Comment by troxler** [comment]
@sindresorhus Fixed all those remarks.

**Comment by sindresorhus** [comment]
Tweet: https://twitter.com/awesome__re/status/1100633612959997952

**Comment by troxler** [comment]
Thanks :)

**Pull request merged**
