### PR TITLE
Add Q#

### PR DESCRIPTION
**Pull request by ebraminio**
https://github.com/ebraminio/awesome-qsharp

Brand new domain specific language just released recently by Microsoft, expected to become popular

Created just for getting feedback to know whether this has any chance ever to be here, <s>the below conditions are not just have met yet, that's why I am closing the PR just on its creation and will open it when below is done but waiting for feedback in the meanwhile.</s> (updated and reopened in 2019)

----

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title.<br>For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
	- Be added at the bottom of the appropriate category.
- The list I'm submitting complies with these requirements:
	- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
	- It's the result of hard work and the best I could possibly produce.
	- Non-generated Markdown file in a GitHub repo.
	- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
	- Not a duplicate.
	- Only has awesome items. Awesome lists are curations of the best, not everything.
	- Includes a project logo/illustration whenever possible.
		- Either fullwidth or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
		- The image should link to the project website or any relevant website.
		- The image should be high-DPI. Set it to maximum half the width of the original image.
	- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
	- Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
		- Should be placed on the right side of the readme heading.
		- Should link back to this list.
	- Has a Table of Contents section.
		- Should be named `Contents`, not `Table of Contents`.
		- Should be the first section in the list.
		- Should only have one level of sub-lists, preferably none.
	- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
		- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
		- [WTFPL](http://www.wtfpl.net) and [Unlicense](http://unlicense.org) are not acceptable licenses.
		- If you use a license badge, it should be SVG, not PNG.
	- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
		- The file should be named `contributing.md`. Casing is up to you.
	- Has consistent formatting and proper spelling/grammar.
		- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
		- The description starts with an uppercase character and ends with a period.
		- Drop all the `A` / `An` prefixes in the descriptions.
		- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
	- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.
- Go to the top and read it again.

### CODE REVIEW

**Comment by ebraminio** [comment]
Hey there. Please have a look now. The project has all the conditions mentioned in https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md except "Includes a project logo/illustration whenever possible." which Wikipedia also don't so I think can be forgiven for now and license https://github.com/ebraminio/awesome-qsharp/pull/4 which @tcNickolas should accept it. Thanks :)

**Comment by ebraminio** [comment]
Removed merge extra artifacts I was unaware of and in order to make sure this will be seen, due to oldness of the PR (which I had kept it closed) I am pinging @sindresorhus also. Sorry for the trouble and thanks!

**Comment by sindresorhus** [comment]
There are still things remaining, like:

> The description starts with an uppercase character and **ends with a period.**

Please go through the list point for point.

**Comment by sindresorhus** [comment]
```
❯ awesome-lint https://github.com/ebraminio/awesome-qsharp
✖ Linting

  README.md:20:1
  ✖   1:1    Missing Awesome badge after the main heading                                          awesome/badge
  ✖   1:1    Missing License section                                                               awesome/license
  ✖  17:1    ToC item "Blogs" does not match corresponding heading "Demos and Samples"             awesome/toc
  ✖  20:1    Marker style should be -                                                              unordered-list-marker-style
  ✖  21:1    Marker style should be -                                                              unordered-list-marker-style
  ✖  22:1    Marker style should be -                                                              unordered-list-marker-style
  ✖  23:1    Marker style should be -                                                              unordered-list-marker-style
  ✖  23:79   List item link and description must be separated with a dash                          awesome/list-item
  ✖  25:1    Marker style should be -                                                              unordered-list-marker-style
  ✖  26:1    Marker style should be -                                                              unordered-list-marker-style
  ✖  29:1    Marker style should be -                                                              unordered-list-marker-style
  ✖  29:62   List item description must end with proper punctuation                                awesome/list-item
  ✖  30:1    Marker style should be -                                                              unordered-list-marker-style
  ✖  30:89   List item description must end with proper punctuation                                awesome/list-item
  ✖  31:1    Marker style should be -                                                              unordered-list-marker-style
  ✖  31:73   List item description must end with proper punctuation                                awesome/list-item
  ✖  34:1    Marker style should be -                                                              unordered-list-marker-style
  ✖  34:91   List item link and description must be separated with a dash                          awesome/list-item
  ✖  35:1    Marker style should be -                                                              unordered-list-marker-style
  ✖  35:111  List item link and description must be separated with a dash                          awesome/list-item
  ✖  36:1    Marker style should be -                                                              unordered-list-marker-style
  ✖  36:132  List item link and description must be separated with a dash                          awesome/list-item
  ✖  37:1    Marker style should be -                                                              unordered-list-marker-style
  ✖  37:106  List item link and description must be separated with a dash                          awesome/list-item
  ✖  40:1    Marker style should be -                                                              unordered-list-marker-style
  ✖  40:83   List item link and description must be separated with a dash                          awesome/list-item
  ✖  41:1    Marker style should be -                                                              unordered-list-marker-style
  ✖  42:1    Marker style should be -                                                              unordered-list-marker-style
  ✖  43:1    Marker style should be -                                                              unordered-list-marker-style
  ✖  44:1    Marker style should be -                                                              unordered-list-marker-style
  ✖  47:1    Marker style should be -                                                              unordered-list-marker-style
  ✖  48:1    Marker style should be -                                                              unordered-list-marker-style
  ✖  49:1    Marker style should be -                                                              unordered-list-marker-style
  ✖  50:1    Marker style should be -                                                              unordered-list-marker-style
  ✖  53:1    Marker style should be -                                                              unordered-list-marker-style
  ✖  54:1    Marker style should be -                                                              unordered-list-marker-style
  ✖  55:1    Marker style should be -                                                              unordered-list-marker-style
  ✖  56:1    Marker style should be -                                                              unordered-list-marker-style
  ✖  57:1    Marker style should be -                                                              unordered-list-marker-style
  ✖  60:1    Marker style should be -                                                              unordered-list-marker-style
  ✖  60:75   List item description must end with proper punctuation                                awesome/list-item
  ✖  61:1    Marker style should be -                                                              unordered-list-marker-style
  ✖  61:110  List item description must end with proper punctuation                                awesome/list-item
  ✖  62:1    Marker style should be -                                                              unordered-list-marker-style
  ✖  63:1    Marker style should be -                                                              unordered-list-marker-style
  ✖  63:57   Link to https://github.com/elbruno/Blog/search?utf8=✓&q=extension%3Aqs&type= is dead  no-dead-urls
```

https://github.com/sindresorhus/awesome-lint

**Comment by ebraminio** [comment]
Interesting tool! Installed it and fixed most of the reported issues,

```
  ✖   1:1    Missing file contributing.md                                 awesome/contributing
  ✖   1:1    Missing License section                                      awesome/license
```

First one is just about the casing I think and the second will be resolved soon I guess.

**Comment by ebraminio** [comment]
Hey there copyright issue is also resolved and this may is ready to have. Thanks!

**Comment by ebraminio** [comment]
Hey there. No other blocking things I guess, right?

**Comment by ebraminio** [comment]
Friend ping, or, even ping pong :)

**Comment by samber** [comment]
Hey!

To improve quality of awesome lists, Sindresorhus made a simple linter.
You can embed it into a Travis CI pipeline easily: https://github.com/sindresorhus/awesome-lint

###### package.json

```json
{
	"scripts": {
		"test": "awesome-lint"
	},
	"devDependencies": {
		"awesome-lint": "*"
	}
}
```

###### .travis.yml

```
language: node_js
node_js:
  - 'node'
```

**Comment by ebraminio** [comment]
Done. https://travis-ci.org/ebraminio/awesome-qsharp/builds/491872621

**Comment by sindresorhus** [comment]
`Q#` in `Q# is a domain-specific programming language used for expressing` should be linkified to the official website.

**Comment by sindresorhus** [comment]
Tweet: https://twitter.com/awesome__re/status/1100254078695747586

**Comment by ebraminio** [comment]
Thank you! :)

**Comment by ebraminio** [comment]
> `Q#` in `Q# is a domain-specific programming language used for expressing` should be linkified to the official website.

Done https://github.com/ebraminio/awesome-qsharp/commit/0086b8da743cfab7dc61aa0730a095c3d6453fe3

**Pull request merged**
