### PR TITLE
add IoT

### PR DESCRIPTION
**Pull request by phodal**

### CODE REVIEW

**Comment by appleboy** [comment]
nice :+1:

**Comment by sindresorhus** [comment]
Good idea, but the list needs a lot of work. When I first landed on your repo I had no idea what it was about. I clicked English, and I got presented with a lot of random info, but still no idea what exactly the list is supposed to be about. It seems like some kind of collection of IoT tools, but I can't be sure. The link should also go directly to the English version.

Please read:
https://github.com/sindresorhus/awesome/blob/master/contributing.md
https://github.com/sindresorhus/awesome/blob/master/awesome.md

Ping me here in a few weeks when you've worked on improving it and I'll reconsider ;)

**Comment by phodal** [comment]
@sindresorhus  would you like to check it again?

**Comment by sindresorhus** [comment]
I think the list still needs a lot of work:

- Don't mix English and Chinese. That's just distracting.
- Explain what IoT is and what the the purpose of the list is, at the top.
- Don't use numbered lists, use bullets `- `.
- Many items are missing descriptions
- The item formatting is weird. Use this instead: `[Name]() - Description.`
- Add a [TOC](https://en.wikipedia.org/wiki/Table_of_contents) at the top for the top-level sections.

You clearly didn't read the links I provided in my previous comment, as the list is still missing a license and contributing.md.

Awesome lists are expected to have high-standards as they're, you know, awesome. 

Ping me in a month and I'll reconsider again.

**Comment by phodal** [comment]
@sindresorhus Ping you again~~

**Comment by aleksandar-todorovic** [comment]
I still don't see any license. I still don't see any info about what the list is trying to do. But what I do see is inconsistency (`iot`, `IoT`, `IOT`) and misspells (`inlucde`, `Frameworki` etc.

Not even worth re-opening.

**Comment by phodal** [comment]
@aleksandar-todorovic Thanks for Suggestion

**Pull request closed without merging**
