### PR TITLE
Add Code Review

### PR DESCRIPTION
**Pull request by joho**
https://github.com/joho/awesome-code-review

List of code review tools, books, papers, talks etc. Code review is a very common engineering practice and there are lot of interesting resources going back ~40 years and new talks and tools coming out all the time.

# By submitting this pull request I confirm I've read and complied with the below requirements.

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title.<br>For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should:
	- [x] Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
	- [x] Be added at the bottom of the appropriate category.
- The list I'm submitting complies with these requirements:
	- [x] **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
	- [x] It's the result of hard work and the best I could possibly produce.
	- [x] Non-generated Markdown file in a GitHub repo.
	- [x] **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- [x] The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
	- [x] Not a duplicate.
	- [x] Only has awesome items. Awesome lists are curations of the best, not everything.
	- [x] Includes a project logo/illustration whenever possible.
		- Either fullwidth or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
		- The image should link to the project website or any relevant website.
		- The image should be high-DPI. Set it to maximum half the width of the original image.
	- [x] Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
	- [x] Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
		- Should be placed on the right side of the readme heading.
		- Should link back to this list.
	- [x] Has a Table of Contents section.
		- Should be named `Contents`, not `Table of Contents`.
		- Should be the first section in the list.
		- Should only have one level of sub-lists, preferably none.
	- [x] Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
		- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
		- [WTFPL](http://www.wtfpl.net) and [Unlicense](http://unlicense.org) are not acceptable licenses.
		- If you use a license badge, it should be SVG, not PNG.
	- [x] Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
		- The file should be named `contributing.md`. Casing is up to you.
	- [x] Has consistent formatting and proper spelling/grammar.
		- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
		- The description starts with an uppercase character and ends with a period.
		- Drop all the `A` / `An` prefixes in the descriptions.
		- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
	- [x] Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.
- Go to the top and read it again.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

**Comment by joho** [comment]
Hi @sindresorhus thanks for the speedy reply.

I've converted the list over to checkboxes and ticked the ones I think I'm safely in.
 (if you think i should untick any please let me know). I used the yeoman generator recommended to set the structure so I'd hope the nitty gritty was all right (though I did have to manually change "Table of contents" to "contents" to comply with the list)

That leaves

> Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
(in your list) None of the surrounding entries had descriptions and I believe the title is descriptive enough, if you disagree I'm happy to add it.

>  Includes a project logo/illustration whenever possible.
I can jam something in there if you feel strongly about it but it didn't seem to me a consistent thing in lists I'd read, and doing it just to do it didn't seem high value to me.

>  Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
(in my list) Less than half have descriptions, but I thought I had the balance right here. Happy to hear otherwise

**Comment by joho** [comment]
OK I've updated my awesome list as per the checklist, actually checked off the checklist, and tidied up the commit history on this branch.

Could I request a re-review and a merge please?

**Comment by sindresorhus** [comment]
> Includes a succinct description of the project/theme at the top of the readme. (Example)

This is not done. It should be a description that succinctly describes what a code review is. You could take something from: https://en.m.wikipedia.org/wiki/Code_review Also linkify the word `code review` to the Wikipedia page.

**Comment by joho** [comment]
Fixed in https://github.com/joho/awesome-code-review/commit/6a5fd047927342808007662f3c8c04bfaea6669a

**Comment by sindresorhus** [comment]
I think it would look better as:

> A curated list of tools, articles, books, and any other resource related to code review.

Code review is the systematic examination (sometimes referred to as peer review) of computer source code.

**Pull request merged**
