### PR TITLE
Append `#readme` to all awesome list links

### LINKED ISSUE #1227: Consider appending `#readme` to all awesome lists links
This will jump straight to the `readme` of the awesome list which is the most important part in an awesome list.

Like for example in [node.js awesome list](https://github.com/sindresorhus/awesome-nodejs#readme).

What do you think?

### PR DESCRIPTION
**Pull request by peterhuerlimann**
I appended #readme to every link, where appropriate. 

Fixes #1227

### CODE REVIEW

**Comment by nikitavoloboev** [comment]
I would also change `contributing.md` to add this as a requirement so all new lists added will also have `#readme` prepended to them.

I think it would also be awesome that the awesome badge will link to:
https://github.com/sindresorhus/awesome#readme

Instead of https://github.com/sindresorhus/awesome

I think this change would really be awesome if added. I hope @sindresorhus agrees.

**Comment by peterhuerlimann** [comment]
@nikitavoloboev I have added b4739e9 to reflect proposed changes in `contributing.md`.

**Comment by sstt011** [comment]
@sindresorhus this looks OK to me

**Comment by sindresorhus** [comment]
> It would also be great if awesome.re would link to:
sindresorhus/awesome#readme

Done

**Pull request merged**
