### PR TITLE
Add awesome-gyazo

### PR DESCRIPTION
**Pull request by pastak**
https://github.com/gyazo/awesome-gyazo

### CODE REVIEW

**Comment by kevva** [comment]
A little light on content imo.

**Comment by sindresorhus** [comment]
Please read the [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

**Comment by sindresorhus** [comment]
Light on content and a bit obscure.

**Comment by sindresorhus** [comment]
And it's `Node.js`, not `NodeJS`.

**Comment by sindresorhus** [comment]
Closing this for now. Feel free to ping me here in a few months and I'll reconsider.

**Pull request closed without merging**
