### PR TITLE
add awesome-github

### PR DESCRIPTION
**Pull request by waldyrious**
and group github-related entries under the Developer Environment section

### CODE REVIEW

**Comment by sindresorhus** [comment]
How is this different from GitHub Cheat Sheet?

Also, please read: https://github.com/sindresorhus/awesome/blob/master/contributing.md and https://github.com/sindresorhus/awesome/blob/master/awesome.md

Currently the list is just a list of random links. It needs some context in form of description for each link.

**Comment by waldyrious** [comment]
@Kikobeats can you comment?

**Comment by Kikobeats** [comment]
In the case of awesome-github, I'm trying to collect websites or services that work based in Github data or Github API, and also tools that complement Github workflow.

**Comment by sindresorhus** [comment]
Well, that's definitely not clear from the repo name or description:

> An exquisite list of awesome :octocat: secrets.

Which is exactly what `github-cheat-sheet` is.

**Pull request closed without merging**
