### PR TITLE
added web components awesome list

### PR DESCRIPTION
**Pull request by afonsopacifer**
added web components awesome list and renamed the other web components list.

### CODE REVIEW

**Comment by sindresorhus** [comment]
What's the difference? Not super keen on having two almost identical lists.

**Comment by afonsopacifer** [comment]
Yes, they are almost identical , but I think the two are complementary, eventually one may have a different content from each other , this can be important for anyone who is studying about . I understand your point, it's just a suggestion :D

**Comment by sindresorhus** [comment]
I'm gonna pass on this. Tell the author to instead cooperate with https://github.com/mateusortiz/webcomponents-the-right-way ;)

**Comment by obetomuniz** [comment]
Hmm... no problem @sindresorhus :+1:

**Pull request closed without merging**
