### PR TITLE
Add FastAPI

### PR DESCRIPTION
**Pull request by mjhea0**
https://github.com/mjhea0/awesome-fastapi

The list is about [FastAPI](https://fastapi.tiangolo.com/), a Python-based, async web application framework. It should be included since (1) the isn't already a FastAPI awesome list and (2) FastAPI is a popular framework for Python web app development.

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

### CODE REVIEW

**Comment by mjhea0** [comment]
Reviewed PRs:

1. https://github.com/sindresorhus/awesome/pull/1783#issuecomment-640826981
1. https://github.com/sindresorhus/awesome/pull/1782#issuecomment-640845698

**Comment by mjhea0** [comment]
unicorn

**Comment by mjhea0** [comment]
Lint: https://travis-ci.org/github/mjhea0/awesome-fastapi/builds/698251428#L233

**Comment by sindresorhus** [comment]
The header looks a bit messy with both the logo and the "Awesome FastAPI" title. Either move the logo to the right and make it smaller, or create an image that has the "Awesome" wording above the FastAPI logo and then drop the text heading (many lists do this).

**Comment by sindresorhus** [comment]
> Includes a succinct description of the project/theme at the top of the readme. (Example)

**Comment by sindresorhus** [comment]
Some entries are missing a description.

**Comment by sindresorhus** [comment]
Typescript => TypeScript

**Comment by biesiadamich** [comment]
LGTM. No linter errors. On the top 'Share on Twitter' without image, but maybe it's deliberate action.

**Comment by mjhea0** [comment]
> Some entries are missing a description.

Are you saying that all entries need a description? From the guide it looked like this was subjective and up to me - `Entries have a description, unless the title is descriptive enough by itself`. Is that note the case? If not, I can add descriptions.

**Comment by sindresorhus** [comment]
> Are you saying that all entries need a description? From the guide it looked like this was subjective and up to me - Entries have a description, unless the title is descriptive enough by itself. Is that note the case? If not, I can add descriptions.

All items, unless the title is descriptive enough, which it rarely is.

**Comment by mjhea0** [comment]
Updates:

1. Fixed the header (removed the share on twitter link as well as the FastAPI image)
1. Typescript => TypeScript
1. Add descriptions to all relevant entries

Commit: https://github.com/mjhea0/awesome-fastapi/commit/406f45ada8c506ea970a9b2eb42e6f1feb599c5c
CI Build: https://travis-ci.org/github/mjhea0/awesome-fastapi/builds/703907954

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/awesome/pull/1800#issuecomment-647015239 is not done.

**Comment by mjhea0** [comment]
> [#1800 (comment)](https://github.com/sindresorhus/awesome/pull/1800#issuecomment-647015239) is not done.

"Includes a succinct description of the project/theme at the top of the readme. (Example)"

1. At the very top? Above the "Awesome FastAPI" title?
1. Is "A curated list of awesome things related to FastAPI" not succinct enough?
1. What does `(Example)` mean? Did you mean to add a link to an example?

**Comment by sindresorhus** [comment]
The description should describe what FastAPI is, not what the list contains.

**Comment by sindresorhus** [comment]
> What does (Example) mean? Did you mean to add a link to an example?

It's a copy-paste from: https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md The link is there.

**Comment by mjhea0** [comment]
Just updated with:

FastAPI is a modern, high-performance, batteries-included Python web framework that's perfect for building RESTful APIs.

**Comment by sindresorhus** [comment]
Tweet: v

**Pull request merged**
