### PR TITLE
Add BitShares

### PR DESCRIPTION
**Pull request by ioBanker**
[BitShares](https://github.com/bitshares/awesome-bitshares#readme)

BitShares Blockchain; the first Blockchain As Organization (BAO) and financial technology platform, starting from BitShares first release back in July 19, 2014 focusing on bringing about a beyond Bitcoin financial technology platform. BitShares Blockchain is an industrial-grade decentralized Web 3.0 platform built for high-performance financial technology and smart contracts. It represents the first decentralized autonomous community that lets its BTS core token holders decide on its future direction and products development.

### CODE REVIEW

**Review by 3kh0 — APPROVED** [review]
Looks good!

**Review by lyqht — APPROVED** [review]
LGTM

**Comment by paulbradish** [comment]
This list is missing a license. I also detected a large number of formatting errors when running awesome-lint.

**Review by waleedsadek-panx — CHANGES_REQUESTED** [review]
Great repo! The awesome-lint check, failed. So you need to address the following:

1- Use `_` instead of `**` for bold/strong 
2- Don't use multiple top level headings
3- `code-of-conduct.md` replace the default email with yours
4-  Check all letters casing and  use "JavaScript" instead of "javascript"
5- List items and headings can't end with `:` or `.`

There are many more to see all of them I suggest you:
Run `awesome-lint` from your terminal/cli to see all the issues.

**Comment by sindresorhus** [comment]
Bump

**Comment by sindresorhus** [comment]
Closing for lack of response.

**Pull request closed without merging**
