### PR TITLE
Update Flask

### PR DESCRIPTION
**Pull request by mjhea0**
https://github.com/mjhea0/awesome-flask

This PR is a follow up of #1918.

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

### CODE REVIEW

**Comment by mjhea0** [comment]
Unicorn

**Comment by neiesc** [comment]
LGTM

**Comment by neiesc** [comment]
What PR reviews you have? 
"You have to review at least 2 other open pull requests."

**Comment by mjhea0** [comment]
Reviewed PRs:

1. https://github.com/sindresorhus/awesome/pull/1783#issuecomment-640826981
1. https://github.com/sindresorhus/awesome/pull/1782#issuecomment-640845698

**Comment by mjhea0** [comment]
Those are associated with https://github.com/sindresorhus/awesome/pull/1800. Let me know if I need to do two new ones for this PR.

**Comment by neiesc** [comment]
LGTM

**Pull request merged**
