### PR TITLE
Add Flame

### PR DESCRIPTION
**Pull request by impulse**
I reviewed the following PRs: https://github.com/sindresorhus/awesome/pull/1782 https://github.com/sindresorhus/awesome/pull/1770 https://github.com/sindresorhus/awesome/pull/1769

https://github.com/flame-engine/awesome-flame

Awesome list for the Flutter-based Game Engine called Flame. 
We curate Flame games, projects, libraries, tools, tutorials, articles, and more.

Thanks for your consideration and time.

Linting is done via workflow.

### By submitting this pull request I confirm I've read and complied with the awesome requirements 🖖

### CODE REVIEW

**Comment by impulse** [comment]
unicorn

**Comment by sindresorhus** [comment]
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

**Comment by luanpotter** [comment]
Thanks @biesiadamich , I will change to be `Foo bar foobar, by Bob.` (instead of `Foo bar foobar. By Bob` that we have now).

I agree package names should not be uppercased (eg bonfire, flame_gamepad).

**Comment by biesiadamich** [comment]
@luanpotter my pleasure! In my opinion, that's great 🔥

**Comment by sindresorhus** [comment]
I decided to rename `master` branch to `main`, and apparently that permanently closes all PRs. Ugh. Sorry about that. Can you reopen this PR targeting the `main` branch? Include a link to this PR in the new one, so we can quickly see what was discussed previously.

**Pull request closed without merging**
