### PR TITLE
Awesome Creatives

### PR DESCRIPTION
**Pull request by afang**
[Awesome Creatives](https://github.com/afang/awesome-creatives) is a curated list of fine photography, videos, patterns, and illustration.

I never enjoyed existing creative lists because they didn't have high standards for each resource. The standards Awesome Creative adheres to are:

1. to be actively maintained and updated
2. to be searchable and easy to navigate
3. to be cost-free, copyright-free, without sacrificing quality

Some resources also include a description so it's easier to scan through the list and find a niche uses. These are only the creatives I've used, and can vouch for, but any others in the future will be added by readers and myself.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please read the [instructions](https://github.com/sindresorhus/awesome/blob/master/create-list.md) for creating a new list, [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

Especially this part:

> Wait at least a couple of weeks after creating a list before submitting to give it a chance to mature.

Ping me here in a few weeks and I'll reopen ;)

**Comment by sindresorhus** [comment]
Quick feedback:

- Only using `Creatives` in the title is a bit ambiguous.
- Logo is blurry on retina screens. Export a bigger resolution or use SVG.
- Drop the `awesome for` in the description.

**Comment by afang** [comment]
@sindresorhus thanks for the feedback, I've implemented the changes. :)

**Comment by sindresorhus** [comment]
You've only resolved the last item in the feedback. You also seem to have not read:

> Please read the instructions for creating a new list, contributing guidelines and the awesome manifest.

**Pull request closed without merging**
