### PR TITLE
Add Racket

### PR DESCRIPTION
**Pull request by avelino**
https://github.com/avelino/awesome-racket

A curated list of awesome Racket frameworks, libraries and software, maintained by Community

### CODE REVIEW

**Comment by sindresorhus** [comment]
Pasting in the guidelines here as it was removed from the PR description:


### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

## Requirements for your pull request

- **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).** Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration.
- I have read and understood the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title in the format `Add Name of List` (Example: `Add Swift`), not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
	- Be added at the bottom of the appropriate category.
- The list I'm submitting complies with the below requirements.


## Requirements for your Awesome list

- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
- It's the result of hard work and the best I could possibly produce.
- Non-generated Markdown file in a GitHub repo.
- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
- Not a duplicate.
- Only has awesome items. Awesome lists are curations of the best, not everything.
- Includes a project logo/illustration whenever possible.
	- Either fullwidth or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
	- The image should link to the project website or any relevant website.
	- The image should be high-DPI. Set it to maximum half the width of the original image.
- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
	- Should be placed on the right side of the readme heading.
	- Should link back to this list.
- Has a Table of Contents section.
	- Should be named `Contents`, not `Table of Contents`.
	- Should be the first section in the list.
	- Should only have one level of sub-lists, preferably none.
- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
	- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
	- [WTFPL](http://www.wtfpl.net) and [Unlicense](http://unlicense.org) are not acceptable licenses.
	- If you use a license badge, it should be SVG, not PNG.
- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
	- The file should be named `contributing.md`. Casing is up to you.
- Has consistent formatting and proper spelling/grammar.
	- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
	- The description starts with an uppercase character and ends with a period.
	- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.

Go to the top and read it again.

**Comment by sindresorhus** [comment]
> The entry in the Awesome list should:
> **Be added at the bottom of the appropriate category.**

**Comment by uraimo** [comment]
Other than what Sindre and padawan already said, please notice that there is a requirement for a "something like CC0, not a code licence like MIT, BSD, Apache, etc." license, while you are using MIT atm.
And I'd remove the "Awesome-Racket" item from the content section since it doesn't seem to have a purpose.
If you need an example for `contributing.md`, you could check out the one of awesome-nodejs [here](https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md).

**Comment by sfischer13** [comment]
- Not all of the descriptions under section headings end with a full stop.
- The usage af "A/An" at the beginning of your list items is inconsistent.

**Comment by sfischer13** [comment]
Here is the output of [awesome-lint](https://github.com/sindresorhus/awesome-lint):

```
  README.md:12:5
  ✖    1:1   Missing Awesome badge after the main heading                  awesome/badge
  ✖    1:1   Missing file contributing.md                                  awesome/contributing
  ✖    1:1   Awesome list must reside in a valid git repository            awesome/git-repo-age
  ✖    1:1   Missing License section                                       awesome/license
  ✖    1:1   Missing or invalid Table of Contents                          awesome/toc
  ✖   11:3   Invalid list item link URL                                    awesome/list-item
  ✖   12:5   Incorrect indentation before bullet: remove 2 spaces          list-item-bullet-indent
  ✖   12:7   Invalid list item link URL                                    awesome/list-item
  ✖   31:1   Marker style should be -                                      unordered-list-marker-style
  ✖   32:1   Marker style should be -                                      unordered-list-marker-style
  ✖   33:1   Marker style should be -                                      unordered-list-marker-style
  ✖   34:1   Marker style should be -                                      unordered-list-marker-style
  ✖   41:1   Marker style should be -                                      unordered-list-marker-style
  ✖   42:1   Marker style should be -                                      unordered-list-marker-style
  ✖   43:1   Marker style should be -                                      unordered-list-marker-style
  ✖   44:1   Marker style should be -                                      unordered-list-marker-style
  ✖   45:1   Marker style should be -                                      unordered-list-marker-style
  ✖   46:1   Marker style should be -                                      unordered-list-marker-style
  ✖   47:1   Marker style should be -                                      unordered-list-marker-style
  ✖   54:1   Marker style should be -                                      unordered-list-marker-style
  ✖   55:1   Marker style should be -                                      unordered-list-marker-style
  ✖   64:65  List item description must end with proper punctuation        awesome/list-item
  ✖   69:49  Text "Mac OS X" should be written as "macOS"                  awesome/spell-check
  ✖   93:62  List item description must end with proper punctuation        awesome/list-item
  ✖  101:1   Marker style should be -                                      unordered-list-marker-style
  ✖  102:1   Marker style should be -                                      unordered-list-marker-style
  ✖  125:82  List item link and description must be separated with a dash  awesome/list-item
  ✖  152:46  List item description must end with proper punctuation        awesome/list-item
  ✖  154:44  List item description must start with valid casing            awesome/list-item
```

Once you have fixed this issues, I'd be happy to have another look at your list.

**Comment by sindresorhus** [comment]
@avelino Ping :)

**Comment by sindresorhus** [comment]
Closing for lack of response.

**Pull request closed without merging**
