### PR TITLE
Add Effective Altruism

### PR DESCRIPTION
**Pull request by sheonhan**
**https://github.com/sheonhan/awesome-effective-altruism**

**A new philosophical movement called Effective Altruism (EA) has reported success at addressing the problems with traditional methods of philanthropy. It's swiftly overcoming endemic inefficiencies of large charities. However, while nearly 22% of people who reported themselves as Effective Altruists are programmers, there is no existing programmatic work related to the movement. Awesome-Effective-Altruism hopes to be a platform to both expand the movement to a wider audience and vitalize the developer community to create projects and tools related to Effective Altruism.**

# By submitting this pull request I confirm I've read and complied with the below requirements.

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title.<br>For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
	- Be added at the bottom of the appropriate category.
- The list I'm submitting complies with these requirements:
	- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
	- It's the result of hard work and the best I could possibly produce.
	- Non-generated Markdown file in a GitHub repo.
	- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
	- Not a duplicate.
	- Only has awesome items. Awesome lists are curations of the best, not everything.
	- Includes a project logo/illustration whenever possible.
		- Placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
		- The image should link to the project website or any relevant website.
		- The image should be high-DPI. Set it to maximum half the width of the original image.
	- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
	- Has the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- Has a Table of Contents section.
		- Should be named `Contents`, not `Table of Contents`.
		- Should be the first section in the list.
	- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
		- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
		- If you use a license badge, it should be SVG, not PNG.
	- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
		- The file should be named `contributing.md`. Casing is up to you.
	- Has consistent formatting and proper spelling/grammar.
		- Each link description starts with an uppercase character and ends with a period.<br>Example: `- [AVA](…) - JavaScript test runner.`
		- Drop all the `A` / `An` prefixes in the descriptions.
		- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
	- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.
- Go to the top and read it again.

### CODE REVIEW

**Comment by kevva** [comment]
It's missing link descriptions. Also, it'd benefit from maturing a little imo.

**Comment by sheonhan** [comment]
Hey, thanks! I think the link description is there. For the maturity, I'm spreading the word out about the repo, and I thought it would benefit more if it officially becomes a part of awesome-repos!

**Comment by legodude17** [comment]
Not Followed:
* Should be named Contents, not Table of Contents.
* Entries have a description, unless the title is descriptive enough by itself. It rarely is though.

Suggestions:
* Describe what altruism is. After reading the description I still don't know
* `sheon.han[at]gmail.com` -> `sheon.han@gmail.com`
* Effective Altruism Wiki -> Wiki
* Effective Altruism Facebook Group -> Facebook Group
* Effective Altruism Forum -> Forum
* Effective Altruism at Harvard -> Harvard

**Comment by sheonhan** [comment]
@legodude17 By description, you mean the one on the awesome-effective-altruism repo, right? I just changed what wasn't being followed. I changed my email address as you suggested. For the other ones, I think people in the Effective Altruism community are more familiar with the full names. But let me know what you think!

**Comment by legodude17** [comment]
Now you should just add descriptions to things, almost none of them have a description (descriptions should be more than just the author).

**Comment by sheonhan** [comment]
@legodude17 I added the link descriptions. Let me know if there's anything more.

**Comment by sindresorhus** [comment]
Linkify `Effective Altruism` in the top description to https://en.wikipedia.org/wiki/Effective_altruism

**Comment by sindresorhus** [comment]
Interesting topic! :)

**Comment by sindresorhus** [comment]
Added

**Pull request merged**
