### PR TITLE
Add A-Frame VR

### PR DESCRIPTION
**Pull request by ngokevin**
Waited a few weeks and went over the guidelines. Let me know how this looks.

Previously at https://github.com/sindresorhus/awesome/pull/447

### CODE REVIEW

**Comment by sindresorhus** [comment]
From the previous PR:

> Ping me here in a few weeks **and I'll reopen** ;)

But I guess we can take it from here.

**Comment by sindresorhus** [comment]
I would like to see more descriptions for items. Like here: https://github.com/aframevr/awesome-aframe#components and here https://github.com/aframevr/awesome-aframe#scenes

**Comment by sindresorhus** [comment]
Added :)

**Comment by ngokevin** [comment]
Thanks! Sorry I was considering re-opening but the previous PR wasn't reflecting my force-pushed changes. I will add more description.

**Pull request closed without merging**
