### PR TITLE
Add Vert.x

### PR DESCRIPTION
**Pull request by michel-kraemer**
**https://github.com/vert-x3/vertx-awesome**

**Vert.x Awesome is an list of awesome frameworks, libraries or other components for use with or that use Vert.x version 3. This list will help other Java back-end developers.**

# ALL THE BELOW CHECKBOXES SHOULD BE DONE AND CHECKED AND THE ABOVE PLACEHOLDERS SHOULD BE FILLED IN BEFORE SUBMITTING A PULL REQUEST!

- [x] I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- [x] This pull request has a descriptive title.
- The list I added
	- [x] **has been around for at least 20 days,**
	- [x] is not a duplicate,
	- [x] only has awesome items with descriptions,
	- [x] contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- [x] has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license),
	- [x] has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- [x] has been checked for inconsistent formatting, spelling and grammar, and
	- [x] has been added at the bottom of the appropriate category.

### CODE REVIEW

**Comment by sindresorhus** [comment]
> has an appropriate license,

This is not followed. Please actually read the linked text.

> has been checked for inconsistent formatting, spelling and grammar, and

Neither this. Lots of inconsistent formatting. Be consistent about ending all descriptions in a `.`. The first character in descriptions should be capitalized. Use consistent naming of `Vert.x`.

-

- I would like to see more than just libraries. Include some blog posts, tutorials, links to community resources (Example: https://github.com/sindresorhus/awesome-electron#community), videos of talks, book, learning material, etc.
- Include project logo in the top right, like e.g. https://github.com/sindresorhus/awesome-electron
- The repo is missing a description.

**Comment by sindresorhus** [comment]
ping

**Comment by michel-kraemer** [comment]
Thanks for reviewing the list and your comments. Very kind. I'll try my very best to make the list comply to your requirements but it'll take a couple of days as my free time is limited at the moment.

In the meantime I have a question regarding the license.

> This is not followed. Please actually read the linked text ;)

I don't understand what we did wrong here. The repo has a license. It was one of the first things we added many months ago. Is it because it's the Apache License? This is the project's default license and it's not my call to change that. If that's the reason, then I need to talk to the project leads first.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license

**Comment by michel-kraemer** [comment]
Yes, I read the link for the third time. It only *recommends* CC but doesn't not *require* it. We have Apache-2.0.

**Comment by egeerardyn** [comment]
Apache 2.0 is often also called ASL2.0: Apache Software License? However, I don't see problems with using ASL2.0 for documentation as is the case here (the license itself also [explicitly mentions](http://www.apache.org/licenses/LICENSE-2.0) that documentation can be seen as source files (emphasis mine)):

> *"Source"* form shall mean the preferred form for making modifications, including but not limited to software source code, **documentation source**, and configuration files.

I think such use should be allowed here as well, unless there are objections to some specific terms in the ASL.

**Comment by michel-kraemer** [comment]
@sindresorhus I improved the list and covered all your points.

One thing that remains to be discussed is the license. In my opinion ASL2.0 should be OK. It conforms to your contribution guidelines. Please let me know what you think.

**Comment by sindresorhus** [comment]
Awesome lists are not documentation. I don't understand why you're so insistent on using the Apache license for this. It's clearly not the optimal license for non-software. The Creative Commons licenses were made exactly for this purpose. Having the same license for all awesome lists also makes it easier for users. http://choosealicense.com/non-software/ But fine, not interested in wasting more time discussing this.

**Comment by sindresorhus** [comment]
Btw, the link in the logo is incorrect.

**Pull request merged**
