### PR TITLE
Add Awesome Infosec

### PR DESCRIPTION
**Pull request by oneohtrix**
https://github.com/onlurking/awesome-infosec

This awesome list contains resources that'll aid people in learning about information security. 

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

I reviewed the PRs #1448 and #1428.

### CODE REVIEW

**Comment by sindresorhus** [comment]
It looks like the list doesn't follow the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

// @onlurking

**Comment by onlurking** [comment]
Hi @sindresorhus, thanks for the attention.
Well, my list is heavily outdated right now and doesn't comply to your guideline.
Give enough time in the next days I will rewrite it from scratch, if you want to keep this PR open I will ping you right here when is done.
Thanks.

**Comment by sindresorhus** [comment]
Closing as the list still doesn't comply with the guidelines.

@onlurking Open a new PR when you've done the needed tweaks to the list.

**Comment by sindresorhus** [comment]
```
❯ awesome-lint https://github.com/onlurking/awesome-infosec
✖ Linting

  readme.md:1:1
  ✖    1:1    Missing or invalid Table of Contents                                          remark-lint:awesome/toc
  ✖    1:1    Headings should use atx                                                       remark-lint:heading-style
  ✖    1:1    Missing Awesome badge after the main heading                                  remark-lint:awesome/badge
  ✖    1:1    License section must be at heading depth 2                                    remark-lint:awesome/license
  ✖   10:1    Headings should use atx                                                       remark-lint:heading-style
  ✖   10:1    Don’t use multiple top level headings (1:1)                                   remark-lint:no-multiple-toplevel-headings
  ✖   13:4    Invalid list item link URL                                                    remark-lint:awesome/list-item
  ✖   14:4    Invalid list item link URL                                                    remark-lint:awesome/list-item
  ✖   15:4    Invalid list item link URL                                                    remark-lint:awesome/list-item
  ✖   16:4    Invalid list item link URL                                                    remark-lint:awesome/list-item
  ✖   17:4    Invalid list item link URL                                                    remark-lint:awesome/list-item
  ✖   18:4    Invalid list item link URL                                                    remark-lint:awesome/list-item
  ✖   19:4    Invalid list item link URL                                                    remark-lint:awesome/list-item
  ✖   20:4    Invalid list item link URL                                                    remark-lint:awesome/list-item
  ✖   21:4    Invalid list item link URL                                                    remark-lint:awesome/list-item
  ✖   22:5    Invalid list item link URL                                                    remark-lint:awesome/list-item
  ✖   23:5    Invalid list item link URL                                                    remark-lint:awesome/list-item
  ✖   25:1    Headings should use atx                                                       remark-lint:heading-style
  ✖   25:1    Don’t use multiple top level headings (1:1)                                   remark-lint:no-multiple-toplevel-headings
  ✖   63:1    Headings should use atx                                                       remark-lint:heading-style
  ✖   63:1    Don’t use multiple top level headings (1:1)                                   remark-lint:no-multiple-toplevel-headings
  ✖   75:1    Marker style should be -                                                      remark-lint:unordered-list-marker-style
  ✖   75:3    Incorrect indentation before bullet: remove 1 space                           remark-lint:list-item-bullet-indent
  ✖   76:1    Marker style should be -                                                      remark-lint:unordered-list-marker-style
  ✖   76:3    Incorrect indentation before bullet: remove 1 space                           remark-lint:list-item-bullet-indent
  ✖   82:1    Marker style should be -                                                      remark-lint:unordered-list-marker-style
  ✖   82:3    Incorrect indentation before bullet: remove 1 space                           remark-lint:list-item-bullet-indent
  ✖   84:7    Remove 1 space before this heading’s content                                  remark-lint:no-heading-content-indent
  ✖   90:7    Remove 1 space before this heading’s content                                  remark-lint:no-heading-content-indent
  ✖   93:1    Marker style should be -                                                      remark-lint:unordered-list-marker-style
  ✖   95:7    Remove 1 space before this heading’s content                                  remark-lint:no-heading-content-indent
  ✖  100:7    Remove 1 space before this heading’s content                                  remark-lint:no-heading-content-indent
  ✖  102:3    Don’t pad link with inner spaces                                              remark-lint:no-inline-padding
  ✖  102:67   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  105:74   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  108:76   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  111:93   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  114:82   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  117:84   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  120:77   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  123:80   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  126:85   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  129:78   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  132:90   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  140:97   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  143:65   Invalid list item link                                                        remark-lint:awesome/list-item
  ✖  146:80   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  149:91   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  152:129  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  155:135  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  158:72   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  161:90   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  164:94   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  167:91   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  170:122  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  173:101  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  176:135  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  179:80   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  182:91   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  185:79   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  188:66   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  192:79   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  195:94   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  198:97   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  203:99   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  206:105  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  209:136  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  214:104  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  217:94   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  220:121  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  223:97   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  226:98   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  229:129  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  236:60   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  239:69   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  242:69   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  245:73   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  248:87   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  251:75   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  254:56   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  257:61   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  260:57   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  263:87   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  266:91   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  269:101  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  272:99   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  275:85   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  278:63   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  281:147  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  284:93   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  287:102  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  290:90   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  293:87   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  296:76   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  299:57   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  302:133  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  307:101  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  310:86   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  313:105  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  316:99   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  319:87   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  322:113  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  325:109  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  328:105  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  332:1    Headings should use atx                                                       remark-lint:heading-style
  ✖  332:1    Don’t use multiple top level headings (1:1)                                   remark-lint:no-multiple-toplevel-headings
  ✖  344:109  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  347:100  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  350:128  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  354:101  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  357:107  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  360:105  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  363:92   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  370:85   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  373:94   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  376:92   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  379:94   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  382:112  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  385:107  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  388:122  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  391:99   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  394:83   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  397:95   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  407:99   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  410:106  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  413:89   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  416:97   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  422:95   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  425:102  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  428:91   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  431:98   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  437:88   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  440:95   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  443:84   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  446:95   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  452:113  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  455:103  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  458:87   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  464:101  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  467:95   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  470:110  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  476:99   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  479:98   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  485:87   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  488:93   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  491:118  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  494:76   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  497:82   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  500:108  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  503:76   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  506:65   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  509:112  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  512:70   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  515:78   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  518:102  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  521:86   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  524:67   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  527:92   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  530:125  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  533:77   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  536:96   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  539:93   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  542:79   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  548:3    Link to http://www.binary-auditing.com/ is dead                               remark-lint:no-dead-urls
  ✖  560:5    Remove 1 space before this heading’s content                                  remark-lint:no-heading-content-indent
  ✖  565:5    Remove 1 space before this heading’s content                                  remark-lint:no-heading-content-indent
  ✖  598:3    Link to http://www.securitytube.net/user/Audi is dead                         remark-lint:no-dead-urls
  ✖  600:1    Don’t use multiple top level headings (1:1)                                   remark-lint:no-multiple-toplevel-headings
  ✖  600:1    Headings should use atx                                                       remark-lint:heading-style
  ✖  620:52   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  623:63   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  626:63   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  629:63   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  632:63   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  637:28   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  640:49   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  643:1    Headings should use atx                                                       remark-lint:heading-style
  ✖  643:1    Don’t use multiple top level headings (1:1)                                   remark-lint:no-multiple-toplevel-headings
  ✖  648:1    Marker style should be -                                                      remark-lint:unordered-list-marker-style
  ✖  648:3    Link to http://www.securitytube.net/groups?operation=view&groupId=10 is dead  remark-lint:no-dead-urls
  ✖  648:114  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  651:1    Marker style should be -                                                      remark-lint:unordered-list-marker-style
  ✖  651:3    Link to http://www.securitytube.net/groups?operation=view&groupId=9 is dead   remark-lint:no-dead-urls
  ✖  651:122  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  654:1    Marker style should be -                                                      remark-lint:unordered-list-marker-style
  ✖  654:3    Link to http://www.securitytube.net/groups?operation=view&groupId=7 is dead   remark-lint:no-dead-urls
  ✖  654:93   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  657:1    Marker style should be -                                                      remark-lint:unordered-list-marker-style
  ✖  657:3    Link to http://www.securitytube.net/groups?operation=view&groupId=4 is dead   remark-lint:no-dead-urls
  ✖  657:115  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  660:1    Don’t use multiple top level headings (1:1)                                   remark-lint:no-multiple-toplevel-headings
  ✖  660:1    Headings should use atx                                                       remark-lint:heading-style
  ✖  691:1    Don’t use multiple top level headings (1:1)                                   remark-lint:no-multiple-toplevel-headings
  ✖  691:1    Headings should use atx                                                       remark-lint:heading-style
  ✖  698:1    Headings should use atx                                                       remark-lint:heading-style
  ✖  698:1    Don’t use multiple top level headings (1:1)                                   remark-lint:no-multiple-toplevel-headings
  ✖  718:1    Headings should use atx                                                       remark-lint:heading-style
  ✖  718:1    Don’t use multiple top level headings (1:1)                                   remark-lint:no-multiple-toplevel-headings
  ✖  721:62   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  724:64   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  727:81   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  730:82   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  733:57   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  736:65   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  739:68   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  742:84   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  745:89   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  748:72   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  751:65   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  754:66   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  757:119  List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  760:74   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  763:68   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  766:58   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  769:58   List item link and description must be separated with a dash                  remark-lint:awesome/list-item
  ✖  772:1    Headings should use atx                                                       remark-lint:heading-style
  ✖  772:1    Don’t use multiple top level headings (1:1)                                   remark-lint:no-multiple-toplevel-headings
  ✖  777:1    Headings should use atx                                                       remark-lint:heading-style
  ✖  777:1    Don’t use multiple top level headings (1:1)                                   remark-lint:no-multiple-toplevel-headings

  219 errors
```

https://github.com/sindresorhus/awesome-lint

**Pull request closed without merging**
