### PR TITLE
Add "Movies for Hackers" awesome list

### PR DESCRIPTION
**Pull request by oneohtrix**
https://github.com/k4m4/movies-for-hackers

An awesome list containing movies relating to hacker culture.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

**Comment by sindresorhus** [comment]
I think you should include a very short summary for each movie. That would make the list more useful. Now it's just a table of random lists. As a user, I'm not going to click them all to find what I want.

**Comment by sindresorhus** [comment]
The `/10` part of the rating `6.8/10` is moot. Just say at the top that the rating is from 1 to 10 and then just use `6.8` for rating instead.

**Comment by sindresorhus** [comment]
// @k4m4

**Comment by stevesong** [comment]
This does not quite seem to meet the criteria of "awesome" resources as many of the movies listed have relatively low ratings.

**Comment by jzarca01** [comment]
Some movies in the "action" category shouldnt be in the list, like The Italian Job, or The island
How is that relevant to hackers ?

**Comment by sindresorhus** [comment]
Closing for lack of response from the submitter. And I agree that the list shouldn't list movies with low-score rating unless it has commentary there from users on why it's good enough to be included. Actually, the list is not that useful because it's just a list of movies without any kind of justification on why they're awesome/recommended. I would take a note on how it's done here: https://github.com/sindresorhus/awesome-scifi Where users add commentary on why they liked something.

// @k4m4

**Comment by k4m4** [comment]
I appreciate your feedback and will work on it soon. Thanks!

**Pull request closed without merging**
