### PR TITLE
Add Open Source Jobs

### PR DESCRIPTION
**Pull request by timqian**
**https://github.com/t9tio/open-source-jobs#readme**

**It is a list of open source projects offering jobs, might be helpful for people who want to find a job contribute to open source**

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

## Requirements for your pull request

- [x] **Don't waste my time.** Do a good job, adhere to all the guidelines, and be responsive.
- [ ] **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).**
	Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration.
- [x] You have read and understood the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- [x] This pull request has a title in the format `Add Name of List`.
	- ✅ `Add Swift`
	- ✅ `Add Software Architecture`
	- ❌ `Update readme.md`
	- ❌ `Add Awesome Swift`
	- ❌ `Add swift`
	- ❌ `Adding Swift`
	- ❌ `Added Swift`
- [x] Your entry here should include a short description about the project/theme of the list. **It should not describe the list itself.** The first character should be uppercase and the description should end in a dot. It should be an objective description and not a tagline or marketing blurb.
	- ✅ `- [iOS](…) - Mobile operating system for Apple phones and tablets.`
	- ✅ `- [Framer](…) - Prototyping interactive UI designs.`
	- ❌ `- [iOS](…) - Resources and tools for iOS development.`
	- ❌ `- [Framer](…)`
	- ❌ `- [Framer](…) - prototyping interactive UI designs`
- [x] Your entry should be added at the bottom of the appropriate category.
- The suggested Awesome list complies with the below requirements.

## Requirements for your Awesome list

- [x] **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
- [x] Don't open a Draft / WIP pull request while you work on the guidelines. A pull request should be 100% ready and should adhere to all the guidelines when you open it.
- [x] Run [`awesome-lint`](https://github.com/sindresorhus/awesome-lint) on your list and fix the reported issues. If there are false-positives or things that cannot/shouldn't be fixed, please [report it](https://github.com/sindresorhus/awesome-lint/issues/new).
- [x] **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- ✅ `Mobile operating system for Apple phones and tablets.`
	- ✅ `Prototyping interactive UI designs.`
	- ❌ `Resources and tools for iOS development.`
	- ❌ `Awesome Framer packages and tools.`
- [x] It's the result of hard work and the best I could possibly produce.
	**If you have not put in considerable effort into your list, your pull request will be immediately closed.**
- [x] The repo name of your list should be in lowercase slug format: `awesome-name-of-list`.
	- ✅ `awesome-swift`
	- ✅ `awesome-web-typography`
	- ❌ `awesome-Swift`
	- ❌ `AwesomeWebTypography`
- [ ] The heading title of your list should be in [title case](https://capitalizemytitle.com/) format: `# Awesome Name of List`.
	- ✅ `# Awesome Swift`
	- ✅ `# Awesome Web Typography`
	- ❌ `# awesome-swift`
	- ❌ `# AwesomeSwift`
- [x] Non-generated Markdown file in a GitHub repo.
- [x] The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
- [x] Not a duplicate. Please search for existing submissions.
- [x] Only has awesome items. Awesome lists are curations of the best, not everything.
- [x] Includes a project logo/illustration whenever possible.
	- Either centered, fullwidth, or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
	- The image should link to the project website or any relevant website.
	- **The image should be high-DPI.** Set it to maximum half the width of the original image.
- [x] Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- [x] Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
	- [x] Should be placed on the right side of the readme heading.
		- Can be placed centered if the list has a centered graphics header.
	- [x] Should link back to this list.
- [x] Has a Table of Contents section.
	- Should be named `Contents`, not `Table of Contents`.
	- Should be the first section in the list.
	- Should only have one level of [nested lists](https://commonmark.org/help/tutorial/10-nestedLists.html), preferably none.
- [x] Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
	- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
	- [WTFPL](http://www.wtfpl.net) and [Unlicense](http://unlicense.org) are not acceptable licenses.
	- **If you use a license badge, it should be SVG, not PNG.**
	- To verify that you've read all the guidelines, please add comment with just the word `unicorn`.
- [x] Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
	- The file should be named `contributing.md`. Casing is up to you.
- [x] Has consistent formatting and proper spelling/grammar.
	- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
	- The description starts with an uppercase character and ends with a period.
	- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
- [x] Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.
- [x] Doesn't include an `Inspired by awesome-foo` or `Inspired by the Awesome project` kinda link at the top of the readme. The Awesome badge is enough.

**Go to the top and read it again.**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

**Comment by timqian** [comment]
- About the name, I don't put an "awesome" in the beginning as the repo has been there for a while, I am afraid changing the name makes it harder for people to find it.  Also, I find some repos in the list did not begin with "awesome" too. So I guess it might be fine.

- About `awesome-lint`
Screen Shot 2019-07-08 at 10 48 34 AM

I resolved most of the problems, expect these two, but these two URLs are actually accessible. Not sure it is the network issue on my computer

**Comment by eselkin** [comment]
- Title should be title capital letters beginning each word that is not a preposition with spaces not dashes.
- The majority of the README.md does not appear to be a list. I think having the documentation of the service somewhere other than the awesome list seems more in line with the mission.

**Comment by timqian** [comment]
@eselkin thanks for your review, 

- the title has been updated: https://github.com/t9tio/open-source-jobs/commit/e78f7c5fbbc4836bc80131d9477d97f8c4369cac
- The README.md is a list, but in a table format. That is because it looks better in that style

**Comment by eselkin** [comment]
I agree about the table, I meant the sections after the table.

**Comment by CompSciLauren** [comment]
This is a great idea for a list! I have a few things to suggest:

- Add "awesome" to the beginning of the repo name. I understand you worry it could make your repo harder to find, but GitHub actually does a great job of preventing this problem. If you rename your repo, then when users attempt to go to the old URL, it will immediately redirect them to the updated URL. Here's [GitHub's article on renaming a repository](https://help.github.com/en/articles/renaming-a-repository) for more information.
- The first two sentences in the readme are: "A list of Open Source projects offering jobs. For who want to work on open source and get paid." I think the second sentence could be rephrased a little. Maybe something like "This is useful for anyone who wants to get paid to work on open source projects." Up to you though. If you do keep it the way it is, "For who want" should be "For whoever wants".
- Consider adding more GitHub topics if you can think of some other relevant ones. Maybe "open source" or "jobs" etc.
- Maybe add a section in the contents on your readme for contributing and link to the contributing file
- Above the contents section, you have "Filter the orgs, suggest a new org, post a new job" in a list. I think it would make more sense to move that list underneath the Repos section but above the table of repos.

Let me know if you have any questions about what I suggested. Nice work finding all those open source jobs!

**Comment by irazasyed** [comment]
- I think the awesome list itself should be a different repo without the entire code and released under some license like CC0 if possible.
- While the table format may look good, it doesn't fit the requirements.
- You haven't read the guidelines fully as it's missing a requirement in your PR and I can't point it out as it's a requirement to make sure you've gone through everything properly.

**Comment by sindresorhus** [comment]
@timqian Bump

**Comment by cliffordfajardo** [comment]
Make sure to add a comment to this pull request with the word `unicorn` as indicated by the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) to let us know you've read everything

**Pull request closed without merging**
