### PR TITLE
Added awesome Appcelerator Titanium list

### PR DESCRIPTION
**Pull request by wienke**
Added an awesome list of Appcelerator Titanium modules and tools.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks, but Titanium definitely isn't awesome.

**Comment by wienke** [comment]
I don't agree

**Comment by Topener** [comment]
I'm sure a lot of developers disagree with you. Titanium is awesome for building native iOS & Android apps without having to know both Java and Obj-C/Swift.

Isn't this `curated list of awesome lists` for everyone?

**Comment by thevirtualforge** [comment]
@sindresorhus I'm not looking to defend Titanium but I'd be very interested to know what you don't like about it

**Comment by shodanuk** [comment]
@sindresorhus  I'm not looking to defend Titanium but I'd be very interested to know what you don't like about it

(sorry about the delete / repost)

**Comment by sindresorhus** [comment]
> Isn't this curated list of awesome lists for everyone?

Notice `curated`. This is nothing against the list. I'm sure it's good. Just not interested in promoting anything Titanium related.

> I'm not looking to defend Titanium but I'd be very interested to know what you don't like about it

There's lots of post about it if you google it. But in short: The company is awful, they've screwed over developers many times, Titanium is a super buggy piece of crap, and they introduce more regressions than they fix. I got bitten by it by creating a couple of apps that used Titanium and wasted so much time on a gadzillion bug reports that went nowhere.

https://www.google.no/url?sa=t&rct=j&q=&esrc=s&source=web&cd=8&cad=rja&uact=8&ved=0CFkQFjAH&url=https%3A%2F%2Fusingimho.wordpress.com%2F2011%2F06%2F14%2Fwhy-you-should-stay-away-from-appcelerators-titanium%2F&ei=LTCRVYHTLaSfygOkhLOADA&usg=AFQjCNHr1Xx1VIyHGg0nezVKWJfZLrSGEg&sig2=t_0UW1wKEiuKuELCExtwtg

https://plus.google.com/+PascalHartig/posts/LZ4nahYJ7vC (since deleted by them)

**Comment by mcvendrell** [comment]
@sindresorhus I also want to know "why not". For me is awesome that you can program native apps for iOS and Android without the need of known obj-C/Java.

**Comment by shodanuk** [comment]
Fair enough. I'd suggest giving it another chance though. A lot has changed since 2011 & 2012 when those blog posts were written and things have improved greatly since then.

**Comment by wienke** [comment]
@sindresorhus I agree with @shodanuk your judgement seems to be based on previous experiences.

**Comment by sindresorhus** [comment]
> Fair enough. I'd suggest giving it another chance though. A lot has changed since 2011 & 2012 when those blog posts were written and things have improved greatly since then.

I used it a month ago. It IMHO hasn't. Maybe with the [Hyperloop](http://www.appcelerator.com/blog/2013/10/introducing-hyperloop/) stuff, but I doubt it with their track record. YMMV though.

I would rather recommend https://github.com/facebook/react-native

**Pull request closed without merging**
