### PR TITLE
Add Creative Coding

### PR DESCRIPTION
**Pull request by terkelg**
**https://github.com/terkelg/awesome-creative-coding**

**It can be hard to get started with more advance creative coding. This is a list of beginner-friendly tools, resources and things to get you started**

# By submitting this pull request I confirm I've read and complied with the below requirements.

Failure to properly do so will just result in the pull request being closed and everyone's time wasted. Please read it twice. Most people miss many things.

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title. For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should include a short description about the list project/theme (not the list itself), and should be added at the bottom of the appropriate category.
- The list I added
	- **has been around for at least 30 days,**
	- is the result of hard work and is the best I could possibly produce,
	- is a non-generated Markdown file in a GitHub repo,
	- is not a duplicate,
	- includes a succinct description of the project/theme at the top ([example](https://github.com/willempienaar/awesome-quantified-self)),
	- includes a project logo/illustration (whenever possible) at the top right of the readme ([example](https://github.com/sindresorhus/awesome-electron)). (The logo should link to the project website or any relevant website. The logo should be high-DPI, so set it to maximum half the width of the original image.),
	- only has awesome items **with descriptions** *(Awesome lists are curations of the best, not of everything)*,
	- contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- has a Table of Contents section **named `Contents`** as the first section,
	- has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license) *(Meaning something like CC0, NOT a code licence like MIT, BSD, Apache, etc)* *(If you use a license badge, it should be SVG, not PNG)*,
	- has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- doesn't include a Travis badge,
	- has been checked for inconsistent formatting, spelling, and grammar:
		- Each link description starts with an uppercase character and ends with a period.
		- Drop all the `A` / `An` prefixes in the descriptions.
		- Consistent naming. For example, `Node.js`, not `NodeJS` or `node.js`.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Looks pretty good :)

---

> The entry in the Awesome list should include a short description about the list project/theme **(not the list itself)**, and should be added at the bottom of the appropriate category.

Not followed.

> includes a succinct description of the project/theme at the top (example),

Not followed.

---

The `Contents` should not be hidden by default. The whole point of it is to be able to get to a specific section quickly.

---

> abandonedart.org - Generative art ideas by Matt Pearson.
iquilezles.org - Home of Íñigo Quílez.
bit-101.com - Blog by Keith Peters.

I think you should shortly explain why it's worth reading what these people write.

**Comment by terkelg** [comment]
Thanks, feedback much appreciated. Sorry for the inconvenience. The list should be updated to comply with the guidelines.

**Comment by sindresorhus** [comment]
> The entry in the Awesome list should include a short description about the list project/theme (not the list itself), and should be added at the bottom of the appropriate category.
Not followed.

Please read the text carefully. The description here should be about the theme, not the list itself.

**Comment by sindresorhus** [comment]
Can you linkify `Creative coding` in the top description to https://en.wikipedia.org/wiki/Creative_coding

**Comment by terkelg** [comment]
Updated with link and new description.

**Comment by sindresorhus** [comment]
> The entry in the Awesome list should include a short description about the list project/theme (not the list itself), and should be added at the bottom of the appropriate category.
Not followed.
Please read the text carefully. The description here should be about the theme, not the list itself.

Not sure how I can possibly make this clearer. The description here needs to be improved according to the above requirements: https://github.com/sindresorhus/awesome/pull/864/files#diff-0730bb7c2e8f9ea2438b52e419dd86c9R475

---

Your commit messages in your repo should also be more descriptive than `Update README`.

**Pull request merged**
