### PR TITLE
add Linux Containers

### PR DESCRIPTION
**Pull request by Friz-zy**
https://github.com/Friz-zy/awesome-linux-containers#security

### CODE REVIEW

**Comment by sindresorhus** [comment]
The list should be in the section the list fits into, not where a section of the list fits into.

**Comment by sindresorhus** [comment]
Please read the [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

**Comment by Friz-zy** [comment]
There is no right section except maybe 'Miscellaneous' that too general.
This list was created for security notes.

**Comment by sindresorhus** [comment]
The description says otherwise:

> A curated list of awesome **Linux Containers frameworks, libraries and software**

**Comment by sindresorhus** [comment]
Can you fix the merge conflict?

**Comment by sindresorhus** [comment]
You also need to include some contribution guidelines: https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines

**Comment by Friz-zy** [comment]
Done, thanks for your tips

**Comment by sindresorhus** [comment]
Added.

Would be awesome if you could add the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) to your readme :D

**Comment by Friz-zy** [comment]
Sure.
Thanks a lot!

**Pull request closed without merging**
