### PR TITLE
Add UNIX

### PR DESCRIPTION
**Pull request by sirredbeard**
**[Insert URL to the list here]**

https://github.com/sirredbeard/Awesome-UNIX

**[Explain what this list is about and why it should be included here]**

This list is about the history and influence of UNIX and UNIX philosophy. UNIX philosophy pervades computer science and it's approach dominates current development, including on macOS, Android, and increasingly Windows.

# By submitting this pull request I confirm I've read and complied with the below requirements.

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md). 

YES

- This pull request has a descriptive title.<br>For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.

YES

- The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.

YES
	- Be added at the bottom of the appropriate category.
YES
- The list I'm submitting complies with these requirements:
	- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
YES
	- It's the result of hard work and the best I could possibly produce.
YES
	- Non-generated Markdown file in a GitHub repo.
YES
	- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
YES
	- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
YES
	- Not a duplicate.
YES
	- Only has awesome items. Awesome lists are curations of the best, not everything.
YES
	- Includes a project logo/illustration whenever possible.
YES, an infographic is included in the relevant section.
		- Either fullwidth or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
		- The image should link to the project website or any relevant website.
		- The image should be high-DPI. Set it to maximum half the width of the original image.
	- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
YES.
	- Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
YES.
		- Should be placed on the right side of the readme heading.
		- Should link back to this list.
	- Has a Table of Contents section.
YES.
		- Should be named `Contents`, not `Table of Contents`.
		- Should be the first section in the list.
		- Should only have one level of sub-lists, preferably none.
	- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
		- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
YES
		- [WTFPL](http://www.wtfpl.net) and [Unlicense](http://unlicense.org) are not acceptable licenses.
		- If you use a license badge, it should be SVG, not PNG.
	- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
YES
		- The file should be named `contributing.md`. Casing is up to you.
	- Has consistent formatting and proper spelling/grammar.
YES
		- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
		- The description starts with an uppercase character and ends with a period.
		- Drop all the `A` / `An` prefixes in the descriptions.
		- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
	- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.
YES
- Go to the top and read it again.
DONE.

### CODE REVIEW

**Comment by legodude17** [comment]
In `Contents`, either make those subtopics links or remove them entirely.

**Comment by sirredbeard** [comment]
Done. https://github.com/sirredbeard/Awesome-UNIX/commit/80a0338314d7c9fb6fc7ab97a957af4b7ece198b

**Comment by sindresorhus** [comment]
Hey, sorry for the lack of response, please see #1363.

**Comment by sindresorhus** [comment]
@sirredbeard Can you fix the merge conflict?

**Comment by edm00se** [comment]
Review: ✔

Aside from the noted merge conflict by GH, my review of this PR is positive.

**Comment by seriousmac** [comment]
It is really awesome list! However, does it have still conflicts?

**Comment by sirredbeard** [comment]
Yes, I just haven't had time to go in and fix.

**Comment by sindresorhus** [comment]
@sirredbeard Can you fix the merge conflict?

**Comment by sindresorhus** [comment]
The link to `http://www.inspursystems.com/product/32-way-system/` is dead.

---

> * The description starts with an uppercase character and **ends with a period.**

---

Don't use the Awesome badge for the links to other Awesome lists. It's makes your list very noisy and it doesn't add much.

---

Only the heading should be a `#` heading. The sections like `Contents` and others should be `##` (second-level) sections.

---

`UNIX` in `This list is an exploration of the world of UNIX®` should be linkified to the Wikipedia page about UNIX.

**Comment by sindresorhus** [comment]
Closing for lack of response.

**Pull request closed without merging**
