### PR TITLE
Add Broadcasting

### PR DESCRIPTION
**Pull request by barroco**

### CODE REVIEW

**Comment by aleksandar-todorovic** [comment]
Where's the license?

**Comment by sindresorhus** [comment]
See: https://github.com/sindresorhus/awesome/pull/68

> You also have disabled the issue tracker. I won't add anything with an disabled issue tracker.

**Comment by barroco** [comment]
Hello @sindresorhus and @aleksandar-todorovic, 
License added (https://github.com/ebu/awesome-broadcasting/pull/41) and issue tracker enabled.
Thanks!
Michael

**Comment by sindresorhus** [comment]
Added :)

**Pull request closed without merging**
