### PR TITLE
 Added Awesome Deep Vision List

### PR DESCRIPTION
**Pull request by eungbean**
**[Awesome Deep Vision v2](https://github.com/eungbean/Awesome-Deep-Vision-v2)**

**[The original Repo [Awesome Deep Vision](https://github.com/kjw0612/awesome-deep-vision) is nolonger maintained since 2017.]**

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

## Requirements for your pull request

- **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).** Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration.
- I have read and understood the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title in the format `Add Name of List` (Example: `Add Swift`), not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
	- Be added at the bottom of the appropriate category.
- The list I'm submitting complies with the below requirements.

## Requirements for your Awesome list

- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
- It's the result of hard work and the best I could possibly produce.
- Non-generated Markdown file in a GitHub repo.
- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
- Not a duplicate.
- Only has awesome items. Awesome lists are curations of the best, not everything.
- Includes a project logo/illustration whenever possible.
	- Either centered, fullwidth, or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
	- The image should link to the project website or any relevant website.
	- The image should be high-DPI. Set it to maximum half the width of the original image.
- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
	- Should be placed on the right side of the readme heading.
		- Can be placed centered if the list has a centered graphics header.
	- Should link back to this list.
- Has a Table of Contents section.
	- Should be named `Contents`, not `Table of Contents`.
	- Should be the first section in the list.
	- Should only have one level of [nested lists](https://commonmark.org/help/tutorial/10-nestedLists.html), preferably none.
- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
	- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
	- [WTFPL](http://www.wtfpl.net) and [Unlicense](http://unlicense.org) are not acceptable licenses.
	- If you use a license badge, it should be SVG, not PNG.
- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
	- The file should be named `contributing.md`. Casing is up to you.
- Has consistent formatting and proper spelling/grammar.
	- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
	- The description starts with an uppercase character and ends with a period.
	- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.

Go to the top and read it again.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

**Comment by moltar** [comment]
- Move contribution instructions into `contributing.md` file
- Should be named `Contents`, not `Table of Contents`
- Should only have one level of [nested lists](https://commonmark.org/help/tutorial/10-nestedLists.html), preferably none.

**Comment by sindresorhus** [comment]
@oorryy You didn't do a very good/thorough job reviewing this. Please try harder on a different PR. This PR is missing a lot of things.

**Comment by sindresorhus** [comment]
```
❯ awesome-lint https://github.com/eungbean/Awesome-Deep-Vision-v2
✖ Linting

  README.md:437:11
  ✖    1:1    Missing License section                                                             remark-lint:awesome/license
  ✖    1:1    Git repository must be at least 30 days old                                         remark-lint:awesome/git-repo-age
  ✖    1:1    Missing file contributing.md                                                        remark-lint:awesome/contributing
  ✖    1:1    Missing or invalid Table of Contents                                                remark-lint:awesome/toc
  ✖    2:27   Invalid badge source                                                                remark-lint:awesome/badge
  ✖   41:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   41:83   List item link and description must be separated with a dash                        remark-lint:awesome/list-item
  ✖   42:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   42:72   List item link and description must be separated with a dash                        remark-lint:awesome/list-item
  ✖   43:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   43:84   List item link and description must be separated with a dash                        remark-lint:awesome/list-item
  ✖   44:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   44:73   List item link and description must be separated with a dash                        remark-lint:awesome/list-item
  ✖   49:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   49:3    Invalid list item link URL                                                          remark-lint:awesome/list-item
  ✖   50:3    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   50:5    Invalid list item link URL                                                          remark-lint:awesome/list-item
  ✖   51:3    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   51:5    Invalid list item link URL                                                          remark-lint:awesome/list-item
  ✖   52:3    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   52:5    Invalid list item link URL                                                          remark-lint:awesome/list-item
  ✖   53:3    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   53:5    Invalid list item link URL                                                          remark-lint:awesome/list-item
  ✖   54:3    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   54:5    Invalid list item link URL                                                          remark-lint:awesome/list-item
  ✖   55:3    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   55:5    Invalid list item link URL                                                          remark-lint:awesome/list-item
  ✖   56:3    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   56:5    Invalid list item link URL                                                          remark-lint:awesome/list-item
  ✖   57:5    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   57:7    Invalid list item link URL                                                          remark-lint:awesome/list-item
  ✖   58:7    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   58:9    Invalid list item link URL                                                          remark-lint:awesome/list-item
  ✖   59:3    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   59:5    Invalid list item link URL                                                          remark-lint:awesome/list-item
  ✖   60:3    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   60:5    Invalid list item link URL                                                          remark-lint:awesome/list-item
  ✖   61:3    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   61:5    Invalid list item link URL                                                          remark-lint:awesome/list-item
  ✖   62:3    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   62:5    Invalid list item link URL                                                          remark-lint:awesome/list-item
  ✖   63:5    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   63:7    Invalid list item link URL                                                          remark-lint:awesome/list-item
  ✖   64:5    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   64:7    Invalid list item link URL                                                          remark-lint:awesome/list-item
  ✖   65:5    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   65:7    Invalid list item link URL                                                          remark-lint:awesome/list-item
  ✖   66:3    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   66:5    Invalid list item link URL                                                          remark-lint:awesome/list-item
  ✖   67:3    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   67:5    Invalid list item link URL                                                          remark-lint:awesome/list-item
  ✖   68:3    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   68:5    Invalid list item link URL                                                          remark-lint:awesome/list-item
  ✖   69:3    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   69:5    Invalid list item link URL                                                          remark-lint:awesome/list-item
  ✖   70:3    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   70:5    Invalid list item link URL                                                          remark-lint:awesome/list-item
  ✖   71:3    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   71:5    Invalid list item link URL                                                          remark-lint:awesome/list-item
  ✖   72:3    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   72:5    Invalid list item link URL                                                          remark-lint:awesome/list-item
  ✖   73:5    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   73:7    Invalid list item link URL                                                          remark-lint:awesome/list-item
  ✖   74:5    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   74:7    Invalid list item link URL                                                          remark-lint:awesome/list-item
  ✖   75:5    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   75:7    Invalid list item link URL                                                          remark-lint:awesome/list-item
  ✖   76:3    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   76:5    Invalid list item link URL                                                          remark-lint:awesome/list-item
  ✖   77:3    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   77:5    Invalid list item link URL                                                          remark-lint:awesome/list-item
  ✖   78:3    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   78:5    Invalid list item link URL                                                          remark-lint:awesome/list-item
  ✖   79:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   79:3    Invalid list item link URL                                                          remark-lint:awesome/list-item
  ✖   80:3    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   80:5    Invalid list item link URL                                                          remark-lint:awesome/list-item
  ✖   81:3    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   81:5    Invalid list item link URL                                                          remark-lint:awesome/list-item
  ✖   82:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   82:3    Invalid list item link URL                                                          remark-lint:awesome/list-item
  ✖   89:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   90:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   91:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   92:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   93:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   96:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖   97:5    Invalid list item link                                                              remark-lint:awesome/list-item
  ✖   97:5    Found reference to undefined definition                                             remark-lint:no-undefined-references
  ✖   97:127  Found reference to undefined definition                                             remark-lint:no-undefined-references
  ✖   98:78   List item link and description must be separated with a dash                        remark-lint:awesome/list-item
  ✖   99:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖  100:5    Found reference to undefined definition                                             remark-lint:no-undefined-references
  ✖  100:5    Invalid list item link                                                              remark-lint:awesome/list-item
  ✖  101:5    Found reference to undefined definition                                             remark-lint:no-undefined-references
  ✖  101:5    Invalid list item link                                                              remark-lint:awesome/list-item
  ✖  102:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖  103:5    Invalid list item link                                                              remark-lint:awesome/list-item
  ✖  103:5    Found reference to undefined definition                                             remark-lint:no-undefined-references
  ✖  104:5    Invalid list item link                                                              remark-lint:awesome/list-item
  ✖  104:5    Found reference to undefined definition                                             remark-lint:no-undefined-references
  ✖  105:5    Invalid list item link                                                              remark-lint:awesome/list-item
  ✖  105:5    Found reference to undefined definition                                             remark-lint:no-undefined-references
  ✖  106:96   List item link and description must be separated with a dash                        remark-lint:awesome/list-item
  ✖  107:128  List item link and description must be separated with a dash                        remark-lint:awesome/list-item
  ✖  107:153  Found reference to undefined definition                                             remark-lint:no-undefined-references
  ✖  108:89   List item link and description must be separated with a dash                        remark-lint:awesome/list-item
  ✖  109:107  List item link and description must be separated with a dash                        remark-lint:awesome/list-item
  ✖  110:73   List item link and description must be separated with a dash                        remark-lint:awesome/list-item
  ✖  114:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖  115:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖  116:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖  117:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖  118:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖  119:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖  120:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖  121:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖  122:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖  126:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖  127:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖  128:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖  131:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖  131:3    Incorrect indentation before bullet: remove 2 spaces                                remark-lint:list-item-bullet-indent
  ✖  132:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖  132:3    Incorrect indentation before bullet: remove 2 spaces                                remark-lint:list-item-bullet-indent
  ✖  133:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖  133:3    Incorrect indentation before bullet: remove 2 spaces                                remark-lint:list-item-bullet-indent
  ✖  134:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖  134:3    Incorrect indentation before bullet: remove 2 spaces                                remark-lint:list-item-bullet-indent
  ✖  136:3    Remove empty section: "Books"                                                       remark-lint:no-empty-sections
  ✖  137:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖  137:4    Incorrect indentation before bullet: remove 2 spaces                                remark-lint:list-item-bullet-indent
  ✖  137:6    Incorrect list-item indent: remove 1 space                                          remark-lint:list-item-indent
  ✖  141:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖  141:3    Incorrect indentation before bullet: remove 2 spaces                                remark-lint:list-item-bullet-indent
  ✖  145:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖  151:5    Invalid list item link                                                              remark-lint:awesome/list-item
  ✖  151:5    Found reference to undefined definition                                             remark-lint:no-undefined-references
  ✖  152:3    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖  169:52   Found reference to undefined definition                                             remark-lint:no-undefined-references
  ✖  170:1    Link to https://pdfs.semanticscholar.org/.../c4000f5c71c22fb4a22fcf5dd0... is dead  remark-lint:no-dead-urls
  ✖  223:82   Link to http://202.118.75.4/lu/Paper/ICCV2015/iccv15_lijun.pdf is dead              remark-lint:no-dead-urls
  ✖  246:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖  255:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖  292:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖  302:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖  309:88   Found reference to undefined definition                                             remark-lint:no-undefined-references
  ✖  361:67   Link to http://www.cs.cmu.edu/~xinleic/papers/cvpr15_rnn.pdf is dead                remark-lint:no-dead-urls
  ✖  415:54   Link to http://www.cs.toronto.edu/~mren/imageqa/data/cocoqa/ is dead                remark-lint:no-dead-urls
  ✖  432:3    Incorrect indentation before bullet: remove 2 spaces                                remark-lint:list-item-bullet-indent
  ✖  434:3    Remove empty section: "Image Generation"                                            remark-lint:no-empty-sections
  ✖  435:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖  435:3    Incorrect indentation before bullet: remove 2 spaces                                remark-lint:list-item-bullet-indent
  ✖  437:11   Checkboxes should be followed by a single character                                 remark-lint:checkbox-content-indent
  ✖  438:11   Checkboxes should be followed by a single character                                 remark-lint:checkbox-content-indent
  ✖  439:1    Marker style should be *                                                            remark-lint:unordered-list-marker-style
  ✖  439:3    Incorrect indentation before bullet: remove 2 spaces                                remark-lint:list-item-bullet-indent
  ✖  440:5    Don’t pad emphasis with inner spaces                                                remark-lint:no-inline-padding
  ✖  440:7    Found reference to undefined definition                                             remark-lint:no-undefined-references
  ✖  441:7    Found reference to undefined definition                                             remark-lint:no-undefined-references
  ✖  442:5    Don’t pad emphasis with inner spaces                                                remark-lint:no-inline-padding
  ✖  442:7    Found reference to undefined definition                                             remark-lint:no-undefined-references
  ✖  443:7    Found reference to undefined definition                                             remark-lint:no-undefined-references
  ✖  444:5    Don’t pad emphasis with inner spaces                                                remark-lint:no-inline-padding
  ✖  444:7    Found reference to undefined definition                                             remark-lint:no-undefined-references
  ✖  445:7    Found reference to undefined definition                                             remark-lint:no-undefined-references
  ✖  446:5    Don’t pad emphasis with inner spaces                                                remark-lint:no-inline-padding
  ✖  446:7    Found reference to undefined definition                                             remark-lint:no-undefined-references
  ✖  447:7    Found reference to undefined definition                                             remark-lint:no-undefined-references
  ✖  448:5    Don’t pad emphasis with inner spaces                                                remark-lint:no-inline-padding
  ✖  448:7    Found reference to undefined definition                                             remark-lint:no-undefined-references
  ✖  449:7    Found reference to undefined definition                                             remark-lint:no-undefined-references
  ✖  451:1    Code blocks should be fenced                                                        remark-lint:code-block-style
  ✖  455:7    Found reference to undefined definition                                             remark-lint:no-undefined-references
  ✖  457:1    Code blocks should be fenced                                                        remark-lint:code-block-style
  ✖  480:1    Code blocks should be fenced                                                        remark-lint:code-block-style
  ✖  505:3    Remove 2 spaces before this heading                                                 remark-lint:no-heading-indent
  ✖  506:3    Incorrect indentation before bullet: remove 2 spaces                                remark-lint:list-item-bullet-indent
  ✖  506:5    Invalid list item link                                                              remark-lint:awesome/list-item
  ✖  506:5    Found reference to undefined definition                                             remark-lint:no-undefined-references
  ✖  507:3    Incorrect indentation before bullet: remove 2 spaces                                remark-lint:list-item-bullet-indent
  ✖  507:5    Found reference to undefined definition                                             remark-lint:no-undefined-references
  ✖  507:5    Invalid list item link                                                              remark-lint:awesome/list-item
  ✖  507:72   Text "github" should be written as "GitHub"                                         remark-lint:awesome/spell-check

  184 errors
```

https://github.com/sindresorhus/awesome-lint

**Comment by sindresorhus** [comment]
@eungbean Closing as your list is less than 30 days and **very** far from being accepted to the Awesome repo. Please put more work into it, especially when it comes to following the guidelines, formatting, fixing typos (you have a lot of those).

**Pull request closed without merging**
