### PR TITLE
Add JavaScript Design Patterns list

### PR DESCRIPTION
**Pull request by mazzur**
I haven't found such collection among the awesome lists, so I've started working on my own. It's far from being complete yet, but it already might be usuful for someone trying to grasp desing patterns in JavaScript.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please read the [instructions](https://github.com/sindresorhus/awesome/blob/master/create-list.md) for creating a new list, [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

Especially this part:

> Wait at least a couple of weeks after creating a list before submitting to give it a chance to mature.

Ping me here in a few weeks and I'll reopen ;)

**Comment by sindresorhus** [comment]
The list will also need more content before being accepted.

**Comment by mazzur** [comment]
@sindresorhus it's been few weeks, the [list](https://github.com/mazzur/awesome-javascript-design-patterns) has grown and matured a bit, so you might consider reopenning.

**Comment by aleksandar-todorovic** [comment]
From awesome manifesto:

> ## Comment on why something is awesome
> Apart from suggesting a particular item on your list, you should also inform your readers why it's on the list and how they will benefit from it.

I don't see any comments on why the things posted there are awesome.

**Comment by mazzur** [comment]
@aleksandar-todorovic, the listed resources are all awesome in the same thing - explaining design pattern(s) stated in their titles, which I mentioned in the repo description. But you're right, specific reasons for adding them to the list would be a benefit for the readers and an additional  filter for not-that-awesome stuff.

**Pull request closed without merging**
