### PR TITLE
Add React Components

### PR DESCRIPTION
**Pull request by brillout**
My first curated list 😊 :sparkles:  

**https://github.com/brillout/awesome-react-components**

**React Components, categorized**

- [x] I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- [x] This pull request has a descriptive title.
- The list I added
	- [x] **has been around for at least 20 days,**
	- [x] is not a duplicate,
	- [x] only has awesome items with descriptions,
	- [x] contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- [x] has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license),
	- [x] has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- [x] has been checked for inconsistent formatting, spelling and grammar, and
	- [x] has been added at the bottom of the appropriate category.

### CODE REVIEW

**Comment by sindresorhus** [comment]
This is already covered by https://github.com/enaqx/awesome-react#components though. Maybe you could collaborate with them somehow?

// @browniefed @enaqx

**Comment by brillout** [comment]
Collaboration would be great. There are so many react components out there. It's astonishing.

I'd like the awesome-react-components list to not include learning material. I would therefore not merge both list. They serve two distinct use cases;
 - If I want to learn about React then I go to awesome-react
 - If I'm write code and I need a specific component then I go to awesome-react-components

I like the idea of keeping things small, "do one thing and do it well".

Although, there are some components that are innovative and stumbling upon them represents a learning experience. See the creative section https://github.com/brillout/awesome-react-components#creative-things. For example, when I first stumbled upon `react-virtualized`, I learnt about the idea of lazy loaded tables. Therefore the creative things section would make sense in awesome-react.

@browniefed @enaqx what do you think?

@sindresorhus thanks for the feedback :)

**Comment by browniefed** [comment]
No opinion here :), there are a lot of resources out there like react.rocks, js.coach, etc that list both just components, resources, or a mix a both.
The more the merrier.

**Comment by hatzopoulos** [comment]
Nice list @brillout !

> has been around for at least 20 days,

Looking at the commit history, it would seem like this has only been up on github for 3 days.

> is not a duplicate

Since the other list, https://github.com/enaqx/awesome-react#components contains components I would consider this a duplicate because eventually the components list will just be a variation of the of the other. 

> Collaboration would be great

Yes! It would be really nice if your efforts were combined into that already awesome list of react stuff. The way you have categorized the components is great. It would be awesome if that categorization found its way into the `awesome-react` list. 

Whether I am learning react for the first time or a veteran using the list as a toolbox resource, having one one list is great for both cases.

Alternatively perhaps the `awesome-react` list can remove the components list all together and just link to your `awesome-react-components` list, but for that it would be nice if you merged any missing components into your list.

**Comment by browniefed** [comment]
If you're interested we can just add you as a maintainer and you can help out with the `aweseome-react` repo if that interests you at all.

**Comment by brillout** [comment]
@hatzopoulos 

> Nice list

thanks :)

> this has only been up on github for 3 days.

Yes, it's on GitHub since 3 days only. I've started creating it ~2 months ago though.
I've interpreted "has been around for at least 20 days" as "has been alive for at least 20 days". If it means "has been public for at least 20 days" then I'll uncheck the checkbox and close the PR.

> The way you have categorized the components is great

I see categorization to be super important.
Actually, I think that sections that have more then ~15 items should systematically be broken down into sub-sections.
And I could see that to be a meaningful rule for creating Awesome Lists.
@sindresorhus what do you think?

> It would be really nice if your efforts were combined into that already awesome list of react stuff

I'd love to "join forces".

> Whether I am learning react for the first time or a veteran using the list as a toolbox resource, having one one list is great for both cases

I struggle with the idea of having only one React list that includes both learning material and components.
Personally, I am more interested in the components part and less in the learning material part.
I can see other people to be also interested in only either one.
Having `awesome-react` and `awesome-react-components` would allow one to watch either one or both.
I'm considering implementing automated manipulations on the list (show number of GitHub stars for every component, sort components after repository creation date and GitHub stars, etc.). In that context it would feel cluttered to apply automation on only a subset of a huge list.

> would be nice if you merged any missing components into your list.

Yes. Although I consider some of the components to be low quality and I would discard them.

<br/>

@browniefed 

> If you're interested we can just add you as a maintainer

Thanks and yes I'd be up for that!
Since we would be 3 maintainers, maybe we should create a GitHub organization then?

**Comment by sindresorhus** [comment]
> Actually, I think that sections that have more than ~15 items should systematically be broken down into sub-sections. And I could see that to be a meaningful rule for creating Awesome Lists. @sindresorhus what do you think?

Hard to find a number in scenarios. Common sense should work here.

> I'd love to "join forces".

👌

**Pull request closed without merging**
