### PR TITLE
Add ActionScript 3

### PR DESCRIPTION
**Pull request by hgupta9**
**https://github.com/hgupta9/awesome-actionscript3/**

**Awesome tools, libraries and components for ActionScript 3 and Adobe AIR.** 

I have complied with the below requirements:
1. Created 30+ days ago (Jun 10th). 60 commits. Hand curated.
2. Result of hard work and truly the best I could make it. 
3. Only has awesome items.
4. Not a duplicate.
5. Has a TOC. Well categorized. Has a logo of Flash & AIR on top-right.
6. All entries have a hand-written description, not just a copy-paste from the project.
7. All entries are FOSS unless specified in the section heading (only a few tools are Commercial)
8. Has consistent formatting 
9. No travis badge in the readme

### CODE REVIEW

**Comment by sindresorhus** [comment]
Good job, but many of the requirements are not followed. Read https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md more thoroughly.

**Comment by hgupta9** [comment]
Can you be somewhat more specific? You mean the descriptions need to be cleaned up? The casing? Spacing? What??

**Comment by sindresorhus** [comment]
Just go through each point and check that you've done it.

**Comment by hgupta9** [comment]
Why can't you just specify and make it simpler for both of us? Please? I fixed the license thing.

**Comment by hgupta9** [comment]
What, you want me to take away all the double categories and make it just a single set of categories?

**Comment by hgupta9** [comment]
- [x]  Has been around for at least 30 days.
- [x]   That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
- [x]  It's the result of hard work and the best I could possibly produce.
- [x]   Non-generated Markdown file in a GitHub repo.
- [x]  Includes a succinct description of the project/theme at the top of the readme. (Example)
- [x]  The repo should have awesome-list & awesome as GitHub topics. I encourage you to add more relevant topics.
- [x]  Not a duplicate.
- [x]  Only has awesome items. Awesome lists are curations of the best, not everything.
- [x]  Includes a project logo/illustration whenever possible.
- [x]   Placed at the top-right of the readme. (Example)
- [x]   The image should link to the project website or any relevant website.
- [x]   The image should be high-DPI. Set it to maximum half the width of the original image.
- [x]  Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- [x]   Has the Awesome badge on the right side of the list heading,
- [x]  Has a Table of Contents section.
- [x]   Should be named Contents, not Table of Contents.
- [x]   Should be the first section in the list.
- [x]    Should only have one level of sub-lists, preferably none.
- [x]   Has an appropriate license.
- [x]  That means something like CC0, not a code licence like MIT, BSD, Apache, etc.
- [x]   Has contribution guidelines.
- [x]   The file should be named contributing.md. Casing is up to you.
- [x]   Has consistent formatting and proper spelling/grammar.
- [x]   Each link description starts with an uppercase character and ends with a period.
- [x]    Example: - [AVA](…) - JavaScript test runner.
- [x]   Drop all the A / An prefixes in the descriptions.
- [x]    Consistent and correct naming. For example, Node.js, not NodeJS or node.js.
- [x]   Doesn't include a Travis badge.

**Comment by Jogai** [comment]
> Why can't you just specify and make it simpler for both of us? Please? I fixed the license thing.

Maintaining is a lot of work. He has no time to point out the issues for every pr.

**Comment by sindresorhus** [comment]
Many of the descriptions starts with `AS3`, but that is moot as it's implied.

**Comment by hgupta9** [comment]
Thank you for replying!!

**Comment by hgupta9** [comment]
**Done.**
- [x] The TOC doesn't need to list every sub-section, just the main ones.
- [x] Has the Awesome badge on the right side of the list heading
- [x] Includes a succinct description of the project/theme at the top of the readme
- [x] Heading: awesome-actionscript3 => Awesome ActionScript 3
- [x] The image should be high-DPI. Set it to maximum half the width of the original image.

**Not done.**
> The entry in the Awesome list should: Include a short description about the project/theme of the list. 

Most of the other languages don't have a description (eg JS, .NET) so I followed that scheme. AS3 is a very wide language like .NET, meaning you can build apps, games, libs and whatnot so I cannot possibly summarize it in 5 words. I hope thats ok.

**In progress**
> Each link description starts with an uppercase character and ends with a period.

**Comment by hgupta9** [comment]
**All done.**
- [x] Each link description starts with an uppercase character and ends with a period.

@sindresorhus 
Can you check if it meets your standards?

https://github.com/hgupta9/awesome-actionscript3/

**Comment by hgupta9** [comment]
@sindresorhus
Are there any more issues with this?

**Comment by sindresorhus** [comment]
Linkify `ActionScript 3` and `Adobe AIR` in the readme description to their Wikipedia pages.

---

> Most of the other languages don't have a description (eg JS, .NET) so I followed that scheme. AS3 is a very wide language like .NET, meaning you can build apps, games, libs and whatnot so I cannot possibly summarize it in 5 words. I hope thats ok.

Can simply be something like:

> Object-oriented language targeting Adobe AIR.

**Comment by hgupta9** [comment]
**Done.**
- [x] Linkify ActionScript 3 and Adobe AIR in the readme description to their Wikipedia pages.
- [x] Object-oriented language targeting Adobe AIR.

Can you merge it now?

**Comment by hgupta9** [comment]
Thank you!

**Pull request merged**
