### PR TITLE
Add Text Editing

### PR DESCRIPTION
**Pull request by dok**

### CODE REVIEW

**Comment by davisonio** [comment]
I think it'd be best to leave this for a bit for it to mature and get a few more resources added to the list. 

Could you add a license (preferably CC0) and some contributing guidelines in the meantime?

**Comment by dok** [comment]
Sure thing. Thanks for the feedback. I'll make some updates tomorrow.

**Comment by sindresorhus** [comment]
Please read the [instructions](https://github.com/sindresorhus/awesome/blob/master/create-list.md) for creating a new list, [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

Especially this part:

> Wait at least a couple of weeks after creating a list before submitting to give it a chance to mature.

The list will need a lot of work to be accepted. Ping me here when it's in a better shape, at the earliest in a couple of weeks, and I'll reopen ;)

**Comment by dok** [comment]
Hey @sindresorhus, thanks for the suggestions. Could you take another gander at this repo? Please let me know if you want me to make any changes to the list.

Thanks!

**Comment by sindresorhus** [comment]
Sure. Please read https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license. MIT is not a good non-code license.

You also need to fix the merge conflict. (Don't open a new PR for that)

**Comment by dok** [comment]
@sindresorhus thanks for the review. I changed the license to CC0 as you suggested and fixed the merge conflict.

**Pull request closed without merging**
