### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by rahulkapoor90**
Added Better java in miscellaneous section.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please read the [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

**Comment by rahulkapoor90** [comment]
Can i know what's wrong.

**Comment by sindresorhus** [comment]
Yes, by actually reading it.

**Comment by rahulkapoor90** [comment]
Yes, fair enough but is that because it doesn't has contribution.md file and i haven't mentioned why is it awesome in pull request description?

**Pull request closed without merging**
