### PR TITLE
Add `For Girls`

### PR DESCRIPTION
**Pull request by cristianoliveira**
aweasome4Girls is a list of awesome inclusive events/projects/initiatives for women in the tech area. This list brings some good resources where girls/women can find good places for starting in Tech area. :D 

I followed guidelines for contributing since close of issue #424. (Well I think I did.)

Feel free to review.

### CODE REVIEW

**Comment by sindresorhus** [comment]
I don't think `awesome4girls` is a good list title. Maybe something like `For Girls`?

// @davisonio

**Comment by cristianoliveira** [comment]
Hey @davisonio.
What is the matter with the title? Is the 4Somenthing?
Cause we've created this based in other greate projects that we have here in Brazil that is Js4Girls.

**Comment by cristianoliveira** [comment]
PS. @sindresorhus liked the idea first time I suggested. :/

**Comment by uratang** [comment]
예
2016. 1. 19. 오전 5:18에 "Sindre Sorhus" <notifications@github.com>님이 작성:

**Comment by davisonio** [comment]
The "Awesome" part of the title is redundant so I don't think we should have it. (i.e. It's 

You don't need to change anything in the respository just change `[Awesome4Girls](https://github.com/cristianoliveira/awesome4girls)` to `For Girls` or maybe `4Girls`.

**Comment by cristianoliveira** [comment]
Oh I got it. I'm going to change it

**Comment by sindresorhus** [comment]
Can you also fix the merge conflict.

**Comment by cristianoliveira** [comment]
Done both
.

**Comment by cristianoliveira** [comment]
Done both.

**Pull request closed without merging**
