### PR TITLE
Add Nim to programming languages

### PR DESCRIPTION
**Pull request by MartinSeeler**
https://github.com/VPashkov/awesome-nim

Nim is an efficient and growing programming language and should be noticed by more people.

### CODE REVIEW

**Comment by vitalkanev** [comment]
Please review https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md  . Many of the rules are **not followed**

**Comment by sindresorhus** [comment]
Ping :)

**Comment by sindresorhus** [comment]
// @VPashkov

**Comment by VPashkov** [comment]
@sindresorhus, I made some changes in [awesome-nim repo](https://github.com/VPashkov/awesome-nim). Please, see if it's enough.

**Comment by legodude17** [comment]
Not done:
- Drop starting `A` / `An` in descriptions

**Comment by VPashkov** [comment]
I think it's no longer a requirement - https://github.com/sindresorhus/awesome/commit/38fe46962507c035d2cfdbc95f78186f6c529991#diff-081a901bcd6f61bef29110a1bc408818L50
But I removed starting A / An in descriptions.

**Comment by VPashkov** [comment]
Unfortunately, I can't rebase PR which is not mine.
@MartinSeeler , could you please rebase this PR?

**Comment by MartinSeeler** [comment]
Sure, done 👍

**Comment by sindresorhus** [comment]
Hey, sorry for the lack of response, please see #1363.

**Comment by sfischer13** [comment]
There are still several issues, e.g. there is no license section. You can also use [awesome-lint](https://github.com/sindresorhus/awesome-lint) for finding more issues.

**Comment by sindresorhus** [comment]
Closing for lack of response. Feel free to open a new PR if you ever get around to fixing the above mentioned issues and ensure you're following the Awesome guidelines :)

**Pull request closed without merging**
