### PR TITLE
Add CLI Apps

### PR DESCRIPTION
**Pull request by aharris88**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks for the suggestion :)

Please read the [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

**Comment by sindresorhus** [comment]
Why did you close?

**Comment by aharris88** [comment]
I'm going to work on it a bit, and then reopen it. Since you linked to the guidelines and the manifest I just thought I must have gotten something not quite right. So I'm going to check it out.

**Comment by sindresorhus** [comment]
Ok, just ping me when you want it reopened.

**Comment by aharris88** [comment]
https://github.com/aharris88/awesome-cli-apps

I believe that this is different enough from https://github.com/herrbischoff/awesome-osx-command-line, which focuses more on commands that you can run in the command line.

I also believe that it's different enough from https://github.com/alebcay/awesome-shell, which only has a small section devoted to apps.

**Comment by sindresorhus** [comment]
:+1: Can you update the name and URL?

**Comment by aharris88** [comment]
Done. :+1:

**Pull request closed without merging**
