### PR TITLE
Add Stockfree to awesome resources list

### PR DESCRIPTION
**Pull request by ravisuhag**

### CODE REVIEW

**Comment by sindresorhus** [comment]
This already exists:

- [Images](https://github.com/heyalexej/awesome-images)
- [Stock Resources](https://github.com/neutraltone/awesome-stock-resources)

How is yours any different?

**Comment by ravisuhag** [comment]
I curated this long time back but didn't submit. Have updated it to be very extensive. But yes I agree, It is not very differnent from already avaiable. Feel free to close the request if you think it won't be helpful.

**Comment by sindresorhus** [comment]
Yeah, sorry, too similar. I would recommend you contribute missing things to "Stock Resources". That would benefit everyone :)

// @neutraltone

**Comment by ravisuhag** [comment]
sure :)

**Pull request closed without merging**
