### PR TITLE
Add Neovim

### PR DESCRIPTION
**Pull request by tversteeg**
https://github.com/rockerBOO/awesome-neovim

This list lists plugins for the neovim text editor.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

**Comment by stn1slv** [comment]
You have missed unicorn and check the license for the repo.

**Comment by tversteeg** [comment]
`unicorn`

**Comment by sindresorhus** [comment]
> Includes a succinct description of the project/theme at the top of the readme. (Example) - https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md

**Comment by sindresorhus** [comment]
> The link and description are separated by a dash. 
Example: - [AVA](…) - JavaScript test runner.
The description starts with an uppercase character and ends with a period.

Some items are not in this format.

**Comment by sindresorhus** [comment]
Bump

**Comment by tversteeg** [comment]
> > The link and description are separated by a dash.
> > Example: - [AVA](%E2%80%A6) - JavaScript test runner.
> > The description starts with an uppercase character and ends with a period.
> 
> Some items are not in this format.

FIxed this.

> Includes a succinct description of the project/theme at the top of the readme. (Example) - [`main`/pull_request_template.md](https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md?rgh-link-date=2021-10-04T06%3A39%3A51Z)

I don't understand this. Isn't "Collections of awesome Neovim plugins. Mostly targeting Neovim specific features." succinct enough?

**Comment by sindresorhus** [comment]
> I don't understand this. Isn't "Collections of awesome Neovim plugins. Mostly targeting Neovim specific features." succinct enough?

Yes, but it doesn't actually describe what it's asking for. It's asking for a description of the project/theme, not what the list contains. Please look at the examples in the guidelines.

**Comment by tversteeg** [comment]
Understood, is the current description good enough?

**Comment by sindresorhus** [comment]
Tweet: https://twitter.com/awesome__re/status/1464095955846791171

**Pull request merged**
