### PR TITLE
Changed "awesome-cryptography" link

### PR DESCRIPTION
**Pull request by sobolevn**
https://github.com/sobolevn/awesome-cryptography

`awesome-cryptography` is all about cryptography and encryption.

It has all started with [this issue](https://github.com/sindresorhus/awesome/issues/663). I have requested a new list about `encryption`, soon I have found [`retter`](https://github.com/MaciejCzyzewski/retter), which seemed to be an `awesome-cryptography` list. 

With all the respect to the author, his great work, and the content itself, `retter` is not an `awesome-list`. It is a collection of different implementations of cryptography algorithms in `C`, and a structured folder of bookmarks.

That was an original reason I have started my own list. But, I can also add the fact `retter` was not updated for 10 month now.

Things I have improved in my list:

- [x] Follows `awesome` format ("flat is better than nested")
- [x] Has a bunch of integrations to keep people interested: [twitter](https://twitter.com/awe_crypto_bot) and [gitter](https://gitter.im/sobolevn/awesome-cryptography)
- [x] Integrated `remark-lint` with [a lot of style-checks](https://github.com/sobolevn/awesome-cryptography/blob/master/package.json#L31)
- [ ] `awesome-lint` [WIP](https://github.com/sobolevn/awesome-cryptography/issues/24)

I have not found any recommendations or rules about this particular situation. Anyway it is up to you to make the final decision.

## Checkboxes

- [x] I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- [x] This pull request has a descriptive title.
- The list I added
	- [x] **has been around for at least 20 days,**
	- [x] is a non-generated Markdown file in a GitHub repo,
	- [ ] is not a duplicate,
	- [x] only has awesome items with descriptions,
	- [x] contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- [x] has a Table of Contents section named `Contents` as the first section,
	- [x] has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license),
	- [x] has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- [x] has been checked for inconsistent formatting, spelling, and grammar,
	- [ ] has been added at the bottom of the appropriate category.

### CODE REVIEW

**Comment by davisonio** [comment]
Good stuff, it seems that the previous list has changed format and is no longer an awesome list and this is a good replacement.

**Comment by sindresorhus** [comment]
I'm good with adding this.

Some nitpick:

- There should be no empty lines between the Table of Contents entries
- All descriptions should start with an uppercase letter and end in a `.`

**Comment by sobolevn** [comment]
Refactored ([commit](https://github.com/sobolevn/awesome-cryptography/commit/62788880194b982a928ccd2fc76341c65b22bb26)).

**Comment by sindresorhus** [comment]
Looks good :)

**Pull request merged**
