### PR TITLE
Added list of landing page resources to business category

### PR DESCRIPTION
**Pull request by Langhalsdino**
Added, https://github.com/eibrahim/landing-pages-resources, a list of landing page resources to business category.

[Awesome landing page resources](https://github.com/eibrahim/landing-pages-resources)

This list contains a lot of use full resources for the creation of landing pages.
It covers books, blogs, platforms and online courses to give a full overview on the topic.

# By submitting this pull request I confirm I've read and complied with the below requirements.

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title.<br>For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
	- Be added at the bottom of the appropriate category.
- The list I'm submitting complies with these requirements:
	- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
	- It's the result of hard work and the best I could possibly produce.
	- Non-generated Markdown file in a GitHub repo.
	- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
	- Not a duplicate.
	- Only has awesome items. Awesome lists are curations of the best, not everything.
	- Includes a project logo/illustration whenever possible.
		- Either fullwidth or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
		- The image should link to the project website or any relevant website.
		- The image should be high-DPI. Set it to maximum half the width of the original image.
	- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
	- Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
		- Should be placed on the right side of the readme heading.
		- Should link back to this list.
	- Has a Table of Contents section.
		- Should be named `Contents`, not `Table of Contents`.
		- Should be the first section in the list.
		- Should only have one level of sub-lists, preferably none.
	- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
		- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
		- If you use a license badge, it should be SVG, not PNG.
	- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
		- The file should be named `contributing.md`. Casing is up to you.
	- Has consistent formatting and proper spelling/grammar.
		- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
		- The description starts with an uppercase character and ends with a period.
		- Drop all the `A` / `An` prefixes in the descriptions.
		- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
	- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.
- Go to the top and read it again.

### CODE REVIEW

**Comment by Jogai** [comment]
The anchors of the ToC aren't working

**Comment by Langhalsdino** [comment]
Thank you, fixed the issue in new pull request 👍 
https://github.com/eibrahim/landing-pages-resources/pull/8

**Comment by sindresorhus** [comment]
Hey, sorry for the lack of response, please see #1363.

**Comment by sindresorhus** [comment]
```
❯ awesome-lint https://github.com/eibrahim/landing-pages-resources
✖ Linting

  README.md:7:3
  ✖    1:1    Missing or invalid Table of Contents                                                                          remark-lint:awesome/toc
  ✖    1:64   Invalid badge source                                                                                          remark-lint:awesome/badge
  ✖    7:3    Incorrect indentation before bullet: remove 2 spaces                                                          remark-lint:list-item-bullet-indent
  ✖    7:5    Invalid list item link URL                                                                                    remark-lint:awesome/list-item
  ✖    8:3    Incorrect indentation before bullet: remove 2 spaces                                                          remark-lint:list-item-bullet-indent
  ✖    8:5    Invalid list item link URL                                                                                    remark-lint:awesome/list-item
  ✖    9:3    Incorrect indentation before bullet: remove 2 spaces                                                          remark-lint:list-item-bullet-indent
  ✖    9:5    Invalid list item link URL                                                                                    remark-lint:awesome/list-item
  ✖   10:3    Incorrect indentation before bullet: remove 2 spaces                                                          remark-lint:list-item-bullet-indent
  ✖   10:5    Invalid list item link URL                                                                                    remark-lint:awesome/list-item
  ✖   11:3    Incorrect indentation before bullet: remove 2 spaces                                                          remark-lint:list-item-bullet-indent
  ✖   11:5    Invalid list item link URL                                                                                    remark-lint:awesome/list-item
  ✖   12:3    Incorrect indentation before bullet: remove 2 spaces                                                          remark-lint:list-item-bullet-indent
  ✖   12:5    Invalid list item link URL                                                                                    remark-lint:awesome/list-item
  ✖   13:3    Incorrect indentation before bullet: remove 2 spaces                                                          remark-lint:list-item-bullet-indent
  ✖   13:5    Invalid list item link URL                                                                                    remark-lint:awesome/list-item
  ✖   18:39   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   19:35   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   20:41   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   21:46   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   22:35   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   25:196  List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   26:43   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   27:41   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   28:50   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   29:37   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   30:38   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   31:54   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   32:37   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   33:3    Link to http://www.incomepress.com/freelandingpagegenerator is dead                                           remark-lint:no-dead-urls
  ✖   33:70   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   34:62   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   35:77   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   36:48   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   37:43   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   38:56   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   39:29   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   40:35   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   41:3    Link to https://www.simplycast.com/software/landing-page-generator is dead                                    remark-lint:no-dead-urls
  ✖   41:76   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   42:39   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   43:44   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   44:54   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   45:46   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   46:31   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   47:46   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   48:34   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   49:3    Link to https://pop.co/%23 is dead                                                                            remark-lint:no-dead-urls
  ✖   49:31   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   50:52   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   51:40   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   52:91   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   53:36   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   54:61   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   55:3    Link to http://undelay.io is dead                                                                             remark-lint:no-dead-urls
  ✖   55:32   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   56:39   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   57:46   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   58:41   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   59:43   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   63:40   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   64:30   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   65:61   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   66:35   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   67:35   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   68:37   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   69:40   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   73:91   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   74:97   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   75:40   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   76:81   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   77:76   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   78:3    Link to https://athemes.com/collections/best-landing-page-wordpress-themes/%23 is dead                        remark-lint:no-dead-urls
  ✖   78:85   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   79:69   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   80:65   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   81:73   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   82:3    Link to https://shapebootstrap.net/html-templates/landing-pages is dead                                       remark-lint:no-dead-urls
  ✖   82:77   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   83:58   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   84:81   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   85:74   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   86:77   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   87:68   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   88:80   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   89:60   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   90:59   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   91:88   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   92:40   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   93:49   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   94:54   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   95:3    Link to https://codecanyon.net/item/parallax-gravity-landing-page-builder/6899707?ref%3Dtnsblog is dead       remark-lint:no-dead-urls
  ✖   95:110  List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   96:40   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   97:40   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   98:107  List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖   99:104  List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  100:96   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  101:99   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  102:85   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  103:35   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  107:54   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  108:35   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  109:44   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  110:50   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  111:45   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  112:59   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  113:48   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  114:46   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  115:3    Link to https://www.optimizely.com/&sa=D&ust=1507602582983000&usg=AFQjCNGpcPvalCPFkz4wBOs_T-m7AHTxnQ is dead  remark-lint:no-dead-urls
  ✖  115:110  List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  116:46   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  117:37   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  118:40   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  119:36   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  120:3    Link to https://www.reachforce.com/marketsmarter is dead                                                      remark-lint:no-dead-urls
  ✖  120:58   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  121:39   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  125:51   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  126:48   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  127:63   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  128:49   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  129:48   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  130:43   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  131:46   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  132:60   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  133:35   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  134:54   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  135:46   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  136:43   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  137:49   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  138:43   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  139:46   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  140:56   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  144:74   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  145:38   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  146:82   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  147:3    Link to http://sitetuners.com/resources/podcasts is dead                                                      remark-lint:no-dead-urls
  ✖  147:58   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  148:60   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  149:71   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  150:82   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  151:73   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  152:3    Link to http://www.digitalmarketer.com/landing-page-conversion-rate is dead                                   remark-lint:no-dead-urls
  ✖  152:82   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  153:78   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  154:55   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  155:80   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  159:3    Link to https://www.udemy.com/crank-out-high-converting-squeeze-pages-in-record-time is dead                  remark-lint:no-dead-urls
  ✖  159:112  List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  160:3    Link to https://www.udemy.com/crank-out-high-converting-squeeze-pages-in-record-time is dead                  remark-lint:no-dead-urls
  ✖  160:108  List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  161:3    Link to https://www.udemy.com/the-perfect-landing-page-boost-your-conversions is dead                         remark-lint:no-dead-urls
  ✖  161:100  List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  162:3    Link to https://www.udemy.com/the-complete-course-on-building-killer-landing-pages is dead                    remark-lint:no-dead-urls
  ✖  162:105  List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  163:3    Link to https://www.udemy.com/v2-optinsqueeze-page-creation-new-leads-in-48-hours is dead                     remark-lint:no-dead-urls
  ✖  163:101  List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  167:74   List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  168:151  List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  172:146  List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item
  ✖  173:179  List item link and description must be separated with a dash                                                  remark-lint:awesome/list-item

  162 errors
```

https://github.com/sindresorhus/awesome-lint

**Comment by sindresorhus** [comment]
// @eibrahim

**Comment by eibrahim** [comment]
> // @eibrahim

Thanks, do I need to fix it or is this just an FYI?

**Comment by sindresorhus** [comment]
Yes, you need to fix it.

**Comment by sindresorhus** [comment]
Closing for lack of response.

**Pull request closed without merging**
