### PR TITLE
Added linux

### PR DESCRIPTION
**Pull request by MCSH**
* Added linux awesome list

### CODE REVIEW

**Comment by sindresorhus** [comment]
There's almost no content in that list. Gonna go with https://github.com/sindresorhus/awesome/issues/188#issuecomment-113938571 instead.

**Comment by MCSH** [comment]
I respect your opinion but, there is a technical difference there, that one is about Linux distributions this is about Linux packages.

**Comment by sindresorhus** [comment]
Show that in the list, not in words here, and I'll reconsider including it in the future. Might be worth narrowing down the scope to a niche in the Linux world ;)

**Comment by aleksandar-todorovic** [comment]
@MCSH No, my list is _not_ about the distributions. I just added top 10 distributions to the list (I used Distrowatch's top 10 in the last 12 months) and I have no intention of including any more of them (and I included this as a warning in the `CONTRIBUTING.md` file). Making an awesome-linux list about Linux distributions is no way productive and could lead to nothing but "fanboyism". But I really do think that any awesome-linux repository should include some kind of a list of distributions.

Having that said, my list is currently focused on the learning resources. I am planning to expand it to include applications, windows managers and desktop environments as well, but I have to be extremely careful not to recommend anything I didn't test on my own (hence why I am not able to add a lot of entries on my own). After all, I can't say something is awesome if I haven't tested it out myself.

If you're interested, we could work on combining those two lists together into a single one.

**Comment by MCSH** [comment]
Forgive my ignorance,  I said what I saw in the first glance.

I'd be happy to contribute to your list then :)

**Pull request closed without merging**
