### PR TITLE
Added Awesome Email Newsletters List

### PR DESCRIPTION
**Pull request by vredniy**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please read and adhere to https://github.com/sindresorhus/awesome/blob/master/contributing.md and https://github.com/sindresorhus/awesome/blob/master/awesome.md

Not interested in a new category for this. Could go under `Entertainment`, `Learn` or `Misc`.

**Comment by vredniy** [comment]
Thank you for your response. Fixed.

**Comment by sindresorhus** [comment]
I don't think you read https://github.com/sindresorhus/awesome/blob/master/awesome.md It's still missing a license and contribution guidelines.

**Comment by vredniy** [comment]
I hope everything is good now. Can you please check it?

**Comment by sindresorhus** [comment]
Looks good. Thanks :)

**Comment by vredniy** [comment]
Thank you :+1:

**Pull request merged**
