### PR TITLE
Add an '.md' file which attaches repo info (stars, pushed at)

### PR DESCRIPTION
**Pull request by chaconnewu**
I collected all the GitHub repositories info from README.md via GitHub API, and attached the number of stars and last pushed at for each curated item. It is intended for users to quickly get some basic info of repositories instead of clicking on each. The data was collected today, and I can update the .md file regularly or as needed.

The format above TOC is a little off, which I think was caused by generating GitHub flavored markdown with pandoc.

### CODE REVIEW

**Comment by sindresorhus** [comment]
What benefit would that give the user? Stars are meaningless for this sort of thing.

**Comment by egeerardyn** [comment]
I don't think it's completely meaningless: it gives an idea (sometimes more of an idea how popular a technique is, rather than how popular/good/useful/awesome/... that particular awesome list is). So as with all metrics: it's just a metric (and it's likely to be the wrong metric to look at).

Anyhow, I think such lists would be better suited for dynamic generation, i.e. a website where the number of stars, last update, ... of each repository is shown to the user by querying that information on the fly. 
I fear that having such a secondary (statically generated) list will mainly generate noise in the versioning history.

**Comment by sindresorhus** [comment]
Maybe something that could be added to https://github.com/sindresorhus/awesome/issues/427 Although I personally only see it as useless clutter.

**Comment by chaconnewu** [comment]
Why do you think stars count is meanless (or not completely meaningless) for this sort of things? It might be meaningless to you because you already know most of the things included in the list. But for users, they may only visit the list once, or once every couple of months. What do they see except a plain list? Do you know what is the first information after a user click on a curated item? The number of stars and when the repository is last updated. I know this because I did user studies on curated repositories for the past months.

Also, the repositories include in the list are curated software projects, maintained by people. They are only as awesome as they are actively maintained to keep things updated. Just by looking at the list I genereted you will notice that several of them weren't updated for about half a year. In that case, why users still believe they are awesome?

**Comment by sindresorhus** [comment]
Stars is a good quality of popularity, but not quality. Last updated could indeed be useful for the maintainers here so we can open issues about switching out lists with something that is actually maintained, but not something I would expose to users. So, I encourage you to open issues in this repo about lists that haven't been updated in a long while and we can try to either get the author to add collaborator or fork and link to the fork instead.

**Pull request closed without merging**
