### PR TITLE
Add GIF

### PR DESCRIPTION
**Pull request by Syskaw**
[awesome-Gif](https://github.com/Syskaw/awesome-gif)

### CODE REVIEW

**Comment by sindresorhus** [comment]
Ensure your lists follows: https://github.com/sindresorhus/awesome/blob/master/awesome.md ;)

**Comment by Syskaw** [comment]
added: 
- contributing.md 
- table of contents
- short description 
;)

**Comment by sindresorhus** [comment]
Would be awesome if you could link back here in your list so users can easily discover more awesome lists ;)

**Comment by Syskaw** [comment]
added ;)

**Pull request merged**
