### PR TITLE
Add Web Scraper

### PR DESCRIPTION
**Pull request by pokeball99**
**https://github.com/duyetdev/awesome-web-scraper**

**(really don't know what to put here as personally the way this is worded sounds silly to me,but i do thinks its noteworthy enough to be put in here) was found via #470**

- [x] I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- [x] This pull request has a descriptive title.
- The list I added
	- [x] is not a duplicate,
	- [x] has been around for a few weeks,
	- [x] only has awesome items with descriptions,
	- [x] contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- [x] has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license),
	- [x] has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- [ ] has been checked for inconsistent formatting, spelling and grammar, and
	- [x] has been added at the bottom of the appropriate category.

### CODE REVIEW

**Comment by davisonio** [comment]
Perhaps we should consider looking at https://github.com/lorien/awesome-web-scraping instead? Has many more resources and seems more popular. Not sure whether you saw that one or not.

**Comment by pokeball99** [comment]
@davisonio #675 is much better than that repo

**Comment by pokeball99** [comment]
@davisonio, up to @sindresorhus

**Comment by sindresorhus** [comment]
I think it would be better to open an issue on that list on what needs improving.

For example, I would like to see more than just libraries. It should include some blog posts, tutorials, links to community resources (Example: https://github.com/sindresorhus/awesome-electron#community), videos of talks, book, learning material, etc.

> has an appropriate license,

Nope. This is not correct.

**Pull request closed without merging**
