### PR TITLE
Add Knative

### PR DESCRIPTION
**Pull request by anksos**
There is a lot of stuff around Knative currently and there is not currently an active list.

**https://github.com/anksos/awesome-knative#readme**   

Reviewed Pull Requests #1827 #1821   

**There is no currently an active knative list and there is a lot of spread info around. This list will help everyone having as much as possible the resources available in one place.**

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

## Requirements for your pull request

- **Don't waste my time.** Do a good job, adhere to all the guidelines, and be responsive.
- **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).** 
	Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration. **Just commenting “looks good” or simply marking the pull request as approved does not count!** You have to actually point out mistakes or improvement suggestions.
- You have read and understood the [instructions for creating a list](create-list.md).
- This pull request has a title in the format `Add Name of List`.
	- ✅ `Add Swift`
	- ✅ `Add Software Architecture`
	- ❌ `Update readme.md`
	- ❌ `Add Awesome Swift`
	- ❌ `Add swift`
	- ❌ `Adding Swift`
	- ❌ `Added Swift`
- Your entry here should include a short description about the project/theme of the list. **It should not describe the list itself.** The first character should be uppercase and the description should end in a dot. It should be an objective description and not a tagline or marketing blurb.
	- ✅ `- [iOS](…) - Mobile operating system for Apple phones and tablets.`
	- ✅ `- [Framer](…) - Prototyping interactive UI designs.`
	- ❌ `- [iOS](…) - Resources and tools for iOS development.`
	- ❌ `- [Framer](…)`
	- ❌ `- [Framer](…) - prototyping interactive UI designs`
- Your entry should be added at the bottom of the appropriate category.
- The suggested Awesome list complies with the below requirements.

## Requirements for your Awesome list

- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
- Don't open a Draft / WIP pull request while you work on the guidelines. A pull request should be 100% ready and should adhere to all the guidelines when you open it.
- Run [`awesome-lint`](https://github.com/sindresorhus/awesome-lint) on your list and fix the reported issues. If there are false-positives or things that cannot/shouldn't be fixed, please [report it](https://github.com/sindresorhus/awesome-lint/issues/new).
- The default branch should be named [`main`, not `master`](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/).
- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- ✅ `Mobile operating system for Apple phones and tablets.`
	- ✅ `Prototyping interactive UI designs.`
	- ❌ `Resources and tools for iOS development.`
	- ❌ `Awesome Framer packages and tools.`
- It's the result of hard work and the best I could possibly produce.
	**If you have not put in considerable effort into your list, your pull request will be immediately closed.**
- The repo name of your list should be in lowercase slug format: `awesome-name-of-list`.
	- ✅ `awesome-swift`
	- ✅ `awesome-web-typography`
	- ❌ `awesome-Swift`
	- ❌ `AwesomeWebTypography`
- The heading title of your list should be in [title case](https://capitalizemytitle.com/) format: `# Awesome Name of List`.
	- ✅ `# Awesome Swift`
	- ✅ `# Awesome Web Typography`
	- ❌ `# awesome-swift`
	- ❌ `# AwesomeSwift`
- Non-generated Markdown file in a GitHub repo.
- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
- Not a duplicate. Please search for existing submissions.
- Only has awesome items. Awesome lists are curations of the best, not everything.
- Does not contain items that are unmaintained, has archived repo, deprecated, or missing docs. If you really need to include such items, they should be in a separate Markdown file.
- Includes a project logo/illustration whenever possible.
	- Either centered, fullwidth, or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
	- The image should link to the project website or any relevant website.
	- **The image should be high-DPI.** Set it to maximum half the width of the original image.
- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- Includes the [Awesome badge](awesome.md#awesome-badge).
	- Should be placed on the right side of the readme heading.
		- Can be placed centered if the list has a centered graphics header.
	- Should link back to this list.
- Has a Table of Contents section.
	- Should be named `Contents`, not `Table of Contents`.
	- Should be the first section in the list.
	- Should only have one level of [nested lists](https://commonmark.org/help/tutorial/10-nestedLists.html), preferably none.
- Has an appropriate license.
	- **We strongly recommend the [CC0 license](https://creativecommons.org/publicdomain/zero/1.0/), but any [Creative Commons license](https://creativecommons.org/choose/) will work.**
		- Tip: You can quickly add it to your repo by going to this URL: `https://github.com/<user>/<repo>/community/license/new?branch=master&template=cc0-1.0` (replace `<user>` and `<repo>` accordingly).
	- A code license like MIT, BSD, Apache, GPL, etc, is not acceptable. Neither are WTFPL and [Unlicense](https://unlicense.org).
	- Place a file named `license` or `LICENSE` in the repo root with the license text.
	- **Do not** add the license name or text to the readme. GitHub already shows the license name at the top of the repo.
	- To verify that you've read all the guidelines, please comment on your pull request with just the word `unicorn`.
- Has [contribution guidelines](awesome.md#include-contribution-guidelines).
	- The file should be named `contributing.md`. Casing is up to you.
- Has consistent formatting and proper spelling/grammar.
	- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
	- The description starts with an uppercase character and ends with a period.
	- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.
- Doesn't include an `Inspired by awesome-foo` or `Inspired by the Awesome project` kinda link at the top of the readme. The Awesome badge is enough.

**Go to the top and read it again.**

### CODE REVIEW

**Comment by anksos** [comment]
unicorn

**Comment by sindresorhus** [comment]
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

**Comment by kolomied** [comment]
I strongly suggest playing with [awesome-lint](https://github.com/sindresorhus/awesome-lint). It will show you most of the formatting issues you need to fix (lists, dots, descriptions, content section, etc.)

Start with the tool and then go through the checklist again. I've been there, it really helps :)

**Comment by anksos** [comment]
@kolomied thanks for the information
@sindresorhus can you please take a look and let me know if something is still missing?

- descriptions fixed (in majority of them the link is explanatory by itself so according to guidance it doesn't need description)
- master branch changed to main as default
- table of contents added
- have reviewed another 2 open PRs (is already add in my PR)
- topics added
- fixed the knative description/explanation on the main awesome list

**Comment by anksos** [comment]
@sindresorhus any update on that? Thank you.

**Comment by sindresorhus** [comment]
> can you please take a look and let me know if something is still missing?

I would recommend going through the guidelines again and check. The reason the guidelines exists is so that I don't have to point out stuff written there.

**Comment by anksos** [comment]
> > can you please take a look and let me know if something is still missing?
> 
> I would recommend going through the guidelines again and check. The reason the guidelines exists is so that I don't have to point out stuff written there.

Thanks @sindresorhus i will try to fix those, I was able to spot majority of those.

**Comment by wernerkrauss** [comment]
The Video section is missing the descriptions. The other descriptions are often redundant

> Knative Cookbook - Knative cookbook from O'Reilly.

Could be something like "Knative Cookbook - A collection of recipes for XXX by O'Reilly". This is just a suggestion without knowing this book.

Did you run awesome-lint? I get a bunch of errors on your list:

```
awesome-lint  https://github.com/anksos/awesome-knative
- Linting(node:15128) ExperimentalWarning: The fs.promises API is experimental
× Linting

  README.md:1:1
  ×   1:1    Headings should use atx                                                      remark-lint:heading-style
  ×   1:20   Invalid badge source                                                         remark-lint:awesome-badge
  ×   4:1    Don’t add a trailing ? to headings                                           remark-lint:no-heading-punctuation
  ×   7:1    Don’t add a trailing : to headings                                           remark-lint:no-heading-punctuation
  ×   9:1    Missing marker in block quote                                                remark-lint:no-blockquote-without-marker
  ×   9:5    Incorrect indentation before bullet: remove 2 spaces                         remark-lint:list-item-bullet-indent
  ×  11:1    Missing marker in block quote                                                remark-lint:no-blockquote-without-marker
  ×  11:5    Incorrect indentation before bullet: remove 2 spaces                         remark-lint:list-item-bullet-indent
  ×  13:1    Table of Contents must be the first section                                  remark-lint:awesome-toc
  ×  14:1    ToC item "Contributing" does not match corresponding heading "Books / Docs"  remark-lint:awesome-toc
  ×  25:1    Headings should use atx                                                      remark-lint:heading-style
  ×  25:16   Remove 1 space after this heading’s content                                  remark-lint:no-heading-content-indent
  ×  26:44   List item description must end with proper punctuation                       remark-lint:awesome-list-item
  ×  27:95   List item description must end with proper punctuation                       remark-lint:awesome-list-item
  ×  29:88   List item description must end with proper punctuation                       remark-lint:awesome-list-item
  ×  30:57   List item description must end with proper punctuation                       remark-lint:awesome-list-item
  ×  36:98   List item description must end with proper punctuation                       remark-lint:awesome-list-item
  ×  37:70   List item description must end with proper punctuation                       remark-lint:awesome-list-item
  ×  38:74   List item description must end with proper punctuation                       remark-lint:awesome-list-item
  ×  42:46   List item description must end with proper punctuation                       remark-lint:awesome-list-item
  ×  43:91   List item description must end with proper punctuation                       remark-lint:awesome-list-item
  ×  44:65   List item description must end with proper punctuation                       remark-lint:awesome-list-item
  ×  45:85   List item description must end with proper punctuation                       remark-lint:awesome-list-item
  ×  58:3    https://www.youtube.com/watch?v=riq0x5xdfNg                                  remark-lint:double-link
  ×  68:3    https://www.youtube.com/watch?v=riq0x5xdfNg                                  remark-lint:double-link
  ×  89:103  List item description must end with proper punctuation                       remark-lint:awesome-list-item
  ×  90:107  List item description must end with proper punctuation                       remark-lint:awesome-list-item

  27 errors

```

Reading the guidelines again and reviewing other lists (existing and in the PRs) might show you other things you can improve to make your list _really_ awesome!

**Comment by anksos** [comment]
@wernerkrauss thanks mate, yes already have run the lint I just didn't had yet the time to fix them! Really appreciate your view! cheers

**Comment by sindresorhus** [comment]
Bump

**Comment by zrosenbauer** [comment]
@anksos any update here? I can take a stab at fixing the errors if needed.

**Comment by anksos** [comment]
> @anksos any update here? I can take a stab at fixing the errors if needed.

feel free mate!!! Thanks for the reminder!

**Comment by zrosenbauer** [comment]
Haven't forgot about this but been working on more Cloud Run OSS at the moment. Are you able to knock this out or should I add this to my weekend OSS queue this week or next?

**Comment by pgollucci** [comment]
Running awesome-lint on your patch-1 (this pr) gives issues

diff --git i/readme.md w/readme.md
index 98772aa..32172f9 100755
--- i/readme.md
+++ w/readme.md
@@ -742,17 +742,13 @@
 - [Biomedical Information Extraction](https://github.com/caufieldjh/awesome-bioie#readme) - How to extract information from unstructured biomedical data and text.
 - [Web Archiving](https://github.com/iipc/awesome-web-archiving#readme) - An effort to preserve the Web for future generations.
 - [WP-CLI](https://github.com/schlessera/awesome-wp-cli#readme) - Command-line interface for WordPress.
-- [Knative](https://github.com/anksos/awesome-knative#readme) - Kubernetes-based platform to deploy and manage serverless workloads.
 - [Credit Modeling](https://github.com/mourarthur/awesome-credit-modeling#readme) - Methods for classifying credit applicants into risk classes.
 - [Ansible](https://github.com/KeyboardInterrupt/awesome-ansible#readme) - A Python-based, open source IT configuration management and automation platform.
 - [Biological Visualizations](https://github.com/keller-mark/awesome-biological-visualizations#readme) - Interactive visualization of biological data on the web.
 - [QR Code](https://github.com/aureooms/awesome-qr-code#readme) - A type of matrix barcode that can be used to store and share a small amount of information.
 - [Veganism](https://github.com/sdassow/awesome-veganism#readme) - Making the plant-based lifestyle easy and accessible.
 - [Translations](https://github.com/mbiesiad/awesome-translations#readme) - The transfer of the meaning of a text from one language to another.
-- [Knative](https://github.com/anksos/awesome-knative#readme) - Learning Knative
-- [Knative](https://github.com/anksos/awesome-knative#readme) - Knative resources and events list.
-- [Knative](https://github.com/anksos/awesome-knative#readme) - Knative is a kubernetes-based platform to deploy and manage serverless workloads.
-- [Knative](https://github.com/anksos/awesome-knative#readme) - Kubernetes-based platform to deploy and manage serverless workloads.
+- [Knative](https://github.com/anksos/awesome-knative#readme) - Learning Knative.

**Pull request closed without merging**
