### PR TITLE
Add awesome-game-analysis

### PR DESCRIPTION
**Pull request by K1ngst0m**
**https://github.com/OTFCG/Awesome-Game-Analysis**

**a repository dedicated to the collection and analysis of various games, including graphics breakdown, frame analysis, gameplay design, networking and anything about game development (much focus on the programming side).**

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

## Requirements for your pull request

- [X] Don't open a Draft / WIP pull request while you work on the guidelines. A pull request should be 100% ready and should adhere to all the guidelines when you open it. **Instead use [#2242](https://github.com/sindresorhus/awesome/issues/2242) for incubation visibility**.
- [X] **Don't waste my time.** Do a good job, adhere to all the guidelines, and be responsive.
- [X] **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).**
	Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration. **Just commenting “looks good” or simply marking the pull request as approved does not count!** You have to actually point out mistakes or improvement suggestions. Comments pointing out lint violation are allowed, but does **not** count as a review.

Other PR's Reviewed prior to this PR:

- https://github.com/sindresorhus/awesome/pull/2692
- https://github.com/sindresorhus/awesome/pull/2524

- [X] You have read and understood the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/main/create-list.md).
- [X] This pull request has a title in the format `Add Name of List`. It should not contain the word `Awesome`.
	- ✅ `Add Swift`
	- ✅ `Add Software Architecture`
	- ❌ `Update readme.md`
	- ❌ `Add Awesome Swift`
	- ❌ `Add swift`
	- ❌ `add Swift`
	- ❌ `Adding Swift`
	- ❌ `Added Swift`
- [X] Your entry here should include a short description about the project/theme of the list. **It should not describe the list itself.** The first character should be uppercase and the description should end in a dot. It should be an objective description and not a tagline or marketing blurb.
	- ✅ `- [iOS](…) - Mobile operating system for Apple phones and tablets.`
	- ✅ `- [Framer](…) - Prototyping interactive UI designs.`
	- ❌ `- [iOS](…) - Resources and tools for iOS development.`
	- ❌ `- [Framer](…)`
	- ❌ `- [Framer](…) - prototyping interactive UI designs`
- [X] Your entry should be added at the bottom of the appropriate category.
- [X] The title of your entry should be title-cased and the URL to your list should end in `#readme`.
	- Example: `- [Software Architecture](https://github.com/simskij/awesome-software-architecture#readme) - The discipline of designing and building software.`
- [X] No blockchain-related lists.
- [X] The suggested Awesome list complies with the below requirements.

## Requirements for your Awesome list

- [X] **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
- [X] Run [`awesome-lint`](https://github.com/sindresorhus/awesome-lint) on your list and fix the reported issues. If there are false-positives or things that cannot/shouldn't be fixed, please [report it](https://github.com/sindresorhus/awesome-lint/issues/new).
- [X] The default branch should be named [`main`, not `master`](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/).
- [X] **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- ✅ `Mobile operating system for Apple phones and tablets.`
	- ✅ `Prototyping interactive UI designs.`
	- ❌ `Resources and tools for iOS development.`
	- ❌ `Awesome Framer packages and tools.`
- [X] It's the result of hard work and the best I could possibly produce.
	**If you have not put in considerable effort into your list, your pull request will be immediately closed.**
- [X] The repo name of your list should be in lowercase slug format: `awesome-name-of-list`.
	- ✅ `awesome-swift`
	- ✅ `awesome-web-typography`
	- ❌ `awesome-Swift`
	- ❌ `AwesomeWebTypography`
- [X] The heading title of your list should be in [title case](https://capitalizemytitle.com/) format: `# Awesome Name of List`.
	- ✅ `# Awesome Swift`
	- ✅ `# Awesome Web Typography`
	- ❌ `# awesome-swift`
	- ❌ `# AwesomeSwift`
- [X] Non-generated Markdown file in a GitHub repo.
**(we use the [toml format data](https://github.com/OTFCG/Awesome-Game-Analysis/blob/main/data/games.toml) for [generation workflow](https://github.com/OTFCG/Awesome-Game-Analysis/blob/main/.github/workflows/Awesome-Game-Analysis.yml) and [friendly change submission](https://github.com/OTFCG/Awesome-Game-Analysis/blob/main/CONTRIBUTING.md) and for convinient of our future production)**
- [X] The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
- [X] Not a duplicate. Please search for existing submissions.
- [X] Only has awesome items. Awesome lists are curations of the best, not everything.
- [X] Does not contain items that are unmaintained, has archived repo, deprecated, or missing docs. If you really need to include such items, they should be in a separate Markdown file.
- [X] Includes a project logo/illustration whenever possible.
	- Either centered, fullwidth, or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
	- The image should link to the project website or any relevant website.
	- **The image should be high-DPI.** Set it to maximum half the width of the original image.
- [X] Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- [X] Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/main/awesome.md#awesome-badge).
	- Should be placed on the right side of the readme heading.
		- Can be placed centered if the list has a centered graphics header.
	- Should link back to this list.
- [X] Has a Table of Contents section.
	- Should be named `Contents`, not `Table of Contents`.
	- Should be the first section in the list.
	- Should only have one level of [nested lists](https://commonmark.org/help/tutorial/10-nestedLists.html), preferably none.
	- Must not feature `Contributing` or `Footnotes` sections.
**(We only have a few headlines, so we don't need them)**
- [X] Has an appropriate license.
	- **We strongly recommend the [CC0 license](https://creativecommons.org/publicdomain/zero/1.0/), but any [Creative Commons license](https://creativecommons.org/choose/) will work.**
		- Tip: You can quickly add it to your repo by going to this URL: `https://github.com/<user>/<repo>/community/license/new?branch=main&template=cc0-1.0` (replace `<user>` and `<repo>` accordingly).
	- A code license like MIT, BSD, Apache, GPL, etc, is not acceptable. Neither are WTFPL and [Unlicense](https://unlicense.org).
	- Place a file named `license` or `LICENSE` in the repo root with the license text.
	- **Do not** add the license name, text, or a `Licence` section to the readme. GitHub already shows the license name and link to the full text at the top of the repo.
	- To verify that you've read all the guidelines, please comment on your pull request with just the word `unicorn`.
- [X] Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/main/awesome.md#include-contribution-guidelines).
	- The file should be named `contributing.md`. Casing is up to you.
	- It can optionally be linked from the readme in a dedicated section titled `Contributing`, positioned at the top or bottom of the main content.
	- The section should not appear in the Table of Contents.
- [X] All non-important but necessary content (like extra copyright notices, hyperlinks to sources, pointers to expansive content, etc) should be grouped in a `Footnotes` section at the bottom of the readme. The section should not be present in the Table of Contents.
- [X] Has consistent formatting and proper spelling/grammar.
	- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
	- The description starts with an uppercase character and ends with a period.
	- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
- [X] Does not use [hard-wrapping](https://stackoverflow.com/questions/319925/difference-between-hard-wrap-and-soft-wrap).
- [X] Does not include a CI (e.g. GitHub Actions) badge.<br>You can still use a CI for linting, but the badge has no value in the readme.
- [X] Does not include an `Inspired by awesome-foo` or `Inspired by the Awesome project` kinda link at the top of the readme. The Awesome badge is enough.

**Go to the top and read it again.**

### CODE REVIEW

**Comment by ddanieltan** [comment]
For this requirement, can you add links to the 2 reviews you've made? 
>You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).

You can see an example of how and where to add your links from this [PR](https://github.com/sindresorhus/awesome/pull/2715).

**Comment by K1ngst0m** [comment]
> For this requirement, can you add links to the 2 reviews you've made?
> 
> > You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).
> 
> You can see an example of how and where to add your links from this [PR](https://github.com/sindresorhus/awesome/pull/2715).

Updated.

**Comment by sindresorhus** [comment]
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

**Comment by K1ngst0m** [comment]
> * Contributing
```
❯ npx awesome-lint https://github.com/OTFCG/Awesome-Game-Analysis
✖ Linting

  README.md:76:84
  ✖    1:1   Git repository must be at least 30 days old                       remark-lint:awesome-git-repo-age
  ✖   76:84  https://simonschreibt.de/gat/alien-vs-wolfenstein-cutting-torch/  remark-lint:double-link
  ✖   77:93  https://simonschreibt.de/gat/alien-vs-wolfenstein-cutting-torch/  remark-lint:double-link
  ✖   80:76  http://simonschreibt.de/gat/dont-starve-diablo-parallax-7/        remark-lint:double-link
  ✖   82:82  http://simonschreibt.de/gat/dont-starve-diablo-parallax-7/        remark-lint:double-link
  ✖   84:88  http://simonschreibt.de/gat/oblivion-territory-tree-vs-palm/      remark-lint:double-link
  ✖   85:95  http://simonschreibt.de/gat/oblivion-territory-tree-vs-palm/      remark-lint:double-link
  ✖  171:74  https://www.youtube.com/watch?v=RkS8DmGqUmk                       remark-lint:double-link
  ✖  172:85  https://www.youtube.com/watch?v=RkS8DmGqUmk                       remark-lint:double-link
  ✖  186:81  https://www.youtube.com/watch?v=7jb0FOcImdg                       remark-lint:double-link
  ✖  187:79  https://www.youtube.com/watch?v=7jb0FOcImdg                       remark-lint:double-link
  ✖  219:86  https://www.youtube.com/watch?v=ItwtpX1SFcA                       remark-lint:double-link
  ✖  220:81  https://www.youtube.com/watch?v=ItwtpX1SFcA                       remark-lint:double-link

  13 errors
```

here's my awesome-lint output, the remainder of the errors is double links, but I want to quickly reference articles of relative games so I put these comparison articles (Game A vs Game B) in both game entries.

**Comment by joewdavies** [comment]
- Your list was created on the 11th July 2023, it is not 30 days old yet.
- You did not comment on either of the PRs you claim to have reviewed.

**Comment by K1ngst0m** [comment]
> * Your list was created on the 11th July 2023, it is not 30 days old yet.
> * You did not comment on either of the PRs you claim to have reviewed.

Thanks for your kind reminder!

**Comment by hazanasec** [comment]
You will have to be patient and wait those 30 days! In the mean time [your logo is 404](https://raw.githubusercontent.com/OTFCG/Awesome-Game-Analysis/update/logo.svg)  
I can also see a list of already analysed games, why not add resources for learning the process also?

**Comment by lucas-op** [comment]
The list is looking good! Just a suggestion: it would be great to include a game genre column as well.

**Comment by sindresorhus** [comment]
Bump

**Comment by sindresorhus** [comment]
Items in the "References" section are missing descriptions.

**Comment by sindresorhus** [comment]
> Non-generated Markdown file in a GitHub repo.

This apply to all lists.

**Comment by sindresorhus** [comment]
Closing for lack of response.

**Pull request closed without merging**
