### PR TITLE
Add Credit Modeling

### PR DESCRIPTION
**Pull request by mourarthur**
**https://github.com/mourarthur/awesome-credit-modeling**

The list consolidates several resources on the subject of credit risk modeling and credit scoring. The financial services industry has seen deep changes in the past decade due to the increase in data variety and availability when it comes to determining a consumer's creditworthiness.

## Requirements for your pull request

- [x] **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).**
	- Reviewed PRs: #1784 , #1797 , #1798 , #1803 .
- [x] You have read and understood the [instructions for creating a list](create-list.md).
- [x] This pull request has a title in the format `Add Name of List`.
	- PR Name: **Add Credit Modeling**
- [x] Your entry here should include a short description about the project/theme of the list. **It should not describe the list itself.** The first character should be uppercase and the description should end in a dot. It should be an objective description and not a tagline or marketing blurb.
	- Entry: **Methods for classifying credit applicants into risk classes.**
- [x] Your entry should be added at the bottom of the appropriate category.
- [x] The suggested Awesome list complies with the below requirements.

## Requirements for your Awesome list

- [x] **Has been around for at least 30 days.**
- [x] Run [`awesome-lint`](https://github.com/sindresorhus/awesome-lint) on your list and fix the reported issues.
- [x] The default branch should be named [`main`, not `master`](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/).
- [x] **Includes a succinct description of the project/theme at the top of the readme.**
- [x] It's the result of hard work and the best I could possibly produce.
- [x] The repo name of your list should be in lowercase slug format: `awesome-name-of-list`.
- [x] The heading title of your list should be in [title case](https://capitalizemytitle.com/) format: `# Awesome Name of List`.
- [x] Non-generated Markdown file in a GitHub repo.
- [x] The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics).
- [x] Not a duplicate. Please search for existing submissions.
- [x] Only has awesome items. Awesome lists are curations of the best, not everything.
- [x] Does not contain items that are unmaintained, has archived repo, deprecated, or missing docs. If you really need to include such items, they should be in a separate Markdown file.
- [ ] Includes a project logo/illustration whenever possible.
- [x] Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- [x] Includes the [Awesome badge](awesome.md#awesome-badge).
	- [x] Should be placed on the right side of the readme heading.
	- [x] Should link back to this list.
- [x] Has a Table of Contents section.
	- [x] Should be named `Contents`, not `Table of Contents`.
	- [x] Should be the first section in the list.
	- [x] Should only have one level of [nested lists](https://commonmark.org/help/tutorial/10-nestedLists.html), preferably none.
	- [x] Must not feature `Contributing` or `Footnotes` sections.
- [x] Has an appropriate license.
	- [x] Place a file named `license` or `LICENSE` in the repo root with the license text.
	- [x] **Do not** add the license name, text, or a `Licence` section to the readme. GitHub already shows the license name and link to the full text at the top of the repo.
- [x] Has [contribution guidelines](awesome.md#include-contribution-guidelines).
	- [x] The file should be named `contributing.md`. Casing is up to you.
- [x] Has consistent formatting and proper spelling/grammar.
	- [x] The link and description are separated by a dash.
	- [x] The description starts with an uppercase character and ends with a period.
	- [x] Consistent and correct naming.
- [x] Doesn't use [hard-wrapping](https://stackoverflow.com/questions/319925/difference-between-hard-wrap-and-soft-wrap).
- [x] Doesn't include a Travis badge.
- [x] Doesn't include an `Inspired by awesome-foo` or `Inspired by the Awesome project` kinda link at the top of the readme. The Awesome badge is enough.

### CODE REVIEW

**Comment by mourarthur** [comment]
unicorn

**Comment by sindresorhus** [comment]
Remove the license badge. GitHub already shows that in its UI.

**Comment by mourarthur** [comment]
@sindresorhus done!

**Comment by sindresorhus** [comment]
Tweet: https://twitter.com/awesome__re/status/1321961712380268546

**Pull request merged**
