### PR TITLE
Add FOSS Production Apps

### PR DESCRIPTION
**Pull request by jwaterfaucett**
Hi, this PR would add a new list I've started curating that tracks high quality open sourced production apps for web, desktop, and mobile. For myself I often want to see how non-trivial quality software is built usually using a particular stack and hope this might be useful to other developers.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you try to follow the stuff in https://github.com/sindresorhus/awesome/issues/207 ? Mainly the items need better description and commentary on why they're included.

**Comment by jwaterfaucett** [comment]
Oh yes didn't notice that, https://github.com/sindresorhus/awesome-scifi#cities-in-flight-1970-by-james-blish-40 is a great example of how to do this. I'll add and update the PR.

**Comment by sindresorhus** [comment]
Make sure to also update the contributing.md file with requirement to add it for new submissions ;)

**Comment by jwaterfaucett** [comment]
@sindresorhus  I just finished updating the awesome-foss-apps repo with the new descriptions about each project. It also made me drop one when I realized it didn't really fit up to the standards, so I think this is a good idea. I updated the awesome-foss-apps contributing.md for its particular use case, but I'm unsure how to go about doing that for awesome's contributing.md. Maybe there needs to be more discussion before that happens I'm looking at #212 and #207 .

**Comment by sindresorhus** [comment]
> but I'm unsure how to go about doing that for awesome's contributing.md. Maybe there needs to be more discussion before that happens I'm looking at #212 and #207 .

Yes, let's keep that discussion in the relevant thread.

-

Screenshots for the apps could also be nice ;)

**Pull request merged**
