### PR TITLE
Change link from sysadmin repo to sysadmin forum

### PR DESCRIPTION
**Pull request by n1trux**
Hi, I decided to archive [my awesome-sysadmin list](https://github.com/n1trux/awesome-sysadmin) and move it to a Flarum installation I manage:

https://awesome.tilde.fun/t/sysadmin

While this certainly means that the list can be inaccessible at any time, I try to make sure to host it indefinitely. Flarum uses Markdown format and I'm sure we can find a way to mirror this to a git repository somehow.

The reason for my decision is that searching via tags and discussing the software is way easier in Flarum than it is in a Github markdown list. I will try to create an extension to mirror the layout/design of the initial markdown list with a powerful search interface, but for now I think Flarum's search features are good enough™.

I'll enable Github OAuth access so everyone with a Github account can log in into the awesome-sysadmin forum and contribute there.

Tagging @nodiscc and @Kickball for consideration.

### CODE REVIEW

**Comment by nodiscc** [comment]
Hi @n1trux I don't really know where to stand with this change:

- Pros:
  - awesome-sysadmin becomes self-hosted.
  - It enables tag-based organization instead of trying to fit all items in specific categories (currently it seems projects are still grouped without precise tags on your flarum instance, probably because you just moved the list and did not split it yet? I was expecting one post per item)
  - it enables discussions/reviews on software projects which was not possible with the old system
- Cons:
  - a forum to manage the list itself is about the worst system I can think of :) The contribution process is not detailed but I expect it will be painful to manage
  - a forum requires higher maintenance/moderation than a simple list of items (but good if you plan to invest time in it)
  - search feature is not as good as a simple Ctrl+F (the single-page format of the old list made search really easy)

What I would have liked, is designing a conventional format to store info about software projects (that could be reused across _awesome-*_ projects), like what I started [here](https://github.com/n8225/awesome-selfhosted-gen/issues/10). This could mean one YAML file per project, easy to fill and maintain (and lends itself well to automation like grabbing last commit date, github/gitlab stars count, etc.), then feeding this data to a simple static site generator (I started something with Sphinx + ablog) that would take care of presentation, tag list, etc. [This project does something similar](https://github.com/bevry/staticsitegenerators-list/blob/master/source/list.ts) with some differences (single file, json instead of yaml...). However the system is far from ready, the forum solution has the advantage of being already available.

@n8225 also has a working prototype at https://n8225.github.io/awesome-selfhosted-gen/ wich requires some tweaks (and built in go from scratch which is not ideal IMHO)

This would amount to creating an FOSS version of [alternativeto](https://alternativeto.net/), which is no simple task, but is the good way to go.

Archiving the repo might not be the best thing to do (the message about the list being moved is clear enough), because it will mask it from search results while it's still a good resource and is hugely popular. So I would advise un-archiving it even if you plan to go forum-based for the future.

**Comment by n1trux** [comment]
Thanks a lot @nodiscc for your thoughts.

>a forum to manage the list itself is about the worst system I can think of :)

I totally agree that a forum itself is a pretty bad system to organise this. But I really like the lower bar to entry compared to a git-based approach.

Of course, going forward, we'd need a good system of displaying stuff. There's countless addons for Flarum which add single-page functionalities, so a linked-list format would be pretty easy ("find all posts with "list of X", display them on one page).

> search feature is not as good as a simple Ctrl+F

Usually you don't really Ctrl+F through these lists anyway, or do you? If I want to discover software, I rarely know what it's called. And if you needed a specific kind of software you could easily Ctrl+F on the overview page.

The awesome-selfhosted gen is great. I think it still has a high bar of entry if you want to discuss software alternatives. My "role model" would be alternativeto.net as they provide(d) a pretty good interface for finding and discussing alternatives. Maybe we can have ratings and comments in Flarum which would be hard to do in other formats.

>The system is far from ready, the forum solution has the advantage of being already available.

This is why I chose it. The idea came to me as I showered and thought about how annoying it is to find anything on those awesome-lists and how I'd like other people's opinions when clicking on that list. Then I remembered ye good olde days of bulletin boards and Flarum and took 2 hours of my day converting the list into forum posts.

What really sucks now is the initial display, what's great is tagged filtering and the ability to do more with the source material. I think there's a middle ground between my solution and the optimal one, but for now IMHO Flarum is a pretty good base for a simple list format.

We shouldn't forget where we came from: sharing knowledge and basically building a link database with useful stuff you can't easily find in a simple Google search. Nowadays awesome-lists have been fragmented all over the place and discussion is scattered amongst multiple repositories. In forum format, people can share their stacks and discuss on the best way to use software. Reddit (r/selfhosted) is shit for stuff like this as it separates the content from the discussion too much, IMHO. It also fosters repetition so for one topic you get dozens of (non-curated) results.

I'd really like if we could combine the human-readable and -interactable format that is Flarum with the machine-readable selfhosted-gen way of things. Maybe one could rewrite @n8225's solution as a Flarum plugin and autolink software to their discussion thread?

**Comment by nodiscc** [comment]
> lower bar to entry compared to a git-based approach.

The bar to entry is not that bad ([CONTRIBUTING.md](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/.github/CONTRIBUTING.md)). I'd say it adds an extra layer of curation since someone with basic git knowledge or some time to go through the process will _probably_ send a PR to add a project once it is know/awesome enough.

But I get what you mean. The ideal contribution process would probably be some kind of web form that in turn, opens a pull request (it would only work for additions though).

> if you want to discuss software alternatives  
> I'd like other people's opinions when clicking on that list.

That's the big upside of forum-based workflow. Yes reddit r/selfhosted is inappropriate for this since threads "fade" over time and this leads to reposts.

I'd still prefer a system, where comments/reviews/discussions are separate from the list itself (eg. a `reviews` link to the dedicated forum page for each entry in the list).

If the forum supports a rating system, and results can be accessed through an API, we could automate scraping ratings and adding them to the list. Careful about the exact implementation though, a high count of upvotes/stars only means a project is popular, not necessarily high-quality :) It's also vulnerable to fake reviews/ratings.

> you don't really Ctrl+F through these lists anyway, or do you?

I do, I use Ctrl+F to search for keywords, features (Ctrl+F  `whiteboard`...) in the absence of tags... Even if there was a tag list I'd probably Ctrl+F on it, if it gets large enough (it will).

The other major use case is probably just browsing through the list to discover new interesting software. It's hard to follow what exactly gets added over time unless you keep eyes on the commit feed, something a regular release/consolidated update/newsletter... would fix. It has been [suggested](https://github.com/awesome-selfhosted/awesome-selfhosted/issues/2235). It can also be automated :)

> alternativeto.net as they provide(d) a pretty good interface for finding and discussing alternatives

They do. The list view is not condensed enough for my taste, but detail pages are great, and finding software by related tags/auto-suggestion of alternatives is great. For a while I thought about abusing [Shaarli](https://shaarli.readthedocs.io/en/master/)'s tag-based organization (+ [Isso](https://posativ.org/isso/) [plugin](https://shaarli.readthedocs.io/en/master/Plugins/)). But it makes contributions harder than git/PR-based workflow.

> I think there's a middle ground between my solution and the optimal one

Biggest improvement I can suggest right now is splitting posts, one post per list item, properly tagged (`logs`, `monitoring`, `orchestration`...). And maybe a general thread "Request new software additions here"? And let's see how it evolves over time. thanks for un-archiving the repo by the way :+1: 

> Nowadays awesome-lists have been fragmented all over the place

Hence a shared database in YAML/machine-readable format would help a lot.

> combine the human-readable and -interactable format that is Flarum with the machine-readable selfhosted-gen way

linking list items to forum threads looks good to me

> rewrite @n8225's solution as a Flarum plugin [...] ?

Generating the list from a static site generator like https://github.com/n8225/awesome-selfhosted-gen looks better to me (it can automate info/metadata retrieval, it can generate multiple formats, generate releases...). But flarum plugins would help exposing info such as rating, number of comments...

I tried to define requirements on https://github.com/n8225/awesome-selfhosted-gen/issues which is a good start, but can't make the changes because I'm still really bad at golang :) That's why I was tempted to rewrite it in $FAVORITE_LANGUAGE/reuse as much existing software as possible (am familiar with [sphinx](https://www.sphinx-doc.org/en/master/)/[readthedocs](https://docs.readthedocs.io/en/stable/)...)

**Comment by sindresorhus** [comment]
You are free to do what you want with your Awesome list, but the requirements for Awesome lists included in this repo are clear.

**Comment by nodiscc** [comment]
I think moving it to forum-based install breaks some of the requirements in https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md @sindresorhus is that right? If so what about just leaving it as-is (the list is not stale yet)

**Comment by fabacab** [comment]
@sindresorhus I have been maintaining forks of several useful-to-me Awesome lists for some time, including the now-retired awesome-sysadmin list. I also have consistently maintained several other lists included in your listing here, such as Lockpicking and Cybersecurity Blue Team.

Would you be willing to re-add the Awesome Sysadmin listing pointing to my fork instead?

**Pull request closed without merging**
