### PR TITLE
Add Jupyter

### PR DESCRIPTION
**Pull request by markusschanta**
https://github.com/markusschanta/awesome-jupyter

A curated list of awesome Jupyter projects, libraries and resources. The Jupyter Notebook is an open-source web application that allows you to create and share documents that contain live code, equations, visualizations and narrative text.

At present, there are about [1.5 million Jupyter notebooks tracked on GitHub](https://github.com/parente/nbestimate) and the number is steadily increasing. There is a large number of projects related to Jupyter and this list can serve as an entry point to get an overview of the space.

# By submitting this pull request I confirm I've read and complied with the below requirements.

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title.<br>For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
	- Be added at the bottom of the appropriate category.
- The list I'm submitting complies with these requirements:
	- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
	- It's the result of hard work and the best I could possibly produce.
	- Non-generated Markdown file in a GitHub repo.
	- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
	- Not a duplicate.
	- Only has awesome items. Awesome lists are curations of the best, not everything.
	- Includes a project logo/illustration whenever possible.
		- Either fullwidth or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
		- The image should link to the project website or any relevant website.
		- The image should be high-DPI. Set it to maximum half the width of the original image.
	- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
	- Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
		- Should be placed on the right side of the readme heading.
		- Should link back to this list.
	- Has a Table of Contents section.
		- Should be named `Contents`, not `Table of Contents`.
		- Should be the first section in the list.
		- Should only have one level of sub-lists, preferably none.
	- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
		- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
		- [WTFPL](http://www.wtfpl.net) and [Unlicense](http://unlicense.org) are not acceptable licenses.
		- If you use a license badge, it should be SVG, not PNG.
	- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
		- The file should be named `contributing.md`. Casing is up to you.
	- Has consistent formatting and proper spelling/grammar.
		- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
		- The description starts with an uppercase character and ends with a period.
		- Drop all the `A` / `An` prefixes in the descriptions.
		- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
	- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.
- Go to the top and read it again.

### CODE REVIEW

**Comment by markusschanta** [comment]
@sindresorhus jupyter-awesome is now at 103 stars, 59 commits, 78 items on the list and 9 forks. It's getting more and more traction. It would be great if you can let me know if you think it needs to mature more or if there's something I should change about the format of the list for it to be included here. Thanks.

**Comment by legodude17** [comment]
Suggestions: 
 * Table of Contents should be named `Contents`
 * Remove `The` at the beginning of descriptions (ex. Jupyter Notebook instead of The Jupyter Notebook)
 * Make descriptions more descriptive (`Jupyter Notebook - The Jupyter notebook.` isn't very helpful)

**Comment by legodude17** [comment]
> DataScience.com
Domino Data Lab
Google Cloud Datalab

None of these have descriptions.

**Comment by markusschanta** [comment]
Cheers! Added descriptions for these as well. The remaining items without explicit descriptions are links to tutorials/articles where the title is descriptive enough in my opinion.

**Comment by markusschanta** [comment]
A couple of days ago [Jupyter has been awarded the 2017 ACM Software System Award](https://blog.jupyter.org/jupyter-receives-the-acm-software-system-award-d433b0dfe3a2), an award that has previously been given to major projects of computing history, including Unix, TeX, the Web, Mosaic, Java, and more. Think this is a good testimonial for having an Awesome List dedicated to Jupyter on awesome.

**Comment by sindresorhus** [comment]
Hey, sorry for the lack of response, please see #1363.

**Comment by markusschanta** [comment]
Hi @sindresorhus, I've done further work to move this forward:

1) As per your suggestions, I've reviewed [three](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen+reviewed-by%3Amarkusschanta+) (really going the extra mile here 🤣) other PR's to share the load a bit.
2) I've ran this through [awesome-lint](https://github.com/sindresorhus/awesome-lint) which pointed out some issues and I [fixed them](https://github.com/markusschanta/awesome-jupyter/pull/23).
3) In my three reviews, I have always referenced [awesome-lint](https://github.com/sindresorhus/awesome-lint) to spread the word. If more people used this, there would be fewer issues to review...

Meanwhile [jupyter-awesome](https://github.com/markusschanta/awesome-jupyter) is now at 151 stars, 79 commits, 79 items on the list and 16 forks. If there's things you would like to see changed, please let me know, happy to make changes. At this point, I feel like I'm leaving things better than I found them. 😊

**Comment by sindresorhus** [comment]
@markusschanta Thanks for helping out. Looks good now when https://github.com/markusschanta/awesome-jupyter/pull/24 is merged.

**Comment by sindresorhus** [comment]
Tweet: https://twitter.com/awesome__re/status/1027876259068407809

**Comment by markusschanta** [comment]
Thanks for approving, merging and tweeting! 😊

**Pull request merged**
