### PR TITLE
Add link in Learn: Dive into Machine Learning

### PR DESCRIPTION
**Pull request by hangtwenty**
Hey there. Love the Awesome lists and the Awesome List of Awesome Lists :)

I feel like there is a place for my guide here. Hope you feel the same.

Regarding which section to put it in ... I put it in "Learn" since it really is introductory (very tightly curated so as to NOT be overwhelming). The other lists in the "Machine Learning" section are more exhaustive. So I think this belongs in "Learn." Let me know!

### CODE REVIEW

**Comment by sindresorhus** [comment]
It's in the grey zone, but I'll allow since it's such a great resource.

**Comment by sindresorhus** [comment]
Would be awesome if you could add the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) to your readme :D

**Comment by hangtwenty** [comment]
Hey thanks for merging! I assume you didn't think it should be moved to a diff. section, then?

Added the badge :wink:

**Comment by sindresorhus** [comment]
Nah, it's fine there :)

**Comment by hangtwenty** [comment]
:beers:

**Pull request closed without merging**
