### PR TITLE
Added awesome-speaking

### PR DESCRIPTION
**Pull request by matteofigus**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Some guidelines you might want to consider for your list, especially the part about license and contributin.md: https://github.com/sindresorhus/awesome/blob/awesome-guidelines/awesome.md

**Comment by matteofigus** [comment]
Thanks, I reviewd, including adding the license and and the contributing guidelines now :+1:

**Comment by aleksandar-todorovic** [comment]
The list looks great! I hope it'll get enough traction and include much more entries in the future!

**Comment by matteofigus** [comment]
Thanks, I hope too :+1:

**Comment by sindresorhus** [comment]
Fyi, MIT is mainly a code license, CC licenses are better suited for normal text content.

**Comment by sindresorhus** [comment]
Would be awesome if you could link back here in your list so users can easily discover more awesome lists ;)

**Comment by matteofigus** [comment]
Done https://github.com/matteofigus/awesome-speaking#miscellaneous :+1:

**Pull request merged**
