### PR TITLE
Add Motion UI Design

### PR DESCRIPTION
**Pull request by fliptheweb**
https://github.com/fliptheweb/motion-ui-design

I'm really have doubt about choosing of category for my list. Yep, it's related to front-end development and i use it in this way, but your list have many items (and my list, in the future, I hope 😅) that's more about design (Material design, Sketch etc). 
Is it time to make new `Design` category? I can make pull request if you want.

### CODE REVIEW

**Comment by davisonio** [comment]
I think adding a design category is a great idea! We'll have to think about the difference between front-end development and design - [this answer](https://www.quora.com/What-is-the-difference-between-web-design-and-front-end-development) summarises it quite nicely.

In the terms of this addition it looks great to me, nice work. :+1:

**Comment by sindresorhus** [comment]
- Items in many sections need descriptions, like `Sites`, `Html/css/js`, etc.
- The items in `Processing and other weird, but funny stuff` need title and description. Just random URLs isn't very useful.
- `Speeches, presentations, videos`, same as above with many of the items.

**Comment by sindresorhus** [comment]
@davisonio What other lists would be in a `Design` category?

**Comment by davisonio** [comment]
Hmm there isn't actually as many as I thought there was. But here's a couple:

- https://github.com/diessica/awesome-sketch (design app)
- https://github.com/sachin1092/awesome-material

Design category would have to wait a bit probably then until there's a few more lists specifically about design.

**Comment by sindresorhus** [comment]
I wouldn't say the Material list is design. It's more front-end development.

**Comment by fliptheweb** [comment]
@sindresorhus can you check it again, please. I added description for all items where it was possible. Many items in "speeches" section have self-explain title and i think descriptions for them is too much.

@davisonio @sindresorhus yep, awesome-material list more about front-end development and components for material design, sorry. But itself material design is about design :) Anyway found great https://github.com/troyericg/awesome-design by @troyericg, perhaps he'll started new section, if he wants.

**Comment by fliptheweb** [comment]
❤️

**Pull request closed without merging**
