### PR TITLE
Added Test Automation repository on the Miscellaneous section.

### PR DESCRIPTION
**Pull request by facundofarias**

### CODE REVIEW

**Comment by egeerardyn** [comment]
I think this is a really awesome resource.

However, I don't know whether I'm really a fan of the different sub-lists. I don't really like how quite some sub-lists contain a huge amount of boilerplate (links back to all the other sublists, contribution links (sometimes even in the middle of a document!), ...).
I think that makes it a bit of a maintenance nightmare. Perhaps it's better to just provide 1 link: back to the list that is one level higher in the hierarchy.

Also, while randomly clicking on a few links, I saw some dead ones, e.g. "HP Unified Functional Testing (UFT), formerly known as (QTP)" does not seem to work. So you might want to check for dead links as well.

**Comment by facundofarias** [comment]
Hey, hi.
Do you prefer a new section ("Testing"?) and then, the sub-links instead?
Cheers

**Comment by egeerardyn** [comment]
I don't mind the sub-lists as such (I think they create a lot of useful structure and allows readers to focus on the particular language they use without having to scroll like madmen).

Rather, I don't like that each sublist ends in

> # Resources
> Where to discover new libraries, information, tools, etc.

> ## Websites

> * [automated-testing.info](http://automated-testing.info) - Test automation community
> * [atinfo.github.io/at.info-knowledge-base](http://atinfo.github.io/at.info-knowledge-base/)  - Knowledge base for test automation examples on different tools and technologies

> # Other Awesome Test Automation Lists

> * [python test automation](https://github.com/atinfo/awesome-test-automation/blob/master/python-test-automation.md)
> * [java test automation](https://github.com/atinfo/awesome-test-automation/blob/master/java-test-automation.md)
> * [ruby test automation](https://github.com/atinfo/awesome-test-automation/blob/master/ruby-test-automation.md)
> * [c# test automation](https://github.com/atinfo/awesome-test-automation/blob/master/c%23-test-automation.md)
> * [php test automation](https://github.com/atinfo/awesome-test-automation/blob/master/php-test-automation.md)
> * [javascript test automation](https://github.com/atinfo/awesome-test-automation/blob/master/javascript-test-automation.md)
> * [test automation and software testing as services](https://github.com/atinfo/awesome-test-automation/blob/master/automation-and-testing-as-service.md)
> * [mobile, tablet and tv test automation](https://github.com/atinfo/awesome-test-automation/blob/master/mobile-test-automation.md)
> * [general purpose test automation tools](https://github.com/atinfo/awesome-test-automation/blob/master/general-purpose-test-automation-tools.md)

> # [Contributing](https://github.com/atinfo/awesome-test-automation/blob/master/CONTRIBUTING.md)
> Your contributions are always welcome! [Contribute](https://github.com/atinfo/awesome-test-automation/blob/master/CONTRIBUTING.md)

That's basically a copy of the top-level, which doesn't add anything new.

**Comment by sindresorhus** [comment]
Good effort, but I think you need to limit your scope. My first impression is that it's trying to do too much and the result is pretty mediocre. The JavaScript part of it is highly outdated and inaccurate. Many parts are almost empty. Lots of grammar mistakes and typos. Most descriptions of items could be improved. Try to focus on one thing instead and do it well. Many of the sub-lists would be better as separate lists. Work on it some more and I'd be happy to reconsider in a few months, but right now it's not a good fit for the awesome format.

**Pull request closed without merging**
