### PR TITLE
Adding a PHP framework, PyroCMS

### PR DESCRIPTION
**Pull request by websemantics**
PyroCMS, great PHP framework / CMS platform for Web development .. definitely deserves an AWESOME badge ..

### CODE REVIEW

**Comment by kevva** [comment]
I feel like it's a little lightweight on content currently to be considered really useful.

**Comment by websemantics** [comment]
Totally understand, ..  it's relatively new framework, built initially for CodeIgniter, but the new release PyroCMS 3 was rebuilt from the grounds-up on https://laravel.com, still beta, https://github.com/pyrocms/pyrocms/tree/v3.0.0-beta3 hence not much content / projects, but I positive it will become very popular in the PHP community, especially Laravel developers at large for the clean concepts / code it was built on .. it's your call, .. and thank you for the feedback

**Comment by RyanThompson** [comment]
@kevva While I agree, we've got a lot of content to get up and grow (working on this nearly every day). I agree with @websemantics - I don't think this will be just another CMS. Even in it's relatively early stage - it's been snatched up by small/large development agencies doing work on companies that are a household name, publicly traded, leaders in their industry, etc. Pretty exciting to see, and I think that speaks volumes for the software. I think it'd be symbiotic addition - you could benefit from a powerful CMS / app sdk exposure, and we could benefit from your exposure which will only help grow the community as a whole.

Just my tw.. ten cents ^_^

**Comment by sindresorhus** [comment]
Gonna pass on this for now as both the framework and list are too immature. Happy to reconsider in the future :)

> definitely deserves an AWESOME badge ..

Note that the "awesome" part isn't about the framework/subject, but the list itself. Work hard on making the list really good. You're of course free to use the badge even though the list is not yet included here.

**Pull request closed without merging**
