### PR TITLE
Add Hackathon

### PR DESCRIPTION
**Pull request by loleg**
https://github.com/dribdat/awesome-hackathon

Tips and tools for running tolerant and productive hackathons. We started this list a year ago to connect with other hackathon organizers. In my opinion, hackathons are placed perfectly at the intersection of awesome "Learning" and "Security" topics.

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

- **Don't waste my time.** Do a good job, adhere to all the guidelines, and be responsive. :heavy_check_mark: 
- **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).** :heavy_check_mark: 
  - [#2431](https://github.com/sindresorhus/awesome/pull/2431#pullrequestreview-1188329868)
  - [#2428](https://github.com/sindresorhus/awesome/pull/2428#pullrequestreview-1188337238)
- You have read and understood the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/main/create-list.md). :heavy_check_mark: 
- This pull request has a title in the format `Add Name of List`. :heavy_check_mark: 
- Your entry here should include a short description about the project/theme of the list. **It should not describe the list itself.** The first character should be uppercase and the description should end in a dot. It should be an objective description and not a tagline or marketing blurb.  :heavy_check_mark: 
- Your entry should be added at the bottom of the appropriate category.  :heavy_check_mark: 
- The title of your entry should be title-cased and the URL to your list should end in `#readme`.  :heavy_check_mark: 
- The suggested Awesome list complies with the below requirements.  :heavy_check_mark: 

## Requirements for your Awesome list

- **Has been around for at least 30 days.** :heavy_check_mark: 
- Don't open a Draft / WIP pull request while you work on the guidelines. :heavy_check_mark: 
- Run [`awesome-lint`](https://github.com/sindresorhus/awesome-lint) on your list and fix the reported issues. :heavy_check_mark: 
- The default branch should be named [`main`, not `master`](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/). :heavy_check_mark: 
- **Includes a succinct description of the project/theme at the top of the readme.** :heavy_check_mark: 
- It's the result of hard work and the best I could possibly produce. :heavy_check_mark: 
- The repo name of your list should be in lowercase slug format: `awesome-name-of-list`. :heavy_check_mark: 
- The heading title of your list should be in [title case](https://capitalizemytitle.com/) format: `# Awesome Name of List`. :heavy_check_mark: 
- Non-generated Markdown file in a GitHub repo. :heavy_check_mark: 
- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics. :heavy_check_mark: 
- Not a duplicate. Please search for existing submissions. :heavy_check_mark: 
- Only has awesome items. Awesome lists are curations of the best, not everything. :heavy_check_mark: 
- Does not contain items that are unmaintained, has archived repo, deprecated, or missing docs. If you really need to include such items, they should be in a separate Markdown file. :heavy_check_mark: 
- Includes a project logo/illustration whenever possible. :heavy_check_mark: 
- Entries have a description, unless the title is descriptive enough by itself. It rarely is though. :heavy_check_mark: 
- Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/main/awesome.md#awesome-badge). :heavy_check_mark: 
- Has a Table of Contents section. :heavy_check_mark: 
- Has an appropriate license. :heavy_check_mark: 
- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/main/awesome.md#include-contribution-guidelines). :heavy_check_mark: 
- All non-important but necessary content (like extra copyright notices, hyperlinks to sources, pointers to expansive content, etc) should be grouped in a `Footnotes` section at the bottom of the readme. The section should not be present in the Table of Contents. :heavy_check_mark: 
- Has consistent formatting and proper spelling/grammar. :heavy_check_mark: 
- Doesn't use [hard-wrapping](https://stackoverflow.com/questions/319925/difference-between-hard-wrap-and-soft-wrap). :heavy_check_mark: 
- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme. :heavy_check_mark: 
- Doesn't include an `Inspired by awesome-foo` or `Inspired by the Awesome project` kinda link at the top of the readme. The Awesome badge is enough. :heavy_check_mark: 

**Go to the top and read it again.**

### CODE REVIEW

**Comment by loleg** [comment]
unicorn

**Comment by steven2358** [comment]
Here are a few comments:

- Several items don't have descriptions. Although the titles are somewhat descriptive, it is recommended to add an explicit description.
- Some items don't follow the format `- [iOS](…) - Mobile operating system for Apple phones and tablets.`, i.e. the dash etc.

Apart from that, nice job! The list looks very useful.

PS: What is that "unicorn" thing that everybody is commenting?

**Comment by sindresorhus** [comment]
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

**Comment by loleg** [comment]
@steven2358 @sindresorhus 

Great feedback! I've revised the list to confirm even more closely to the guidelines (I read them carefully, trust me, but there are a lot of things to think about!) In addition to revisions to the list, I have moved the location of the entry to the arguably more appropriate 'Security' section.

Please add yourself as reviewer to approve the Pull Request (top right of the page) - thanks!

**Comment by loleg** [comment]
🙈 Reverted back to previous location.

**Comment by loleg** [comment]
Woo, thank you. By the way, the 'unicorn' is one of the things the
guidelines ask you to do..

**Comment by Symbitic** [comment]
This is my first review of an Awesome list, so I may not be the best at judging.
The categorizing seemed somewhat confusing to me, especially the subcategories for tools (which I'm not sure is necessary).
My other suggestion would be to find companies that have hackathons. I know Microsoft has one.

**Comment by modenero** [comment]
this is a fantastic list! definitely a topic that i'm very interested in, so i'm sure i'll be using it's resources in the near future.

the only "style" comment I would make is to: use `>` to "quote" the explanations you offer under each new section, eg.

> By awesome hackathon platforms, we mean web or mobile applications that are specifically designed to run a hackathon, or which have effectively adapted for use in events of this type. They typically allow organizers to announce the schedule and topics, register participants, and document the results.

otherwise, really terrific! :+1:

**Review by andrzejsydor — APPROVED** [review]

**Comment by loleg** [comment]
Thanks @Symbitic @modenero and @andrzejsydor 

I've incorporated your content and formatting suggestions.

**Comment by sindresorhus** [comment]
Tweet: https://twitter.com/awesome__re/status/1650054808844500992

**Review by loleg — COMMENTED** [review]
👍

**Pull request merged**
