### PR TITLE
Add awesome carbon repo

### PR DESCRIPTION
**Pull request by detherminal**
I looked for other [repos](https://github.com/Omikorin/awesome-carbon) but they seem inactive so I created a repo for it. I will keep it updated so you can add the repo to the list.

### CODE REVIEW

**Comment by detherminal** [comment]
I tried to fix things. How can I run checks again?

**Comment by sindresorhus** [comment]
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

**Comment by waleedsadek-panx** [comment]
By navigating to `Checks` tab you can see you have these four errors:
✖  1:1  Missing Awesome badge after the main heading
  ✖  1:1  Missing file contributing.md               
  ✖  1:1  Git repository must be at least 30 days old 
  ✖  1:1  Missing or invalid Table of Contents

Since this repo is new add it [here](https://github.com/sindresorhus/awesome/issues/2242) and once it's been 30 days or more, read this [guide](https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md#requirements-for-your-awesome-list) and once your repo is complying with it open a pull a request.

**Review by waleedsadek-panx — CHANGES_REQUESTED** [review]
Your entry needs to be at the bottom of the appropriate topic according to the guides.

Also make sure to pass the [checks](https://github.com/sindresorhus/awesome/pull/2465/checks)

**Pull request closed without merging**
