### PR TITLE
Add Relay

### PR DESCRIPTION
**Pull request by expede**
https://github.com/expede/awesome-relay

Relay is _very young_, so the list isn't very long — yet! I'm using Relay day-to-day, so this will be actively added to as my colleagues and others come across new resources.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Good start :) Very well organized structure. I would like to see some more content. I'm sure you could find some more blog posts and libraries.

https://www.npmjs.com/browse/keyword/react-relay
https://www.npmjs.com/search?q=react+relay
https://www.youtube.com/watch?v=9sc8Pyc51uU

Oh, and you've linked to the wrong Relay project in the readme description.

-

Please read the [instructions](https://github.com/sindresorhus/awesome/blob/master/create-list.md) for creating a new list, [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

Especially this part:

> Wait at least a couple of weeks after creating a list before submitting to give it a chance to mature.

Ping me here in a few weeks and I'll reopen ;)

**Comment by sindresorhus** [comment]
> Ping me here in a few weeks and I'll reopen ;)

@expede Would you like to resubmit?

**Comment by expede** [comment]
@sindresorhus Sorry for the late reply (busy product launch). Here is the aforementioned ping :wink:

**Comment by sindresorhus** [comment]
Can you add a license to your repo? See https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license

**Comment by sindresorhus** [comment]
Added: https://github.com/sindresorhus/awesome/commit/162e14c11a2a44626be611561a3cfa54f04555d0

**Pull request closed without merging**
