### PR TITLE
Add GitHub Alternatives

### PR DESCRIPTION
**Pull request by anatolinicolae**
https://github.com/ianchanning/awesome-github-alternatives

A list of alternatives to Github after Microsoft acquisition 🤷‍♂️ .

### CODE REVIEW

**Comment by legodude17** [comment]
The list must be around for 30 days before it can be added.

**Comment by sindresorhus** [comment]
Hey, sorry for the lack of response, please see #1363.

**Comment by ianchanning** [comment]
Thanks @anatolinicolae. I've fixed those issues from @transitive-bullshit 's [comment](https://github.com/sindresorhus/awesome/pull/1330#pullrequestreview-141333436), I had tried to meet most of the guidelines, but at the time there was the hard and fast rule of 30 days.

I think I meet all the criteria except for these two arguable points:

* It's the result of hard work and the best I could possibly produce.
* Only has awesome items. Awesome lists are curations of the best, not everything.

It's not a massive list, so there's only so much work required. I also haven't gone through the work of installing and trying all the systems. I did get all sources that came from what I thought were reasonable recommendations (mostly Hacker News) and then matched them up with the website's information. I've made the effort to make sure that everything is neatly categorised so that if you want a specific technology / license then it's easy to find.

**Comment by ianchanning** [comment]
Also I obviously need to review two other awesome lists which I haven't done yet.

**Comment by ianchanning** [comment]
I have now been through at least two awesome lists done a basic review and left comments, but I'm not sure how you get added as a reviewer.

**Comment by sindresorhus** [comment]
```
❯ awesome-lint https://github.com/ianchanning/awesome-github-alternatives
✖ Linting

  README.md:22:1
  ✖  22:1   Marker style should be *                                      remark-lint:unordered-list-marker-style
  ✖  23:11  List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  24:1   Marker style should be *                                      remark-lint:unordered-list-marker-style
  ✖  25:11  List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  26:1   Marker style should be *                                      remark-lint:unordered-list-marker-style
  ✖  27:11  List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  28:1   Marker style should be *                                      remark-lint:unordered-list-marker-style
  ✖  29:36  List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  30:1   Marker style should be *                                      remark-lint:unordered-list-marker-style
  ✖  31:18  List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  32:1   Marker style should be *                                      remark-lint:unordered-list-marker-style
  ✖  33:37  List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  34:1   Marker style should be *                                      remark-lint:unordered-list-marker-style
  ✖  34:42  List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖  36:1   Marker style should be *                                      remark-lint:unordered-list-marker-style
  ✖  36:44  Text "github" should be written as "GitHub"                   remark-lint:awesome/spell-check
  ✖  37:17  List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  38:1   Marker style should be *                                      remark-lint:unordered-list-marker-style
  ✖  39:39  List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  40:1   Marker style should be *                                      remark-lint:unordered-list-marker-style
  ✖  41:17  List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  42:1   Marker style should be *                                      remark-lint:unordered-list-marker-style
  ✖  43:16  List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  44:1   Marker style should be *                                      remark-lint:unordered-list-marker-style
  ✖  45:32  List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  46:1   Marker style should be *                                      remark-lint:unordered-list-marker-style
  ✖  47:15  List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  48:1   Marker style should be *                                      remark-lint:unordered-list-marker-style
  ✖  48:3   Link to https://www.tuleap.org is dead                        remark-lint:no-dead-urls
  ✖  49:22  List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  50:1   Marker style should be *                                      remark-lint:unordered-list-marker-style
  ✖  51:11  List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  52:1   Marker style should be *                                      remark-lint:unordered-list-marker-style
  ✖  53:11  List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  54:1   Marker style should be *                                      remark-lint:unordered-list-marker-style
  ✖  55:18  List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  56:1   Marker style should be *                                      remark-lint:unordered-list-marker-style
  ✖  57:18  List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  63:1   Marker style should be *                                      remark-lint:unordered-list-marker-style
  ✖  63:38  List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  64:1   Marker style should be *                                      remark-lint:unordered-list-marker-style
  ✖  64:52  List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  65:1   Marker style should be *                                      remark-lint:unordered-list-marker-style
  ✖  66:1   Marker style should be *                                      remark-lint:unordered-list-marker-style
  ✖  66:3   Link to https://www.tuleap.org is dead                        remark-lint:no-dead-urls
  ✖  66:35  List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  67:1   Marker style should be *                                      remark-lint:unordered-list-marker-style
  ✖  68:5   List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  69:1   Marker style should be *                                      remark-lint:unordered-list-marker-style
  ✖  70:1   Marker style should be *                                      remark-lint:unordered-list-marker-style
  ✖  71:1   Marker style should be *                                      remark-lint:unordered-list-marker-style
  ✖  72:1   Marker style should be *                                      remark-lint:unordered-list-marker-style
  ✖  73:5   List item description must end with proper punctuation        remark-lint:awesome/list-item
  ✖  74:1   Marker style should be *                                      remark-lint:unordered-list-marker-style
  ✖  75:5   List item description must end with proper punctuation        remark-lint:awesome/list-item

  55 errors
```

https://github.com/sindresorhus/awesome-lint

**Comment by sindresorhus** [comment]
Can you fix the merge conflict?

**Comment by sindresorhus** [comment]
It's not clear how the header image is related to GitHub?

**Comment by sindresorhus** [comment]
> Lie back and read the Ts & Cs to see how they harvest your data.

Not clear what `Ts` and `Cs` is.

**Comment by sindresorhus** [comment]
> GitLab - See above

Don't force the user to interrupt their flow and go look for the other entry. Duplicating the description is totally fine.

**Comment by ianchanning** [comment]
@sindresorhus Thank you for your comments, I can fix all the other issues, but https://www.tuleap.org is the correct working link, so I don't know how to get past the linter if it thinks that that is broken.

```sh
channi16@ICT0115123:~/$ wget https://www.tuleap.org
--2019-02-26 10:10:47--  https://www.tuleap.org/
Resolving www.tuleap.org (www.tuleap.org)... 163.172.41.21
Connecting to www.tuleap.org (www.tuleap.org)|163.172.41.21|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14790 (14K) [text/html]
Saving to: ‘index.html’

index.html                 100%[=====================================>]  14.44K  --.-KB/s    in 0s      

2019-02-26 10:10:47 (85.2 MB/s) - ‘index.html’ saved [14790/14790]
```

**Comment by anatolinicolae** [comment]
Running the linter locally would mark that as a working link since you're correctly resolving it 🤔

**Comment by ianchanning** [comment]
I haven't tried running the linter locally yet - but if it works locally that won't stop the problem that the server is having when it runs it

**Comment by ianchanning** [comment]
I'm just going to link to their Github repo, they bury links to their source code quite deeply

**Comment by ianchanning** [comment]
@sindresorhus I've run the linter locally and fixed all the linting issues. I've tried to improve the list by putting a section for each language rather than tags at the end and used badges for the licences to make them clearer. 

I'm not sure what to do about the icon - it's just a hand waving bye bye. I couldn't think of a better logo. I can just remove it - I don't know the copyright issues around using the GitHub logo

**Comment by sindresorhus** [comment]
> but [tuleap.org](https://www.tuleap.org) is the correct working link, so I don't know how to get past the linter if it thinks that that is broken.

https://github.com/transitive-bullshit/check-links/issues/4

**Comment by sindresorhus** [comment]
> I couldn't think of a better logo. I can just remove it - I don't know the copyright issues around using the GitHub logo

The rules for using the GitHub logo is strict, but you could use an octocat instead: https://octodex.github.com/ (Just make sure you give proper credit) Combine that with the bye bye emoji and it could look good.

**Comment by ianchanning** [comment]
Is it ok if I just remove the logo? At the moment I can't see a good way of combining those two and I'm not good enough of a designer to make something that does look decent.

**Comment by sindresorhus** [comment]
Yes

**Comment by ianchanning** [comment]
Ok, removed

**Comment by ianchanning** [comment]
@sindresorhus Is there anything more required for this PR?

**Comment by sindresorhus** [comment]
The diff in this PR is not correct. It includes a lot of unrelated changes: https://github.com/sindresorhus/awesome/pull/1330/files

**Pull request closed without merging**
