### PR TITLE
Add Full-Text Search

### PR DESCRIPTION
**Pull request by Kikobeats**
Hello,

I added https://github.com/Kikobeats/awesome-full-text-search under the JavaScript section since this is the list I'm maintaining for the last 5 years.

- [x] branch name is `main`.
- [x] linter is reporting 0 issues.
- [x] added the item with a description in the right position.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

**Comment by ozh** [comment]
A couple pointers to help out @Kikobeats : 

* you didn't review (at least 2) open PR and state here what your reviews were (point 2 of the [PR requirements](https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md#requirements-for-your-pull-request))
* you didn't stick to the "short description about the project/theme of the list" guideline (point 5 of the PR reqs)
* you didn't add your list to the bottom of the appropriate category (point 6 of the PR reqs)

The best is, well, to just stick to the PR template, I guess :)

Hope that helps !

**Comment by brianmingus2** [comment]
The main problem with this list is that it is nowhere close to including all of the great full-text search engines that have been developed. For example, your project does not include Lucene, which is by far the most popular full text search engine, and has been around the longest as well.

**Comment by Kikobeats** [comment]
@brianmingus2 most of the items on the list are lucene-like projects

**Comment by prokopsimek** [comment]
Hi, it's 26 days since the last comment already and the PR still doesn't fulfill all rules described in [PR requirements](https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md#requirements-for-your-pull-request).

Please re-read the requirements and I'd suggest starting from the beginning and re-create the PR that fulfills all rules.

- Your PR title is wrong
- Your first PR description should be formatted as PR template
- You have to review 2 more PRs and mention them in your PR description
...and many more...

**Comment by Kikobeats** [comment]
Fixed title!

**Comment by ozh** [comment]
This repo and rules are just zealotry at their finest. I've given up long ago on getting my own list listed here.

**Comment by Kikobeats** [comment]
@ozh I agree – Rules like `You have to review at least 2 other` are just adding a lot of noise over PRs with silly comments just to fulfilled the rule.

I can understand why these rules are necessary for a repo with giant dimensions like this, but honestly, they are not working.

**Comment by prokopsimek** [comment]
@ozh @Kikobeats I agree with contributing rules but the truth is this guide is very long and it's easy to lose in it. Especially reviewing 2 PRs is a great idea. Worse are the nitpicking rules about formatting. There are many of them.

**Pull request closed without merging**
