### PR TITLE
Add Git Hooks

### PR DESCRIPTION
**Pull request by CompSciLauren**
**https://github.com/CompSciLauren/awesome-git-hooks**

**This list is about git hooks, scripts that can be customized to automate a wide variety of tasks during git workflows.**

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖
Yes

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**
Yes

## Requirements for your pull request

- **Don't waste my time.** Do a good job, adhere to all the guidelines, and be responsive.
Understood

- **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).**
PR: https://github.com/sindresorhus/awesome/pull/1582
PR: https://github.com/sindresorhus/awesome/pull/1585

- You have read and understood the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
Yes

- This pull request has a title in the format `Add Name of List`.
Yes

- Your entry here should include a short description about the project/theme of the list. **It should not describe the list itself.** The first character should be uppercase and the description should end in a dot. It should be an objective description and not a tagline or marketing blurb.
Yes

- Your entry should be added at the bottom of the appropriate category.
Exception requested - Added it to the bottom of the git/GitHub related lists under Development Environment, but that is not the very bottom of the section. The git/GitHub lists seem to be grouped together, so it makes sense to me that git hooks would be with them rather than separate at the bottom. I thought this would be okay, but if moving it to the bottom is preferred still then I will move it.

- The suggested Awesome list complies with the below requirements.
Yes

## Requirements for your Awesome list

- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
Yes

- Don't open a Draft / WIP pull request while you work on the guidelines. A pull request should be 100% ready and should adhere to all the guidelines when you open it.
Waited

- Run [`awesome-lint`](https://github.com/sindresorhus/awesome-lint) on your list and fix the reported issues. If there are false-positives or things that cannot/shouldn't be fixed, please [report it](https://github.com/sindresorhus/awesome-lint/issues/new).
Awesome-Lint Passing

- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
Yes

- It's the result of hard work and the best I could possibly produce.
	**If you have not put in considerable effort into your list, your pull request will be immediately closed.**
Yes

- The repo name of your list should be in lowercase slug format: `awesome-name-of-list`.
Yes

- The heading title of your list should be in [title case](https://capitalizemytitle.com/) format: `# Awesome Name of List`.
Yes

- Non-generated Markdown file in a GitHub repo.
Yes

- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
Yes, with added topics as well

- Not a duplicate. Please search for existing submissions.
Not a duplicate, though other attempts have already been made by others but were not added. I looked through them to make sure I would not run into the same issues discussed in those ones.

- Only has awesome items. Awesome lists are curations of the best, not everything.
Yes

- Includes a project logo/illustration whenever possible.
	- Either centered, fullwidth, or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
	- The image should link to the project website or any relevant website.
	- **The image should be high-DPI.** Set it to maximum half the width of the original image.
Yes

- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
Yes

- Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
	- Should be placed on the right side of the readme heading.
		- Can be placed centered if the list has a centered graphics header.
	- Should link back to this list.
Yes

- Has a Table of Contents section.
	- Should be named `Contents`, not `Table of Contents`.
	- Should be the first section in the list.
	- Should only have one level of [nested lists](https://commonmark.org/help/tutorial/10-nestedLists.html), preferably none.
Yes, and did not nest any lists. Under "Overview of Hooks" I have nine sub-sections based on the type of hook described. However, the Overview of Hooks section is not terribly long so I didn't think nesting each category was necessary. As more hooks are added over time it could become necessary. I chose to not include a nested list, but I'm open to feedback on this if anyone thinks it would be better to have the categories mentioned in the table of contents.

- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
	- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
	- [WTFPL](http://www.wtfpl.net) and [Unlicense](http://unlicense.org) are not acceptable licenses.
	- **If you use a license badge, it should be SVG, not PNG.**
Yes. Uses CC0 license.

	- To verify that you've read all the guidelines, please add comment with just the word `unicorn`.
See comments section :)

- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
	- The file should be named `contributing.md`. Casing is up to you.
Yes

- Has consistent formatting and proper spelling/grammar.
	- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
	- The description starts with an uppercase character and ends with a period.
	- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
Yes

- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.
No Travis badge

- Doesn't include an `Inspired by awesome-foo` or `Inspired by the Awesome project` kinda link at the top of the readme. The Awesome badge is enough.
Yes

**Go to the top and read it again.**
I went through considerable effort to make sure I did everything correctly, re-read it multiple times and compared what I have to previous PRs and other lists in the Awesome list. Optimistic that I did everything correctly but I'll be quick to fix any changes if needed! Thank you for your time!

### CODE REVIEW

**Comment by CompSciLauren** [comment]
Unicorn! :unicorn:

**Comment by irazasyed** [comment]
Nice project, but doesn't it look quite verbose?

Also, you can place the awesome badge in the center since your header graphics are in the center too.

This is less of a list and more of a guide TBH. At least the way it has been laid out.

**Comment by CompSciLauren** [comment]
Yeah I guess my original intention was to make the repo a one-stop place to learn the basics as well as see a list of git hook scripts. I can see how my list doesn't quite look like the others since I added explanations throughout.

Centered the badge.

I removed the guide aspects from the repo. The only "guide" section I kept is the Quick Start section because I think it's important and concise enough to stay. I renamed Overview of Hooks to be Git Hook Scripts and took out the explanation for it as well.

**Comment by rafaskb** [comment]
Project looks good! Quite verbose like irazasyed said, and not quite a list, but follows the guidelines nicely, is very intuitive and _awesome_. I would just capitalize the hook section descriptions such as changing "invoked by git commit" to "Invoked by git commit", and also list the Git Hook Scripts sub topics in the table of contents.

Looks great though, and I learned a lot while reviewing it, I hope it's approved! :)

**Comment by CompSciLauren** [comment]
@rafaskb are you sure you saw my current readme and not the outdated version? irazasyed's comment is about an earlier version, I updated it and fixed the issues he mentioned.

I respectfully disagree about it being "quite verbose". Which section is quite verbose to you? An initial paragraph is very common to include in an awesome list. The quick start section is concise and I explained my reasoning for keeping it even though it's a "guide". The rest of it is a bunch of lists, so I don't understand why you say it's "not quite a list" unless you were accidentally reviewing an older version somehow.

**Comment by rafaskb** [comment]
@CompSciLauren About the verbose part, I didn't mean to make it sound like it was an issue, it just seemed more verbose than other awesome lists I've used in the past. Maybe that has to be with the Quick Start section being in the middle of the Table of Contents and the actual list, like a separator that's not present in most lists. It serves a great purpose though.

The info on invoking hooks probably helped with that impression as well, and with them removed and the table of contents improved, the list looks much cleaner now.

**Comment by CompSciLauren** [comment]
@rafaskb Oh okay. I think I misinterpreted what you were saying, sorry. That all makes sense though. Maybe it would be better to have the actual list of scripts first, then the quick start section second. I went ahead and updated it, could you take a look and let me know what do you think?

**Comment by rafaskb** [comment]
@CompSciLauren I really like this change! As someone who never used git hooks I access the list, see the table of contents, then all the specific hooks, and I already spot some hooks that would be useful to my projects. My next thought is "Okay but how do I use them?" and the very next section of your list is exactly that.
I think this change gives the list a very natural flow, and the information on how to use hooks is still there, but no longer as an obstacle to the actual list of hooks. :)

**Comment by CompSciLauren** [comment]
Definitely! I like this a lot better too. Thanks for all your help! I appreciate it.

**Comment by weidenba** [comment]
It's great work and I think this list will help a lot of people.
However there are few things you should change:

1: According to the Guidlines: You should remove the travis badge
2: There is a license missmatch: 
> This work is licensed under a Creative Commons Attribution 4.0 International License 

But you added a `Creative Commons Zero v1.0 Universal` License file.

**Comment by sindresorhus** [comment]
Tweet: https://twitter.com/awesome__re/status/1175838794756440065

**Pull request merged**
