### PR TITLE
Add Ethereum

### PR DESCRIPTION
**Pull request by void4**
Add awesome-ethereum to decentralized systems, since there is no such resource yet.

https://github.com/void4/awesome-ethereum#readme
There are lists of Bitcoin and other decentralized systems, but not one for the Ethereum system, the second largest system in operation. 

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

## Requirements for your pull request

- **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).** Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration. **I seem to be unable to comment on other PRs**
- I have read and understood the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title in the format `Add Name of List` (Example: `Add Swift`), not `Update readme.md` or `Add awesome list`. ✓
- The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.** <br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.  ✓
	- Be added at the bottom of the appropriate category. ✓
- The list I'm submitting complies with the below requirements.

## Requirements for your Awesome list

- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent. ✓
- It's the result of hard work and the best I could possibly produce. ✓
- Non-generated Markdown file in a GitHub repo. ✓
- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)] (https://github.com/willempienaar/awesome-quantified-self) ✓
- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics. ✓
- Not a duplicate. ✓
- Only has awesome items. Awesome lists are curations of the best, not everything. ✓
- Includes a project logo/illustration whenever possible. ✓
	- Either centered, fullwidth, or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
	- The image should link to the project website or any relevant website.
	- The image should be high-DPI. Set it to maximum half the width of the original image.
- Entries have a description, unless the title is descriptive enough by itself. It rarely is though. ✓
- Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge). ✓
	- Should be placed on the right side of the readme heading. ✓
		- Can be placed centered if the list has a centered graphics header.
	- Should link back to this list.
- Has a Table of Contents section.
	- Should be named `Contents`, not `Table of Contents`. ✓
	- Should be the first section in the list. ✓
	- Should only have one level of [nested lists](https://commonmark.org/help/tutorial/10-nestedLists.html), preferably none. ✓
- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
	- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.** ✓
	- [WTFPL](http://www.wtfpl.net) and [Unlicense](http://unlicense.org) are not acceptable licenses.
	- If you use a license badge, it should be SVG, not PNG.
- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines). ✓
	- The file should be named `contributing.md`. Casing is up to you. ✓
- Has consistent formatting and proper spelling/grammar.
	- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`✓
	- The description starts with an uppercase character and ends with a period. ✓
	- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`. ✓
- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme. ✓

Go to the top and read it again.

### CODE REVIEW

**Comment by deveshp** [comment]
The image for Ethereum logo seems to be broken

**Comment by void4** [comment]
Fixed.

**Comment by steven2358** [comment]
Interesting list but most entries don't have a description. Would improve greatly by adding a description to each entry.

**Comment by void4** [comment]
Okay, added descriptions to most of them.

**Comment by wolfika** [comment]
Thank you for the submission. However, it seems like you're missing the contribution guidelines. Proper and consistent spelling/grammar and more descriptive descriptions could would be a huge improvement as well.

**Comment by dreamingechoes** [comment]
Looks good, but it seems that there's another pull request about Ethereum opened: https://github.com/sindresorhus/awesome/pull/1452. I don't know what's the way to solve this kind of situations, maybe @sindresorhus can help with this 😄

**Comment by sindresorhus** [comment]
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

**Comment by sindresorhus** [comment]
```
❯ awesome-lint https://github.com/void4/awesome-ethereum
✖ Linting

  README.md:108:3
  ✖    1:21   Invalid badge source                                                   awesome/badge
  ✖   19:1    ToC item "Books" does not match corresponding heading "Related Lists"  awesome/toc
  ✖   47:4    Text "Youtube" should be written as "YouTube"                          awesome/spell-check
  ✖   54:3    Link to https://ethereumfoundation.org/devcon3/ is dead                no-dead-urls
  ✖   56:91   List item description must end with proper punctuation                 awesome/list-item
  ✖   57:102  List item description must end with proper punctuation                 awesome/list-item
  ✖   65:55   List item description must start with valid casing                     awesome/list-item
  ✖   67:46   Text "Javascript" should be written as "JavaScript"                    awesome/spell-check
  ✖   68:3    Link to https://ethcore.io/parity.html is dead                         no-dead-urls
  ✖   75:35   List item link and description must be separated with a dash           awesome/list-item
  ✖   86:3    Link to http://dapps.ethercasts.com/ is dead                           no-dead-urls
  ✖  108:3    Link to http://truffleframework.com/ is dead                           no-dead-urls
  ✖  152:3    Text "github" should be written as "GitHub"                            awesome/spell-check
  ✖  153:3    Text "github" should be written as "GitHub"                            awesome/spell-check
  ✖  154:3    Text "github" should be written as "GitHub"                            awesome/spell-check
  ✖  155:3    Text "github" should be written as "GitHub"                            awesome/spell-check
  ✖  156:3    Text "github" should be written as "GitHub"                            awesome/spell-check
  ✖  160:2    License image must be SVG                                              awesome/license
```

https://github.com/sindresorhus/awesome-lint

**Comment by sindresorhus** [comment]
Closing this in favor of https://github.com/sindresorhus/awesome/pull/1452. That list was more complete and the author was very responsive.

**Pull request closed without merging**
