### PR TITLE
Add awesome-influxdb to Databases section

### PR DESCRIPTION
**Pull request by mark-rushakoff**

### CODE REVIEW

**Comment by aleksandar-todorovic** [comment]
Seems good enough for me. :+1:

**Comment by arthurvr** [comment]
contributing.md: 

> Link additions should be added to the bottom of the relevant category.

**Comment by aleksandar-todorovic** [comment]
@arthurvr I don't think that's really necessary. Even though this list does not sort its items alphabetically, that doesn't mean that others cannot do so if they wish.

**Comment by arthurvr** [comment]
@aleksandar-todorovic If only some items are ordered alphabetically that only causes confusion. Right now they are ordered by date of addition. We required this before too, and people should just learn to read the contribution guidelines ;)

**Comment by mark-rushakoff** [comment]
It threw me off because the Databases section was already sorted alphabetically. I've updated the branch to add it to the bottom of the section.

**Comment by sindresorhus** [comment]
@aleksandar-todorovic @arthurvr I think you're talking past eachother. @arthurvr Was commenting on the actual contribution here, not how the referenced list is sorted.

**Comment by sindresorhus** [comment]
@mark-rushakoff Added. Would be awesome if you could link back here in your list so users can easily discover more awesome lists ;)

**Comment by mark-rushakoff** [comment]
Linked back in https://github.com/mark-rushakoff/awesome-influxdb/commit/8100ee04e91e24fcd07e77758cc3289c050d89a2. Thanks!

**Pull request merged**
