### PR TITLE
Add Grid

### PR DESCRIPTION
**Pull request by MikhailTatsky**
**[Grid](https://github.com/FancyGrid/awesome-grid)**

**This url is about Grid solutions for Front-End. It will be useful for community to have links on all grid solutions without wasting time on finding serious by self.**

# ALL THE BELOW CHECKBOXES SHOULD BE DONE AND CHECKED AND THE ABOVE PLACEHOLDERS SHOULD BE FILLED IN BEFORE SUBMITTING A PULL REQUEST!

- [x] I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- [x] This pull request has a descriptive title.
- The list I added
	- [x] **has been around for at least 20 days,**
	- [x] is not a duplicate,
	- [x] only has awesome items with descriptions,
	- [x] contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- [x] has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license),
	- [x] has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- [x] has been checked for inconsistent formatting, spelling and grammar, and
	- [x] has been added at the bottom of the appropriate category.

### CODE REVIEW

**Comment by aleksandar-todorovic** [comment]
MIT is a software license, not a license for the documentation, and therefore, it is not recommended (as it is mentioned [here](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license)).

Any chance you could reconsider your decision?

**Comment by MikhailTatsky** [comment]
Done.

**Comment by davisonio** [comment]
A few suggestions:

- capitalise the top heading in the realm to be `Awesome Grid`
- "Inspired by the Awesome thing." isn't really necessary if the badge is there. Maybe you could replace this with a description of what grid libraries are?
- the page breaks aren't needed - a new section is started with a new heading
- libraries link in table of contents is broken

**Comment by sindresorhus** [comment]
- Pretty much every description should be improved somehow.
- I would like to see more than just libraries. Include some blog posts, tutorials, videos of talks, book, learning material, etc.
- The categorization needs to be improved. Like, why is `Libraries (Plugins Free)` not under `Free and Open Source Libraries`.
- `JQuery` => `jQuery`
- `Angular` => `AngularJS`
- `feature( 1 000 000 rows)` => `feature (1 000 000 rows)`
- The category sections should be `##`, not `###`.
- The first character in descriptions should be capitalized.

Take a look at other lists for inspiration on how to improve yours.

**Comment by sindresorhus** [comment]
ping

**Comment by MikhailTatsky** [comment]
I changed several points.
But about
 Materials, I am afraid I do not know any.
Althought I am about grids for 4+ years.

**Comment by MikhailTatsky** [comment]
Check it out, please.

**Comment by sindresorhus** [comment]
Multiple things in our feedback are not resolved. Closing for now. Happy to reopen in a month when you've had some chance to generally improve the list, including our feedback.

**Pull request closed without merging**
