### PR TITLE
Add a link to Yeoman generator for awesome lists

### PR DESCRIPTION
**Pull request by dar5hak**
I wrote [this Yeoman generator](https://github.com/dar5hak/generator-awesome-list) to make it easy to get started building an awesome list, and thought maybe the readers of this doc might find it useful. The generated directory structure looks [like this](https://github.com/dar5hak/generator-awesome-list/tree/master/app/templates).

Is it okay to add it here?

# By submitting this pull request I confirm I've read and complied with the below requirements.

Failure to properly do so will just result in the pull request being closed and everyone's time wasted. Please read it twice. Most people miss many things.

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title. For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should include a short description about the list project/theme (not the list itself), and should be added at the bottom of the appropriate category.
- The list I added
	- **has been around for at least 30 days,**
	- is the result of hard work and is the best I could possibly produce,
	- is a non-generated Markdown file in a GitHub repo,
	- is not a duplicate,
	- includes a succinct description of the project/theme at the top ([example](https://github.com/willempienaar/awesome-quantified-self)),
	- includes a project logo/illustration (whenever possible) at the top right of the readme ([example](https://github.com/sindresorhus/awesome-electron)). (The logo should link to the project website or any relevant website. The logo should be high-DPI, so set it to maximum half the width of the original image.),
	- only has awesome items **with descriptions** *(Awesome lists are curations of the best, not of everything)*,
	- contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- has a Table of Contents section **named `Contents`** as the first section,
	- has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license) *(Meaning something like CC0, NOT a code licence like MIT, BSD, Apache, etc)* *(If you use a license badge, it should be SVG, not PNG)*,
	- has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- doesn't include a Travis badge,
	- has been checked for inconsistent formatting, spelling, and grammar:
		- Each link description starts with an uppercase character and ends with a period.
		- Drop all the `A` / `An` prefixes in the descriptions.
		- Consistent naming. For example, `Node.js`, not `NodeJS` or `node.js`.

### CODE REVIEW

**Comment by aleksandar-todorovic** [comment]
Seems to me like it has pretty sane defaults. Leaving the decision up to someone else, but I quite like this and appreciate the effort you've put into it!

**Comment by sindresorhus** [comment]
Good idea, but please make sure it actually follows the guidelines. There are multiple things it doesn't follow correctly. It should also create the `Contents` section and maybe also a dummy section with dummy content to show how to properly format it.

`Inspired by the awesome list thing.` - Drop this.

**Comment by dar5hak** [comment]
Sure thing. I'll comment back here in a day or two.

**Comment by dar5hak** [comment]
All right, how does [this](https://github.com/dar5hak/generator-awesome-list/tree/master/app/templates) look?

**Comment by sindresorhus** [comment]
> includes a succinct description of the project/theme at the top (example),

⬆️

> has an appropriate license (Meaning something like CC0, NOT a code licence like MIT, BSD, Apache, etc) **(If you use a license badge, it should be SVG, not PNG),**

⬆️ 

---

I tried running the generator, but it exited early, before all the prompts were asked:

```
/private/var/folders/3x/jf5977fn79jbglr7rk0tq4d00000gn/T/qyXZwUqmJv
❯ yo awesome-list
? The name of your awesome list Foo

/private/var/folders/3x/jf5977fn79jbglr7rk0tq4d00000gn/T/qyXZwUqmJv
❯
```

**Comment by dar5hak** [comment]
@sindresorhus 

> includes a succinct description of the project/theme at the top (example),
But as a generator, how do we decide what's succinct? Shouldn't it just leave that to the user? 😕 

> has an appropriate license
It does use CC0 in the readme.

> I tried running the generator, but it exited early, before all the prompts were asked
Oh! 😮  I'll have a look tonight.

**Comment by dar5hak** [comment]
> I tried running the generator, but it exited early, before all the prompts were asked

Fixed in 1.3.1 :tada:

**Comment by dar5hak** [comment]
And now it makes sure it always complies to `awesome-lint`!

**Comment by sindresorhus** [comment]
> It does use CC0 in the readme.

That's not what I was referring to. I bolded what you're missing. Please read it more closely.

**Comment by dar5hak** [comment]
Ah, sorry. My bad. Fixed it.

**Pull request merged**
