### PR TITLE
Add Unique ID to misc category

### PR DESCRIPTION
**Pull request by grantcarthew**
https://github.com/grantcarthew/awesome-id

List of ID generation and hashing packages.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Hey, sorry for the lack of response, please see #1363.

**Comment by sindresorhus** [comment]
It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

**Comment by sindresorhus** [comment]
```
❯ awesome-lint https://github.com/grantcarthew/awesome-unique-id
✖ Linting

  README.md:1:22
  ✖   1:1   Missing or invalid Table of Contents                          remark-lint:awesome/toc
  ✖   1:22  Invalid badge source                                          remark-lint:awesome/badge
  ✖   8:3   Invalid list item link URL                                    remark-lint:awesome/list-item
  ✖   9:3   Invalid list item link URL                                    remark-lint:awesome/list-item
  ✖  13:48  List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖  14:34  List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖  15:46  List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖  16:41  List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖  17:65  List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖  18:46  List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖  19:47  List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖  20:54  List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖  21:49  List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖  22:38  List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖  23:54  List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖  24:51  List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖  25:56  List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖  26:49  List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖  27:47  List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖  28:55  List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖  29:55  List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖  30:73  List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖  30:76  Text "github" should be written as "GitHub"                   remark-lint:awesome/spell-check
  ✖  34:54  List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖  35:36  List item link and description must be separated with a dash  remark-lint:awesome/list-item
  ✖  35:39  Text "github" should be written as "GitHub"                   remark-lint:awesome/spell-check

  26 errors
```

https://github.com/sindresorhus/awesome-lint

**Comment by sindresorhus** [comment]
Can you fix the merge conflict?

**Comment by grantcarthew** [comment]
Sorry, this is on my todo list.

**Comment by sindresorhus** [comment]
Closing for lack of response.

**Comment by grantcarthew** [comment]
Sorry @sindresorhus, I'll get back to it when I can. Appreciate the work you have done.

**Pull request closed without merging**
