### PR TITLE
Add awesome-transit

### PR DESCRIPTION
**Pull request by luqmaan**
A collection of awesome transit projects. This includes a variety of APIs, apps, visualizations, resources, and libraries for consuming transit data.

https://github.com/luqmaan/awesome-transit

:bus:

### CODE REVIEW

**Comment by aleksandar-todorovic** [comment]
It's missing contributing guidelines at the moment (as stated in `awesome.md` file in this repository).

**Comment by luqmaan** [comment]
Thanks, I've added them now: https://github.com/luqmaan/awesome-transit/blob/master/CONTRIBUTING.md

**Comment by sindresorhus** [comment]
Awesome! More of these kinds of lists please.

**Comment by luqmaan** [comment]
:heart:

**Pull request merged**
