### PR TITLE
Add Python Books

### PR DESCRIPTION
**Pull request by Junnplus**
https://github.com/Junnplus/awesome-python-books
Some awesome books of Python programming language

### CODE REVIEW

**Comment by sindresorhus** [comment]
Some feedback:

- The contributing.md file could be improved. See: https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md
- `Resources` should be named `Table of Contents`
- Would look nicer if the `Grammar` section used sub-headings instead of sub-lists.
- It looks very messy having the links on the right side. I would instead linkify the whole thing to the book and have extra links on the right side for Online edition and other languages.

**Comment by Junnplus** [comment]
@sindresorhus Thanks for the feedback! :D

- [x] Update contributing.md.
- [x] `Resources` renamed `Table of Contents`.
- [x] Used sub-headings instead of sub-lists in `Grammar` section.
- [x] Fixed messy links on the right side.

**Comment by sindresorhus** [comment]
> Fixed messy links on the right side.

I don't see this change? Did you understand what I was referring to?

**Comment by sindresorhus** [comment]
❓

**Pull request closed without merging**
