### PR TITLE
Add Django

### PR DESCRIPTION
**Pull request by wsvincent**
Adding https://github.com/wsvincent/awesome#readme

This is an up-to-date Django repo. The previous Django list [was recently removed](https://github.com/sindresorhus/awesome/pull/1477) since it had not been updated for quite some time.

I believe I have met all the requirements for submitting a new list.

### CODE REVIEW

**Comment by sindresorhus** [comment]
The link is not correct.

**Comment by wsvincent** [comment]
You are correct @sindresorhus . Now fixed. Thank you for all your efforts maintaining this list. I know it must seem like a thankless task at times but it is a huge benefit to the community.

**Comment by simskij** [comment]
Good job! Really appreciate the effort you've put into this list.

With that said, here are some pointers:
* Change descriptive block quotes to italic or just regular text. The current usage of blocks makes the list feel cluttered and messy.
* Change the block quotes in the Videos section to headers as they describe a group of content.
* A lot of resources still lack descriptions.
* Please indicate which links have affiliate id's in some way, or even better: drop the affiliate id's all together. We all do this for free.

**Comment by wsvincent** [comment]
I rearranged a lot based on your feedback. Affiliate links are gone. Tried to simplify things while also adding more description where needed.

https://github.com/wsvincent/awesome-django#readme

**Comment by sindresorhus** [comment]
> You have to review at least 2 other open pull requests. Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration.

---

> The entry in the Awesome list should:
Include a short description about the project/theme of the list. It should not describe the list itself.
Example: - [Fish](…) - User-friendly shell., not - [Fish](…) - Resources for Fish..

---

> Includes a succinct description of the project/theme at the top of the readme. (Example)


---

Includes a project logo/illustration whenever possible.

**The image should link to the project website or any relevant website.**

---

Has an appropriate license.

**If you use a license badge, it should be SVG, not PNG.**

---

The description starts with an uppercase character **and ends with a period.**

**Comment by sindresorhus** [comment]
The items in the `Official Resources` don't need the `Django` word in their titles. It's implied. Same with the `Community` section.

**Comment by sindresorhus** [comment]
Closing for lack of response.

**Pull request closed without merging**
