### PR TITLE
Add Swift Education

### PR DESCRIPTION
**Pull request by hsavit1**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Generally looks, but have to admit the emoji links are over the top and more confusing than useful.

**Comment by hsavit1** [comment]
So what are you saying I should do. Remove all emojis and change everything to generic links?

I think people wouldn't like that and there's already 3000+ stars. I also would be pretty adverse to changing it

**Comment by sindresorhus** [comment]
I'm not saying you should do anything. Just sharing my observation as a visitor to your list.

**Comment by hsavit1** [comment]
Thanks for the opinion. I cleaned it up a little bit

**Pull request closed without merging**
