### PR TITLE
Add DevOps

### PR DESCRIPTION
**Pull request by wmariuss**
https://github.com/wmariuss/awesome-devops

Combine the platforms, tools, practice and resources to create and improve DevOps culture, as well Site Reliability Engineering in a org.

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

## Requirements for your pull request

- **Don't waste my time.** Do a good job, adhere to all the guidelines, and be responsive.
- **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).**
	Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration. **Just commenting “looks good” or simply marking the pull request as approved does not count!** You have to actually point out mistakes or improvement suggestions.
- You have read and understood the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/main/create-list.md).
- This pull request has a title in the format `Add Name of List`.
	- ✅ `Add Swift`
	- ✅ `Add Software Architecture`
	- ❌ `Update readme.md`
	- ❌ `Add Awesome Swift`
	- ❌ `Add swift`
	- ❌ `add Swift`
	- ❌ `Adding Swift`
	- ❌ `Added Swift`
- Your entry here should include a short description about the project/theme of the list. **It should not describe the list itself.** The first character should be uppercase and the description should end in a dot. It should be an objective description and not a tagline or marketing blurb.
	- ✅ `- [iOS](…) - Mobile operating system for Apple phones and tablets.`
	- ✅ `- [Framer](…) - Prototyping interactive UI designs.`
	- ❌ `- [iOS](…) - Resources and tools for iOS development.`
	- ❌ `- [Framer](…)`
	- ❌ `- [Framer](…) - prototyping interactive UI designs`
- Your entry should be added at the bottom of the appropriate category.
- The title of your entry should be title-cased and the URL to your list should end in `#readme`.
	- Example: `- [Software Architecture](https://github.com/simskij/awesome-software-architecture#readme) - The discipline of designing and building software.`
- The suggested Awesome list complies with the below requirements.

## Requirements for your Awesome list

- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
- Don't open a Draft / WIP pull request while you work on the guidelines. A pull request should be 100% ready and should adhere to all the guidelines when you open it. **Instead use [#2242](https://github.com/sindresorhus/awesome/issues/2242) for incubation visibility**.
- Run [`awesome-lint`](https://github.com/sindresorhus/awesome-lint) on your list and fix the reported issues. If there are false-positives or things that cannot/shouldn't be fixed, please [report it](https://github.com/sindresorhus/awesome-lint/issues/new).
- The default branch should be named [`main`, not `master`](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/).
- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- ✅ `Mobile operating system for Apple phones and tablets.`
	- ✅ `Prototyping interactive UI designs.`
	- ❌ `Resources and tools for iOS development.`
	- ❌ `Awesome Framer packages and tools.`
- It's the result of hard work and the best I could possibly produce.
	**If you have not put in considerable effort into your list, your pull request will be immediately closed.**
- The repo name of your list should be in lowercase slug format: `awesome-name-of-list`.
	- ✅ `awesome-swift`
	- ✅ `awesome-web-typography`
	- ❌ `awesome-Swift`
	- ❌ `AwesomeWebTypography`
- The heading title of your list should be in [title case](https://capitalizemytitle.com/) format: `# Awesome Name of List`.
	- ✅ `# Awesome Swift`
	- ✅ `# Awesome Web Typography`
	- ❌ `# awesome-swift`
	- ❌ `# AwesomeSwift`
- Non-generated Markdown file in a GitHub repo.
- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
- Not a duplicate. Please search for existing submissions.
- Only has awesome items. Awesome lists are curations of the best, not everything.
- Does not contain items that are unmaintained, has archived repo, deprecated, or missing docs. If you really need to include such items, they should be in a separate Markdown file.
- Includes a project logo/illustration whenever possible.
	- Either centered, fullwidth, or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
	- The image should link to the project website or any relevant website.
	- **The image should be high-DPI.** Set it to maximum half the width of the original image.
- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/main/awesome.md#awesome-badge).
	- Should be placed on the right side of the readme heading.
		- Can be placed centered if the list has a centered graphics header.
	- Should link back to this list.
- Has a Table of Contents section.
	- Should be named `Contents`, not `Table of Contents`.
	- Should be the first section in the list.
	- Should only have one level of [nested lists](https://commonmark.org/help/tutorial/10-nestedLists.html), preferably none.
	- Must not feature `Contributing` or `Footnotes` sections.
- Has an appropriate license.
	- **We strongly recommend the [CC0 license](https://creativecommons.org/publicdomain/zero/1.0/), but any [Creative Commons license](https://creativecommons.org/choose/) will work.**
		- Tip: You can quickly add it to your repo by going to this URL: `https://github.com/<user>/<repo>/community/license/new?branch=main&template=cc0-1.0` (replace `<user>` and `<repo>` accordingly).
	- A code license like MIT, BSD, Apache, GPL, etc, is not acceptable. Neither are WTFPL and [Unlicense](https://unlicense.org).
	- Place a file named `license` or `LICENSE` in the repo root with the license text.
	- **Do not** add the license name, text, or a `Licence` section to the readme. GitHub already shows the license name and link to the full text at the top of the repo.
	- To verify that you've read all the guidelines, please comment on your pull request with just the word `unicorn`.
- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/main/awesome.md#include-contribution-guidelines).
	- The file should be named `contributing.md`. Casing is up to you.
	- It can optionally be linked from the readme in a dedicated section titled `Contributing`, positioned at the top or bottom of the main content.
	- The section should not appear in the Table of Contents.
- All non-important but necessary content (like extra copyright notices, hyperlinks to sources, pointers to expansive content, etc) should be grouped in a `Footnotes` section at the bottom of the readme. The section should not be present in the Table of Contents.
- Has consistent formatting and proper spelling/grammar.
	- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
	- The description starts with an uppercase character and ends with a period.
	- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
- Doesn't use [hard-wrapping](https://stackoverflow.com/questions/319925/difference-between-hard-wrap-and-soft-wrap).
- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.
- Doesn't include an `Inspired by awesome-foo` or `Inspired by the Awesome project` kinda link at the top of the readme. The Awesome badge is enough.

**Go to the top and read it again.**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

**Review by andrzejsydor — APPROVED** [review]

**Review by Almaliky19 — APPROVED** [review]

**Review by waleedsadek-panx — CHANGES_REQUESTED** [review]
Hi wmariuss,

After running `npx awesome-lint https://github.com/wmariuss/awesome-devops` from my terminal, I found the below 36 issues that fixing:

1. ✖    1:1    Missing Awesome badge after the main heading                                                               remark-lint:awesome-badge, which means you need to add the `awesome-bage` right after `Awesome DevOps` heading not after the break. 
2. ✖    1:1    Forbidden license section found                                                                            remark-lint:awesome-license, 
3. ✖   23:1    ToC item "Observability and Monitoring" does not match corresponding heading "Observability & Monitoring"  remark-lint:awesome-toc
4. ✖   68:85   "’" is used without matching "‘"                                                                           remark-lint:match-punctuation
5. ✖  137:41   List item description must start with valid casing                                                         remark-lint:awesome-list-item
6. ✖  148:42   List item description must end with proper punctuation                                                     remark-lint:awesome-list-item
7. ✖  158:37   List item description must start with valid casing                                                         remark-lint:awesome-list-item
8. ✖  159:74   List item description must start with valid casing                                                         remark-lint:awesome-list-item
9. ✖  160:38   List item description must start with valid casing                                                         remark-lint:awesome-list-item
10. ✖  161:44   List item description must start with valid casing                                                         remark-lint:awesome-list-item
11. ✖  162:43   List item description must start with valid casing                                                         remark-lint:awesome-list-item
12. ✖  163:43   List item description must start with valid casing                                                         remark-lint:awesome-list-item
13. ✖  165:52   List item description must start with valid casing                                                         remark-lint:awesome-list-item
14. ✖  166:56   List item description must start with valid casing                                                         remark-lint:awesome-list-item
15. ✖  168:33   List item description must start with valid casing                                                         remark-lint:awesome-list-item
16. ✖  173:43   List item description must start with valid casing                                                         remark-lint:awesome-list-item
17. ✖  173:139  "’" is used without matching "‘"                                                                           remark-lint:match-punctuation
18. ✖  174:53   List item description must start with valid casing                                                         remark-lint:awesome-list-item
19. ✖  175:34   List item description must start with valid casing                                                         remark-lint:awesome-list-item
20. ✖  179:40   List item description must start with valid casing                                                         remark-lint:awesome-list-item
21. ✖  179:73   "’" is used without matching "‘"                                                                           remark-lint:match-punctuation
22. ✖  180:39   List item description must start with valid casing                                                         remark-lint:awesome-list-item
23. ✖  182:40   List item description must start with valid casing                                                         remark-lint:awesome-list-item
24. ✖  183:40   List item description must start with valid casing                                                         remark-lint:awesome-list-item
25. ✖  185:6    Text "Github" should be written as "GitHub"                                                                remark-lint:awesome-spell-check
26. ✖  193:4    Text "Github" should be written as "GitHub"                                                                remark-lint:awesome-spell-check
27. ✖  195:46   List item description must end with proper punctuation                                                     remark-lint:awesome-list-item
28. ✖  205:3    http://nginx.org/                                                                                          remark-lint:double-link
29. ✖  216:69   "’" is used without matching "‘"                                                                           remark-lint:match-punctuation
30. ✖  217:7    "’" is used without matching "‘"                                                                           remark-lint:match-punctuation
31. ✖  298:3    https://konghq.com/                                                                                        remark-lint:double-link
32. ✖  318:3    https://konghq.com/                                                                                        remark-lint:double-link
33. ✖  318:90   "’" is used without matching "‘"                                                                           remark-lint:match-punctuation
34. ✖  324:3    https://nginx.org/                                                                                         remark-lint:double-link
35. ✖  412:3    https://landing.google.com/sre/books/                                                                      remark-lint:double-link
36. ✖  413:3    https://landing.google.com/sre/books                                                                       remark-lint:double-link

**Comment by wmariuss** [comment]
> Hi wmariuss,
> 
> After running `npx awesome-lint https://github.com/wmariuss/awesome-devops` from my terminal, I found the below 36 issues that fixing:
> 
> 1. ✖    1:1    Missing Awesome badge after the main heading                                                               remark-lint:awesome-badge, which means you need to add the `awesome-bage` right after `Awesome DevOps` heading not after the break.
> 2. ✖    1:1    Forbidden license section found                                                                            remark-lint:awesome-license,
> 3. ✖   23:1    ToC item "Observability and Monitoring" does not match corresponding heading "Observability & Monitoring"  remark-lint:awesome-toc
> 4. ✖   68:85   "’" is used without matching "‘"                                                                           remark-lint:match-punctuation
> 5. ✖  137:41   List item description must start with valid casing                                                         remark-lint:awesome-list-item
> 6. ✖  148:42   List item description must end with proper punctuation                                                     remark-lint:awesome-list-item
> 7. ✖  158:37   List item description must start with valid casing                                                         remark-lint:awesome-list-item
> 8. ✖  159:74   List item description must start with valid casing                                                         remark-lint:awesome-list-item
> 9. ✖  160:38   List item description must start with valid casing                                                         remark-lint:awesome-list-item
> 10. ✖  161:44   List item description must start with valid casing                                                         remark-lint:awesome-list-item
> 11. ✖  162:43   List item description must start with valid casing                                                         remark-lint:awesome-list-item
> 12. ✖  163:43   List item description must start with valid casing                                                         remark-lint:awesome-list-item
> 13. ✖  165:52   List item description must start with valid casing                                                         remark-lint:awesome-list-item
> 14. ✖  166:56   List item description must start with valid casing                                                         remark-lint:awesome-list-item
> 15. ✖  168:33   List item description must start with valid casing                                                         remark-lint:awesome-list-item
> 16. ✖  173:43   List item description must start with valid casing                                                         remark-lint:awesome-list-item
> 17. ✖  173:139  "’" is used without matching "‘"                                                                           remark-lint:match-punctuation
> 18. ✖  174:53   List item description must start with valid casing                                                         remark-lint:awesome-list-item
> 19. ✖  175:34   List item description must start with valid casing                                                         remark-lint:awesome-list-item
> 20. ✖  179:40   List item description must start with valid casing                                                         remark-lint:awesome-list-item
> 21. ✖  179:73   "’" is used without matching "‘"                                                                           remark-lint:match-punctuation
> 22. ✖  180:39   List item description must start with valid casing                                                         remark-lint:awesome-list-item
> 23. ✖  182:40   List item description must start with valid casing                                                         remark-lint:awesome-list-item
> 24. ✖  183:40   List item description must start with valid casing                                                         remark-lint:awesome-list-item
> 25. ✖  185:6    Text "Github" should be written as "GitHub"                                                                remark-lint:awesome-spell-check
> 26. ✖  193:4    Text "Github" should be written as "GitHub"                                                                remark-lint:awesome-spell-check
> 27. ✖  195:46   List item description must end with proper punctuation                                                     remark-lint:awesome-list-item
> 28. ✖  205:3    http://nginx.org/                                                                                          remark-lint:double-link
> 29. ✖  216:69   "’" is used without matching "‘"                                                                           remark-lint:match-punctuation
> 30. ✖  217:7    "’" is used without matching "‘"                                                                           remark-lint:match-punctuation
> 31. ✖  298:3    https://konghq.com/                                                                                        remark-lint:double-link
> 32. ✖  318:3    https://konghq.com/                                                                                        remark-lint:double-link
> 33. ✖  318:90   "’" is used without matching "‘"                                                                           remark-lint:match-punctuation
> 34. ✖  324:3    https://nginx.org/                                                                                         remark-lint:double-link
> 35. ✖  412:3    https://landing.google.com/sre/books/                                                                      remark-lint:double-link
> 36. ✖  413:3    https://landing.google.com/sre/books                                                                       remark-lint:double-link

I know. Fixing it.

**Review by gingerheart86 — APPROVED** [review]

**Comment by Karneades** [comment]
Hi @wmariuss 

Wow, awesome list! 

A few comments:
* Some parts are already covered in the awesome list, e.g. CI and could be merged together with the corresponding list.
* You should rewrite the text or at least include a description of the topic instead of describing the list. Means describe what DevOps and SRE are.
* Furthermore, according to the guidelines **Do not add the license name, text, or a Licence section to the readme. GitHub already shows the license name and link to the full text at the top of the repo.**.
* _Authors_ section is not useful.

**Comment by wmariuss** [comment]
> https://github.com/wmariuss/awesome-devops

Thanks for the feedback. I will take a look to the changes later.

**Comment by wmariuss** [comment]
unicorn

**Comment by vhladiienko** [comment]
Hi @wmariuss, thanks for the list!

I suggest using heading levels where relevant instead of second level bullet points, e.g.

```
### Metrics/Metrics collection

- [Thundra Foresight](https://www.thundra.io/foresight) - Visibility into CI pipeline by spotting test failures in no time.
- [Prometheus](https://prometheus.io/) - Power your metrics and alerting with a leading open-source monitoring solution.
```

Instead of:

```
- Metrics/Metrics collection
  - [Thundra Foresight](https://www.thundra.io/foresight) - Visibility into CI pipeline by spotting test failures in no time.
  - [Prometheus](https://prometheus.io/) - Power your metrics and alerting with a leading open-source monitoring solution.
```

I also think below category descriptions are unnecessarily redundant.\
image

**Comment by zakarialaoui10** [comment]
The linter returns 31 errors 

✖    1:1    Missing Awesome badge after the main heading                                                               remark-lint:awesome-badge
  ✖   11:[10](https://github.com/zakarialaoui10/linters/actions/runs/4164077368/jobs/7205241733#step:4:11)4  "’" is used without matching "‘"                                                                           remark-lint:match-punctuation
  ✖   27:1    ToC item "Observability and Monitoring" does not match corresponding heading "Observability & Monitoring"  remark-lint:awesome-toc
  ✖   72:85   "’" is used without matching "‘"                                                                           remark-lint:match-punctuation
  ✖  142:41   List item description must start with valid casing                                                         remark-lint:awesome-list-item
  ✖  153:42   List item description must end with proper punctuation                                                     remark-lint:awesome-list-item
  ✖  163:37   List item description must start with valid casing                                                         remark-lint:awesome-list-item
  ✖  164:74   List item description must start with valid casing                                                         remark-lint:awesome-list-item
  ✖  165:38   List item description must start with valid casing                                                         remark-lint:awesome-list-item
  ✖  166:44   List item description must start with valid casing                                                         remark-lint:awesome-list-item
  ✖  167:43   List item description must start with valid casing                                                         remark-lint:awesome-list-item
  ✖  168:43   List item description must start with valid casing                                                         remark-lint:awesome-list-item
  ✖  170:52   List item description must start with valid casing                                                         remark-lint:awesome-list-item
  ✖  171:56   List item description must start with valid casing                                                         remark-lint:awesome-list-item
  ✖  173:33   List item description must start with valid casing                                                         remark-lint:awesome-list-item
  ✖  178:43   List item description must start with valid casing                                                         remark-lint:awesome-list-item
  ✖  178:[13](https://github.com/zakarialaoui10/linters/actions/runs/4164077368/jobs/7205241733#step:4:14)9  "’" is used without matching "‘"                                                                           remark-lint:match-punctuation
  ✖  [17](https://github.com/zakarialaoui10/linters/actions/runs/4164077368/jobs/7205241733#step:4:18)9:53   List item description must start with valid casing                                                         remark-lint:awesome-list-item
  ✖  [18](https://github.com/zakarialaoui10/linters/actions/runs/4164077368/jobs/7205241733#step:4:19)0:34   List item description must start with valid casing                                                         remark-lint:awesome-list-item
  ✖  184:40   List item description must start with valid casing                                                         remark-lint:awesome-list-item
  ✖  184:73   "’" is used without matching "‘"                                                                           remark-lint:match-punctuation
  ✖  185:39   List item description must start with valid casing                                                         remark-lint:awesome-list-item
  ✖  187:40   List item description must start with valid casing                                                         remark-lint:awesome-list-item
  ✖  188:40   List item description must start with valid casing                                                         remark-lint:awesome-list-item
  ✖  [19](https://github.com/zakarialaoui10/linters/actions/runs/4164077368/jobs/7205241733#step:4:20)0:6    Text "Github" should be written as "GitHub"                                                                remark-lint:awesome-spell-check
  ✖  [20](https://github.com/zakarialaoui10/linters/actions/runs/4164077368/jobs/7205241733#step:4:21)0:46   List item description must end with proper punctuation                                                     remark-lint:awesome-list-item
  ✖  2[21](https://github.com/zakarialaoui10/linters/actions/runs/4164077368/jobs/7205241733#step:4:22):69   "’" is used without matching "‘"                                                                           remark-lint:match-punctuation
  ✖  [22](https://github.com/zakarialaoui10/linters/actions/runs/4164077368/jobs/7205241733#step:4:23)2:7    "’" is used without matching "‘"                                                                           remark-lint:match-punctuation
  ✖  303:3    https://konghq.com/                                                                                        remark-lint:double-link
  ✖  3[23](https://github.com/zakarialaoui10/linters/actions/runs/4164077368/jobs/7205241733#step:4:24):3    https://konghq.com/                                                                                        remark-lint:double-link
  ✖  323:90   "’" is used without matching "‘"                                                                           remark-lint:match-punctuation

  [31](https://github.com/zakarialaoui10/linters/actions/runs/4164077368/jobs/7205241733#step:4:32) errors

**Comment by praveen-klaytn** [comment]
HI @wmariuss ,  
  
Thanks for the list. Could you please check below items once.

1.  Review atleast 2 open PRs
2.  CI badge is not required in the readme as per the guidelines.

**Comment by sindresorhus** [comment]
Closing for lack of response.

**Pull request closed without merging**
