### PR TITLE
Added link to Go hardware list

### PR DESCRIPTION
**Pull request by kpashka**
Awesome list of tools, packages and tutorials about usage of Go in hardware projects.

### CODE REVIEW

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/awesome/blob/master/contributing.md

**Comment by kpashka** [comment]
@sindresorhus Update PR title & description, what else am I missing?

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/awesome/blob/master/create-list.md
https://github.com/sindresorhus/awesome/blob/master/awesome.md

**Comment by kpashka** [comment]
Oh, you mean only authors of lists can contribute. Ok, nevermind.

**Comment by sindresorhus** [comment]
@kpashka I didn't mean that. Anyone can contribute. But the list is missing a license and contributing guidelines as outlined in https://github.com/sindresorhus/awesome/blob/master/awesome.md

// @ rakyll

**Comment by sindresorhus** [comment]
@rakyll

**Comment by rakyll** [comment]
I will license the list with CC0 later today, there is no reason I haven't yet :)

**Comment by rakyll** [comment]
Licensed with Apache 2.

**Comment by sindresorhus** [comment]
@rakyll Submit a PR to add your list. @kpashka deleted his fork so I can't reopen this.

Apache 2 is a code license. The Creative Commons licenses are better for normal text content. Also needs a contributing.md file. Feel free to steal the one in this repo.

**Pull request closed without merging**
