### PR TITLE
Add Markdown

### PR DESCRIPTION
**Pull request by BubuAnabelas**
https://github.com/BubuAnabelas/awesome-markdown/

**Markdown has been arround for a long time and it's becoming widley used among web-devs and bloggers. This list contains useful and delighful resources for Markdown**

# By submitting this pull request I confirm I've read and complied with the below requirements.

Failure to properly do so will just result in the pull request being closed and everyone's time wasted. Please read it twice. Most people miss many things.

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title. For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should include a short description about the list project/theme (not the list itself), and should be added at the bottom of the appropriate category.
- The list I added
	- **has been around for at least 30 days,**
	- is the result of hard work and is the best I could possibly produce,
	- is a non-generated Markdown file in a GitHub repo,
	- is not a duplicate,
	- includes a succinct description of the project/theme at the top ([example](https://github.com/willempienaar/awesome-quantified-self)),
	- includes a project logo/illustration (whenever possible) at the top right of the readme ([example](https://github.com/sindresorhus/awesome-electron)). (The logo should link to the project website or any relevant website. The logo should be high-DPI, so set it to maximum half the width of the original image.),
	- only has awesome items **with descriptions** *(Awesome lists are curations of the best, not of everything)*,
	- contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- has a Table of Contents section **named `Contents`** as the first section,
	- has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license) *(Meaning something like CC0, NOT a code licence like MIT, BSD, Apache, etc)* *(If you use a license badge, it should be SVG, not PNG)*,
	- has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- doesn't include a Travis badge,
	- has been checked for inconsistent formatting, spelling, and grammar:
		- Each link description starts with an uppercase character and ends with a period.
		- Drop all the `A` / `An` prefixes in the descriptions.
		- Consistent naming. For example, `Node.js`, not `NodeJS` or `node.js`.

### CODE REVIEW

**Comment by aleksandar-todorovic** [comment]
I wouldn't really call Static Site Generators CMSs.

> has been checked for inconsistent formatting, spelling, and grammar:
> * Each link description starts with an uppercase character and ends with a period.
> * Drop all the A / An prefixes in the descriptions.
> * Consistent naming. For example, Node.js, not NodeJS or node.js.

The later two are not respected.

**Comment by davisonio** [comment]
Two other awesome markdown lists I found:
https://github.com/mundimark/awesome-markdown
https://github.com/mashk/awesome-markdown

**Comment by BubuAnabelas** [comment]
@aleksandar-todorovic That's why I called that section _"CMS / Blogs"_ because of Ghost and Grav are CMS, Svbtle is a blogging platform and the others are Static Site Generators which can be used to make a blog website.
In https://github.com/BubuAnabelas/awesome-markdown/commit/95fe2a6e78e2963164b04eda51e3dc2b339ca1d7 I fixed the descriptions and the consistent naming I'm almost certain, tell me if you notice anything off please.

@davisonio Even though that lists can be useful to some people what I'm trying to do is to make a truly _awesome_ list. Not just add content without checking if it is different from anything else (that's why I didn't add too many editors), or adding poor stuff.

**Comment by sindresorhus** [comment]
> The entry in the Awesome list should include a short description about the list project/theme (not the list itself), and should be added at the bottom of the appropriate category.

Not followed.

> includes a succinct description of the project/theme at the top (example),

Not followed.

> has a Table of Contents section named Contents as the first section,

Not followed.

---

- `Inspired by the awesome list thing.` - Drop this
- `💎 means really awesome/useful.` - Items marked with this should really have a comment on why you think they're extra awesome/useful.
- `Github's Mastering` => `GitHub's Mastering`
- Could be useful to include the best modules for rendering Markdown in each ecosystem (Node.js, PHP, etc). For example, the best one in the Node.js ecosystem is https://github.com/markdown-it/markdown-it
- `Markdown To PDF` => `Markdown to PDF`, and needs a description.
- The items in the editor section should indicate what operating systems they work on.
- https://ia.net/writer/ is missing from the Editor section
- I would also link to http://stackoverflow.com/questions/tagged/markdown somewhere

**Comment by BubuAnabelas** [comment]
@sindresorhus Can you tell me specifically where I didn't follow:
> "The entry in the Awesome list should include a short description about the list project/theme (not the list itself), and should be added at the bottom of the appropriate category."

So I can fix it.

Is it because it isn't at the bottom of the category? (because it's an old PR)

    
I'm working on the other points, will push the update in some days and update you right away.

Thanks for your patience!

**Comment by sindresorhus** [comment]
> Can you tell me specifically where I didn't follow:

⬇️ 

> "The entry in the Awesome list should include a short description about the list project/theme **(not the list itself)**

**Comment by BubuAnabelas** [comment]
Been working on the points you made and marked those which are done. Will be working on the unfinished once on the following days.

> - [x] The entry in the Awesome list should include a short description about the list project/theme (not the list itself), and should be added at the bottom of the appropriate category.

> - [x] includes a succinct description of the project/theme at the top (example),

> - [x] has a Table of Contents section named Contents as the first section,

- [x] Inspired by the awesome list thing. - Drop this
- [x] 💎 means really awesome/useful. - Items marked with this should really have a comment on why you think they're extra awesome/useful.
- [x] Github's Mastering => GitHub's Mastering
- [ ] Could be useful to include the best modules for rendering Markdown in each ecosystem (Node.js, PHP, etc). For example, the best one in the Node.js ecosystem is https://github.com/markdown-it/markdown-it
- [x] Markdown To PDF => Markdown to PDF, and needs a description.
- [ ] The items in the editor section should indicate what operating systems they work on.
- [x] https://ia.net/writer/ is missing from the Editor section
- [x] I would also link to http://stackoverflow.com/questions/tagged/markdown somewhere

Please tell me if there's anything more to change or add.

**Comment by BubuAnabelas** [comment]
@sindresorhus I belive it's all done! :smile:

**Pull request merged**
