### PR TITLE
Add "Startup Accelerators & Incubators" lists

### PR DESCRIPTION
**Pull request by ahmadnassri**
These are independent lists as the two types have very distinct audiences

- https://github.com/ahmadnassri/awesome-incubators - Startup incubators around the globe.
- https://github.com/ahmadnassri/awesome-accelerators - Startup accelerators around the globe.

> By submitting this pull request I confirm I've read and complied with the requirements. :+1: :100:

### CODE REVIEW

**Comment by legodude17** [comment]
Please use the template that was provided.

**Comment by ahmadnassri** [comment]
I've gone through each and every item in the template checklist and verified all is followed.

the pull request description follows the guidelines, just abbreviated the long item list.

not sure what the point of copy pasting blindly! if anything, this shows my pull requests are actually thoughtful and not random junk.

**Comment by sindresorhus** [comment]
From https://github.com/sindresorhus/awesome/blob/master/contributing.md#adding-to-this-list
> Make an individual pull request for each suggestion.

**Comment by sindresorhus** [comment]
I don't really see how these are Awesome lists though.

**Pull request closed without merging**
