### PR TITLE
Add choo

### PR DESCRIPTION
**Pull request by YerkoPalma**
**https://github.com/YerkoPalma/awesome-choo**

**`choo` is a _fun functional_ 5Kb front end framework. With an atractive set of [features](https://github.com/yoshuawuyts/choo#features), is an easy to use alternative to other popular frameworks like React.**

# ALL THE BELOW CHECKBOXES SHOULD BE DONE AND CHECKED AND THE ABOVE PLACEHOLDERS SHOULD BE FILLED IN BEFORE SUBMITTING A PULL REQUEST!

- [x] I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- [x] This pull request has a descriptive title. *(For example: `Add Node.js`)*
- The list I added
	- [x] **has been around for at least 20 days,**
	- [x] is a non-generated Markdown file in a GitHub repo,
	- [x] is not a duplicate,
	- [x] only has awesome items with descriptions *(Awesome lists are curations of the best, not of everything)*,
	- [x] contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- [x] has a Table of Contents section named `Contents` as the first section,
	- [x] has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license) *(Meaning something like CC0, NOT a code licence like MIT, BSD, Apache, etc)*,
	- [x] has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- [x] has been checked for inconsistent formatting, spelling, and grammar *(This includes starting each link description with an uppercase character and ending it with a dot, and consistent naming)*,
	- [x] has been added at the bottom of the appropriate category.

### CODE REVIEW

**Comment by sindresorhus** [comment]
> only has awesome items **with descriptions**

-

> has a Table of Contents section **named Contents** as the first section,

-

It's not clear what the `Dependencies` section is. Could use a description. The items there also needs descriptions.

-

In the `Official resources` section there's no reason to prefix `choo`. That's obvious.

-

In the readme description, linkify `choo` to its website.

**Comment by sindresorhus** [comment]
// @yoshuawuyts

**Comment by YerkoPalma** [comment]
updated, please check

**Comment by sindresorhus** [comment]
> has been checked for inconsistent formatting, spelling, and grammar (This includes starting each link description with an **uppercase character and ending it with a dot**, and consistent naming),

**Comment by sindresorhus** [comment]
> has a Table of Contents section **named Contents** as the first section,

Not followed

**Comment by yoshuawuyts** [comment]
@sindresorhus is there a formatter available for this? - even if we follow the guidelines now, I doubt we'll be able to uphold conventions unless enforceable through tooling

**Comment by sindresorhus** [comment]
@yoshuawuyts https://github.com/sindresorhus/awesome/issues/569#issuecomment-236695005

**Comment by sindresorhus** [comment]
Happy to merge when my above feedback is fixed.

**Comment by YerkoPalma** [comment]
@sindresorhus thanks for the feedback, it has been added now, please check.

**Pull request merged**
