### PR TITLE
Add Flutter

### PR DESCRIPTION
**Pull request by Solido**
https://github.com/Solido/awesome-flutter

Flutter is a new mobile app SDK to help developers and designers build modern mobile apps for iOS and Android. It's supported by Google and is gaining a lot of traction.

# By submitting this pull request I confirm I've read and complied with the below requirements.

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title.<br>For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
	- Be added at the bottom of the appropriate category.
- The list I'm submitting complies with these requirements:
	- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
	- It's the result of hard work and the best I could possibly produce.
	- Non-generated Markdown file in a GitHub repo.
	- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
	- Not a duplicate.
	- Only has awesome items. Awesome lists are curations of the best, not everything.
	- Includes a project logo/illustration whenever possible.
		- Placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
		- The image should link to the project website or any relevant website.
		- The image should be high-DPI. Set it to maximum half the width of the original image.
	- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
	- Has the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- Has a Table of Contents section.
		- Should be named `Contents`, not `Table of Contents`.
		- Should be the first section in the list.
	- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
		- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
		- If you use a license badge, it should be SVG, not PNG.
	- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
		- The file should be named `contributing.md`. Casing is up to you.
	- Has consistent formatting and proper spelling/grammar.
		- Each link description starts with an uppercase character and ends with a period.<br>Example: `- [AVA](…) - JavaScript test runner.`
		- Drop all the `A` / `An` prefixes in the descriptions.
		- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
	- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.
- Go to the top and read it again.

### CODE REVIEW

**Comment by legodude17** [comment]
* `flutter[at]robbieone.com` -> `flutter@robbieone.com`
* Add events
* More descriptive descriptions

**Comment by Solido** [comment]
[At] You've accepted this model with https://github.com/jondot/awesome-react-native 
So I've just align to be consistent and like a wise guy avoid robot spam.

Add events : Last events was Google IO 17. No events currently planned.

I'm not sure I've the right to override how projects describe themself ? what's the official direction on this point ?

**Comment by legodude17** [comment]
* Ok. But, you it should say "Have something that belongs under "Events"? Drop me a line at flutter@robbieone.com."
* Add Google IO 17 under events
* Stuff under Auth, Storage, and Monetization. Also, add more to the ones the just say "by <name>"

**Comment by sindresorhus** [comment]
> I'm not sure I've the right to override how projects describe themself ? what's the official direction on this point ? some entries in particular that need review ?

Feel free to edit descriptions. From experience, most project descriptions could be better. For example, with https://github.com/sindresorhus/awesome-nodejs, I've edited/improved pretty much every description.

**Comment by sindresorhus** [comment]
> Includes a project logo/illustration whenever possible. **The image should be high-DPI. Set it to maximum half the width of the original image.**

:arrow_up:

---

`Awesome Flutter, getting you effective quickly` => `Awesome Flutter`

---

Remove the unused section `Training & tutorials`

---

> Each link description **starts with an uppercase character and ends with a period**.
Example: `- [AVA](…) - JavaScript test runner.`

:arrow_up:

---

> Drop all the `A` / `An` prefixes in the descriptions.

:arrow_up:

**Comment by Solido** [comment]
Damn ! Have to say this is a lot of work to get the things up properly ;)

**Comment by Solido** [comment]
Everything should be in place now +1

**Comment by sindresorhus** [comment]
> Includes a project logo/illustration whenever possible. Placed at the top-right of the readme.

:arrow_up:

---

> Each link description starts with an uppercase character and ends with a period.
Example: - [AVA](…) - JavaScript test runner.
⬆️

Not fixed.

---

Formatting and general content need more work.

The list contains stuff like:

> Lottie - After Effect for Flutter ???

> GoogleAdmob supports interstitial

> What's happening at 2:38 ? Brandon told me it's the Intellij Plugin.

**Comment by sindresorhus** [comment]
Closing for lack of response.

**Comment by Solido** [comment]
Project is still alive and well. I'll candidate again in some time when I got time to conform to all the rules. Thx for your time.

**Pull request closed without merging**
