### PR TITLE
Add Vehicle Security and Car Hacking

### PR DESCRIPTION
**Pull request by jaredmichaelsmith**
**https://github.com/jaredmichaelsmith/awesome-vehicle-security**

**This list contains the most relevant resources for learning and practicing vehicle security research, car hacking, and reverse engineering of vehicles. The community is rather small now and vehicle security is an emerging field, but I wanted to jump in early and provide this resource to those wanting to jump right into the field.

Note, this list has *not* been around for at least 20 days, but was created yesterday from my own previous list of resources, but I wanted to go ahead and get this in the system in case you find other bugs :)
**

# ALL THE BELOW CHECKBOXES SHOULD BE DONE AND CHECKED AND THE ABOVE PLACEHOLDERS SHOULD BE FILLED IN BEFORE SUBMITTING A PULL REQUEST!

- [X] I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- [X] This pull request has a descriptive title. *(For example: `Add Node.js`)*
- The list I added
	- [X] **has been around for at least 20 days,**
	- [X] is a non-generated Markdown file in a GitHub repo,
	- [X] is not a duplicate,
	- [X] only has awesome items with descriptions *(Awesome lists are curations of the best, not of everything)*,
	- [X] contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- [X] has a Table of Contents section named `Contents` as the first section,
	- [X] has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license) *(Meaning something like CC0, NOT a code licence like MIT, BSD, Apache, etc)*,
	- [X] has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- [X] has been checked for inconsistent formatting, spelling, and grammar *(This includes starting each link description with an uppercase character and ending it with a dot, and consistent naming)*,
	- [X] has been added at the bottom of the appropriate category.

Find it at: [https://github.com/jaredmichaelsmith/awesome-vehicle-security](https://github.com/jaredmichaelsmith/awesome-vehicle-security).

### CODE REVIEW

**Comment by aleksandar-todorovic** [comment]
I've removed the check sign from one of the items, since it's not respected.

Couple of things I would recommend:

* Bold the `Legend:` string.
* Arrange `Resources to Learn` section alphabetically.
* Link `Contributions welcome!` string in the `Blogs` section to contributing guidelines.
* Remove the `Inspired by...` sentence.
* Either add `<hr>` between all of the main sections, or remove it completely.

I feel bad closing this PR, but unfortunately I will have to do so because of our 20 days rule.

I would _love_ to have it here after the 20 days mark! Please remember to ping us.

**Comment by sindresorhus** [comment]
@jaredmichaelsmith Looks great! I just have some minor nitpick in addition to @aleksandar-todorovic's feedback:

- `Table of Contents` => `Contents`
- I would name `Resources to Learn` just `Learn`

**Comment by sindresorhus** [comment]
> Arrange Resources to Learn section alphabetically.

@aleksandar-todorovic No, things should be sorted by importance/interestingness, not alphabetically.

**Comment by jaredmichaelsmith** [comment]
Thanks so much @sindresorhus and @aleksandar-todorovic, I will update it now and get back to here.

**Comment by jaredmichaelsmith** [comment]
Okay, I updated with your suggested changes. Is this ready to add in now?

**Comment by sindresorhus** [comment]
Yup, looks good. One tiny thing, move the awesome badge to the right of the title like all other lists.

**Pull request merged**
