### PR TITLE
Add Algorithms Education

### PR DESCRIPTION
**Pull request by gaerae**
https://github.com/gaerae/awesome-algorithms-education

A curated list to learning and practicing about algorithm.

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

## Requirements for your pull request

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title.<br>For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
	- Be added at the bottom of the appropriate category.
- The list I'm submitting complies with these requirements:

## Requirements for your Awesome list

- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
- It's the result of hard work and the best I could possibly produce.
- Non-generated Markdown file in a GitHub repo.
- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
- Not a duplicate.
- Only has awesome items. Awesome lists are curations of the best, not everything.
- Includes a project logo/illustration whenever possible.
	- Either fullwidth or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
	- The image should link to the project website or any relevant website.
	- The image should be high-DPI. Set it to maximum half the width of the original image.
- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
	- Should be placed on the right side of the readme heading.
	- Should link back to this list.
- Has a Table of Contents section.
	- Should be named `Contents`, not `Table of Contents`.
	- Should be the first section in the list.
	- Should only have one level of sub-lists, preferably none.
- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
	- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
	- [WTFPL](http://www.wtfpl.net) and [Unlicense](http://unlicense.org) are not acceptable licenses.
	- If you use a license badge, it should be SVG, not PNG.
- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
	- The file should be named `contributing.md`. Casing is up to you.
- Has consistent formatting and proper spelling/grammar.
	- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
	- The description starts with an uppercase character and ends with a period.
	- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.

Go to the top and read it again.

### CODE REVIEW

**Comment by legodude17** [comment]
> Judges

What does this mean?

**Comment by gaerae** [comment]
@legodude17 
online judge is an online system to test programs in programming contests. 
[wikipedia: Onlinejudge](https://en.wikipedia.org/wiki/Online_judge)

**Comment by legodude17** [comment]
Would it be possible to add some descriptions to the online judges? Like, what makes them unique, the difficulty, and so on.

**Comment by gaerae** [comment]
Done. added description.

**Online judges**
> An Online Judging system is an online system to test programs in programming contests automatically.

**Comment by sindresorhus** [comment]
Hey, sorry for the lack of response, please see #1363.

**Comment by sindresorhus** [comment]
>> Would it be possible to add some descriptions to the online judges? Like, what makes them unique, the difficulty, and so on.
> Done. added description.

He meant a description per item, not just a description of the section.

**Comment by sindresorhus** [comment]
`Javascript` => `JavaScript
`Youtube` => `YouTube`
`Github` => `GitHub`

**Comment by sindresorhus** [comment]
The header image should be centered and you don't need the text header.

**Comment by sindresorhus** [comment]
> The link and description are separated by a dash. 
Example: - [AVA](…) - JavaScript test runner.

**Comment by sindresorhus** [comment]
> Includes a project logo/illustration whenever possible.
**The image should be high-DPI. Set it to maximum half the width of the original image.**

**Comment by sindresorhus** [comment]
> Includes a succinct description of the project/theme at the top of the readme. (Example)

**Comment by gaerae** [comment]
@sindresorhus Please confirm.
- [x] He meant a description per item, not just a description of the section.
- [x] Online judges → Competitive programming
- [x] Javascript → JavaScript, Youtube → YouTube, Github → GitHub`
- [x] The link and description are separated by a dash.
- [x] Includes a project logo/illustration whenever possible. → Removed logo image.
- [x] Includes a succinct description of the project/theme at the top of the readme.

**Comment by sindresorhus** [comment]
```
❯ awesome-lint https://github.com/gaerae/awesome-algorithms
✖ Linting

  readme-en.md:74:3
  ✖   10:3    ToC item "Introductory" missing corresponding heading                                       remark-lint:awesome/toc
  ✖   25:93   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   26:99   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   27:143  List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   30:116  List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   31:65   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   32:94   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   33:181  List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   34:164  List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   35:84   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   36:111  List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   37:81   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   38:82   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   39:83   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   40:84   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   43:120  List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   44:94   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   47:62   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   48:51   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   49:39   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   50:38   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   51:39   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   52:38   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   53:37   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   54:38   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   55:62   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   56:38   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   57:81   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   58:45   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   59:39   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   60:36   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   61:73   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   62:57   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   63:54   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   64:36   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   65:33   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   66:52   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   67:43   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   68:36   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   69:61   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   70:44   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   71:48   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   72:38   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   73:35   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   74:3    Link to http://judge.lavida.us is dead                                                      remark-lint:no-dead-urls
  ✖   74:35   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   75:36   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   76:36   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   77:34   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   78:29   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   79:42   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   80:60   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   81:43   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   82:55   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   85:62   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   86:103  List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   87:35   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   88:42   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   89:68   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   90:98   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   91:88   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   92:31   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   93:86   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   94:64   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   95:75   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖   96:60   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖  101:84   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖  102:81   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖  103:113  List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖  106:106  List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖  107:73   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖  108:107  List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖  109:118  List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖  110:111  List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖  111:59   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖  112:69   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖  113:67   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖  116:67   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖  117:105  List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖  118:3    Link to https://www.digitalculture.or.kr/koi/StudyBook.do is dead                           remark-lint:no-dead-urls
  ✖  118:88   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖  119:136  List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖  120:137  Link to https://www.hackerrank.com/domains/tutorials/cracking-the-coding-interview is dead  remark-lint:no-dead-urls
  ✖  120:227  List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖  125:69   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖  128:3    Link to http://www.stoimen.com/blog/category/algorithms is dead                             remark-lint:no-dead-urls
  ✖  128:71   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖  129:170  List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖  130:144  List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖  131:63   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖  140:47   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖  141:40   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖  142:46   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖  143:68   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖  144:48   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖  147:95   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖  148:67   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖  150:78   List item description must end with proper punctuation                                      remark-lint:awesome/list-item
  ✖  151:87   List item description must end with proper punctuation                                      remark-lint:awesome/list-item

  99 errors
```

https://github.com/sindresorhus/awesome-lint

**Comment by sindresorhus** [comment]
The links in the `Contents` section should not be bold.

**Comment by gaerae** [comment]
@sindresorhus Modified.

❯ awesome-lint https://github.com/gaerae/awesome-algorithms
√ Linting

**Comment by sindresorhus** [comment]
I don't really see the point in including Korean things in the English version of the list. They can be included in the Korean translation only. This would make the list less noisy.

**Comment by sindresorhus** [comment]
The descriptions in the `Tools` section make no sense. They should describe what the tool is/does.

**Comment by sindresorhus** [comment]
Descriptions should not be titleized. For example, `Free and Paid Content.` and `PDF Content.`.

**Comment by sindresorhus** [comment]
The heading of your list should be `Awesome Algorithms Education` and the repo URL should be `https://github.com/gaerae/awesome-algorithms-education`.

**Comment by sindresorhus** [comment]
> * **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)

This should succinctly explain what algorithms are.

**Comment by gaerae** [comment]
Fixed the problem. However, URL can not be changed because it is open to the public. 😢

**Comment by sindresorhus** [comment]
> However, URL can not be changed because it is open to the public.

Of course it can. GitHub handles the redirection automatically.

**Comment by gaerae** [comment]
Awesome! But, github pages domain not redirection automatically.

**Comment by sindresorhus** [comment]
I really don't see the point of the website version. It's just a worse formatted version of the repo readme...

**Comment by gaerae** [comment]
Renamed! :) 
https://github.com/gaerae/awesome-algorithms-education

**Comment by sindresorhus** [comment]
Tweet: https://twitter.com/awesome__re/status/1139796670009368576

**Pull request merged**
