### PR TITLE
Add Awesome Remote Job

### PR DESCRIPTION
**Pull request by lukasz-madon**
Curated list of awesome remote jobs and job boards

### CODE REVIEW

**Comment by sindresorhus** [comment]
Nice start, but way too little content to be useful. Add more links and description to the links. Try again in a few months when it's grown more ;)

**Comment by lukasz-madon** [comment]
I made to the HN front page https://news.ycombinator.com/item?id=8825308

It will grow quickly.

**Comment by lukasz-madon** [comment]
how about now :question:

**Comment by sindresorhus** [comment]
Better, though still room for improvement.

https://github.com/lukasz-madon/awesome-remote-job#companies needs a description of why the company is listed. A random list of companies isn't very useful.

**Pull request closed without merging**
