### PR TITLE
Adding Android Complete Reference

### PR DESCRIPTION
**Pull request by amitshekhariitbhu**
**URL to the list here.**

**Explain what this list is all about and why it should be included here.**

- [x] I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- [x] This pull request has a descriptive title.
- The list I added
	- [x] is not a duplicate,
	- [ ] has been around for a few weeks,
	- [ ] only has awesome items with descriptions,
	- [ ] contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- [ ] has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license),
	- [ ] has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- [ ] has been checked for inconsistent formatting, spelling and grammar, and
	- [ ] has been added at the bottom of the appropriate category.

### CODE REVIEW

**Comment by lholznagel** [comment]
You should recheck your pull request ;)

**Comment by davisonio** [comment]
@amitshekhariitbhu yes, please update your post...

**Comment by psukys** [comment]
Seems like you haven't read/understood the contribution guidelines, as well as not giving a descriptive title for your pull request

**Comment by amitshekhariitbhu** [comment]
@lholznagel @davisonio @psukys  : please suggest If anything is wrong

**Comment by lholznagel** [comment]
The title was one thing. But you should also check the pull request text. There are some checkboxes you should check

**Comment by amitshekhariitbhu** [comment]
@lholznagel  : checked

**Comment by amitshekhariitbhu** [comment]
@sindresorhus  Please check once I have corrected it now

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md#all-the-below-checkboxes-should-be-done-and-checked-and-the-above-placeholders-should-be-filled-in-before-submitting-a-pull-request

**Comment by amitshekhariitbhu** [comment]
@sindresorhus : I will tick that after one week so please reopen it

**Comment by sindresorhus** [comment]
@amitshekhariitbhu Please stop mentioning me. I've clearly stated what's needed. In the future please actually read the requirements for submitting a pull request. Looking at your list, I don't think it's a good fit for the Awesome concept. Awesome lists are curations of the best in an ecosystem, not everything, like yours. And there already is a list for Android: https://github.com/JStumpp/awesome-android

**Pull request closed without merging**
