### PR TITLE
Add Kubernetes

### PR DESCRIPTION
**Pull request by ramitsurana**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please read the [instructions](https://github.com/sindresorhus/awesome/blob/master/create-list.md) for creating a new list, [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

Especially this part:

> Wait at least a couple of weeks after creating a list before submitting to give it a chance to mature.

Ping me here in a few weeks and I'll reopen ;)

**Comment by sindresorhus** [comment]
Looks like an interesting list, but the items could really need some descriptions.

https://github.com/ramitsurana/awesome-kubernetes#interesting-twitter-accounts Why are those Twitter accounts interesting. Include descriptions of why they're relevant and why I should bother following them. Same with https://github.com/ramitsurana/awesome-kubernetes#amazing-people.

**Comment by ramitsurana** [comment]
Thanks for the tips and the update.I will surely ping you in a few weeks.Actually I am looking out for more and more contributors for the list.Please contribute if you like to.

**Comment by ramitsurana** [comment]
Hi sindresorhus ,
I would like to ping again as you had told me on our last conversation.I have made many changes in the repo as you asked, let me know if any other changes are also required.

**Comment by sindresorhus** [comment]
Looks better, but there's still a lot of formatting that could be improved. Looks at some other awesome lists for inspiration, I don't have time to comment about every individual thing.

**Comment by sindresorhus** [comment]
Landed!

**Pull request closed without merging**
