### PR TITLE
Self-promotion

### PR DESCRIPTION
**Pull request by sindresorhus**
https://www.producthunt.com/posts/lungo

I've spent hundreds of hours for free working on this list. So I think it's ok to add this for a couple of days.

### CODE REVIEW

**Comment by OvermindDL1** [comment]
What does it do, cannot seem to find anything on the link that is not mac related?  Unable to find anything linux related?

**Comment by sindresorhus** [comment]
> What does it do

It's explained in the linked Product Hunt post. Take a moment to read it.

> Unable to find anything linux related?

It's a Mac app, but there are alternatives for Linux: https://launchpad.net/caffeine

**Comment by OvermindDL1** [comment]
> It's a Mac app, but there are alternatives for Linux: https://launchpad.net/caffeine

Seems odd, I'd just do a while sleep loop in a tmux session that pokes dbus on occasion to keep it awake, seems odd to use a package for something so simple...  ^.^;

> It's explained in the linked Product Hunt post. Take a moment to read it.

Yep, just curious what it has to do with an awesome list?  I was expecting it to be a list of something(s).  ^.^;

**Comment by RichardLitt** [comment]
@sindresorhus As far as I know, this link may cause it to get flagged. If too many people go to Product Hunt through the same link, I believe it gets adjusted to offset the possibility of vote manipulation. Telling someone to go to Product Hunt and upvote it is fine, but direct linking is not ideal.

**Comment by sindresorhus** [comment]
@RichardLitt Good point. Fixed.

**Pull request merged**
