### PR TITLE
Add Universal Rendering

### PR DESCRIPTION
**Pull request by brillout**
**https://github.com/brillout/awesome-universal-rendering#readme**

**Universal Rendering is a widely used technique to improve SEO and performance of modern Front-Ends.**

Regarding "Includes a project logo/illustration whenever possible.": Universal Rendering has no official logo/illustration. (I want to create one once I've found an idea for a logo.)

### CODE REVIEW

**Comment by oneohtrix** [comment]
This PR seems be of good quality, and follows the formatting rules.

**Comment by sindresorhus** [comment]
> Includes a succinct description of the project/theme at the top of the readme. (Example)

---

The section descriptions, like `Explains why universal rendering is beneficial, the different techniques of doing universal rendering (SSR, SSG, pre-rendering) and when to use what technique.` should below the actual `Contents` section items, not as a separate section.

---

Some items are missing a description.

**Comment by sindresorhus** [comment]
Closing for lack of response.

**Comment by sindresorhus** [comment]
Also:

```
❯ awesome-lint https://github.com/brillout/awesome-universal-rendering
✖ Linting

  readme.md:116:3
  ✖    1:1   Missing License section                              remark-lint:awesome/license
  ✖    1:1   Missing or invalid Table of Contents                 remark-lint:awesome/toc
  ✖   81:3   Invalid list item link                               remark-lint:awesome/list-item
  ✖   86:3   Invalid list item link                               remark-lint:awesome/list-item
  ✖   90:3   Invalid list item link                               remark-lint:awesome/list-item
  ✖   99:3   Invalid list item link URL                           remark-lint:awesome/list-item
  ✖  100:3   Invalid list item link URL                           remark-lint:awesome/list-item
  ✖  101:3   Invalid list item link URL                           remark-lint:awesome/list-item
  ✖  116:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  117:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  118:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  122:3   Invalid list item link URL                           remark-lint:awesome/list-item
  ✖  123:3   Invalid list item link URL                           remark-lint:awesome/list-item
  ✖  164:3   Invalid list item link                               remark-lint:awesome/list-item
  ✖  168:3   Invalid list item link                               remark-lint:awesome/list-item
  ✖  176:3   Invalid list item link                               remark-lint:awesome/list-item
  ✖  184:3   Invalid list item link                               remark-lint:awesome/list-item
  ✖  187:3   Invalid list item link                               remark-lint:awesome/list-item
  ✖  205:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  206:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  207:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  208:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  212:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  213:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  214:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  218:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  229:3   Invalid list item link URL                           remark-lint:awesome/list-item
  ✖  230:5   Invalid list item link URL                           remark-lint:awesome/list-item
  ✖  231:5   Invalid list item link URL                           remark-lint:awesome/list-item
  ✖  232:5   Invalid list item link URL                           remark-lint:awesome/list-item
  ✖  233:3   Invalid list item link URL                           remark-lint:awesome/list-item
  ✖  234:5   Invalid list item link URL                           remark-lint:awesome/list-item
  ✖  235:5   Invalid list item link URL                           remark-lint:awesome/list-item
  ✖  236:5   Invalid list item link URL                           remark-lint:awesome/list-item
  ✖  237:3   Invalid list item link URL                           remark-lint:awesome/list-item
  ✖  238:5   Invalid list item link URL                           remark-lint:awesome/list-item
  ✖  239:5   Invalid list item link URL                           remark-lint:awesome/list-item
  ✖  240:3   Invalid list item link URL                           remark-lint:awesome/list-item
  ✖  241:5   Invalid list item link URL                           remark-lint:awesome/list-item
  ✖  242:5   Invalid list item link URL                           remark-lint:awesome/list-item
  ✖  255:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  256:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  257:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  258:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  259:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  263:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  264:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  265:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  269:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  273:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  274:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  275:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  276:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  277:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  279:19  Remove empty section: "Pre-Rendering"                remark-lint:no-empty-sections
  ✖  287:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  288:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  289:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  290:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  290:4   Link to http://getseojs.com/ is dead                 remark-lint:no-dead-urls
  ✖  291:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  295:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  301:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  302:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  303:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  304:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  305:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  319:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  320:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  324:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  328:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  329:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  331:19  Remove empty section: "Pre-Rendering"                remark-lint:no-empty-sections
  ✖  339:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  340:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  341:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  342:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  342:4   Link to http://getseojs.com/ is dead                 remark-lint:no-dead-urls
  ✖  343:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  347:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  353:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  354:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  355:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  356:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  369:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  371:19  Remove empty section: "Pre-Rendering"                remark-lint:no-empty-sections
  ✖  379:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  380:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  381:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  382:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  382:4   Link to http://getseojs.com/ is dead                 remark-lint:no-dead-urls
  ✖  383:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  387:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  393:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  394:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  395:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  396:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  407:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  408:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  410:19  Remove empty section: "Pre-Rendering"                remark-lint:no-empty-sections
  ✖  418:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  419:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  420:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  421:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  421:4   Link to http://getseojs.com/ is dead                 remark-lint:no-dead-urls
  ✖  422:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  426:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  432:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  433:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  434:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent
  ✖  435:3   Incorrect indentation before bullet: remove 1 space  remark-lint:list-item-bullet-indent

  111 errors
```

https://github.com/sindresorhus/awesome-lint

**Pull request closed without merging**
