### PR TITLE
Add Bookmarklets

### PR DESCRIPTION
**Pull request by marcobiedermann**
List of front-end bookmarklet tools

### CODE REVIEW

**Comment by davisonio** [comment]
Thanks for the suggestion. :smiley:
Please have a read through of the [instructions](https://github.com/sindresorhus/awesome/blob/master/create-list.md) for creating/adding a new list.

Could you add contributing guidelines, license and awesome badge?

Also https://github.com/marcobiedermann/awesome-bookmarklets/issues/1 should ideally be reviewed.

Maybe this list could also do with a bit more content - GitHub search can help with this: https://github.com/search?o=desc&p=1&q=bookmarklet&s=stars&type=Repositories&utf8=✓

**Comment by marcobiedermann** [comment]
@davisonio Thank you for your suggestion:
- [x] badge
- [x] license
- [x] contribution guidelines

**Comment by sindresorhus** [comment]
I think the formatting and descriptions could use some work. The awesome badge should be on the right side of the title. The bookmarklet titles should use a `###` heading and description should be on a new line. It seems you've just copied the descriptions, but they're of varying quality. Do some work on improving them.

This one:

```
A very simple bookmarklet that analyses the pagespeed of the current page in the browser
``

Could be simplified to:

```
Analyses the pagespeed of the current page
```

It's moot to mention that it's a bookmarklet.

Another example:

```
An open-source bookmarklet that shows you on-page SEO and social metadata information.
```

Could be:

```
Displays SEO and social metadata information.
``

A few are also missing description.

-

I also think all the bookmarklets should be wrapper for a remote script to ensure they never become outdated.

**Comment by sindresorhus** [comment]
ping :)

**Comment by MrBrain295** [comment]
I would be willing to work on this again.

**Pull request closed without merging**
