### PR TITLE
Add list of awesome browser containers

### PR DESCRIPTION
**Pull request by NewAlexandria**
https://github.com/NewAlexandria/awesome-browser-containers

> List has started with plugins for active browsers like Firefox, and can grow as other browsers have tooling, as well as with other ways that browsers may come to support privacy/security of cookies and sessions.

```
Ψ awesome-lint
✔ Linting
```

## Requirements for the pull request

- [x] **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).** Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration.
- [x] I have read and understood the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- [x] This pull request has a descriptive title in the format `Add Name of List` (Example: `Add Swift`), not `Update readme.md` or `Add awesome list`.
- [x] The entry in the Awesome list should:
	- [x] Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
	- [x] Be added at the bottom of the appropriate category.
- [x] The list I'm submitting complies with the below requirements.

## Requirements for the Awesome list

- [x] **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
- [x] It's the result of hard work and the best I could possibly produce.
- [x] Non-generated Markdown file in a GitHub repo.
- [x] **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
- [x] The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
- [x] Not a duplicate.
- [x] Only has awesome items. Awesome lists are curations of the best, not everything.
- [x] Includes a project logo/illustration whenever possible.
	- [x] Either centered, fullwidth, or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
	- [x] The image should link to the project website or any relevant website.
	- [x] The image should be high-DPI. Set it to maximum half the width of the original image.
- [x] Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- [x] Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
	- [x] Should be placed on the right side of the readme heading.
		- Can be placed centered if the list has a centered graphics header.
	- [x] Should link back to this list.
- [x] Has a Table of Contents section.
	- [x] Should be named `Contents`, not `Table of Contents`.
	- [x] Should be the first section in the list.
	- [x] Should only have one level of [nested lists](https://commonmark.org/help/tutorial/10-nestedLists.html), preferably none.
- [x] Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
	- [x] That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
	- [x] [WTFPL](http://www.wtfpl.net) and [Unlicense](http://unlicense.org) are not acceptable licenses.
	- [x] If you use a license badge, it should be SVG, not PNG.
- [x] Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
	- [x] The file should be named `contributing.md`. Casing is up to you.
- [x] Has consistent formatting and proper spelling/grammar.
	- [x] The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
	- [x] The description starts with an uppercase character and ends with a period.
	- [x] Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
- [x] Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.

Go to the top, read it again, everybody walk your dinosaur 🏁 🦕 🎉

### CODE REVIEW

**Comment by leomaurodesenv** [comment]
Add a Browser Session Containers list:
- Link added at the end of the _Security_ section, maybe _Miscellaneous_ section is better.
- The description is not capitalized.
- `awesome-lint` - ok
- Review two pull requests missing

Currently has only Firefox extensions, but looks like a promising list.

**Comment by NewAlexandria** [comment]
Thanks for the review.  I think that they Security section is most-correct, because Privacy is more of a security topic, and there is not another privacy section yet.

I have been working with the maintainer for PR for Live Coding: #1049 and have proposed fixes to get them accepted: [my commits](https://github.com/NewAlexandria/awesome-livecoding/commits/master).
I will work on giving feedback to another PR or more

**Comment by leomaurodesenv** [comment]
I thought in _Miscellaneous_ because I didn't know which the extensions are focus on Privacy. I understood that extensions were for general purposes.

Nice, good work!

**Comment by NewAlexandria** [comment]
On the comment about other-than-firefox browsers, I updated the list to confirm that there really is no similar solution for this in other browsers.  _Nothing awesome_, at least.

**Comment by leomaurodesenv** [comment]
Interesting! This reinforces your Firefox list.
I only suggest changing the IE to Internet Explorer, or Microsoft Edge.

**Comment by NewAlexandria** [comment]
Agreed.  Did that.

**Comment by sindresorhus** [comment]
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

**Comment by sindresorhus** [comment]
It's a good start, but the list doesn't have much content yet. Try submitting again in a couple of months when the list has had more time to mature and gather quality content.

**Pull request closed without merging**
