### PR TITLE
Add awesome-canvas

### PR DESCRIPTION
**Pull request by raphamorim**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Good start, but some things could be improved.

First read: https://github.com/sindresorhus/awesome/blob/master/contributing.md and https://github.com/sindresorhus/awesome/blob/master/awesome.md

MIT is not a good license for this type of content. Creative Commons is a better choice. All the `Examples` need description. You also say it's "best examples of canvas", description for each item should also say why. The `Twitter` section is just a list of links without any context. Each item needs arguments for why I would want to follow that person.

**Comment by raphamorim** [comment]
Leave it to me! I'll notify when finished :)

**Comment by raphamorim** [comment]
@sindresorhus I made the changes. Can you check? :)

**Comment by sindresorhus** [comment]
Good stuff :)

**Comment by sindresorhus** [comment]
Would be awesome if you would add the awesome badge: https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge

**Comment by raphamorim** [comment]
Badge Added! Thanks :)

**Pull request merged**
