### PR TITLE
Add Blazor

### PR DESCRIPTION
**Pull request by AdrienTorris**
Add the awesome-blazor repository (https://github.com/AdrienTorris/awesome-blazor) to the Front-End Development section.

(https://github.com/AdrienTorris/awesome-blazor)

Blazor is an experimental .NET web framework using C#/Razor and HTML that runs in the browser with WebAssembly.

### CODE REVIEW

**Comment by AdrienTorris** [comment]
Solve the issue #1256.

**Comment by AdrienTorris** [comment]
Done.

**Comment by sindresorhus** [comment]
Hey, sorry for the lack of response, please see #1363.

**Comment by sindresorhus** [comment]
Can you fix the merge conflict?

**Comment by sindresorhus** [comment]
```
❯ awesome-lint https://github.com/AdrienTorris/awesome-blazor
✖ Linting

  README.md:27:1
  ✖    1:1    Missing License section                                                              remark-lint:awesome/license
  ✖    1:19   Invalid badge source                                                                 remark-lint:awesome/badge
  ✖   24:1    ToC should not contain section "Contributing"                                        remark-lint:awesome/toc
  ✖   27:1    Don’t add a trailing ? to headings                                                   remark-lint:no-heading-punctuation
  ✖   37:75   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   38:35   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   39:56   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   40:87   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   41:59   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   42:51   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   43:56   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   44:100  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   45:80   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   46:43   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   47:71   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   50:3    Link to https://lupblazordemos.z13.web.core.windows.net/CalculatorPage is dead       remark-lint:no-dead-urls
  ✖   50:85   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   51:3    Link to https://lupblazordemos.z13.web.core.windows.net/ChessPage is dead            remark-lint:no-dead-urls
  ✖   51:75   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   52:3    Link to https://lupblazordemos.z13.web.core.windows.net/ClockCanvas is dead          remark-lint:no-dead-urls
  ✖   52:83   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   53:69   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   54:49   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   55:3    Link to https://lupblazordemos.z13.web.core.windows.net/GameSnakePage is dead        remark-lint:no-dead-urls
  ✖   55:83   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   56:3    Link to https://lupblazordemos.z13.web.core.windows.net/PasswordPatternPage is dead  remark-lint:no-dead-urls
  ✖   56:95   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   57:3    Link to https://lupblazordemos.z13.web.core.windows.net/RawHTML is dead              remark-lint:no-dead-urls
  ✖   57:83   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   58:54   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   59:41   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   60:3    Link to http://blazor-flight-finder.azurewebsites.net/ is dead                       remark-lint:no-dead-urls
  ✖   60:66   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   61:35   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   62:64   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   63:60   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   66:98   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   67:62   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   68:40   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   69:54   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   70:86   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   71:57   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   72:68   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   73:87   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   74:67   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   75:56   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   76:69   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   77:57   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   78:69   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   79:63   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   80:85   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   81:69   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   82:83   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   83:78   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   84:98   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   85:3    Link to https://github.com/Lupusa87/BlazorExcel is dead                              remark-lint:no-dead-urls
  ✖   85:58   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   85:73   Link to https://lupblazordemos.z13.web.core.windows.net/ExcelPage is dead            remark-lint:no-dead-urls
  ✖   86:63   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   87:65   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   88:73   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   89:70   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   90:69   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   91:57   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   91:86   Link to https://lupblazordemos.z13.web.core.windows.net/PaintPage is dead            remark-lint:no-dead-urls
  ✖   92:77   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   93:57   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   94:58   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   95:77   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   96:69   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   97:60   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   98:3    Link to https://github.com/danroth27/BlazorSignalRTest is dead                       remark-lint:no-dead-urls
  ✖   98:70   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖   99:67   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  100:63   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  101:59   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  102:63   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  103:70   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  104:61   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  105:67   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  106:62   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  107:52   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  108:75   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  109:93   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  110:63   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  111:41   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  112:91   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  113:75   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  114:3    Link to https://github.com/ivanchev/KendoBlazorPoc is dead                           remark-lint:no-dead-urls
  ✖  114:63   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  115:42   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  116:66   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  117:70   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  118:60   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  119:49   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  120:74   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  121:62   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  122:51   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  123:70   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  124:70   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  125:56   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  126:51   Text "youtube" should be written as "YouTube"                                        remark-lint:awesome/spell-check
  ✖  126:51   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  127:72   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  128:118  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  128:141  Link to https://lupblazordemos.z13.web.core.windows.net/WebSocketPage is dead        remark-lint:no-dead-urls
  ✖  129:54   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  130:67   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  133:63   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  134:62   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  135:71   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  136:83   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  137:61   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  138:55   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  139:57   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  140:69   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  141:57   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  142:57   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  143:55   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  146:57   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  147:76   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  148:70   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  149:75   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  150:82   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  151:49   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  152:81   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  153:70   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  154:65   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  155:62   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  156:73   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  157:77   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  158:73   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  159:51   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  160:79   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  161:79   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  162:78   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  163:3    Link to https://github.com/vertonghenb/Blazor.Notifications is dead                  remark-lint:no-dead-urls
  ✖  163:78   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  164:51   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  165:72   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  166:64   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  167:77   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  168:61   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  169:69   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  170:65   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  171:70   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  172:63   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  173:55   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  174:67   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  175:83   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  176:98   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  177:62   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  178:68   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  179:64   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  180:61   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  181:78   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  182:44   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  183:88   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  184:71   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  187:75   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  188:109  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  189:72   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  190:84   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  191:78   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  192:102  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  193:3    Invalid list item link URL                                                           remark-lint:awesome/list-item
  ✖  194:68   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  195:110  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  196:135  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  197:113  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  198:111  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  199:67   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  200:67   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  201:94   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  202:116  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  203:87   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  204:104  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  205:85   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  206:99   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  207:82   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  208:81   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  209:109  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  210:99   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  218:82   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  219:90   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  220:153  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  221:78   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  222:140  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  223:129  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  224:77   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  225:134  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  226:176  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  227:107  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  228:117  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  229:113  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  230:90   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  231:230  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  232:126  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  233:141  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  234:85   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  235:124  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  236:175  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  237:178  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  238:132  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  239:89   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  240:131  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  241:117  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  242:152  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  243:161  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  244:85   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  245:122  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  246:125  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  247:113  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  248:165  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  249:113  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  250:101  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  251:86   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  252:133  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  253:90   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  254:147  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  255:112  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  256:143  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  257:112  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  258:129  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  259:106  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  260:121  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  261:153  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  262:169  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  263:113  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  264:125  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  265:97   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  266:151  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  267:117  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  268:121  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  269:129  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  270:109  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  271:148  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  272:131  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  273:102  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  274:104  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  275:131  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  276:104  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  277:132  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  278:131  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  279:149  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  280:68   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  281:106  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  282:142  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  283:98   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  284:67   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  285:144  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  286:110  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  287:153  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  288:128  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  289:114  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  290:89   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  291:91   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  292:118  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  293:98   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  294:131  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  295:124  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  296:115  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  297:162  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  298:79   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  299:92   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  300:153  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  301:130  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  302:92   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  303:166  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  304:128  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  305:110  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  306:111  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  307:153  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  308:105  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  309:73   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  310:127  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  311:150  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  312:114  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  313:131  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  314:121  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  315:113  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  316:155  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  317:189  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  318:141  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  319:166  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  320:147  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  321:95   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  326:77   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  327:146  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  328:108  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  329:95   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  330:146  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  331:111  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  332:70   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  333:100  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  334:139  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  337:109  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  338:43   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  339:3    Link to https://www.microsoft.com/net/download/dotnet-core is dead                   remark-lint:no-dead-urls
  ✖  339:66   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  340:90   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  341:59   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  342:55   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  345:155  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  348:154  List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  351:96   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  354:44   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  355:70   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  356:48   List item link and description must be separated with a dash                         remark-lint:awesome/list-item
  ✖  357:65   List item link and description must be separated with a dash                         remark-lint:awesome/list-item

  310 errors
```

https://github.com/sindresorhus/awesome-lint

**Comment by sindresorhus** [comment]
> Includes a succinct description of the project/theme at the top of the readme. (Example)

https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md

**Comment by sindresorhus** [comment]
Closing for lack of response.

**Comment by AdrienTorris** [comment]
I'm working on it, it will be good today.

**Comment by AdrienTorris** [comment]
It would be better now.

**Comment by AdrienTorris** [comment]
For information the Awesome Blazor GitHub page is mentioned by Microsoft on the official Blazor's website : https://dotnet.microsoft.com/apps/aspnet/web-apps/client

**Pull request closed without merging**
