### PR TITLE
Add Imba

### PR DESCRIPTION
**Pull request by shapkarin**
It's the second PR with `imba` after fixing awesome-lint errors. First was https://github.com/sindresorhus/awesome/pull/1488 

List url:
https://github.com/koolamusic/awesome-imba#readme

Description:
Imba is a language with a syntax inspired by ruby, it compiles to readable and performant JavaScript, and works inside the existing ecosystem.

-------
Also we added `awesome-lint` as a `pre-commit` https://github.com/koolamusic/awesome-imba/pull/18

### CODE REVIEW

**Comment by davisonio** [comment]
* Title should be Awesome Imba not awesome-imba

**Comment by shapkarin** [comment]
@davisonio fixed that

**Comment by CompSciLauren** [comment]
There are a few sentences that could be improved slightly:
- "When working on client-side projects you should rather use imbapack." --> "When working on client-side projects you should use imbapack instead."
- "You can install imba locally and set at webpack config that you need that loader." --> "You can install imba locally and in the webpack config you can set it to use that loader."
- "Learn why imba fast, how it works and then play arounds with it." --> "Learn why imba is fast, how it works and then play around with it."
- "A tool build in imba, that make it easier to prettier JSON." --> "A tool built in imba that makes it easier to have prettier JSON."
- "An app that generate random Quote." --> "An app that generates random quotes."

The word "Imba" is not capitalized consistently.

Under the Contribution section, I would change it to "Are you building great stuff with Imba? Feel free to share with us!" And I would also change the part below it to say "Here are instructions. Please read the Code of Conduct as well." or maybe "Here are instructions. Please also read the Code of Conduct."

This is a great list! Nice work.

**Comment by shapkarin** [comment]
Thanks for improvements! We added that too!

**Comment by sindresorhus** [comment]
You are not following all the guidelines and there are many typos in the description here and in your Awesome list.

**Comment by sindresorhus** [comment]
You need to add your email here like the instruction says: https://github.com/koolamusic/awesome-imba/blob/master/.github/CODE_OF_CONDUCT.md

**Comment by shapkarin** [comment]
Thanks. I'll update that list after I read all guidelines again. I hope that they are not a lot.

**Comment by sindresorhus** [comment]
@shapkarin Ping

**Comment by shapkarin** [comment]
> @shapkarin Ping

thanks, I will prettify it later and let you know

**Comment by shapkarin** [comment]
@sindresorhus hi, hope that I will find time for that and ping you till the end of the week.

**Comment by shapkarin** [comment]
@sindresorhus hello, some improvements was added

**Comment by sindresorhus** [comment]
You're still not following all the guidelines:

> Includes a succinct description of the project/theme at the top of the readme. (Example)
✅ Mobile operating system for Apple phones and tablets.
✅ Prototyping interactive UI designs.
❌ Resources and tools for iOS development.
❌ Awesome Framer packages and tools.

**Comment by sindresorhus** [comment]
Removing the description is not what I asked.

**Comment by shapkarin** [comment]
Ok. I will add description what is Imba to the lists readme and better description for this PR.

**Comment by shapkarin** [comment]
I made some changes. @sindresorhus please, correct me if I got something wrong.

**Comment by shapkarin** [comment]
I have added Imba succinct description. But it seems that we also need to fix some list descriptions.

**Comment by shapkarin** [comment]
@sindresorhus hope now it follows all guidelines. sorry about: `Don't open a Draft... `

**Comment by sindresorhus** [comment]
Tweet: https://twitter.com/awesome__re/status/1188509887845679104

**Pull request merged**
