### PR TITLE
Add awesome-chef

### PR DESCRIPTION
**Pull request by joelhandwell**
Chef is a configuration management tool. This PR will add curated list of Chef related resources.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Cool. Would you mind reading the [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md). Thanks 😎👍

**Comment by sindresorhus** [comment]
ping :)

**Comment by joelhandwell** [comment]
@sindresorhus I realize that the repo is racking "Comment on why something is awesome" in many of the list entries. I'll add them and come back to you.

**Comment by sindresorhus** [comment]
> "Comment on why something is awesome"

That's not a requirement, just a recommendation, especially for things that you have experience with. That's very helpful for users.

-

In general though the list looks ok, but could use some work on formatting, adding descriptions to all items, and add some more learning resources (more articles). Many of the items uses incorrect naming, like `nodejs` => `Node.js`, `python` => `Python`, etc. No need to have the contribution guidelines in the readme, put them in a separate contributing.md file. The list is missing a license, which is clearly mention in the previously linked to [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).

-

Gonna close this for now while you work on the above feedback. Happy to reconsider then.

**Pull request closed without merging**
