### PR TITLE
Add DevSecOps

### PR DESCRIPTION
**Pull request by JakobRPennington**
**https://github.com/TaptuIT/awesome-devsecops**

This list is a collection of resources and tooling related to DevSecOps. DevSecOps is an extension of DevOps - a methodology and philosophy for software development - that aims to incorporate security expertise and testing into the development lifecycle, with the goal of creating more secure software.

This list of resources can help software development teams learn about and adopt DevSecOps practices and tooling, resulting in more secure software for everybody.

Reviewed PRs: #1756 #1758

By submitting this pull request I confirm I've read and complied with the below requirements 🖖

### CODE REVIEW

**Comment by JakobRPennington** [comment]
unicorn

**Comment by JakobRPennington** [comment]
This PR is a resubmission for #1760 after the old PR was closed due to renaming the default branch.

Since that PR was closed, I have resolved all noted issues including:
- Renaming default branch to `main`.
- Replaced banner image with high-DPI version.
- Added a description for each entry.
- Updated the link and description in this repository, as you suggested.

Please let me know if there are any further issues, and thanks for all your effort :D

**Comment by sindresorhus** [comment]
In `DevSecOps is an extension of the DevOps movement that aims to bring security practices into the development lifecycle through developer-centric security tooling and processes.`, can you linkify `DevSecOps` and `DevOps` to good sources where the user can read more about them?

**Comment by JakobRPennington** [comment]
@sindresorhus Good suggestion, I've added links to Atlassian and Rapid7, two really good resources for DevOps and DevSecOps respectively.

@mhxion Thanks for the suggestion, but having two levels of nested lists would be against the list guidelines
> Should only have one level of nested lists, preferably none.

**Comment by sindresorhus** [comment]
Tweet: https://twitter.com/awesome__re/status/1279131546897641473

**Pull request merged**
