### PR TITLE
Add Billing

### PR DESCRIPTION
**Pull request by kdeldycke**
**https://github.com/kdeldycke/awesome-billing**

**Why is this list awesome?**

Any company needs at one point to get money from customers. That's when things gets messy for us developers, as we try to reconcile the complexity of the business with our software stack.

This awesome list helps software engineers bootstrap billing & payments systems and make sense of invoicing, pricing, accounting, marketplace, fraud and business intelligence.

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

✅ I read this PR template multiple times. Better yet: I contributed to refining it: https://github.com/sindresorhus/awesome/commit/488c1051a3089e386ed223a5b45ab8ff8c53397c

## Requirements for your pull request

- [x] **Don't waste my time.** Do a good job, adhere to all the guidelines, and be responsive.
- [x] **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).**
  Sort of. I'm involved in the community by other means:
    ❗ I already contributed to this repository: https://github.com/sindresorhus/awesome/commits?author=kdeldycke
    ❗ I pushed code to `awesome-lint` to automate even more the work of reviewing lists: https://github.com/sindresorhus/awesome-lint/commits?author=kdeldycke
- [x] You have read and understood the [instructions for creating a list](create-list.md).
- [x] This pull request has a title in the format `Add Name of List`.
	- ✅ `Add Swift`
	- ✅ `Add Software Architecture`
	- ❌ `Update readme.md`
	- ❌ `Add Awesome Swift`
	- ❌ `Add swift`
	- ❌ `add Swift`
	- ❌ `Adding Swift`
	- ❌ `Added Swift`
- [x] Your entry here should include a short description about the project/theme of the list. **It should not describe the list itself.** The first character should be uppercase and the description should end in a dot. It should be an objective description and not a tagline or marketing blurb.
	- ✅ `- [iOS](…) - Mobile operating system for Apple phones and tablets.`
	- ✅ `- [Framer](…) - Prototyping interactive UI designs.`
	- ❌ `- [iOS](…) - Resources and tools for iOS development.`
	- ❌ `- [Framer](…)`
	- ❌ `- [Framer](…) - prototyping interactive UI designs`
- [x] Your entry should be added at the bottom of the appropriate category.
- [x] The suggested Awesome list complies with the below requirements.

## Requirements for your Awesome list

- [x] **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
    ✅ This repository has been active since June 2019: https://github.com/kdeldycke/awesome-billing/commit/2f87a717d13399f3aad681126307c08a36753a2f
- [x] Don't open a Draft / WIP pull request while you work on the guidelines. A pull request should be 100% ready and should adhere to all the guidelines when you open it.
- [x] Run [`awesome-lint`](https://github.com/sindresorhus/awesome-lint) on your list and fix the reported issues. If there are false-positives or things that cannot/shouldn't be fixed, please [report it](https://github.com/sindresorhus/awesome-lint/issues/new).
  ✅ `awesome-lint` is run on each commit via a GitHub action: https://github.com/kdeldycke/awesome-billing/actions?query=workflow%3ALint 
- [x] The default branch should be named [`main`, not `master`](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/).
- [x] **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- ✅ `Mobile operating system for Apple phones and tablets.`
	- ✅ `Prototyping interactive UI designs.`
	- ❌ `Resources and tools for iOS development.`
	- ❌ `Awesome Framer packages and tools.`
- [x] It's the result of hard work and the best I could possibly produce.
	**If you have not put in considerable effort into your list, your pull request will be immediately closed.**
  ✅ I've been working on it for a year and a half, made 250+ commits, and highly curated the list (we're far from a simple collection of links).
- [ ] The repo name of your list should be in lowercase slug format: `awesome-name-of-list`.
	- ✅ `awesome-swift`
	- ✅ `awesome-web-typography`
	- ❌ `awesome-Swift`
	- ❌ `AwesomeWebTypography`
- [x] The heading title of your list should be in [title case](https://capitalizemytitle.com/) format: `# Awesome Name of List`.
	- ✅ `# Awesome Swift`
	- ✅ `# Awesome Web Typography`
	- ❌ `# awesome-swift`
	- ❌ `# AwesomeSwift`
- [x] Non-generated Markdown file in a GitHub repo.
- [x] The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
- [x] Not a duplicate. Please search for existing submissions.
- [x] Only has awesome items. Awesome lists are curations of the best, not everything.
- [x] Does not contain items that are unmaintained, has archived repo, deprecated, or missing docs. If you really need to include such items, they should be in a separate Markdown file.
- [x] Includes a project logo/illustration whenever possible.
	- [x] Either centered, fullwidth, or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
	- [x] The image should link to the project website or any relevant website.
	- [x] **The image should be high-DPI.** Set it to maximum half the width of the original image.
- [x] Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- [x] Includes the [Awesome badge](awesome.md#awesome-badge).
	- [x] Should be placed on the right side of the readme heading.
		- [x] Can be placed centered if the list has a centered graphics header.
	- [x] Should link back to this list.
- [x] Has a Table of Contents section.
	- [x] Should be named `Contents`, not `Table of Contents`.
	- [x] Should be the first section in the list.
	- [x] Should only have one level of [nested lists](https://commonmark.org/help/tutorial/10-nestedLists.html), preferably none.
	- [x] Must not feature `Contributing` or `Footnotes` sections.
- [x] Has an appropriate license.
	- [x] **We strongly recommend the [CC0 license](https://creativecommons.org/publicdomain/zero/1.0/), but any [Creative Commons license](https://creativecommons.org/choose/) will work.**
		- Tip: You can quickly add it to your repo by going to this URL: `https://github.com/<user>/<repo>/community/license/new?branch=main&template=cc0-1.0` (replace `<user>` and `<repo>` accordingly).
	- A code license like MIT, BSD, Apache, GPL, etc, is not acceptable. Neither are WTFPL and [Unlicense](https://unlicense.org).
	- [x] Place a file named `license` or `LICENSE` in the repo root with the license text.
	- [x] **Do not** add the license name, text, or a `Licence` section to the readme. GitHub already shows the license name and link to the full text at the top of the repo.
	- [x] To verify that you've read all the guidelines, please comment on your pull request with just the word `unicorn`.
- [x] Has [contribution guidelines](awesome.md#include-contribution-guidelines).
	- [x] The file should be named `contributing.md`. Casing is up to you.
	- [x] It can optionally be linked from the readme in a dedicated section titled `Contributing`, positioned at the top or bottom of the main content.
	- [x] The section should not appear in the Table of Contents.
- [x] All non-important but necessary content (like extra copyright notices, hyperlinks to sources, pointers to expansive content, etc) should be grouped in a `Footnotes` section at the bottom of the readme. The section should not be present in the Table of Contents.
- [x] Has consistent formatting and proper spelling/grammar.
	- [x] The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
	- [x] The description starts with an uppercase character and ends with a period.
	- [x] Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
- [x] Doesn't use [hard-wrapping](https://stackoverflow.com/questions/319925/difference-between-hard-wrap-and-soft-wrap).
- [x] Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.
- [x] Doesn't include an `Inspired by awesome-foo` or `Inspired by the Awesome project` kinda link at the top of the readme. The Awesome badge is enough.

**Go to the top and read it again.**

### CODE REVIEW

**Comment by kdeldycke** [comment]
I still have one open issue on which I can't find any guideline.

The full name of my repository is `Awesome Billing & Payments`. My repository ID is inconsistency named: `awesome-billing`. Should I change it to:
1. `awesome-billing-payments`
2. `awesome-billing-and-payments`
3. leave it be `awesome-billing`

?

**Comment by kdeldycke** [comment]
unicorn

**Comment by OregonSells** [comment]
Write access

**Comment by vmax** [comment]
@kdeldycke judging from the rest of entries, I think it would be most suitable to leave it as `awesome-billing`; the name is short and descriptive already. Also, I believe "Payments" is just a _component_ of "Billing" (one of many); other components would be "Refunds", "Invoicing" etc. which are all described by "Billing" term, judging by [ref](https://en.wikipedia.org/wiki/Telecommunications_billing):

> _Telecommunications_ billing is the group of processes of _communications_ service providers that are responsible to collect consumption data, calculate charging and billing information, produce bills to customers, process their payments and manage debt collection. 

(_italicized_ are the words that could be abstracted away from the definition to prove the point)

**Comment by zrosenbauer** [comment]
The biggest thing is being able to find it, grok it, & understand it quickly. 

To piggyback off of @vmax if I was to search for payments would it come up? Am I more likely to so search for billing? When I see it on the list will I intuitively understand billing includes payments? 

My vote is leave as `awesome-billing` and change the title. You can add Payments in the description if you want as a guide for people.

**Comment by kdeldycke** [comment]
Thanks @vmax and @zrosenbauer for the feedback! There's a clear consensus here to use `awesome-billing` as the canonical name. I'll make the appropriate changes and amend that PR.

As for the reason I went for `Billing & Payments` first, it's because it was the name of the engineering team I created at Scaleway. The domain is big enough to have two dedicated and independent sub-teams, one for all the billing work and another for the payment pipeline. So I carefully gave a name for each, as a kind of SEO tweak, to help people realize that both the payment side of things and the billing ecosystem are critical to business operations.

**Comment by kdeldycke** [comment]
All changes have been made to refer to the repository as `Awesome Billing`.

The official awesome linter is passing upstream. This PR is ready to be merged.

**Review by innocenzi — APPROVED** [review]

**Comment by kdeldycke** [comment]
Checks are failing on this PR for the same reasons other PR fails. It seems to be an issue with the GitHub action workflow of the `main` branch. Other than that, this PR is ready to be merged.

**Comment by sindresorhus** [comment]
Some entries are missing a description, for example, `Pimcore`.

**Comment by sindresorhus** [comment]
Tweet: https://twitter.com/awesome__re/status/1419997203523899398

**Comment by kdeldycke** [comment]
Thanks @sindresorhus for the merge and the rebasing upon the latest version!

> Some entries are missing a description, for example, `Pimcore`.

You're right. I did allow that as per `awesome-lint`. I added the missing descriptions anyway. See: https://github.com/kdeldycke/awesome-billing/commit/e73a6c46de5525ec878d36530494054e07c27571

**Pull request merged**
