### PR TITLE
Add Symfony Education

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by aleksandar-todorovic** [comment]
Why didn't you try combining your content with the existing `awesome-symfony` list?

**Comment by TomasVotruba** [comment]
@aleksandar-todorovic I tried before, but it was dead/rejected. Also I think it would disappear in legacy bundles, that make that list at the moment.

This one is different. It's about informational resources that can educate.

**Comment by sindresorhus** [comment]
> I tried before, but it was dead/rejected.

Link? I couldn't find anything: https://github.com/sitepoint/awesome-symfony/issues?utf8=%E2%9C%93&q=author%3ATomasVotruba+

Have they indicated they don't want educational resources?

-

// @EmanueleMinotto

**Comment by EmanueleMinotto** [comment]
Now it's under sitepoint, probably that was the reason for the rejection (I guess because I don't remember a PR like that, nor if that was submitted under sitepoint/awesome-symfony or EmanueleMinotto/awesome-symfony2)

**Comment by sindresorhus** [comment]
@EmanueleMinotto Would you accept educational resources?

**Comment by EmanueleMinotto** [comment]
I'm not sure if it's possible (see https://github.com/sitepoint/awesome-symfony/issues/48)
/cc @Swader

**Comment by TomasVotruba** [comment]
@sindresorhus Not sure about that. Please take my second reason in account. I prefer this collection to be about education only.

**Comment by davisonio** [comment]
> I prefer this collection to be about education only.

Perhaps you should rename the list to 'Awesome Symfony Education'? It would avoid confusion.

**Comment by TomasVotruba** [comment]
@davisonio Good idea. Would that be enough?

**Comment by davisonio** [comment]
> @davisonio Good idea. Would that be enough?

I think it'd be better to rename to `awesome-symfony-education` as it would fit with the current submissions we have. (e.g. we have Laravel and Laravel Education)

**Comment by TomasVotruba** [comment]
I meant enough to merge. I can do it immediately, if so.

**Comment by TomasVotruba** [comment]
Renamed to Education!

**Comment by davisonio** [comment]
Great, also adding some contributing guidelines would be good. :smile:

**Comment by TomasVotruba** [comment]
@davisonio What exactly do you have in mind?

**Comment by TomasVotruba** [comment]
Ping @davisonio

**Comment by davisonio** [comment]
> @davisonio What exactly do you have in mind?

Read all about it [here](https://github.com/sindresorhus/awesome/blob/master/create-list.md), it's preferred that awesome lists have some contribution guidelines (such as the guidelines for this repository).

**Comment by b1rdex** [comment]
@TomasVotruba I created PR for this.

**Comment by TomasVotruba** [comment]
@b1rdex Merged, thank you a lot!

**Comment by sindresorhus** [comment]
I don't understand why the original list was moved under the Sitepoint org. Seems like a bad move.

Anyways. Added this now.

**Comment by TomasVotruba** [comment]
@sindresorhus Thank you very much"

**Pull request closed without merging**
