### PR TITLE
Add Competitive Coding

### PR DESCRIPTION
**Pull request by hkirat**
Added a Curated list of Topic wise Theory and Questions to Get You Started On Competitive Coding under the domain of Computer Science.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please read the [instructions](https://github.com/sindresorhus/awesome/blob/master/create-list.md) for creating a new list, [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

Especially this part:

> Wait at least a couple of weeks after creating a list before submitting to give it a chance to mature.

Ping me here in a few weeks and I'll reopen ;)

**Comment by sindresorhus** [comment]
Each item in the list could use a succinct description.

**Comment by hkirat** [comment]
Ping for merging.

**Comment by sindresorhus** [comment]
It has not been a few weeks yet and you have not resolved the mentioned issues. Please read through the `awesome manifest` again. You're missing a license, and description for items. Each section like "Prefix and Suffix Trees" could also have a short description of what it is. Awesome lists are hard work. Put some effort into it ;)

**Comment by hkirat** [comment]
Added description for each Item..
Also added the licence.
Any more suggestion would be valuable.

**Comment by sindresorhus** [comment]
From the awesome manifest which I've asked you to read two times now:

> Creative Commons licenses are perfect for this purpose. We would recommend CC0. **Code licenses like MIT, BSD, GPL, and so forth are not recommended.**

You seems to be using an MIT license. Please reconsider.

**Comment by sindresorhus** [comment]
Can you fix the merge conflict?

*(Don't open a new PR. Just amend this one)*

**Comment by hkirat** [comment]
Modified the Licence and fixed the merge conflict.

**Comment by sindresorhus** [comment]
Added

**Pull request closed without merging**
