### PR TITLE
Add Smart Contracts

### PR DESCRIPTION
**Pull request by Overtorment**
https://github.com/Overtorment/awesome-smart-contracts

The list is about platforms where developers can create and run programs, known as Smart Contracts.

# By submitting this pull request I confirm I've read and complied with the below requirements.

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title.<br>For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
	- Be added at the bottom of the appropriate category.
- The list I'm submitting complies with these requirements:
	- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
	- It's the result of hard work and the best I could possibly produce.
	- Non-generated Markdown file in a GitHub repo.
	- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
	- Not a duplicate.
	- Only has awesome items. Awesome lists are curations of the best, not everything.
	- Includes a project logo/illustration whenever possible.
		- Either fullwidth or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
		- The image should link to the project website or any relevant website.
		- The image should be high-DPI. Set it to maximum half the width of the original image.
	- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
	- Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
		- Should be placed on the right side of the readme heading.
		- Should link back to this list.
	- Has a Table of Contents section.
		- Should be named `Contents`, not `Table of Contents`.
		- Should be the first section in the list.
		- Should only have one level of sub-lists, preferably none.
	- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
		- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
		- If you use a license badge, it should be SVG, not PNG.
	- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
		- The file should be named `contributing.md`. Casing is up to you.
	- Has consistent formatting and proper spelling/grammar.
		- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
		- The description starts with an uppercase character and ends with a period.
		- Drop all the `A` / `An` prefixes in the descriptions.
		- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
	- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.
- Go to the top and read it again.

### CODE REVIEW

**Comment by Overtorment** [comment]
@legodude17  bad description removed. License is present

**Comment by sindresorhus** [comment]
Hey, sorry for the lack of response, please see #1363.

**Comment by sindresorhus** [comment]
```
❯ awesome-lint https://github.com/Overtorment/awesome-smart-contracts
✖ Linting

  README.md:84:3
  ✖    1:1    License section must be at heading depth 2            remark-lint:awesome/license
  ✖    1:1    Missing or invalid Table of Contents                  remark-lint:awesome/toc
  ✖    1:28   Invalid badge source                                  remark-lint:awesome/badge
  ✖    5:1    Don’t add a trailing ? to headings                    remark-lint:no-heading-punctuation
  ✖   33:1    Don’t add a trailing ! to headings                    remark-lint:no-heading-punctuation
  ✖   44:130  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   44:170  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   46:61   Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   46:166  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   46:171  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   46:176  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   46:192  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   46:199  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   46:201  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   47:162  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   47:170  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   47:180  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   47:192  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   47:193  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   47:200  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   47:200  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   47:201  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   47:211  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   49:152  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   49:159  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   49:160  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   50:2    Cell should be padded                                 remark-lint:table-cell-padding
  ✖   50:42   Cell should be padded                                 remark-lint:table-cell-padding
  ✖   50:119  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   50:181  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   50:189  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   50:190  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   50:199  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   50:200  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   50:211  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   50:211  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   50:212  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   50:219  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   53:153  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   53:158  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   53:161  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   53:164  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   53:168  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   53:171  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   54:160  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   54:171  Missing final pipe in table fence                     remark-lint:table-pipes
  ✖   54:171  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   55:138  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   55:152  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   55:159  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   55:160  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   56:57   Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   56:57   Cell should be padded                                 remark-lint:table-cell-padding
  ✖   56:63   Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   56:120  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   56:128  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   56:136  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   56:150  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   56:158  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   56:169  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   57:138  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   57:160  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   59:62   Text "Javascript" should be written as "JavaScript"   remark-lint:awesome/spell-check
  ✖   59:71   Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   59:72   Cell should be padded                                 remark-lint:table-cell-padding
  ✖   59:72   Missing final pipe in table fence                     remark-lint:table-pipes
  ✖   61:124  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   61:124  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   61:129  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   61:152  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   61:159  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   61:160  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   62:138  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   62:143  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   62:143  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   62:149  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   62:161  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   62:162  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   62:169  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   62:169  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   62:170  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   62:180  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   65:130  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   65:139  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   65:139  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   65:140  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   65:152  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   65:160  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   67:102  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   67:108  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   67:113  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   67:122  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   67:130  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   67:132  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   68:130  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   68:139  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   68:139  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   68:140  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   68:152  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   68:159  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   69:45   Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   69:62   Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   69:124  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   69:131  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   69:139  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   69:153  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   69:163  Misaligned table fence                                remark-lint:table-pipe-alignment
  ✖   71:160  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   74:130  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   74:152  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   74:160  Cell should be padded                                 remark-lint:table-cell-padding
  ✖   84:3    Incorrect indentation before bullet: remove 2 spaces  remark-lint:list-item-bullet-indent
  ✖   85:3    Incorrect indentation before bullet: remove 2 spaces  remark-lint:list-item-bullet-indent
  ✖   88:3    Text "github" should be written as "GitHub"           remark-lint:awesome/spell-check
  ✖   89:3    Text "github" should be written as "GitHub"           remark-lint:awesome/spell-check
  ✖   90:3    Text "github" should be written as "GitHub"           remark-lint:awesome/spell-check
  ✖  111:3    Incorrect indentation before bullet: remove 1 space   remark-lint:list-item-bullet-indent
  ✖  114:3    Incorrect indentation before bullet: remove 1 space   remark-lint:list-item-bullet-indent
  ✖  114:4    Text "github" should be written as "GitHub"           remark-lint:awesome/spell-check
  ✖  125:3    Text "github" should be written as "GitHub"           remark-lint:awesome/spell-check
  ✖  139:3    Incorrect indentation before bullet: remove 1 space   remark-lint:list-item-bullet-indent
  ✖  140:3    Incorrect indentation before bullet: remove 1 space   remark-lint:list-item-bullet-indent
  ✖  140:4    Text "github" should be written as "GitHub"           remark-lint:awesome/spell-check
  ✖  141:3    Incorrect indentation before bullet: remove 1 space   remark-lint:list-item-bullet-indent
  ✖  157:3    Incorrect indentation before bullet: remove 2 spaces  remark-lint:list-item-bullet-indent
  ✖  158:3    Incorrect indentation before bullet: remove 2 spaces  remark-lint:list-item-bullet-indent
  ✖  161:3    Incorrect indentation before bullet: remove 2 spaces  remark-lint:list-item-bullet-indent
  ✖  187:3    Incorrect indentation before bullet: remove 2 spaces  remark-lint:list-item-bullet-indent
  ✖  188:3    Incorrect indentation before bullet: remove 2 spaces  remark-lint:list-item-bullet-indent
  ✖  191:3    Incorrect indentation before bullet: remove 2 spaces  remark-lint:list-item-bullet-indent
  ✖  222:3    Incorrect indentation before bullet: remove 2 spaces  remark-lint:list-item-bullet-indent
  ✖  222:5    Text "github" should be written as "GitHub"           remark-lint:awesome/spell-check
  ✖  223:3    Incorrect indentation before bullet: remove 2 spaces  remark-lint:list-item-bullet-indent
  ✖  223:5    Text "github" should be written as "GitHub"           remark-lint:awesome/spell-check
  ✖  258:3    Text "github" should be written as "GitHub"           remark-lint:awesome/spell-check
  ✖  259:3    Link to https://neblio.wiki is dead                   remark-lint:no-dead-urls

  136 errors

```

https://github.com/sindresorhus/awesome-lint

**Comment by sindresorhus** [comment]
Can you fix the merge conflict?

**Comment by sindresorhus** [comment]
Don't disable the Issues tab in your repo.

**Comment by sindresorhus** [comment]
Closing for lack of response.

**Pull request closed without merging**
