### PR TITLE
Add Elixir Books

### PR DESCRIPTION
**Pull request by sger**
**https://github.com/sger/ElixirBooks**

**List of books about Elixir programming language**
# ALL THE BELOW CHECKBOXES SHOULD BE DONE AND CHECKED AND THE ABOVE PLACEHOLDERS SHOULD BE FILLED IN BEFORE SUBMITTING A PULL REQUEST!
- [x] I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- [x] This pull request has a descriptive title. _(For example: `Add Node.js`)_
- The list I added
  - [x] **has been around for at least 20 days,**
  - [x] is a non-generated Markdown file in a GitHub repo,
  - [x] is not a duplicate,
  - [x] only has awesome items with descriptions _(Awesome lists are curations of the best, not of everything)_,
  - [x] contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
  - [x] has a Table of Contents section named `Contents` as the first section,
  - [x] has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license) _(Meaning something like CC0, NOT a code licence like MIT, BSD, Apache, etc)_,
  - [x] has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
  - [x] has been checked for inconsistent formatting, spelling, and grammar _(This includes starting each link description with an uppercase character and ending it with a period `.`, and consistent naming)_,
  - [x] has been added at the bottom of the appropriate category.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Reposting my previous comment:

-

Some feedback:

- `Table of Contents` => `Contents`
- Drop the Travis badge.
- Readme is missing a title.
- The `Resources` section should be a list, not headings.
- the `Resources` section should have a link to the main Elixir awesome list: https://github.com/h4cc/awesome-elixir

-

The Elixir Awesome list already has a Books section: https://github.com/h4cc/awesome-elixir#books 
Maybe you could collaborate with @h4cc somhow?

**Comment by sger** [comment]
@sindresorhus Readme is missing a title more specific on this? everything else is OK.

**Comment by davisonio** [comment]
> @sindresorhus Readme is missing a title more specific on this? everything else is OK.

First line in the readme.md file should be:
```
# Awesome Elixir Books [![Awesome](https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg)](https://github.com/sindresorhus/awesome)
```

**Comment by sger** [comment]
@davisonio fixed

**Pull request merged**
