### PR TITLE
Added awesome slim list

### PR DESCRIPTION
**Pull request by xssc**
Added awesome slim list

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please read the [instructions](https://github.com/sindresorhus/awesome/blob/master/create-list.md) for creating a new list, [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

Especially this part:

> Wait at least a couple of weeks after creating a list before submitting to give it a chance to mature.

Ping me here in a few weeks and I'll reopen ;)

**Comment by sindresorhus** [comment]
It will also need more content before being accepted. E.g. more articles, the best plugins, cheat sheets, videos, etc.

**Comment by xssc** [comment]
list has been extended, and has a few stars/forks/watchers

**Comment by sindresorhus** [comment]
Not yet. You didn't even add a description to each package: https://github.com/xssc/awesome-slim#packages-and-middleware

I'm sorry for being so strict, but the whole point of awesome lists are to be a good resource, just not a dump of random links. Please actually read: https://github.com/sindresorhus/awesome/blob/master/awesome.md

> and has a few stars/forks/watchers

Stars/forks/watchers is an irrelevant measure for quality.

**Pull request closed without merging**
