### PR TITLE
Add Bluetooth Beacons

### PR DESCRIPTION
**Pull request by rabschi**
Includes iBeacon and Eddystone resources

### CODE REVIEW

**Comment by sindresorhus** [comment]
I think a better name for the list would be `awesome-beacon`. The current one is way too specific and verbose. If you agree, rename the repo and update this pull request.

**Comment by sindresorhus** [comment]
Please read the [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

**Comment by sindresorhus** [comment]
Feedback:

- `MAC OSX` => `OS X`
- Repo description is not in sync with readme
- You can drop this line "Inspired by awesome-awesomeness and awesome." The badge is enough.
- Missing a license: https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license
- Would be nice to have some resources about beacons in general; blog posts, videos, etc.

**Comment by rabschi** [comment]
Ok, updated according to your feedback and will set up a new pull request. More blog and video resources will follow but a few good ones are linked.

**Comment by sindresorhus** [comment]
> will set up a new pull request

No, just reopen this pull request when it's ready to be reconsidered.

**Pull request closed without merging**
