### PR TITLE
Add Stacks

### PR DESCRIPTION
**Pull request by jdorfman**
https://github.com/stackshareio/awesome-stacks

**[Explain what this list is about and why it should be included here]**

The list took off pretty much the next day. We just recently hit the 1 month mark and we are close to 1,800 stars. A few developers emailed us saying "thank you" which was amazing. I mention that because people are getting a lot of value out of it which is awesome.

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

## Requirements for your pull request

- **Don't waste my time.** Do a good job, adhere to all the guidelines, and be responsive.
- **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).**
	Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration.

Unless I'm missing something, every PR has been reviewed by others and are awaiting the author to act.

- You have read and understood the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a title in the format `Add Name of List`.
	- ✅ `Add Stacks`
- Your entry here should include a short description about the project/theme of the list. **It should not describe the list itself.** The first character should be uppercase and the description should end in a dot. It should be an objective description and not a tagline or marketing blurb.
	- ✅ `- [Stacks](…) - Tech stacks for building different applications and features.`
- ✅Your entry should be added at the bottom of the appropriate category.
- ✅The suggested Awesome list complies with the below requirements.

## Requirements for your Awesome list

- ✅**Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
- ✅Don't open a Draft / WIP pull request while you work on the guidelines. A pull request should be 100% ready and should adhere to all the guidelines when you open it.
- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- ✅ `Tech stacks for building different applications and features.`
	
- It's the result of hard work and the best I could possibly produce.
	**If you have not put in considerable effort into your list, your pull request will be immediately closed.**
    - ✅ Lots of work. We even including a web app https://awesomestacks.dev/

- The heading title of your list should be in the following format: `# Awesome Name of List`
	- ✅ `# Awesome Stacks`
	
- ✅ Non-generated Markdown file in a GitHub repo.
- ✅The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
- ✅ Not a duplicate. Please search for existing submissions.
- ✅ Only has awesome items. Awesome lists are curations of the best, not everything.
- ✅ Includes a project logo/illustration whenever possible.
	- ✅Either centered, fullwidth, or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
	- ✅ The image should link to the project website or any relevant website.
	- ✅ **The image should be high-DPI.** Set it to maximum half the width of the original image.
- ✅ Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- ✅ Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
	- Should be placed on the right side of the readme heading.
		- ✅ Can be placed centered if the list has a centered graphics header.
	- Should link back to this list.
- ✅ Has a Table of Contents section.
	- ✅ Should be named `Contents`, not `Table of Contents`.
	- ✅ Should be the first section in the list.
	- ✅ Should only have one level of [nested lists](https://commonmark.org/help/tutorial/10-nestedLists.html), preferably none.
- ✅ Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
	- ✅ That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
	- [WTFPL](http://www.wtfpl.net) and [Unlicense](http://unlicense.org) are not acceptable licenses.
	- **If you use a license badge, it should be SVG, not PNG.**
	-  To verify that you've read all the guidelines, please add comment with just the word `unicorn`.
- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
	- ✅ The file should be named `contributing.md`. Casing is up to you.
- ✅ Has consistent formatting and proper spelling/grammar.
	- ✅ The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
	- ✅ The description starts with an uppercase character and ends with a period.
	- ✅ Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
- ✅ Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.
- ✅ Doesn't include an `Inspired by awesome-foo` or `Inspired by the Awesome project` kinda link at the top of the readme. The Awesome badge is enough.

**Go to the top and read it again.**

### CODE REVIEW

**Comment by jdorfman** [comment]
`unicorn`

**Comment by sindresorhus** [comment]
> ✅ The image should be high-DPI. Set it to maximum half the width of the original image.

This is not followed.

---

```
❯ awesome-lint https://github.com/stackshareio/awesome-stacks
✖ Linting

  README.md:27:1
  ✖    1:1  Missing or invalid Table of Contents         remark-lint:awesome/toc
  ✖   27:1  Don’t use multiple top level headings (7:1)  remark-lint:no-multiple-toplevel-headings
  ✖   29:3  Invalid list item link URL                   remark-lint:awesome/list-item
  ✖   30:3  Invalid list item link URL                   remark-lint:awesome/list-item
  ✖   31:3  Invalid list item link URL                   remark-lint:awesome/list-item
  ✖   32:3  Invalid list item link URL                   remark-lint:awesome/list-item
  ✖   34:1  Don’t use multiple top level headings (7:1)  remark-lint:no-multiple-toplevel-headings
  ✖  144:1  Don’t use multiple top level headings (7:1)  remark-lint:no-multiple-toplevel-headings
  ✖  289:1  Don’t use multiple top level headings (7:1)  remark-lint:no-multiple-toplevel-headings
  ✖  371:1  Don’t use multiple top level headings (7:1)  remark-lint:no-multiple-toplevel-headings
  ✖  415:1  Don’t use multiple top level headings (7:1)  remark-lint:no-multiple-toplevel-headings
  ✖  419:1  License section must be at heading depth 2   remark-lint:awesome/license
  ✖  419:1  Don’t use multiple top level headings (7:1)  remark-lint:no-multiple-toplevel-headings

  13 errors
```

https://github.com/sindresorhus/awesome-lint

**Comment by jdorfman** [comment]
@sindresorhus yeah about that, we have a [web app](https://awesomestacks.dev) that will need to be modified to fix the linting errors. @dzello what can we do to address these?

**Comment by dzello** [comment]
@jdorfman Let me see how we can change the format to be more in line with what the linter expects. I'll report back shortly.

**Comment by dzello** [comment]
@jdorfman Linter errors are now fixed on master and linter is running clean.

```
✔ Linting
```

**Comment by jdorfman** [comment]
@sindresorhus Let @dzello and I if you need anything else. =)

**Comment by sindresorhus** [comment]
Tweet: https://twitter.com/awesome__re/status/1141366519244267520

**Pull request merged**
