### PR TITLE
Add Audiovisual

### PR DESCRIPTION
**Pull request by stingalleman**
Duplicate of #1775.

**[[https://github.com/stingalleman/awesome-audiovisual](https://github.com/stingalleman/awesome-audiovisual)]**

**[This list is a combination of software, libraries and resources for audio, video and lighting professionals and hobbyists.]**

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

> I reviewed #1769 & #1758 

Duplicate of #1775.

### CODE REVIEW

**Comment by stingalleman** [comment]
Just FYI, GitHub gave a warning when making this PR: "Note: Creating a PR from the default branch is an [anti-pattern](https://blog.jasonmeridth.com/posts/do-not-issue-pull-requests-from-your-master-branch/)."

**Comment by sindresorhus** [comment]
> `GNU/Linux, , Windows`

Please go through each descriptions and  try to improve them.

---

> DMX controller library for Node.js

Missing a dot at the end.

**Comment by stingalleman** [comment]
I updated the descriptions.

**Comment by stingalleman** [comment]
@sindresorhus

**Comment by stingalleman** [comment]
This is a new requirement, so I didn't knew this requirement existed.

While I _**personally**_ disagree with this change, I have renamed the default branch in order to comply with the requirements.

**Comment by sindresorhus** [comment]
Tweet: https://twitter.com/awesome__re/status/1276969260103823361

**Pull request merged**
