### PR TITLE
Add Crystal programming language

### PR DESCRIPTION
**Pull request by veelenga**
Language homepage: http://crystal-lang.org
Source code: https://github.com/manastech/crystal

### CODE REVIEW

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/awesome/blob/master/contributing.md

**Comment by veelenga** [comment]
Bottom of the category of something else ?

**Comment by sindresorhus** [comment]
> Bottom of the category

Yes

**Comment by sindresorhus** [comment]
@n1trux Squash if there's multiple commits so not to litter the changelog with tweak commits ;)

**Comment by n1trux** [comment]
ok, sorry. Still new to Git after a year or so :p

**Comment by sindresorhus** [comment]
@veelenga Would be awesome if you could link back here in your list so users can easily discover more awesome lists ;)

**Comment by veelenga** [comment]
:+1: Done!

**Pull request merged**
