### PR TITLE
Add workflow engines list to Miscellaneous

### PR DESCRIPTION
**Pull request by meirwah**
Add workflow engines list to Miscellaneous

### CODE REVIEW

**Comment by arthurvr** [comment]
Maybe we should wait a bit before adding this one? The list does only contains 8 links yet.

**Comment by sindresorhus** [comment]
Yes, it needs a lot more work and content. Try again in a month or so when it has had time to mature.

**Comment by meirwah** [comment]
Hey @sindresorhus @arthurvr can we re-open this?
it has much more links and stars now...

**Comment by sindresorhus** [comment]
@meirwah Ensure your list adhere to the guidelines in https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md and then do a new PR ;)

**Pull request closed without merging**
