### PR TITLE
docs: add awesome list template

### PR DESCRIPTION
**Pull request by fzn0x**
Since this is not awesome list contributions, so I removed the pull request templates.
---
This pull request adding awesome list template for **awesome**. Which is to make it easier for people to contribute their awesome list.

Also I'm added ready-to-fork template here: https://github.com/bl0cknumber/awesome-template

### CODE REVIEW

**Comment by benjaoming** [comment]
Can this be closed in favor of https://github.com/jthegedus/awesome-list-template ?

**Comment by benjaoming** [comment]
I don't think that this super-simple template is useful to get started. You'll have to do a lot of manual work afterwards to include things like license, issue templates, linting etc.

**Comment by fzn0x** [comment]
> I don't think that this super-simple template is useful to get started. You'll have to do a lot of manual work afterwards to include things like license, issue templates, linting etc.

It's the repository that include things like license, issue templates, linting, you just need to modify it by yourself https://github.com/bl0cknumber/awesome-template

I can't close this.

**Comment by benjaoming** [comment]
It's great that you are maintaining a template. But perhaps you can propose a link directly to the template repository rather than the intermediary .md file.

I find that https://github.com/jthegedus/awesome-list-template has more features and is also equipped with instructions of how to use it.

**Comment by fzn0x** [comment]
> It's great that you are maintaining a template. But perhaps you can propose a link directly to the template repository rather than the intermediary .md file.
> 
> I find that https://github.com/jthegedus/awesome-list-template has more features and is also equipped with instructions of how to use it.

I think you are missing something, I provide the link to the intermediary .md file https://github.com/sindresorhus/awesome/pull/2159/files 

I already take a look of the repository and it's looks promising with one more addition for awesome bot.

Instructions is really useless to add as we can mark the repository to Public template iirc, after all, I will close this PR because I don't have the time to update my repository for awesome bot.

**Pull request closed without merging**
