### PR TITLE
Add Physics

### PR DESCRIPTION
**Pull request by wbierbower**
Add Physics to 'Theory' section

A collaborative list of awesome software for exploring Physics concepts: 
https://github.com/wbierbower/awesome-physics

### CODE REVIEW

**Comment by legodude17** [comment]
> myphysicslab - provides

Please capitalize the descriptions.

**Comment by sindresorhus** [comment]
Hey, sorry for the lack of response, please see #1363.

**Comment by nschloe** [comment]
Hi! I've reviewed this submission and it has a few issues. (Feel free to @-tag me if something is unclear.)

:white_check_mark: Good!
:x: Needs work!
:grey_question: Not sure, not required, or mixed results

Reviewer comments are in bold after an item.

#### Awesome Requirements
:white_check_mark: Has been around for at least 30 days.
:white_check_mark: It's the result of hard work and the best I could possibly produce.
:white_check_mark: Non-generated Markdown file in a GitHub repo.
:x: Includes a succinct description of the project/theme at the top of the readme. **This list is about physics on GitHub (and software for the most part). The title and the description should clarify this.**
:x: The repo should have awesome-list & awesome as GitHub topics.
:white_check_mark: Not a duplicate.
:white_check_mark: Only has awesome items. Awesome lists are curations of the best, not everything.
:white_check_mark: Includes a project logo/illustration whenever possible. Not required
:x: Entries have a description, unless the title is descriptive enough by itself. **Some points lack a description and need one.**
:white_check_mark: Includes the [Awesome badge]
:white_check_mark: Should be placed on the right side of the readme heading.
:grey_question: Should link back to this list. **The link is https://awesome.re**
:white_check_mark: Has a Table of Contents section.
:white_check_mark: Should be named Contents, not Table of Contents.
:x: : Should be the first section in the list.
:white_check_mark: Should only have one level of sub-lists, preferably none.
:white_check_mark: Has an appropriate license.
:white_check_mark: Has contribution guidelines.
:white_check_mark: The file should be named contributing.md. Casing is up to you.
:white_check_mark: Has consistent formatting and proper spelling/grammar. 
:white_check_mark: The link and description are separated by a dash.
:x: The description starts with an uppercase character and ends with a period. **Entries are not consistently capitalized, period missing.**
:white_check_mark: Consistent and correct naming. For example, Node.js, not NodeJS or node.js.
:white_check_mark: Doesn't include a Travis badge.

#### Additional Comments

Entries should not start with "a" or "an".

In addition,
```
awesome-lint README.md
```
gives many errors, mostly `Marker style should be -`.

In general, I'm not too sure about a physics list that is exclusive to GitHub pages. If someone decides to make a "physics software" list one day, there'd be a lot of overlap. Perhaps call your list "awesome-physics-software" and link to the main sites of the projects, not their development repos. (Those could change in time, too.)

**Comment by sindresorhus** [comment]
```
❯ awesome-lint https://github.com/wbierbower/awesome-physics
✖ Linting

  README.md:1:21
  ✖    1:21  Invalid badge source                                    remark-lint:awesome/badge
  ✖    9:1   Table of Contents must be the first section             remark-lint:awesome/toc
  ✖   24:3   Invalid list item link URL                              remark-lint:awesome/list-item
  ✖   25:3   Invalid list item link URL                              remark-lint:awesome/list-item
  ✖   26:3   Invalid list item link URL                              remark-lint:awesome/list-item
  ✖   27:3   Invalid list item link URL                              remark-lint:awesome/list-item
  ✖   31:78  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   35:54  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   36:53  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   37:51  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   38:51  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   39:63  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   40:52  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   41:65  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   42:52  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   43:56  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   44:96  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   45:39  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   46:44  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   47:48  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   51:67  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   52:48  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   53:42  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   57:76  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   58:49  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   59:45  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   63:3   Invalid list item link URL                              remark-lint:awesome/list-item
  ✖   64:3   Invalid list item link URL                              remark-lint:awesome/list-item
  ✖   68:48  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   69:44  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   70:60  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   74:75  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   78:48  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   79:51  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   80:65  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   81:48  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   82:57  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   86:85  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   87:41  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   88:45  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   89:43  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   90:49  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   91:51  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   93:42  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   94:56  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   95:60  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   96:54  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   97:63  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   98:52  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖   99:50  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  103:49  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  104:55  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  105:51  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  106:44  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  107:49  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  108:46  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  109:47  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  113:65  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  114:47  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  118:43  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  119:46  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  120:48  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  121:75  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  122:39  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  123:51  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  125:66  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  126:42  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  127:47  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  128:57  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  132:48  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  133:39  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  134:50  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  135:48  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  136:42  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  140:52  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  141:40  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  142:45  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  146:34  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  147:49  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  148:34  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  149:37  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  150:34  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  151:36  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  152:39  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  153:34  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  154:34  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  155:34  List item description must end with proper punctuation  remark-lint:awesome/list-item

  87 errors
```

https://github.com/sindresorhus/awesome-lint

**Comment by sindresorhus** [comment]
Closing for lack of response.

@wbierbower Feel free to create a new PR if you ever get around to fix the mentioned issues.

**Pull request closed without merging**
