### PR TITLE
Add the list I made for the Stellar decentralized network

### PR DESCRIPTION
**Pull request by francescomalatesta**
**https://github.com/francescomalatesta/awesome-stellar**

Hi, I recently created this awesome-style list for the Stellar network, one of the most interesting projects in the context of decentralized networks :)

Hope you will like it!

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

**Comment by francescomalatesta** [comment]
Woops! Sorry!

I'll fix the list ASAP, thanks for the feedback.

**Comment by sindresorhus** [comment]
Ping. Please also see #1363.

**Comment by sindresorhus** [comment]
@francescomalatesta Ping

**Comment by sindresorhus** [comment]
Closing for lack of response.

**Comment by sindresorhus** [comment]
```
❯ awesome-lint https://github.com/francescomalatesta/awesome-stellar
✖ Linting

  README.md:14:5
  ✖    1:1    Missing Awesome badge after the main heading                    remark-lint:awesome/badge
  ✖    1:1    Missing or invalid Table of Contents                            remark-lint:awesome/toc
  ✖   13:3    Invalid list item link URL                                      remark-lint:awesome/list-item
  ✖   14:5    Incorrect indentation before bullet: remove 2 spaces            remark-lint:list-item-bullet-indent
  ✖   15:5    Incorrect indentation before bullet: remove 2 spaces            remark-lint:list-item-bullet-indent
  ✖   16:5    Incorrect indentation before bullet: remove 2 spaces            remark-lint:list-item-bullet-indent
  ✖   17:5    Incorrect indentation before bullet: remove 2 spaces            remark-lint:list-item-bullet-indent
  ✖   19:3    Invalid list item link URL                                      remark-lint:awesome/list-item
  ✖   21:3    Invalid list item link URL                                      remark-lint:awesome/list-item
  ✖   23:3    Invalid list item link URL                                      remark-lint:awesome/list-item
  ✖   25:3    Invalid list item link URL                                      remark-lint:awesome/list-item
  ✖   26:5    Incorrect indentation before bullet: remove 2 spaces            remark-lint:list-item-bullet-indent
  ✖   27:5    Incorrect indentation before bullet: remove 2 spaces            remark-lint:list-item-bullet-indent
  ✖   28:5    Incorrect indentation before bullet: remove 2 spaces            remark-lint:list-item-bullet-indent
  ✖   29:5    Incorrect indentation before bullet: remove 2 spaces            remark-lint:list-item-bullet-indent
  ✖   31:3    Invalid list item link URL                                      remark-lint:awesome/list-item
  ✖   32:5    Incorrect indentation before bullet: remove 2 spaces            remark-lint:list-item-bullet-indent
  ✖   33:5    Incorrect indentation before bullet: remove 2 spaces            remark-lint:list-item-bullet-indent
  ✖   34:5    Incorrect indentation before bullet: remove 2 spaces            remark-lint:list-item-bullet-indent
  ✖   36:3    Invalid list item link URL                                      remark-lint:awesome/list-item
  ✖   38:3    Invalid list item link URL                                      remark-lint:awesome/list-item
  ✖   39:5    Incorrect indentation before bullet: remove 2 spaces            remark-lint:list-item-bullet-indent
  ✖   40:5    Incorrect indentation before bullet: remove 2 spaces            remark-lint:list-item-bullet-indent
  ✖   44:1    Don’t add a trailing ? to headings                              remark-lint:no-heading-punctuation
  ✖   46:47   List item description must end with proper punctuation          remark-lint:awesome/list-item
  ✖   47:71   List item description must end with proper punctuation          remark-lint:awesome/list-item
  ✖   48:63   List item description must end with proper punctuation          remark-lint:awesome/list-item
  ✖   49:60   List item description must start with valid casing              remark-lint:awesome/list-item
  ✖   53:104  List item description must start with valid casing              remark-lint:awesome/list-item
  ✖   57:69   List item description must end with proper punctuation          remark-lint:awesome/list-item
  ✖   61:96   List item description must end with proper punctuation          remark-lint:awesome/list-item
  ✖   65:192  List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖   67:115  List item description must end with proper punctuation          remark-lint:awesome/list-item
  ✖   71:54   List item description must end with proper punctuation          remark-lint:awesome/list-item
  ✖   72:53   List item description must end with proper punctuation          remark-lint:awesome/list-item
  ✖   73:44   List item description must end with proper punctuation          remark-lint:awesome/list-item
  ✖   77:49   List item description must end with proper punctuation          remark-lint:awesome/list-item
  ✖   78:46   List item description must end with proper punctuation          remark-lint:awesome/list-item
  ✖   79:40   List item description must end with proper punctuation          remark-lint:awesome/list-item
  ✖   80:3    Link to https://cryptoaud.io/ is dead                           remark-lint:no-dead-urls
  ✖   80:39   List item description must end with proper punctuation          remark-lint:awesome/list-item
  ✖   81:62   List item description must end with proper punctuation          remark-lint:awesome/list-item
  ✖   82:38   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖   88:61   List item description must end with proper punctuation          remark-lint:awesome/list-item
  ✖   89:73   List item description must end with proper punctuation          remark-lint:awesome/list-item
  ✖   93:38   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖   94:30   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖   95:31   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖   96:38   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖   97:50   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖   98:57   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖   99:34   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  100:38   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  101:33   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  102:36   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  103:38   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  104:34   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  105:36   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  106:41   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  107:32   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  108:36   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  109:38   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  110:38   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  111:69   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  112:3    Link to https://upbit.com/ is dead                              remark-lint:no-dead-urls
  ✖  112:30   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  116:71   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  117:3    Link to https://stronghold.co/send-receive-lumens.html is dead  remark-lint:no-dead-urls
  ✖  117:63   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  118:42   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  119:56   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  120:41   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  121:31   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  122:41   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  123:27   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  124:87   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  129:35   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  135:79   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  136:81   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  137:58   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  138:55   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  139:70   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  140:69   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  141:58   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  142:120  List item description must end with proper punctuation          remark-lint:awesome/list-item
  ✖  143:53   List item description must end with proper punctuation          remark-lint:awesome/list-item
  ✖  144:59   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  148:58   List item description must end with proper punctuation          remark-lint:awesome/list-item
  ✖  149:48   List item description must end with proper punctuation          remark-lint:awesome/list-item
  ✖  150:62   List item description must end with proper punctuation          remark-lint:awesome/list-item
  ✖  154:95   List item description must end with proper punctuation          remark-lint:awesome/list-item
  ✖  155:3    Link to https://stellarwidget.com is dead                       remark-lint:no-dead-urls
  ✖  161:44   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  162:37   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  163:45   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  164:64   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  168:45   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  169:85   List item link and description must be separated with a dash    remark-lint:awesome/list-item
  ✖  176:35   Link to https://www.facebook.com/malatesta.francesco is dead    remark-lint:no-dead-urls

  99 errors

```

https://github.com/sindresorhus/awesome-lint

**Pull request closed without merging**
