### PR TITLE
Add FastAPI

### PR DESCRIPTION
**Pull request by mjhea0**
https://github.com/mjhea0/awesome-fastapi

The list is about [FastAPI](https://fastapi.tiangolo.com/), a Python-based, async web application framework. It should be included since (1) the isn't already a FastAPI awesome list and (2) FastAPI is a popular framework for Python web app development.

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

### CODE REVIEW

**Comment by mjhea0** [comment]
unicorn

**Comment by mjhea0** [comment]
Lint: https://travis-ci.org/github/mjhea0/awesome-fastapi/builds/696181609#L233

**Comment by mjhea0** [comment]
Reviewed PRs:

1. https://github.com/sindresorhus/awesome/pull/1783#issuecomment-640826981
1. https://github.com/sindresorhus/awesome/pull/1782#issuecomment-640845698

**Comment by sindresorhus** [comment]
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

**Comment by mjhea0** [comment]
I spent a few hours yesterday trying to get my repo to conform to the guidelines. As far as I can tell, the only thing I'm missing is - "The description starts with an uppercase character and ends with a period." I added the following ignore at the top of the README yesterday:

```
<!--lint disable awesome-list-item-->
```

Anyway, I removed it and added all the periods. Lint: https://travis-ci.org/github/mjhea0/awesome-fastapi/jobs/696448202#L220

Am I missing something else?

**Comment by sindresorhus** [comment]
I decided to rename `master` branch to `main`, and apparently that permanently closes all PRs. Ugh. Sorry about that. Can you reopen this PR targeting the `main` branch?

**Pull request closed without merging**
