### PR TITLE
Add serverless-security

### PR DESCRIPTION
**Pull request by oorryy**
https://github.com/puresec/awesome-serverless-security#readme

A curated list of awesome serverless security resources such as (e)books, articles, whitepapers, blogs and research papers.

I reviewed the following PRs:
- #[1523](https://github.com/sindresorhus/awesome/pull/1523#)
- #[1515](https://github.com/sindresorhus/awesome/pull/1515#)
- #[1536](https://github.com/sindresorhus/awesome/pull/1536#)
- #[1533](https://github.com/sindresorhus/awesome/pull/1533#)

By submitting this pull request I confirm I've read and complied with the below requirements 🖖
Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.

Requirements for your pull request
You have to review at least 2 other open pull requests. Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration.
I have read and understood the instructions for creating a list.
This pull request has a descriptive title in the format Add Name of List (Example: Add Swift), not Update readme.md or Add awesome list.
The entry in the Awesome list should:
Include a short description about the project/theme of the list. It should not describe the list itself.
Example: - [Fish](…) - User-friendly shell., not - [Fish](…) - Resources for Fish..
Be added at the bottom of the appropriate category.
The list I'm submitting complies with the below requirements.
Requirements for your Awesome list
Has been around for at least 30 days.
That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
It's the result of hard work and the best I could possibly produce.
Non-generated Markdown file in a GitHub repo.
Includes a succinct description of the project/theme at the top of the readme. (Example)
The repo should have awesome-list & awesome as GitHub topics. I encourage you to add more relevant topics.
Not a duplicate.
Only has awesome items. Awesome lists are curations of the best, not everything.
Includes a project logo/illustration whenever possible.
Either centered, fullwidth, or placed at the top-right of the readme. (Example)
The image should link to the project website or any relevant website.
The image should be high-DPI. Set it to maximum half the width of the original image.
Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
Includes the Awesome badge.
Should be placed on the right side of the readme heading.
Can be placed centered if the list has a centered graphics header.
Should link back to this list.
Has a Table of Contents section.
Should be named Contents, not Table of Contents.
Should be the first section in the list.
Should only have one level of nested lists, preferably none.
Has an appropriate license.
That means something like CC0, not a code licence like MIT, BSD, Apache, etc.
WTFPL and Unlicense are not acceptable licenses.
If you use a license badge, it should be SVG, not PNG.
Has contribution guidelines.
The file should be named contributing.md. Casing is up to you.
Has consistent formatting and proper spelling/grammar.
The link and description are separated by a dash. 
Example: - [AVA](…) - JavaScript test runner.
The description starts with an uppercase character and ends with a period.
Consistent and correct naming. For example, Node.js, not NodeJS or node.js.
Doesn't include a Travis badge.
You can still use Travis for list linting, but the badge has no value in the readme.
Go to the top and read it again.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

**Comment by oorryy** [comment]
Hi - went over the requirements again. 
1) Reviewed two PRs
2) Modified the PR title to "Add list-name"
3) Went over the entire requirements list again to verify everything. Check.

**Comment by beardicus** [comment]
Hi @oorryy , I've reviewed this submission and it mostly has one major issue preventing its inclusion: it does not follow the awesome list formatting for each entry. Tables are not the way awesome lists are formatted. The entries should all be in a list, and each entry should consist of a link, followed by a ' - ', followed by a well-formatted description with proper capitalization and a period.

The content you link to looks great, and your descriptions are mostly good but could use some cleanup. The table formatting is the main thing holding this up.

Thanks for putting together this list it looks nice but needs some tweaks! I've included a detailed checklist below. Also take a look at [awesome-lint](https://github.com/sindresorhus/awesome-lint), a linter which can let you know when your `README.md` is free of errors.

✅: Good!
❌: Needs work!
:grey_question:: Not sure, not required, or mixed results

_**Reviewer comments are in bold italics after an item**_

# Awesome Requirements

- ✅Has been around for at least 30 days.
- ✅ It's the result of hard work and the best I could possibly produce. _**Looks like a good selective list of resources**_
- ✅ Non-generated Markdown file in a GitHub repo.
- ✅ Includes a succinct description of the project/theme at the top of the readme. 
- ✅ The repo should have `awesome-list` & `awesome` as GitHub topics. _**missing `awesome-list` topic**_
- ✅ Not a duplicate.
- ✅ Only has awesome items. Awesome lists are curations of the best, not everything.
- ✅ Includes a project logo/illustration whenever possible.
- ✅ Entries have a description, unless the title is descriptive enough by itself.
- ✅ Includes the [Awesome badge]
	- ✅ Should be placed on the right side of the readme heading.
	- ✅ Should link back to this list.
- ✅ Has a Table of Contents section.
	- ✅ Should be named `Contents`, not `Table of Contents`.
	- ✅ Should be the first section in the list. 
	- ✅ Should only have one level of sub-lists, preferably none.
- ✅ Has an appropriate license.
- ✅ Has contribution guidelines.
	- ✅ The file should be named `contributing.md`. Casing is up to you. 
- ❌ Has consistent formatting and proper spelling/grammar. _**Internally mostly consistent but not consistent with the standard.**_
	- ❌ The link and description are separated by a dash.
	- ❌ The description starts with an uppercase character and ends with a period. _**Mixed period use**_
	- ✅ Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
- ✅ Doesn't include a Travis badge.

**Comment by oorryy** [comment]
@beardicus Thank you for the thorough explanation. I'm working on fixing the problems as we speak and will update with a comment here once done. I truly appreciate your effort and assistance!

**Comment by oorryy** [comment]
@beardicus the list has been modified. I ran the awesome-lint tool and there are no additional warnings reported.

**Comment by beardicus** [comment]
🎉 Looking good! 🎉

**Comment by sindresorhus** [comment]
There are still many things in the guidelines that are not followed.

**Pull request closed without merging**
